### ISSUE TITLE
Jenkins docker image has no make or sudo

### ISSUE THREAD

**Issue by jsachs** [jenkinsci/docker#100]
Per [this Super User post](), I'm having issues with my Jenkins instance due to (1) the lack of `make` in the image and (2) the lack of `sudo`, prohibiting me from installing `make`. Could we either add the `sudo` command, or not specify `USER` in the Dockerfile?

**Comment by carlossg** [comment]
Check this out 
https://github.com/jenkinsci/docker#installing-more-tools

**Comment by jsachs** [comment]
@carlossg exactly what I need, thanks!
