### ISSUE TITLE
Tagging Scheme for Images

### ISSUE THREAD

**Issue by james-crowley** [jenkinsci/docker#1001]
As the project is starting to support multi-arch, jvm options(hotspot/openj9), multiple JDK versions, and more OS options tagging for these variants becomes more important. Giving our users more of a choice when it comes to which variants they want to utilize is great, but it needs to be clear on which image they are pulling. 

Currently, there are a couple problematic tags that easily lead to confusion or problems down the line. 

An example of this would be how the “default” images are handled. Currently, you can pull down `2.261`. While this tag tells the user what version of Jenkins they are using it does not tell the user what the base OS is going to be. Having high level tags like these make sense, but the lack of a more verbose tag is where some of the confusion happens. For all the other variants Jenkins support like `centos` you can see the more verbose tag of `2.261-centos`, but the “default” variant lacks this. The “default” variant is currently set to `Debian` but this could change in the future. Additionally, the “default” variant is not mentioned anywhere in the documentation or on DockerHub, which is common/standard for images.

Another example of problematic tags is the “variant” `jdk11`. Currently, most of the images offered by Jenkins are defaulted to JDK 8. But when JDK 8 end of life comes about or when community support wants to move to JDK 11, what happens to the variant `jdk11`? Now all the images are pointed to JDK 11 by default which could lead to confusion and issues for our users. 

With all the additional support for multi-arch, jvm options, multiple JDK versions, more OS options and the combination of the problematic images, I think we should look at the tagging scheme for the Jenkins images.  

My proposal would to adjust the different variants we offer and their most verbose tags, thus allowing for flexible design that can grow with the needs of the project. There are a couple PRs already merged to help with the standardization of tags such as #985 and #995. These PRs helped organize the images into folders.

The tagging scheme I propose is as follows:

```
{jenkins_version}-{jdk_verison}-{jvm_variant}-{os_name}-{os_version}
```

This tag represents the most verbose tag. This would be the image we re-tag to enable more general tags. For example, you might have a set of tags like the following that represent the same image:

```
2.261-jdk8-hotspot-centos-7
2.261-hotspot-centos-7
2.261-jdk8-centos-7
2.261-centos-7
2.261-centos
centos-7
centos
```

This use of a verbose tag allows for more general tags that users can follow. But also gives the user the option to follow a specific/verbose tag if their environment requires that.

Additionally, if you take the example of the “default” image from before the break down of tags could be:

```
2.261-jdk11-openj9-debian-buster
2.261-openj9-debian-buster
2.261-jdk11-debian-buster
2.261-debian-buster
2.261-debian
debian-buster
debian
2.261
```

These changes in tagging also would help address the issue with having a variant of `jdk11`. Additionally, we would get the added benefit of allow different images to have support for `openj9` and `hotspot`, which the Windows images already support.

The proposal and changes I am suggestion will allow for a more flexible design as the Jenkins project offerings expand and will provide users will the added clarity that they are pulling down the correct image. 

Some changes to our build scripts would be required. These changes would directly affect how #998 is being implemented.

**Comment by bendermIBM** [comment]
I like the granularity of this approach. What are the implications for current users? Would this be a seamless transition to a new schema or would there have to be notices distributed to end-users?

**Comment by james-crowley** [comment]
I should have clarified that in the initial post but there would be no impact for current users. The suggestion I made would be adding in more tags not removing them, thus current users pulling from a given tag should not be affected.


Later down the line the removal of `jdk11` tag would probably be a good idea as I don’t think users would just want to subscribe to a `jdk11` tag. 

That does bring a good point about communicating “defaults” for tags and communicating end of life for tags. There should be some place whether it’s on DockerHub or in the `README` that communicates these points to the users.

**Comment by slide** [comment]
Adding in more tags is a great idea. I like the proposal.

**Comment by vsilverman** [comment]
Agree, reasonable approach

**Comment by james-crowley** [comment]
I am going to work on revamping the scripts we have now to take advantage of the new tagging scheme. Once the revamping is merged via a PR we should be good to merge #998.

The revamping should go pretty smooth thanks to @jordan-cartwright-ibm who published some build script he uses to manage multi-arch images. The scripts he published are over [here](https://github.com/jordan-cartwright-ibm/example-docker-manifest/tree/master/.ci).

Looks like we can take parts of the build scripts and modify them to how Jenkins builds out its images.

**Comment by MarkEWaite** [comment]
Jenkins 2.307 is publishing multi-architecture images for amd64, arm64, ppc64le, and s390x as:
* [2.307-rhel-ubi8-jdk11](https://hub.docker.com/layers/jenkins/jenkins/2.307-rhel-ubi8-jdk11/images/sha256-cef48c38448877bad0a392a81c4f0d55c605da867f4649c9180c1f684cdd0b07?context=explore)
* [2.307-jdk11](https://hub.docker.com/layers/jenkins/jenkins/2.307-jdk11/images/sha256-e294464e4fbe852215b91cb1cb3b8a68936d109ba3058043fd99f7b2d36f5cef?context=explore)
* * [2.307](https://hub.docker.com/layers/jenkins/jenkins/2.307/images/sha256-c915ecbd2e2eab74e323453d2c2acec97cba6c362e55d54f89264cedad837b87?context=explore)

See the [Jenkins Enhancement Proposal for Java 11](https://github.com/jenkinsci/jep/blob/57c441bebe19749f06f023aa02c222323ba9d15c/jep/0000/README.adoc) for more details on the labels applied to the images.

**Comment by timja** [comment]
I think we can close this now?

the above is generally followed and tweaks can be easily made via docker bake file
