### ISSUE TITLE
Make a new Jenkins image

### ISSUE THREAD

**Issue by papioyue** [jenkinsci/docker#1002]
I want to package the running jenkins container into a new image, but I found that running the new image is still a brand new jenkins, and I still need to reconfigure the user and the current plug-in.

build Dockfile:

FROM jenkins/jenkins:latest

USER root
RUN apt-get update
RUN apt-get install zip
RUN apt-get install ssh -y
COPY --chown=jenkins:jenkins ./jenkins_datas /var/jenkins_home

**Comment by Celebes** [comment]
You can set up volume or bind mount to persist data across various containers.

Other than that you can create a groovy script to modify config.xml on container startup, for example:

**executors.groovy**:
```
import jenkins.model.*
Jenkins.instance.setNumExecutors(5)
```

**Dockerfile A:**
```
FROM jenkins/jenkins
COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
RUN /usr/local/bin/install-plugins.sh docker-plugin
```

You can also install plugins on container creation but you will still lose admin setup without volume/bind mount, for example:

**Dockerfile B:**
```
FROM jenkins/jenkins:2.150.3
RUN /usr/local/bin/install-plugins.sh docker-plugin
```

**Comment by slide** [comment]
This is expected behavior and which is why, as @Celebes mentions you should setup a volume for your JENKINS_HOME.
