### ISSUE TITLE
[Proposal] Naming change

### ISSUE THREAD

**Issue by atur94** [jenkinsci/docker#1018]
# Proposition

Plugins for image are placed in `plugins.txt`. When looking for the first time on folder structure, this file looks like someone's note. It would be better if this file was renamed to for instance `list.plugins`, `jenkins.plugins` to directly indicate that file is important

### Expected outcome

The file with plugins should be immidiately recognizable as jenkins plugin list. Extension should be different thant `*.txt`

**Comment by slide** [comment]
If you are building an image that is based on this and putting a plugins.txt in, you should be able to name it anything you want. Can you expound on a specific case that I may be missing?

**Comment by atur94** [comment]
No, that is not specific case. For me, files that contains something and theey are used somewhere in the pipelline shoudn't be extended with "*.txt* That was just suggestion to change that extension or remove it. I am just pedant

**Comment by slide** [comment]
Since the file can be called whatever you want, I don't think we'll change it in the repo.
