### ISSUE TITLE
Latest Release Versions on github.com and hub.docker.com should be in sync

### ISSUE THREAD

**Issue by vsilverman** [jenkinsci/docker#1030]
Version number of [Latest Jenkins Docker Image Release on github.com](https://github.com/jenkinsci/docker/releases) doesn't match version of latest Jenkins Docker release in [Jenkins Documentation](https://www.jenkins.io/download/) and on [hub.docker.com](https://hub.docker.com/r/jenkins/jenkins/tags)

**Comment by timja** [comment]
https://github.com/jenkinsci/docker/blob/master/CHANGELOG.md

These do not relate to jenkins versions at all, they are supposed to help highlight changes that have been done on the packaging side.
