### ISSUE TITLE
i am unable to install jenkins plugins at my first setup

### ISSUE THREAD

**Issue by krishna3008** [jenkinsci/docker#1031]
I am using Windows and 
Java 1.8.0.271
JDK 11.0.9
I have run all the test runs 
I am having the plugins installation Problem
![image](https://user-images.githubusercontent.com/74471606/99156720-431ad700-26e9-11eb-8635-9e406f8bc3c1.png)

**Comment by DanVill29** [comment]
Also see this problem. Working last week

**Comment by slide** [comment]
You mention two different Java versions in your report. Can you mention which specific image you are using?

**Comment by MarkEWaite** [comment]
Closing due to no feedback
