### ISSUE TITLE
Missing JAVA_OPTS argument in script: jenkins-plugin-cli.sh/ps1

### ISSUE THREAD

**Issue by oisis** [jenkinsci/docker#1043]
### Issue description
I run Jenkins on Kubernetes with helm chart: https://artifacthub.io/packages/helm/jenkinsci/jenkins but i am behind proxy which 
decrypt SSL traffic and switching it to SelfSigned SSL certificate. It is ok for Jenkins itself because i can add JAVA_OPTS to Jenkins run command but makes an issue with jenkins-plugin-cli, there is no way to add JAVA_OPTS to it without editing this script. 

### Actual result
Now i can create custom Java truststore and add path to it with JAVA_OPTS arguments for Jenkins but not to jenkins-plugin-cli.sh/ps1 so i cannot install plugins on initContainer stage. I can create issue on helm chart github repo but i do believe it should be done in jenkins-plugin-cli script. 

### Expected outcome
Possibility to add parameters like JAVA_OPTS to command from scripts: 
jenkins-plugin-cli.sh and jenkins-plugin-cli.ps1

### Have you tried a non-dockerized Jenkins and get the expected outcome?
Yes

### Output of `docker version`
N/A

### Other relevant information
Simple solution could be to change script jenkins-plugin-cli.sh to looks like:

```
#!/usr/bin/env bash

java ${JAVA_OPTS} -jar /usr/lib/jenkins-plugin-manager.jar "$@"
```

What do you think?

**Comment by oleg-nenashev** [comment]
I doubt that passing Jenkins Java options to the plugin manager is a
good idea. These are two completely different tools with different
use-cases. I would rather introduce a new environment variable

**Comment by oisis** [comment]
@oleg-nenashev 
New environment variable sounds good to me too. Important is to possibility to pass anything to jenkins-plugin-manager script.

**Comment by dnskr** [comment]
Hi, there is an opened [PR](https://github.com/jenkinsci/docker/pull/1025) for this issue.
@oleg-nenashev could you please have a look at it? I would appreciate your suggestion on alternative solution or alternative name for `JAVA_OPTS` variable.

**Comment by oisis** [comment]
@oleg-nenashev 
Could you please merge/check this PR?

**Comment by timja** [comment]
This was merged and released ages ago
