### ISSUE TITLE
lts latest version has problem in jenkins-plugin-cli

### ISSUE THREAD

**Issue by Hokwang** [jenkinsci/docker#1061]
Hi,

jenkins helm chart use jenkins-plugin-cli for installing jenkins plugins.

but lts latest version docker image's jenkins-plugin-cli 
does not have `JAVA_OPTS`.

This is critical problem for users who should use http proxy like me.

How about update lts image ?

**Comment by oleg-nenashev** [comment]
It should have been fixed by https://github.com/jenkinsci/docker/pull/1025 in recent releases.
Might be useful to get it in LTS

**Comment by Hokwang** [comment]
@oleg-nenashev 
I think you are wrong.

I am using jdk11 image.
```
docker run -it --rm jenkins/jenkins:2.273-jdk11 bash -c 'cat /bin/jenkins-plugin-cli'
#!/bin/bash

exec /bin/bash -c "java $JAVA_OPTS -jar /usr/lib/jenkins-plugin-manager.jar $*"
```

```
docker run -it --rm jenkins/jenkins:2.263.1-lts-jdk11 bash -c 'cat /bin/jenkins-plugin-cli'
#!/usr/bin/env bash

java -jar /usr/lib/jenkins-plugin-manager.jar "$@"
```

**Comment by oleg-nenashev** [comment]
Yes... So the next LTS release should include the fix.
Sorry for inconvenience it caused.

**Comment by Hokwang** [comment]
when will next release come?

**Comment by oleg-nenashev** [comment]
Jan 13 is the current ETA
