### ISSUE TITLE
docker image root password?

### ISSUE THREAD

**Issue by WangShuangQuan-A** [jenkinsci/docker#1065]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

**Comment by slide** [comment]
This is not a place to ask questions. Use the mailing lists for those. In general there is not a root password set via the Jenkins image builds, it would be whatever the base image uses, which may be random.
