### ISSUE TITLE
This is not a place to ask questions. Use the mailing lists for those. In general there is not a root password set via the Jenkins image builds, it would be whatever the base image uses, which may be random.

### ISSUE THREAD

**Issue by WangShuangQuan-A** [jenkinsci/docker#1067]
This is not a place to ask questions. Use the mailing lists for those. In general there is not a root password set via the Jenkins image builds, it would be whatever the base image uses, which may be random.

_Originally posted by @slide in https://github.com/jenkinsci/docker/issues/1065#issuecomment-758721903_

If the builder doesn't know the root password, just provide it for others to use, is it appropriate? I tried to set a series of passwords for initial modification, but I didn’t have permission. Who would use the image without permission at all????

**Comment by slide** [comment]
Please use the mailing list for questions.
