### ISSUE TITLE
Segmentation fault on Mac M1

### ISSUE THREAD

**Issue by jamielsharief** [jenkinsci/docker#1068]
Hi, I am getting a segmentation fault trying to run the official Jenkins image on the MAC M1 (ARM processor)

![image](https://user-images.githubusercontent.com/20553479/105360328-c0d2f580-5bf8-11eb-943a-f6da4fe55850.png)

**Comment by slide** [comment]
We don't have an official image for ARM right now, so I wouldn't use it.

**Comment by KoeketieneDesign** [comment]
I'm having the same problem but another error

```php_1         | mmap() failed: [12] Out of memory
php_1         | Segmentation fault
starter-140_php_1 exited with code 139```

is there anything I can do to get this working on my Mac M1 machine?

**Comment by imrichardcole** [comment]
Is there any plan to fix this?  Anyone invested any time understanding what causes the seg fault?

**Comment by slide** [comment]
@imrichardcole Not that I know of. We don't have a maintainer for the ARM image right now, though it runs on normal AArch64 targets that I have used. I think it is probably something that is specific to Mac M1, so until someone with one of those steps up, there probably will not be any work done on this.

**Comment by imrichardcole** [comment]
@slide I do have one, let me see if I can get any more details

**Comment by vijjukumar** [comment]
Is there any plan to fix this? We don't have docker Jenkins image which supports for Apple Mac M1 (ARM Processor)

**Comment by slide** [comment]
No, there is no current plan to fix this. Jenkins is a volunteer organization. No one apparently has the time or resources to look into this. So, someone with those things will need to step up to look into it.

**Comment by imrichardcole** [comment]
@vijjukumar @slide please see above, I'm trying to look into fixing this myself.  Shall post any progress here

**Comment by timja** [comment]
If you rebuild the images yourself on ARM it works just fine (assuming the base image publishes multi arch), (I verified that the centos one works on mac m1).

Need to get CI process sorted here to publish the images properly (probably non trivial)

**Comment by jamielsharief** [comment]
@timja I done it for MySQL, source and instructions on how I did was here. https://github.com/jamielsharief/docker-mysql If you fancy giving it a go?

**Comment by timja** [comment]
There's a WIP PR here: https://github.com/jenkinsci/docker/pull/1034, I'll see what I do with that as a base

**Comment by timja** [comment]
I've created a draft PR: https://github.com/jenkinsci/docker/pull/1133

you can use it to publish your own multi-arch builds easily if you want to in the meantime

**Comment by timja** [comment]
We're now publishing `arm64`, `ppc64le` and `s390x` images

See tags on dockerhub:
https://hub.docker.com/r/jenkins/jenkins/tags?page=1&ordering=last_updated

Please raise a new issue if any problems with it
