### ISSUE TITLE
Major OS Upgrade vom LTS 2.263.3 -> 2.263.4 Patch Update

### ISSUE THREAD

**Issue by adrianliechti** [jenkinsci/docker#1085]
Hi Jenkins Team,

We noticed a major OS upgrade of the latest patch level

```
docker run -it --rm jenkins/jenkins:2.263.3 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


docker run -it --rm jenkins/jenkins:2.263.4 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This was quite unexpected for us. Especially because also OpenSSL changed within this two releases:
https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#openssl-defaults

including the default cipher settings:

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2

We facing currently issues with e.g. LDAP over TLS, or also by just using cURL in that container.

It seems the root cause is by targeting the AdoptJDK base image which seems not stitching the OS release.
Other base images are especially using tags with a specific OS (e.g. buster or stetch).

I hope you understand our surprise... maybe you are surprised too

Cheers, Adrian

**Comment by slide** [comment]
We moved from Debian 9 to Debian 10 because Debian 9 is EOL. There was a blog entry about it here: https://www.jenkins.io/blog/2021/02/08/docker-base-os-upgrade/. You can use the stretch tag, but it is no longer supported.

**Comment by adrianliechti** [comment]
thanks for your answer and hinting at your blog!

there was no note here: https://www.jenkins.io/changelog-stable/
in compare to a older alpine update. maybe it will help others to note that too in the changelog.

What's new in 2.263.4 (2021-02-10)
- Community reported issues: 1×JENKINS-56812
- Improve performance in fingerprint file creation. (issue 64670)
- Use the correct freestyle font-size for descriptions. (issue 64332)
- Don't tell user's to signup when signup is not available. (issue 64426)

What's new in 2.164.2 (2019-04-10) 
- Major update of the Alpine-based Jenkins Docker image. Jenkins Docker image for Alpine now uses Alpine 3.12 and AdoptOpenJDK 8u262. (upgrade guide)


but then we keep in mind that there might be major changes in patch (not only minor) versions too

**Comment by slide** [comment]
That's a good point, thanks for reminding that it would be good to have in the changelog.
