### ISSUE TITLE
Refusing to marshal org.apache.commons.net.ftp.FTPClient for security reasons

### ISSUE THREAD

**Issue by ahliddin** [jenkinsci/docker#1088]
### Version report

```
Jenkins: 2.263.4
OS: Linux - 4.19.128-microsoft-standard
ftp-rename: 1.2
```
[Jenkins FTP Rename](https://plugins.jenkins.io/ftp-rename/) plugin: v1.2

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows 10 (Docker Desktop)
```

### Reproduction steps

- Install [FTP Rename](https://plugins.jenkins.io/ftp-rename/) plugin
- Add a build step with FTP Rename
- Click save

### Results

*Expected result:*
The build changes successfully saved

*Actual result:*
Failure to save, error: `A problem occurred while processing the request.`
[jenkins_error.log](https://github.com/jenkinsci/docker/files/6085590/jenkins_error.log)

**Comment by oleg-nenashev** [comment]
This error comes from the FTP Rename plugin: https://plugins.jenkins.io/ftp-rename/
Please report it in the Jira issue tracker to the "ftp-rename-plugin" component. Adding the JEP-200 label would also help
