### ISSUE TITLE
Push ubuntu/focal/openj9/ image to DockerHub?

### ISSUE THREAD

**Issue by FF186** [jenkinsci/docker#1091]
Hi,

Is the image in path: "ubuntu/focal/openj9/" available on DockerHub?

Thanks in advance.

**Comment by slide** [comment]
No, we don't currently have a maintainer for the image, so we are not publishing it.

**Comment by lalet** [comment]
@slide Hi Slide, does jenkins have an official image on ubuntu ?
I could see this https://github.com/gbevan/jenkins-ubuntu but I hope that is no longer maintained.

**Comment by slide** [comment]
No, we don't have one because there is no maintainer for it right now.

**Comment by lalet** [comment]
Do you have a documentation guide or anything that I can look up to try to come up with one ?

**Comment by lalet** [comment]
Thank you1

**Comment by timja** [comment]
Why do you want this?

we should have plenty of images to cover most needs

**Comment by MarkEWaite** [comment]
We've dropped support for OpenJ9 images.  I'm closing this request.
