### ISSUE TITLE
Error Response from Daemon when using docker run jenkins

### ISSUE THREAD

**Issue by vmwarelab** [jenkinsci/docker#1099]
getting the following error unless i specify a version tag  . use the latest tag results in the same output

cloudadmin@vra-cloud-vm-805:~/jenkins-data$ docker run -p 8080:8080 -p 50000:50000 -v /home/cloudadmin/jenkins-data:/var/jenkins_home jenkins
Unable to find image 'jenkins:latest' locally
docker: Error response from daemon: manifest for jenkins:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

**Comment by slide** [comment]
You need to use jenkins/jenkins. jenkins is an org on dockerhub, there are multiple images published to the org.

**Comment by vmwarelab** [comment]
shouldn't this be updated then cause it doesn't say to use jenkins/jenkins but its more like 
docker run jenkins

**Comment by slide** [comment]
Updated where?

**Comment by slide** [comment]
You mean the big deprecation notice that says don't use that image?

**Comment by vmwarelab** [comment]
fair enough .. but the example should also reflect that . since it's the first thing you see..

**Comment by slide** [comment]
That repo is not managed by the Jenkins project.
