### ISSUE TITLE
ssh id_pub key

### ISSUE THREAD

**Issue by WillBeebe** [jenkinsci/docker#110]
I'm trying to use the scm-sync-config plugin in jenkins and that needs a ssh key in $JENKINS_HOME/.ssh/id_pub 

I tried ADD and COPY but those don't respect the user they are run as, so the ssh folder is owned by root. Since /var/jenkins_home is a volume chmod does not work either.

Any ideas on how I can get a ssh key into that location owned by the jenkins user?

**Comment by carlossg** [comment]
You put anything that you want in JENKINS_HOME under /usr/share/jenkins/ref/ and the jenkins.sh script will copy it on startup

**Comment by WillBeebe** [comment]
thank you!
