### ISSUE TITLE
install-plugins is deprecated and yet recommended

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/docker#1100]
A warning is printed here: 
https://github.com/jenkinsci/docker/blob/0e8271bf693bddcaa76cfdedb8ef5d8ae940b859/install-plugins.sh#L23

Yet `install-plugins` still seems to be the recommended approach in the documentation because the Plugin Manager / `jenkins-plugin-cli` is listed as in preview:
https://github.com/jenkinsci/docker/blob/ebb29a040aca944474542400a34f48e1eb8fa628/README.md#preinstalling-plugins

**Comment by slide** [comment]
I think this will be resolved with #1101 1101
