### ISSUE TITLE
cannot create directory ‘/var/jenkins_home/init.groovy.d’: Permission denied

### ISSUE THREAD

**Issue by hwangjr** [jenkinsci/docker#111]
NOTE:
This will store the jenkins data in /your/home on the host. Ensure that /your/home is accessible by the jenkins user in container (jenkins user - uid 1000).

STEP:
i just clone the repo, and build the image, then run:
``` bash
docker run --name jenkins -p 8080:8080 -v /data/jenkins:/var/jenkins_home 192.168.1.175:5000/hwangjr/jenkins
```
but i just get error:
``` bash
mkdir: cannot create directory ‘/var/jenkins_home/init.groovy.d’: Permission denied
cp: cannot create regular file ‘/var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy’: No such file or directory
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Jun 12, 2015 2:33:41 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Jun 12, 2015 2:33:41 PM winstone.Logger logInternal
INFO: Winstone shutdown successfully
Jun 12, 2015 2:33:41 PM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.FileNotFoundException: /var/jenkins_home/war/META-INF/MANIFEST.MF (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:280)
	at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
	at winstone.HostGroup.initHost(HostGroup.java:66)
	at winstone.HostGroup.<init>(HostGroup.java:45)
	at winstone.Launcher.<init>(Launcher.java:143)
	at winstone.Launcher.main(Launcher.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Main._main(Main.java:293)
	at Main.main(Main.java:98)

```

SOLUTION:
from google, i found one solution is to set /data/jenkins to 1000, but it just for ubuntu system:
``` bash
chown 1000:1000 -R /data/jenkins
```

BUT:
My system is centos7, not ubuntu. so even i set "chmod 777 -R /data/jenkins", i still get this error. this error is the AUFS error, anyone have solutions?

HELP~~~

**Comment by carlossg** [comment]
You need to make sure the user id (not the name `jenkins`) of the container has permissions in the host  /data/jenkins dir.
Run `ps -fea` in the host and you should see the jenkins process and what user it runs under. Or use `docker run` with `-u` and a user that has permissions in that dir

**Comment by hwangjr** [comment]
i just run:
``` bash
docker run -d --name jenkins -p 8080:8080  192.168.1.175:5000/hwangjr/jenkins
ps -fea | grep jenkins
```
then get:
``` bash
[root@localhost ~]# ps -fea | grep jenkins
1000      13233   5494 99 11:06 ?        00:00:08 java -jar /usr/share/jenkins/jenkins.war
root      13297  13160  0 11:06 pts/0    00:00:00 grep --color=auto jenkins
```

**Comment by hwangjr** [comment]
i think the user id is right: 1000, and i set the permission:
``` bash
chown -R 1000:1000 /data/jenkins
# or chmod -R 777 /data/jenkins
```
But, it does not work~~

**Comment by carlossg** [comment]
so the user 1000 needs permissions in `/data/jenkins`

can you run `su 1000 -c "mkdir /data/jenkins/init.groovy.d"` ?

**Comment by hwangjr** [comment]
i run the command in the host:
``` bash
[root@localhost ~]# su 1000 -c "mkdir /data/jenkins/init.groovy.d"
su: user 1000 does not exist
```

**Comment by frankcarey** [comment]
I've been trying to run this on google container engine for hours with no luck. Using kubectl logs POD, I see the same error. I don't see how I can get the volume to mount like this, any clues?

Here is what I added:
```Diff
                 "protocol": "TCP"
               }
             ],
+            "volumeMounts": [
+              {
+                "name": "jenkins-persistent-storage",
+                "mountPath": "/var/jenkins_home"
+              }
+            ],
             "imagePullPolicy": "IfNotPresent"
           }
         ],
+        "volumes": [
+          {
+            "name": "jenkins-persistent-storage",
+            "gcePersistentDisk": {
+              "pdName": "jenkins-disk",
+              "fsType": "ext4"
+            }
+          }
+        ],
         "restartPolicy": "Always",
         "dnsPolicy": "ClusterFirst"
       }
```

**Comment by carlossg** [comment]
@hwangjr yes, you need the dir to be owned by the same user the container is running as
@frankcarey same thing, you need to take care of permissions of the volumes, see https://github.com/GoogleCloudPlatform/kubernetes/issues/2630

**Comment by jiakuan** [comment]
I encountered the same issue, after I set the folder (on host machine) to
777, then it worked.

**Comment by hwangjr** [comment]
@jiakuan Do u have a user id 1000?   under /etc/passwd file~

**Comment by jiakuan** [comment]
No, I don't have user id.

**Comment by hwangjr** [comment]
@jiakuan This is wired.. can u run:
``` bash
su 1000 -c "mkdir /data/jenkins/init.groovy.d"
```

**Comment by jiakuan** [comment]
FROM jenkins
# if we want to do something via root
USER root
RUN mkdir /data/jenkins/init.groovy.d # other commands such as chmod
can be put here
USER jenkins # drop back to the regular jenkins user - good practice

Perhaps you can do something like this in your Dockerfile?

**Comment by hwangjr** [comment]
@jiakuan This is fine, but if jenkins do not have the permission to create files, then when we run jenkins use user jenkins, it would also have the permission problem like this~

**Comment by frankcarey** [comment]
@jiakuan yeah, your suggestion is what I'm thinking.. Seems like it would make sense for the default Dockerfile to do that.

**Comment by carlossg** [comment]
The Dockerfile can't create anything in a volume dir (jenkins home), it gets lost. That's why plugins and other files are copied at runtime.

**Comment by hwangjr** [comment]
@carlossg so, i have to create a user and the user id should be 1000, then i chown the folder R/W/X permission?

**Comment by carlossg** [comment]
The easiest way is to add 777 permissions to the host dir where the volume is mapped, that way you see what host user is creating the files, and then adjust accordingly

**Comment by hwangjr** [comment]
@carlossg In fact, i have try to add the permission 777, and i got this error too~~   This make me a little confused..

**Comment by theotherwhitemeat** [comment]
If the permissions are setup correctly and you're still encountering this issue, check your SELinux configuration:
http://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

**Comment by hwangjr** [comment]
@theotherwhitemeat Thanks, i will try it later~~

**Comment by Bujail** [comment]
[plugins.txt](https://github.com/jenkinsci/docker/files/1060096/plugins.txt)

[groovyscript.txt.txt](https://github.com/jenkinsci/docker/files/1060095/groovyscript.txt.txt)
Hi All,
I have similar problem. While creating a Jenkins deployment in GKE, It is not loading my groovy scripts in /var/jenkins_home/init.groovy.d files other than "tcp-slave-agent-port.groovy" file. Groovy script loaded to image while building my custom image from the official one. This is happening if I am attaching persistent storage. If I am running the deployment without volume attachment, everything will works fine. Anyone can help me please?

[deployment.txt](https://github.com/jenkinsci/docker/files/1060109/deployment.txt)
[Dockerfile.txt](https://github.com/jenkinsci/docker/files/1060110/Dockerfile.txt)
[groovyscript.txt.txt](https://github.com/jenkinsci/docker/files/1060111/groovyscript.txt.txt)
[plugins.txt](https://github.com/jenkinsci/docker/files/1060112/plugins.txt)
[storage.txt](https://github.com/jenkinsci/docker/files/1060113/storage.txt)
[storageclass.txt](https://github.com/jenkinsci/docker/files/1060114/storageclass.txt)
