### ISSUE TITLE
Where are CentoOS based images?

### ISSUE THREAD

**Issue by juanmariareina** [jenkinsci/docker#1113]
Hi everyone

First of all my apologies if I'm not asking in the right place, but I've found something that  concerns me a little bit. I'm using this image available in dockerhub: jenkins/jenkins:2.291-centos, but I can't find here its source project.

Am I doing something wrong? Has something happened with CentOS based versions? Do I have to move to Debian based? I don't feel completely comfortable not knowing what is included in the image I'm using.

Thanks in advance and again my apologies. I will appreciate if you kindly address me to the right place to ask.

**Comment by slide** [comment]
Here is the dockerfile for that image: https://github.com/jenkinsci/docker/blob/master/8/centos/centos8/hotspot/Dockerfile

**Comment by juanmariareina** [comment]
Hmm, I'm sorry but the image you address doesn't contain the Jenkins versión I mentioned (2.291). In other words what I can find in [dockerhub ](https://hub.docker.com/layers/jenkins/jenkins/2.291-centos/images/sha256-79af994ab1d0e0f82e5e3de73f4278d3f07031d64472f0833af0c70d354db260?context=explore) seems to not being referenced here in github (at least as far as I could see)

**Comment by slide** [comment]
The Jenkins version is a variable in the Dockerfile. It is overridden during the build process on dockerhub builds. 

https://github.com/jenkinsci/docker/blob/master/8/centos/centos8/hotspot/Dockerfile#L53
https://github.com/jenkinsci/docker/blob/master/8/centos/centos8/hotspot/Dockerfile#L57
https://github.com/jenkinsci/docker/blob/master/8/centos/centos8/hotspot/Dockerfile#L60

**Comment by juanmariareina** [comment]
Nice!
Thanks a lot for your information! You really helped me
Have a nice day. Best regards!
