### ISSUE TITLE
This error may also indicate that the docker daemon is not running

### ISSUE THREAD

**Issue by bestofyour** [jenkinsci/docker#1114]
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1...
- Step 2...

### Results

Expected result:

Actual result:

**Comment by slide** [comment]
You missed filling out the template information.

**Comment by MarkEWaite** [comment]
Closing issue due to insufficient information
