### ISSUE TITLE
publish jdk11-slim (11/debian/buster-slim/hotspot)

### ISSUE THREAD

**Issue by pjungermann** [jenkinsci/docker#1115]
### Feature Request

Currently, there are the variants with JDK8
```
{version}
{version}-alpine
{version}-centos
{version}-centos7
{version}-slim
```

and for JDK11, there is only
```
{version}-jdk11
```

Another version `{version}-jdk11-slim` would be great and the basis for it seems to exist at the repo, but is not published.

You could consider to publish all variants for both JDK8 and JDK11 (as long as you still want to maintain JDK8). This seems reasonable as you seem to promote the use of the jdk11 variant (e.g., at the README.md). Nevertheless, JDK8 has more broader support.

```
{version}-{jdk}-{variant}
```

**Comment by slide** [comment]
We are looking at making jdk11 the default for all docker images. We don't want to add that many additional images because then it adds too much time for various aspects of releases (mainly security releases). It may seem like its "free" to do so, but it is not.

**Comment by MarkEWaite** [comment]
[Jenkins enhancement proposal](https://github.com/jenkinsci/jep/pull/374) has been submitted to switch to Java 11 as the default JDK in Docker images.  The [proposal](https://github.com/jenkinsci/jep/blob/78c0bf92e41b50bb7a8e40b3651863fee728bd0b/jep/0000/README.adoc) switches 2.302.1 slim, centos7, alpine, and debian images from Java 8 to Java 11.  Planned release date is Aug 25, 2021.

A new image will be provided with the label `slim-jdk8` for those users who must remain with JDK 8.

**Comment by MarkEWaite** [comment]
Jenkins 2.307 published `slim-jdk11` and `slim` as Java 11 images and `slim-jdk8` as a Java 8 image Aug 17.2021.
