### ISSUE TITLE
docker jenkins log timezone question?

### ISSUE THREAD

**Issue by ICLXL** [jenkinsci/docker#1116]
Run command:
docker run -dit \
-v /data/jenkins_data/jenkins_home:/var/jenkins_home \
-v /usr/local/apache-maven-3.8.1:/usr/local/apache-maven-3.8.1 \
-v /usr/local/apache-maven-3.8.1/repository:/usr/local/apache-maven-3.8.1/repository \
-v /usr/local/jdk-11.0.11:/usr/local/jdk-11.0.11 \
-v /data/jenkins_data/profile:/etc/profile \
-v /etc/localtime:/etc/localtime \
-v /usr/bin/git:/usr/bin/git \
--env JAVA_VERSION=jdk-11.0.11+9 \
--env JAVA_HOME=/usr/local/jdk-11.0.11 \
--env PATH=/sbin:/bin:${PATH} \
--env JAVA_OPTS=-Duser.timezone=Asia/Shanghai \
--restart=always \
-u 1000:1000 \
-p 8080:8080 -p 50000:50000 \
--name nzhixJenkins \
jenkins/jenkins:lts-jdk11

log:
![image](https://user-images.githubusercontent.com/30027321/119783598-f0c03b80-beff-11eb-87ee-fe1f312a027b.png)

current time
![image](https://user-images.githubusercontent.com/30027321/119783654-ff0e5780-beff-11eb-9c5e-b059f1ed1375.png)

**Comment by LinuxSuRen** [comment]
The log output is correct. The time `15:26:48 +8` belongs to UTC-8, `07:11:00` belongs to UTC-0.

`07+8=15`

**Comment by ICLXL** [comment]
yes,
I have tried adding this mapping -v /etc/localtime:/etc/localtime 
Already running ...
step1: docker exec -it nzhixJenkins bash
step2:date -R
step2 result:
![image](https://user-images.githubusercontent.com/30027321/119798157-74ccf000-bf0d-11eb-8fda-caea69faed26.png)

**Comment by ICLXL** [comment]
Jenkins in the container, the system time in the container is not used

**Comment by ICLXL** [comment]
Timestamps in logs are best left in UTC.
https://issues.jenkins.io/browse/JENKINS-57599
