### ISSUE TITLE
I got this error during bind mount.

### ISSUE THREAD

**Issue by tonmoy1996** [jenkinsci/docker#1141]
FROM node:latest
WORKDIR /app
COPY package.json .
RUN npm install
COPY . ./
EXPOSE 3000
CMD ["npm","run","dev"]

//command
docker run -v %cd%: /app -p 3000:3000 -d --name nodec node-app -> my command
Unable to find image 'js:latest' locally
docker: Error response from daemon: pull access denied for js, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by MarkEWaite** [comment]
I see nothing in this issue report that is related to the Docker image for the Jenkins controller.  Can you provide more details that explain why this is related to the Docker for the Jenkins controller.

**Comment by tonmoy1996** [comment]
Basically I used docker run -v %cd%: /app -p 3000:3000 -d --name nodec node-app -> my command
command to run node js app for bind mount so that it can listen to my change in the local directory and update the remote repos in docker as well. But I got the previous error. How can I solve this problem??

**Comment by MarkEWaite** [comment]
I see nothing in your additional explanation that leads me to believe this is related to the Docker image for the Jenkins controller.  Closing this issue.  Please raise questions in other locations rather than using this issue tracker to ask an unrelated question.
