### ISSUE TITLE
Docker images manifest invalid for jenkins/jenkins:2.300-alpine and higher

### ISSUE THREAD

**Issue by bpazera** [jenkinsci/docker#1148]
### Version report

Jenkins and plugins versions report:

```
jenkins:2.300-alpine and higher
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 16.04
Artifactory 7.11.2 rev

Client: Docker Engine - Community     19.03.13
Server: Docker Engine - Community     19.03.13
containerd:      1.3.7
```

### Reproduction steps

- docker pull jenkins/jenkins:2.302-alpine
- docker tag docker.io/jenkins/jenkins:2.302-alpine artifactory.url/jenkins/test:2.302-alpine_no_modif
- docker push artifactory.url/jenkins/test:2.302-alpine_no_modif

### Results

Expected result:

docker pushed successfully

Actual result:

The push refers to repository [artifactory.url/jenkins/test]
49397be1a3c7: Layer already exists 
17d1297bbbbc: Layer already exists 
91729bde23cb: Layer already exists 
bc066fd1cd19: Layer already exists 
ed7aae6b92e6: Layer already exists 
0e92ccb18d3e: Layer already exists 
49973173f45a: Layer already exists 
2d3726108922: Layer already exists 
f3c9d8bc217b: Layer already exists 
2052998cb151: Layer already exists 
88c428ccbc1c: Layer already exists 
2f62d9ed40b9: Layer already exists 
afe24581be4e: Layer already exists 
65886ee6664a: Layer already exists 
72e830a4dff5: Layer already exists 
manifest invalid: manifest invalid

### Additional info

When doing the same but with jenkins/jenkins:2.299-alpine and jenkins/jenkins:2.298-alpine
- docker pull jenkins/jenkins:2.299-alpine
- docker tag docker.io/jenkins/jenkins:2.299-alpine artifactory.url/jenkins/test:2.302-alpine_no_modif
- docker push artifactory.url/jenkins/test:2.302-alpine_no_modif

Everything works without problem
Also no problems for other images tagged the same way

beside invalid manifest on push image works correctly

**Comment by bpazera** [comment]
it may be related with this workaround https://github.com/jenkinsci/docker/commit/c025bbadd264dd585c07932e13cd4e13193d0b1c

**Comment by MarkEWaite** [comment]
I'm unable to duplicate the problem when I push the image to Dockerhub.  The steps I used were:

```
$ docker pull jenkins/jenkins:2.302-alpine
$ docker tag jenkins/jenkins:2.302-alpine markewaite/experiments:2.302-alpine
$ docker push markewaite/experiments:2.302-alpine
The push refers to repository [docker.io/markewaite/experiments]
49397be1a3c7: Mounted from jenkins/jenkins
17d1297bbbbc: Mounted from jenkins/jenkins
91729bde23cb: Mounted from jenkins/jenkins
bc066fd1cd19: Mounted from jenkins/jenkins
ed7aae6b92e6: Mounted from jenkins/jenkins
0e92ccb18d3e: Mounted from jenkins/jenkins
49973173f45a: Mounted from jenkins/jenkins
2d3726108922: Mounted from jenkins/jenkins
f3c9d8bc217b: Mounted from jenkins/jenkins
2052998cb151: Mounted from jenkins/jenkins
88c428ccbc1c: Mounted from jenkins/jenkins
2f62d9ed40b9: Mounted from jenkins/jenkins
afe24581be4e: Mounted from jenkins/jenkins
65886ee6664a: Mounted from jenkins/jenkins
72e830a4dff5: Mounted from jenkins/jenkins
2.302-alpine: digest: sha256:4b72597253c967b7d5ef15a9bd123e840463ca8d49dbd549a35faad4eff29226 size: 3459
```

When I perform the same operations with `jenkins/jenkins:2.299-alpine`, I see similar output:

```
$ docker pull jenkins/jenkins:2.299-alpine
$ docker tag jenkins/jenkins:2.299-alpine markewaite/experiments:2.299-alpine
$ docker push markewaite/experiments:2.299-alpine
c129b280af80: Mounted from jenkins/jenkins
3eff382c5fd6: Mounted from jenkins/jenkins
391b068fcce0: Mounted from jenkins/jenkins
66a7d6bb6438: Mounted from jenkins/jenkins
6f00df9ead15: Mounted from jenkins/jenkins
c5cf1f4aa3de: Mounted from jenkins/jenkins
7e8b28096252: Mounted from jenkins/jenkins
e96892eb93d3: Mounted from jenkins/jenkins
feedf685c110: Mounted from jenkins/jenkins
cec09bc4df38: Mounted from jenkins/jenkins
32096b6c3d15: Mounted from jenkins/jenkins
b35d3039de6c: Mounted from jenkins/jenkins
ce65525c1b81: Mounted from jenkins/jenkins
b2d5eeeaba3a: Mounted from jenkins/jenkins
2.299-alpine: digest: sha256:56e2252f5a86e7e24e93b1bab9a36c4267938f3777000a348e17b78243840f4a size: 3248
```

Possibly a difference between your artifact repository and the Dockerhub artifact repository?
