### ISSUE TITLE
问题描述： 现有一个镜像文件，假如为image1:latest,  情形一 # 当执行以下命令，显示一直在重启 docker run -d --restart=always --gpus all --name test2_autoseg  image1:latest python server.py 1 2 情形二 # 先执行 docker run -it -d --restart=always --gpus all --name test2_autoseg  image1:latest /bin/bash # 再执行 docker exec -it test2_autoseg /bin/bash # 最后执行 python server.py 1 2 3 4 5 6 情形一，一直重启中；情形二，正确。为什么，求助中？ 

### ISSUE THREAD

**Issue by xuwei1119** [jenkinsci/docker#1151]

**Comment by xuwei1119** [comment]
问题描述：
现有一个镜像文件，假如为image1:latest,

情形一
# 当执行以下命令，显示一直在重启
docker run -d --restart=always --gpus all --name test2_autoseg  image1:latest python server.py

情形二
# 先执行
docker run -it -d --restart=always --gpus all --name test2_autoseg  image1:latest /bin/bash
# 再执行
docker exec -it test2_autoseg /bin/bash
# 最后执行
python server.py

**Comment by xuwei1119** [comment]
情形一，一直重启中；情形二，正确。为什么，求助中？

**Comment by timja** [comment]
We require our issues in English, please translate.
