### ISSUE TITLE
Docker self-triggered  python script program Error!

### ISSUE THREAD

**Issue by xuwei1119** [jenkinsci/docker#1152]
Problem description:  There is a image file, if it is image1:latest, 
situation 1： 
docker run -d --restart=always --gpus all --name test2_autoseg image1:latest python server.py 
Situation 2：
    step1:
    docker run -it -d --restart=always --gpus all --name test2_autoseg image1:latest /bin/bash 
    step2:
    docker exec -it test2_autoseg /bin/bash 
    step3:
    python server.py 

In case situation 1：, it's always restarting;  Case Situation 2, correct.  Why, for help?

**Comment by timja** [comment]
This issue doesn’t make any sense, I can’t see how this is related to Jenkins
