### ISSUE TITLE
Jenkins image not available on Docker Hub !

### ISSUE THREAD

**Issue by pankaj-dahiya** [jenkinsci/docker#1168]
ubuntu@ip-172-31-9-42:~$ sudo docker pull jenkins
Using default tag: latest
Error response from daemon: manifest for jenkins:latest not found: manifest unknown: manifest unknown

**Comment by pankaj-dahiya** [comment]
My bad ... found comment mentioning that it has moved to jenkins/jenkins.

My advice.... PUT THIS COMMENT IN CAPITALS that :

THIS IMAGE IS UNAVAILABLE AND SHIFTED TO "THIS" REPO

**Comment by slide** [comment]
We don't control that repo, it is part of the docker folks stuff, with that, we can't change anything on there ourselves. We did get the large DEPRECATION NOTICE that references the correct image on there though.

![image](https://user-images.githubusercontent.com/55871/127522510-3430cabe-f25d-446f-bb49-963bfec0234f.png)
