### ISSUE TITLE
/usr/local/bin/jenkins.sh: line 34: exec: jenkins: not found

### ISSUE THREAD

**Issue by venkatramachandran** [jenkinsci/docker#117]
I created a `jenkins` user using:
```
sudo useradd --system --create-home --home /var/jenkins --uid 1000 jenkins
```

and am running the jenkins image via:
```
docker run --name jenkins -d -p 8080:8080 -v /var/jenkins:/var/jenkins_home jenkins jenkins
```

Yet, the container exits within seconds with `docker logs` producing the following output:
```
/usr/local/bin/jenkins.sh: line 34: exec: jenkins: not found
```

`docker run jenkins ls -l /usr/local/bin/jenkins.sh` produces the following output:
```
-rwxr-xr-x 1 root root 1284 May 15 08:45 /usr/local/bin/jenkins.sh
```

What am I missing here? Why is the container erroring out?

**Comment by carlossg** [comment]
you have an extra `jenkins` at the end of `docker run`

**Comment by venkatramachandran** [comment]
@carlossg : Thanks! Silly me!
