### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): Error making old root private after pivot: invalid argument

### ISSUE THREAD

**Issue by zuowanbushiwo** [jenkinsci/docker#1179]
My host machine:
ubuntu 18.04

and docker version:
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~18.04.1
 Built:             Wed Aug  4 22:43:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu1~18.04.1
  Built:            Wed Aug  4 19:22:59 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          1.0.0~rc95-0ubuntu1~18.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit: 

![GZ~4TTARQ7~OT3U{J~BR_FJ](https://user-images.githubusercontent.com/3354428/129656984-2e11f7e3-8717-4516-8b9a-ec7a0a02cb3a.jpg)

docker image:
docker pull multiarch/crossbuild:latest  (https://hub.docker.com/r/multiarch/crossbuild, github dockerfile:  https://github.com/multiarch/crossbuild/blob/master/Dockerfile)

wrong result:

![RNM_G0) 044)$ OC8NVK5GD](https://user-images.githubusercontent.com/3354428/129656867-e44ba483-1440-4421-9f59-f3b437b9a9b8.jpg)

How to fix this error?  I searched on google for a long time, but no relevant information was found。 Thanks！

**Comment by timja** [comment]
The only docker image mentioned is not maintained by us, why do you think this belongs here?

**Comment by zuowanbushiwo** [comment]
Thanks，I thought this was the forum，can talk about the problems encountered in use。
