### ISSUE TITLE
Multiple DingTalk notifies the robot that the page will be messed up

### ISSUE THREAD

**Issue by enjoycx** [jenkinsci/docker#1195]

**Comment by enjoycx** [comment]
![image](https://user-images.githubusercontent.com/56945691/162698054-12ac514a-bc79-41f9-8001-138f340e2cd7.png)

**Comment by enjoycx** [comment]
![image](https://user-images.githubusercontent.com/56945691/162698295-663c5484-ad3f-45c7-9f33-4bd5cb44d6f1.png)

**Comment by timja** [comment]
This is nothing to do with the https://github.com/jenkinsci/docker/ repository

Likely to do with tables to divs, see https://www.jenkins.io/doc/developer/views/table-to-div-migration/
