### ISSUE TITLE
Tag 2.303.1-lts missing on Docker Hub

### ISSUE THREAD

**Issue by fabricat** [jenkinsci/docker#1196]
### Version report

Jenkins version: **2.303.1**

### Reproduction steps

Look at [Docker Hub](https://hub.docker.com/r/jenkins/jenkins/tags?page=1&ordering=last_updated&name=2.303.1-lts) or run:
```
docker pull jenkins/jenkins:2.303.1-lts
```
### Results

Expected result:

I expected tag `2.303.1-lts` to exist, as like as all the old LTS releases.
```
2.303.1-lts: Pulling from jenkins/jenkins
...
```
Actual result:

Tag does not exist:
```
Error response from daemon: manifest for jenkins/jenkins:2.303.1-lts not found: manifest unknown: manifest unknown
```

**Comment by fabricat** [comment]
I see. Thanks @timja for pointing that out.

Sorry, I missed to carefully read the upgrade guide. I only hastily read the changelog (where this change is not mentioned, though).

**Comment by yeroc** [comment]
Is there any chance this decision will be revisited.  For those of us not embedded in the Jenkins project itself it was really nice to be able to visually confirm the docker image we were referencing was an LTS version.  Having this in the tag was a very nice property up until now.

**Comment by yeroc** [comment]
@timja Incidentally where do we find the JEP you referenced?  I googled for "jenkins jep docker lts tag" and nothing is turning up.  I did see the note in the upgrade guide but no justification was presented.  Can't find a related ticket in JIRA either.

**Comment by MarkEWaite** [comment]
The [Jenkins Enhancement Proposal](https://github.com/jenkinsci/jep/blob/57c441bebe19749f06f023aa02c222323ba9d15c/jep/0000/README.adoc).

**Comment by timja** [comment]
we can probably re-add this given it seems a number of people use it (mostly because the docker hub UI is not the best).

https://github.com/jenkinsci/docker/blob/master/docker-bake.hcl is the file that needs updating
