### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by trick77** [jenkinsci/docker#120]
I'm always getting a permission error in a derived Dockerfile when jenkins.sh is being called. It happens here:
echo "$f" >> $COPY_REFERENCE_FILE_LOG

My solution was to move the VOLUME directive at the end in the original Dockerfile because otherwise the chown permissions won't stick and everything will still be set to root:root instead of jenkins:root.

**Comment by carlossg** [comment]
this has been fixed in c8c95d
just set COPY_REFERENCE_FILE_LOG to somewhere in the JENKINS_HOME

**Comment by trick77** [comment]
Same happens in plugins.sh which tries to write to /usr/share/jenkins/ref/plugins.

**Comment by carlossg** [comment]
are you switching to root user as done in https://github.com/jenkinsci/docker#installing-more-tools ?

**Comment by trick77** [comment]
`FROM jenkins

COPY plugins.txt /usr/share/jenkins/ref/

RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt`

That's what I'm doing, but for some reason the file plugins.txt does not exist in the target directory once the container is up. Looks like a user error but I just can't figure out why something that simple goes wrong.

**Comment by carlossg** [comment]
works fine here

**Comment by shyr** [comment]
Is it closed? It also happen to me. How to solve this problem?

**Comment by trick77** [comment]
In my case, I used a script I wrote in which I used the wrong base image (not the derived).
