### ISSUE TITLE
No lts tag for 2.303.1 version on docker hub

### ISSUE THREAD

**Issue by ranebull** [jenkinsci/docker#1206]
Hello! 

I see, that use lts tag on Dockerhub for
```
jenkins/jenkins:2.289.2-lts
jenkins/jenkins:2.289.3-lts
```
versions and it very useful.

Please, create **lts** tag for **2.303.1** version.

Thank you!

**Comment by timja** [comment]
Duplicate of https://github.com/jenkinsci/docker/issues/1196
