### ISSUE TITLE
Error to install credentials in docker image

### ISSUE THREAD

**Issue by pazfelipe** [jenkinsci/docker#1208]
I've just pulled jenkins from the [docker official repository](https://hub.docker.com/r/jenkins/jenkins). After trying to install suggested plugins, I'm getting this error
![image](https://user-images.githubusercontent.com/19727571/132687884-e5be2d08-874f-449e-afcf-fbeca1da6d04.png)

## Steps I did
I run the following command:
```bash
docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11
```

After I've got many errors in installation, I've tried to install them (plugins) manually and I got the errors above.

_I'm using fedora 38_

**Comment by timja** [comment]
Being tracked at https://issues.jenkins.io/browse/INFRA-3067
