### ISSUE TITLE
Documentation - how to configure ssh keys using volumes

### ISSUE THREAD

**Issue by Toub** [jenkinsci/docker#121]
I don't understand how works ssh keys for jenkins.
I would like to be able to mount a volume containing jenkins ssh files (id_rsa, id_rsa.pub, config and known_hosts) so I don't have to configure them manually in the UI.
Or configure several keys as explained here: https://firmhouse.com/blog/configuring-multiple-private-ssh-deploy-keys-in-jenkins-for-github-com/
I did a few tries, e.g. using /var/jenkins_home/.ssh but I was not able to do it.
I think that this is a very common need and that it should be documented somewhere.

Thanks!

**Comment by carlossg** [comment]
you mount a host volume as explained in the readme

    docker run -p 8080:8080 -p 50000:50000 -v /your/home:/var/jenkins_home jenkins

and put whatever you want in the host /your/home/.ssh/

**Comment by Toub** [comment]
That's what I did, and I have my pub key in /var/jenkins_home/.ssh, but from jenkins UI (git configuration of my build): 
* if I configure the git repository with credential = "none", it fails with "Permission denied"
* if I configure so it uses the key in /var/jenkins_home/.ssh/.id_rsa (" From a file on Jenkins master"), it fails too
* if I configure directly the content of /var/jenkins_home/.ssh/id_rsa as crednetial, it works

Did you manage to make it use the file on the disk?

**Comment by carlossg** [comment]
if the files are there then it is more a question for the jenkins user list
check .ssh permissions are correctly set or ssh client will refuse to read them

**Comment by Toub** [comment]
Thanks for your help.
I finally managed to make it work after executing the following command as root: 
    cp /var/jenkins_home/.ssh/id_rsa* /root/.ssh/

So the trick is that jenkins is not lauched as "jenkins" user, but as root.
However, "jenkins user exists.

So, or we should open a distinct bug to launch the application as "jenkins" user, or we have to document this behavior (at least say in the doc that the server is launched as root, so the ssh config is located at /root/.ssh).

**Comment by carlossg** [comment]
the default user is jenkins not root, for sure
https://github.com/jenkinsci/docker/blob/master/Dockerfile#L43

**Comment by Toub** [comment]
You are right!

The problem was that I have additional install instructions as root in my derived Dockerfile, so the server is launched as root.

So I simply have to append an extra "USER jenkins" in the end of my Dockerfile.

I don't know if there are things to do in jenkins.sh script to prevent this problem to occur?

    #!/bin/bash
    if [[ $EUID -e 0 ]]; then
       echo "This script must NOT be run as root" 
       exit 1
    fi

or 

    su jenkins -c '...

**Comment by carlossg** [comment]
not really, people can choose to run the container under whatever user they want
