### ISSUE TITLE
ERROR: No build record  could be located.

### ISSUE THREAD

**Issue by gilShin** [jenkinsci/docker#1215]
### Version report

Jenkins and plugins versions report:

```
2.289.2-lts
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 18.04
```

### Reproduction steps

Running Jenkins pipeline whilke using shared libraries under vars folder.
Calling a function that exists in the shared libraries under the vars folder

### Results

Expected result:

Function is being called and works properly

Actual result:

It crashed at that point and the only error I can see in the console output is that it couldn't find the buid folder (I made sure that it does exist):
ERROR: No build record <path to job>#137 could be located.

**Comment by timja** [comment]
This repo is for issues directly relating to the docker image not for Jenkins itself or help.
