### ISSUE TITLE
I want to change the root context path for jenkins. So that I can access jenkins via this "http://<jenkinshost>:8080/jenkins"

### ISSUE THREAD

**Issue by PreetiCK** [jenkinsci/docker#122]
I want to change the root context path for jenkins. I can do it by changing /etc/default/jenklins file in normal installation of jenkins. But I am not getting where I need to change in order to change the root context for jenkins image.
 I checked in the container and there is no jenkins file under /etc/default. so I added that file through dockerfile and built new image. But the container is not strarting from the newly built docker image. Please suggest how to achieve this. I want url like http://<jenkinshost>:8080/jenkins

**Comment by carlossg** [comment]
jenkins is not started by init.d so that file is never read 

use something like

    docker run -p 8080:8080 jenkins --prefix=/
