### ISSUE TITLE
OCI runtime error

### ISSUE THREAD

**Issue by qq383199165** [jenkinsci/docker#1241]
### OCI runtime error

```
FATA[0001] OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/default/e068b9cb69f0ee25f6fd20084272991a894f36fe2523c59c3992d56891c0fc43/log.json: no such file or directory): fork/exec /usr/local/sbin/runc: exec format error: unknown
```
I'm a green hand and I don't know why. I would be grateful, if anyone has any information that can help.

**Comment by MarkEWaite** [comment]
The issue tracker is used to track issues with the Jenkins docker image.  Your request seems to be a request for help.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
