### ISSUE TITLE
Permissions stay root

### ISSUE THREAD

**Issue by SullivanWls** [jenkinsci/docker#1242]
Hello, I have jenkins install on Kubernetes, recently I had a crash. So I reinstall Jenkins with latest image but now I have a problem with permissions. All folders are root:jenkins instead of jenkins:jenkins and 777 permissions so too open to start a pipeline, and I don't have touch my deployment. So with this permissions problem I can't install plugins etc..

I don't understand.

`cp: preserving times for '/var/jenkins_home/plugins/blueocean-pipeline-editor.jpi': Operation not permitted`
`cp: preserving times for '/var/jenkins_home/plugins/kubernetes.jpi': Operation not permitted`
`cp: preserving times for '/var/jenkins_home/plugins/checks-api.jpi': Operation not permitted`

And folders permissions:

`drwxrwxrwx 2 root jenkins    0 Nov 24 14:00 casc_config`
`-rwxrwxrwx 1 root jenkins 6343 Nov 24 14:01 copy_reference_file.log`
`drwxrwxrwx 2 root jenkins    0 Nov 24 14:01 plugins`
`drwxrwxrwx 2 root jenkins    0 Nov 24 14:01 war`

expected:

`drwxr-sr-x 134 jenkins jenkins 36864 Nov 23 13:10 plugins`
`-rw-r--r--   1 jenkins jenkins   131 Nov 24 14:04 queue.xml`

Thank you.

**Comment by MarkEWaite** [comment]
The issue tracker is used to track issues with the Jenkins docker image.  Your request seems to be a request for help.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
