### ISSUE TITLE
Non-default TCP port for JNLP slave agents

### ISSUE THREAD

**Issue by jeichel-miovision** [jenkinsci/docker#125]
When I set "TCP port for JNLP slave agents" to a non-default value, such as 50001, the value is resets each time jenkins restarts.

The script, `init.groovy`, overrides my setting with the default value. While I have a workaround, it would be useful if the init.groovy script checked the jenkins config for the appropriate value, or is settable by default to an environmental variable.

Workaround:
For my purposes My dockerfile contains the following command, which sets the port to the environmental variable $JENKINS_SLAVE_AGENT_PORT
```
RUN sed -i -r "s|Jenkins.instance.setSlaveAgentPort\(50000\)|Jenkins.instance.setSlaveAgentPort\(env\['JENKINS_SLAVE_AGENT_PORT'\]\)|" /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
```

```
import hudson.model.*;
import jenkins.model.*;


Thread.start {
      sleep 10000
      println "--> setting agent port for jnlp"
      Jenkins.instance.setSlaveAgentPort(env['JENKINS_SLAVE_AGENT_PORT'])
}
```

**Comment by ndeloof** [comment]
Could you please share this via a pull request ?

**Comment by jeichel-miovision** [comment]
The pull request is based on my fix and will use an environmental variable to set the slave agent port.

A future feature might be reading the value directly from a Jenkins config file.

**Comment by carlossg** [comment]
#133 merged

**Comment by oliverlife** [comment]
qrqw
