### ISSUE TITLE
Releases for lts-rhel-ubi8-jdk11 missing lts from tag

### ISSUE THREAD

**Issue by skorhone** [jenkinsci/docker#1255]
## Description
Latest tag of ubi image is lts-rhel-ubi8-jdk11 while current version specific tag seems to be 2.319.1-rhel-ubi8-jdk11.

Not following the naming scheme makes it hard(er) to pin Dockerfile to specific lts version.

## Current
Tag is: 2.319.1-rhel-ubi8-jdk11

## Expected
Tag is: 2.319.1-lts-rhel-ubi8-jdk11

**Comment by timja** [comment]
can you submit a PR please? https://github.com/jenkinsci/docker/blob/master/docker-bake.hcl

**Comment by skorhone** [comment]
Was about to say that I don't have time, but seemed trivial enough to implement. So there you go

**Comment by timja** [comment]
> Was about to say that I don't have time, but seemed trivial enough to implement. So there you go

😄  easier for you to submit and me to approve something that trivial.
