### ISSUE TITLE
provide docker lts images with jdk8

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/docker#1265]
### What feature do you want to see added?

latest lts docker image seems to run with jdk11

```
docker run --rm -ti --entrypoint="java" jenkins/jenkins:2.319.1-lts -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```

The jdk11-variant has the very same digest
jenkins/jenkins:2.319.1-lts-jdk11

I am looking for the jdk8 variant, however there seems to be none. ;(

From my point of view either drop the jdk11 variant or publish a jdk8 variant as well...

Thx for any feedback

**Comment by pniederlag** [comment]
I created a PR which might solve the problem

https://github.com/jenkinsci/docker/pull/1266

**Comment by timja** [comment]
Sure, we are planning to remove support for Java 8 in the next few months, https://groups.google.com/g/jenkinsci-dev/c/YghQ0YP4m78

I would suggest moving to Java 11 instead if you are able to.

Is there anything holding you back?

**Comment by pniederlag** [comment]
that was blazingly fast, awesome, big thx. :->

Well, we currently use a plugin (crowd2) that is not really maintained and fails on java11, 
https://github.com/jenkinsci/crowd2-plugin/pull/40

We will probably have to replace it with something else, but it'll take another couple of weeks at least.

Thx for raising awareness, hope we will be ready on time.
