### ISSUE TITLE
Conflicting recommendations regarding bind mounts

### ISSUE THREAD

**Issue by noamtamim** [jenkinsci/docker#1267]
### Describe your use-case which is not covered by existing documentation.

In the README file, there are conflicting recommendations.
The [Usage](https://github.com/jenkinsci/docker#usage) section recommends **against** using bind mounts:
> ...
> NOTE: Avoid using a bind mount from a folder on the host machine into /var/jenkins_home ... 

The next section, [Backing up data](https://github.com/jenkinsci/docker#backing-up-data) recommends using bind mounts:
> If you **bind mount** in a volume - you can simply back up that directory (which is jenkins_home) at any time.
> 
> **This is highly recommended**. Treat the jenkins_home directory as you would a database - in Docker you would generally put a database on a volume.

As a user, I honestly don't know which option is better.

**Comment by timja** [comment]
named volumes are the recommendation, see https://github.com/jenkinsci/docker/issues/881#issuecomment-882611061

(docs need updating)

**Comment by noamtamim** [comment]
Thanks @timja for the reference. So I'm guessing this issue should stay open as a documentation task.
