### ISSUE TITLE
Build job cannot be recognized correctly after upgrade to new  version

### ISSUE THREAD

**Issue by jimmy-chow** [jenkinsci/docker#1275]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.319.1
OS: Linux - 3.10.0-957.21.3.el7.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-with-parameters:1.5
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-folder:6.17
command-launcher:1.6
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27.1
data-tables-api:1.11.3-6
display-url-api:2.3.5
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
font-awesome-api:5.15.4-5
generic-webhook-trigger:1.83
git:4.10.3
git-client:3.11.0
git-parameter:0.9.15
git-server:1.10
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:1.6
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0
jdk-tool:1.5
jersey2-api:2.35-3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
localization-support:1.1
localization-zh-cn:1.0.24
mailer:408.vd726a_1130320
matrix-auth:3.0.1
matrix-project:1.20
maven-plugin:3.16
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
publish-over:0.22
publish-over-ssh:1.20.1
resource-disposer:0.17
role-strategy:3.2.0
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
snakeyaml-api:1.29.1
sonar:2.14
ssh:2.6.1
ssh-credentials:1.19
sshd:3.1.0
structs:308.v852b473a2b8c
trilead-api:1.0.13
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1121.va_65b_d2701486
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
ws-cleanup:0.40
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

CentOS 7.6

### Reproduction steps

1. create build jobs in low version 2.222.3, for example, please check the job config.xml （change name to config.txt so that I can upload） in attachment.
[config.txt](https://github.com/jenkinsci/docker/files/7932560/config.txt)

2. upgrade jenkins to version 2.319.1

3. The job cannot be shown correctly in job config page.
- same properties are shown repeatly
- the value of some properties is wrong, for example, the publish server is Pannong_Test1_142 in config.xml, but in the page is shown as demo_env
![jenkins pannongdata com_9000_job_pn_test1_praccount_configure (1)](https://user-images.githubusercontent.com/57430215/150955253-24dc8b94-9210-4a70-8887-3562285fa2bf.png)

### Expected Results

Build job cannot be recognized correctly in new version

### Actual Results

Build job cannot NOT be recognized correctly in new version

**Comment by timja** [comment]
That is nothing to do with the docker image here, see https://www.jenkins.io/doc/developer/views/table-to-div-migration/
