### ISSUE TITLE
Some JDK17 images not being pushed since docker-bake refactor

### ISSUE THREAD

**Issue by timja** [jenkinsci/docker#1290]
### Expected Results

these should be updated:

jdk-17-preview
latest-jdk17-preview

### Actual Results

Last pushed 13 days ago:
![image](https://user-images.githubusercontent.com/21194782/155090943-a7f98481-209f-44bb-b49e-eb0bc5108d42.png)

### Anything else?

This refactoring was done 12 days ago:
https://github.com/jenkinsci/docker/pull/1285

@romainx do you think you could take a look please?

I couldn't see any other tags not being updated, this was reported on gitter https://gitter.im/jenkinsci/docker?at=62139788ddcba117a2ea0981

**Comment by itsmemac** [comment]
Thanks for the bug report, the issues seems to be resolved
Image is being built and published correctly now for JDK17 all images for v2.336
![image](https://user-images.githubusercontent.com/37410297/15529548-b67fee3e-fa38-4869-beb2-b11d7998ffc6.png)

**Comment by timja** [comment]
Maybe there was a one-off failure in pushing.

**Comment by romainx** [comment]
@timja sorry for the late answer and happy to see that it's fixed now.
However I have checked just to be sure and I can say the output is the same before and after refactor.

```bash
# before (494e54b)
LATEST_WEEKLY=true LATEST_LTS=true docker buildx bake -f docker-bake.hcl --print debian_jdk17 | jq -r '.target | keys[] as $k | "\($k) -> \(.[$k] | .tags[])"'                                     
# debian_jdk17 -> docker.io/jenkins/jenkins:2.303-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:latest-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:lts-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:2.303-lts-jdk17-preview

# after refactor
LATEST_WEEKLY=true LATEST_LTS=true docker buildx bake -f docker-bake.hcl --print debian_jdk17 | jq -r '.target | keys[] as $k | "\($k) -> \(.[$k] | .tags[])"'
# debian_jdk17 -> docker.io/jenkins/jenkins:2.303-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:latest-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:lts-jdk17-preview
# debian_jdk17 -> docker.io/jenkins/jenkins:2.303-lts-jdk17-preview
```

Best.
