### ISSUE TITLE
Initial plug-in download and setup in the m1 mac with arm64 image environment is too slow.

### ISSUE THREAD

**Issue by doljae** [jenkinsci/docker#1297]
### Jenkins and plugins versions report

- Used Jenkins image: `jenkins/jenkins:jdk17-preview`

### What Operating System are you using (both controller, and any agents involved in the problem)?

- **OS**: `macOS Monterey 12.2.1`
- **machine**: `Macbook pro (M1 chip)`, `iMac (intel chip)` with same memory
- **docker status**: Both machines are same & remove all containers without Jenkins which I create the docker command
- **docker resources**: Both machines are same(4 cpus, 4G memory, 2G swap)

### Reproduction steps

1. Run docker container using the command below
`docker run -dt -p 8085:8080 jenkins/jenkins:jdk17-preview`
2. Find the password for initialization in logs, enter the password
3. Choose `Install suggested plugins` then wait until all the plugins are fully installed
4. The time from the completion of the plug-in installation until the `Create First Admin User` screen is displayed was measured through the log.

### iMac(intel chip)
```bash
# takes about 8 minutes
2022-03-02 14:34:21.058+0000 [id=73] INFO hudson.PluginManager#install: Starting installation of a batch of 19 plugins plus their dependencies
2022-03-02 14:42:11.690+0000 [id=90] INFO h.m.UpdateCenter$CompleteBatchJob#run: Completing installing of plugin batch…
```
### Macbook Pro(M1 chip)
```bash
# takes too much time...
2022-03-02 14:30:17.373+0000 [id=15] INFO hudson.PluginManager#install: Starting installation of a batch of 19 plugins plus their dependencies
...
2022-03-02 14:48:07.853+0000 [id=86] INFO h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading scm-api
...
2022-03-02 14:54:49.999+0000 [id=86] INFO h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading popper-api
...
```

### Expected Results

The image was created with the same command, and since both images used images that fit each cpu architecture environment(M1 Macbook use arm64 based image), it should take a similar amount of time to download and install the initial plug-in.

### Actual Results

The initial setup time of the M1 Macbook is too long, even though the iMac's processor is much older than that of the Macbook. (While writing this issue, only 5 plugins have been installed yet.)

### Anything else?

At first, I tested it using the docker image of the jdk11 LTS version, had the same result.

**Comment by timja** [comment]
This sounds more like a network performance issue or a mirror issue.

Likely more appropriate on https://github.com/jenkins-infra/helpdesk

Where are you located?

What does this show? (don't need your actual IP but the mirror list at least)

https://get.jenkins.io/plugins/slack/602.v0da_f7458945d/slack.hpi?mirrorlist

On my mac M1 it takes less than 2 minutes:
```
2022-03-02 19:55:04.919+0000 [id=14]	INFO	hudson.PluginManager#install: Starting installation of a batch of 19 plugins plus their dependencies
2022-03-02 19:57:01.268+0000 [id=84]	INFO	h.m.UpdateCenter$CompleteBatchJob#run: Completing installing of plugin batch…
```

**Comment by doljae** [comment]
@timja, I captured and share the mirror server list.

### Mirror Server Lists
<img width="943" alt="image" src="https://user-images.githubusercontent.com/37795866/156470414-4f560a9e-042c-4081-adf0-4f33850a19da.png">

First of all, the network environment of the two PCs uses the same wireless LAN router. The difference is that the iMac is directly connected to the router and the Macbook is connected to Wifi.

I simply googled and tried a tool to measure internet speed, but there was no big difference. Do you have any more things to share or consider? In your M1 mac environment, it is set very quickly, so I think I can try something on my side...(Is your mac is with M1 Pro or Max?, of course I think there's no difference if I prepare M1 Pro or Max machines)

**Comment by doljae** [comment]
It took a very long time, and I was able to access the jenkins web page. However, I saw a notification that some plugins were not installed properly.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/37795866/156500556-c54a32e2-313d-4ed9-b668-33a3c604f2c3.png">

**Comment by timja** [comment]
Mine is the original M1 MacBook Pro from 2020 not one of the more powerful ones from last year.

**Comment by timja** [comment]
```
docker pull  jenkins/jenkins:jdk17-preview
docker run -dt -p 8085:8080 jenkins/jenkins:jdk17-preview
```

1. Unlock
2. Install suggested plugins

<img width="432" alt="image" src="https://user-images.githubusercontent.com/21194782/156607578-f9cb9b96-568e-4e40-be5c-4908c3bc3ae7.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/21194782/156607623-51d622e3-2dbd-46f7-b9ce-70eb0d5f563d.png">

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/21194782/156607682-67419395-bf41-4700-9b8f-770872b8593f.png">

**Comment by doljae** [comment]
I also think there will be a problem with my machine or setting, but I don't know the cause...😭 

Is there anything else I can do besides asking the infrastructure team?

**Comment by timja** [comment]
Not that I’m aware of

**Comment by doljae** [comment]
Sorry for the late reply.
Still seems slow Installing the plugin manually seems to be a way, but I can't seem to figure out the cause of this issue that only occurs on my machine.

**Comment by timja** [comment]
Could you try re-report to the infra help desk as I don’t think it’s to do with the docker image
