### ISSUE TITLE
A dependency job for docker.service failed. See 'journalctl -xe' for details.

### ISSUE THREAD

**Issue by LavenXu** [jenkinsci/docker#1337]
[root@localhost ~]# systemctl start docker
A dependency job for docker.service failed. See 'journalctl -xe' for details.

![微信图片_20220429140721](https://user-images.githubusercontent.com/56871298/165892622-8a314b75-10fb-47c8-b7ca-8fbef4a401b7.png)

**Comment by timja** [comment]
This repo is about the Jenkins controller docker image, not docker itself
