### ISSUE TITLE
Jenkins url not set

### ISSUE THREAD

**Issue by elopio** [jenkinsci/docker#138]
I have a problem with the jenkins url. When I deploy the container, it is not set:

ubuntu@snappy-jenkins:~/jenkins$ grep -r 10.55.32.40
ubuntu@snappy-jenkins:~/jenkins$

If I try to use $BUILD_URL in a job, it is not expanded.

Then I log in and go to http://10.55.32.40:8080/configure
The value of jenkins url is set to http://10.55.32.40:8080/
Next I save it and:

ubuntu@snappy-jenkins:~/jenkins$ grep -r 10.55.32.40
jenkins.model.JenkinsLocationConfiguration.xml:  <jenkinsUrl>http://10.55.32.40:8080/</jenkinsUrl>
ubuntu@snappy-jenkins:~/jenkins$

Now if I use $BUILD_URL, it works.
So the value seems to be set only when I manually go to the config and save it.
I suppose I can create jenkins.model.JenkinsLocationConfiguration.xml on my docker file, but the IP is auto assigned to me by openstack, so I don't know how to tell the docker file to put the IP in there.

**Comment by ndeloof** [comment]
Jenkins can't know it's external IP, it relies on browser to detect it. No way for this to be fixed

**Comment by elopio** [comment]
I guess I can get a known public ip from openstack, and assign it to the machine during the deploy.

**Comment by ndeloof** [comment]
This would then be specific to your deployment. For such case, include a custom init groovy script that will setup jenkins rootUrl according to environment.
