### ISSUE TITLE
  Jenkins container won't start: java.lang.NoClassDefFoundError: sun/security/x509/CertAndKeyGen

### ISSUE THREAD

**Issue by marcosArruda** [jenkinsci/docker#143]
Hi, 
I think there is an issue with the 1.609.2 version. The container fail to start.

the log:

> /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
>  /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy -> init.groovy.d/tcp-slave-agent-port.groovy
> /usr/share/jenkins/ref/jenkins_home/config.xml
>  /usr/share/jenkins/ref/jenkins_home/config.xml -> jenkins_home/config.xml
> /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
>  /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy -> init.groovy.d/tcp-slave-agent-port.groovy
> /usr/share/jenkins/ref/jenkins_home/config.xml
>  /usr/share/jenkins/ref/jenkins_home/config.xml -> jenkins_home/config.xml
> Running from: /usr/share/jenkins/jenkins.war
> webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
> Sep 01, 2015 2:44:13 PM winstone.Logger logInternal
> INFO: Beginning extraction from war file
> Using one-time self-signed certificate
> Sep 01, 2015 2:44:18 PM winstone.Logger logInternal
> INFO: Winstone shutdown successfully
> Sep 01, 2015 2:44:18 PM winstone.Logger logInternal
> SEVERE: Container startup failed
> java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
> 	at winstone.Launcher.spawnListener(Launcher.java:209)
> 	at winstone.Launcher.<init>(Launcher.java:149)
> 	at winstone.Launcher.main(Launcher.java:354)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at Main._main(Main.java:293)
> 	at Main.main(Main.java:98)
> Caused by: java.lang.NoClassDefFoundError: sun/security/x509/CertAndKeyGen
> 	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:100)
> 	at winstone.Launcher.spawnListener(Launcher.java:207)
> 	... 8 more
> Caused by: java.lang.ClassNotFoundException: sun.security.x509.CertAndKeyGen
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 10 more

Just tested this. two weeks ago the container was fine. The only change is the version from 1.609.1 to 1.609.2 

Maybe its a regressive error..?

**Comment by ndeloof** [comment]
Your issue is related to using https and relying on jenkins for this (would be more efficient to use a https reverse proxy). Don't you have the same issue running a plain jenkins installation with OpenJDK ?
