### ISSUE TITLE
System.getProperty("user.home") adds additional quotes

### ISSUE THREAD

**Issue by Jonny-vb** [jenkinsci/docker#1433]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
 Jenkins: 2.356
OS: Windows Server 2019 - 10.0
---
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
display-url-api:2.3.6
git:4.11.4
git-client:3.11.2
jakarta-activation-api:2.0.1-1
jakarta-mail-api:2.0.1-1
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jsch:0.1.55.61.va_e9ee26616e7
mailer:435.v79ef3972b_5c7
plain-credentials:139.ved2b_9cf7587b
scm-api:621.vda_a_b_055e58f7
script-security:1175.v4b_d517d6db_f0
ssh-credentials:295.vced876c18eb_4
structs:324.va_f5d6774f3a_d
trilead-api:1.67.vc3938a_35172f
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows server 2019 1809 17763.3165
Jenkins is running in a docker container
Docker version 20.10.9, build 591094d
The docker image in use is;
jenkins/jenkins:windowsservercore-2019@sha256:32daaca09995bd845b72338ad10cdb30970d8f6ca22f256a1b7cdacdb20c05d4

### Reproduction steps

In the script console run:
```
import java.io.File;
import java.nio.file.Paths;

println System.getProperty("user.home").toString();
```

### Expected Results

```
'C:/ProgramData/Jenkins/JenkinsHome'
```

### Actual Results

```
C:/ProgramData/Jenkins/JenkinsHome
```

### Anything else?

This causes issues with the latest git-client plugin which uses this property to construct paths, which fails due to the extra quotes in the returned name - I originally reported this as a bug against the plugin, [see here for more details](https://issues.jenkins.io/browse/JENKINS-69209)
I'm not sure exactly where that property is retrieved from, but it appears that it doesn't return with the quotes in other instances (including windows without using docker) - see the comments on the git-client issue.
If I instead use java to directly get the JENKINS_HOME environmental variable, it also returns without the quotes, so I'm really not sure where they are creeping in, but it seems specific to running on docker

**Comment by timja** [comment]
It's set with a quote here:
https://github.com/jenkinsci/docker/blob/e6e7014de2cfb18b89672fd814b5702e68d2878b/jenkins.ps1#L34

Likely because on windows spaces are a lot more common than linux so it's probably trying to handle spaces.

git-client plugin should probably handle this.

**Comment by Jonny-vb** [comment]
Hi timja, thanks for the quick response.
Good to know the quotes are intentional, but I'm on the fence about whether I agree they should be there or not.
There are even instances in the jenkins source code I can find where it is expected that getProperty("user.home") returns a valid path, which the quotes would break:
[Example 1](https://github.com/jenkinsci/jenkins/blob/e27b310065b3c036b5fc9d123f1d1d99d3058c00/cli/src/main/java/hudson/cli/PrivateKeyProvider.java#L83)
[Example 2](https://github.com/jenkinsci/jenkins/blob/76e5c98dd3c92ee892c7d094d246602be2e1dc79/core/src/main/java/hudson/FilePath.java#L3543)

**Comment by timja** [comment]
cc @slide any input?

**Comment by Jonny-vb** [comment]
Is there anyway I can easily change the user.home value in the mean time to test _if_ changing it would fix all the issues I'm having?

**Comment by timja** [comment]
replace the jenkins.ps1 script in your docker image with your changes

**Comment by Jonny-vb** [comment]
Great - changing that line to:
```
 $proc = Start-Process -NoNewWindow -Wait -PassThru -FilePath 'java.exe' -ArgumentList "-D`"user.home=$JENKINS_HOME`" $java_opts_array -jar $JENKINS_WAR $jenkins_opts_array $args"
```
appears to have fixed all my issues. I appreciate this might be a non-trivial change though in regards to breaking existing deployments and treating more complicated paths in (that as you point out may contain spaces), so I will await further input from yourselves about how to handle the situation.

**Comment by timja** [comment]
Unsure =/ did you want to file a PR anyway?

**Comment by Jonny-vb** [comment]
PR filed
