### ISSUE TITLE
Download looping docker image

### ISSUE THREAD

**Issue by 1arrcy1** [jenkinsci/docker#1438]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

What am i using:
- Proxmox VE 7.2-7
- Unprivileged container no + protection no
- Ubuntu 22.04 LTS
- LXC

LXC config:
arch: amd64
cores: 3
features: nesting=1
hostname: Kasm
memory: 4096
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.2.1,hwaddr=32:41:2F:73:C9:AB,ip=192.168.2.103/24,tag=10,type=veth
ostype: ubuntu
parent: working
rootfs: storage-nvme:subvol-121-disk-0,size=124G
swap: 1024

Proxmox Packaging versions
proxmox-ve: 7.2-1 (running kernel: 5.15.39-3-pve)
pve-manager: 7.2-7 (running version: 7.2-7/d0dd0e85)
pve-kernel-5.15: 7.2-8
pve-kernel-helper: 7.2-8
pve-kernel-5.13: 7.1-9
pve-kernel-5.11: 7.0-10
pve-kernel-5.4: 6.4-4
pve-kernel-5.15.39-3-pve: 5.15.39-3
pve-kernel-5.15.35-1-pve: 5.15.35-3
pve-kernel-5.13.19-6-pve: 5.13.19-15
pve-kernel-5.13.19-2-pve: 5.13.19-4
pve-kernel-5.11.22-7-pve: 5.11.22-12
pve-kernel-5.4.124-1-pve: 5.4.124-1
pve-kernel-5.4.34-1-pve: 5.4.34-2
ceph-fuse: 14.2.21-1
corosync: 3.1.5-pve2
criu: 3.15-1+pve-1
glusterfs-client: 9.2-1
ifupdown: 0.8.36+pve1
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve1
libproxmox-acme-perl: 1.4.2
libproxmox-backup-qemu0: 1.3.1-1
libpve-access-control: 7.2-4
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.2-2
libpve-guest-common-perl: 4.1-2
libpve-http-server-perl: 4.1-3
libpve-storage-perl: 7.2-7
libqb0: 1.0.5-1
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 5.0.0-3
lxcfs: 4.0.12-pve1
novnc-pve: 1.3.0-3
proxmox-backup-client: 2.2.5-1
proxmox-backup-file-restore: 2.2.5-1
proxmox-mini-journalreader: 1.3-1
proxmox-widget-toolkit: 3.5.1
pve-cluster: 7.2-2
pve-container: 4.2-2
pve-docs: 7.2-2
pve-edk2-firmware: 3.20210831-2
pve-firewall: 4.2-5
pve-firmware: 3.5-1
pve-ha-manager: 3.4.0
pve-i18n: 2.7-2
pve-qemu-kvm: 6.2.0-11
pve-xtermjs: 4.16.0-1
qemu-server: 7.2-3
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.7.1~bpo11+1
vncterm: 1.7-1
zfsutils-linux: 2.1.5-pve1

Installation method
https://docs.docker.com/engine/install/ubuntu/

### Reproduction steps

1. Use the same settings i am using as above
2. Go to https://kasmweb.com/docs/latest/guide/custom_images.html and download every image once at a time for e.g
docker pull kasmweb/atom:1.11.0
docker pull kasmweb/audacity:1.11.0
3. wait a long time till the drive get's filled

### Expected Results

Expected was that it would download these image's in about 2 min per image since i have gigabit internet. I would not expect that 3 image's is enough to fill up the entire disk or take an hour to complete.

### Actual Results

Downloading docker image's without filling up a 100GB + drive. It seems to be continuing to fill up the drive even when the docker layers are already downloaded and it gets to extracting the layers. It seems to freeze up and slow down. After an hour the drive get's filled up and i receive an error prompt that says the drive is full. After this when i check the drive is slowely freeing up space removing 20GB+ from the drive.

### Anything else?

Any feature requested information will be posted, also im not sure if this is a docker bug. It might also be a bug with lxc or proxmox. Im not sure, any insights on how i can possibly solve the issue is greatly appreciated.

### Additional notice:
When using `docker image prune --all` it claims that Total reclaimed space is: 3.274GB
however when i check the actual disk size it's from 124 GB full to 1.02 GB. being about 123 GB of space reclaimed

**Comment by lemeurherve** [comment]
I don't see how downloading docker images from kasmweb is related to this Jenkins repository. 
Wrong repository/project?

**Comment by 1arrcy1** [comment]
> 

Because i tought it might be an issue with docker itself.

**Comment by lemeurherve** [comment]
You should open an issue on the Docker project then, not here in the Jenkins project, unrelated to the internals of docker.

**Comment by 1arrcy1** [comment]
Well it's definitely an issue with docker since all im doing is docker pull image. It should not take that long or fill up a drive
