### ISSUE TITLE
Jenkin Docker JDK17 still points to Java 9

### ISSUE THREAD

**Issue by madukan** [jenkinsci/docker#1440]
### Customer Dockerfile used
```
FROM jenkins/jenkins:jdk17
USER root

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y rsync
RUN apt install -y maven

USER jenkins
```

### Docker commands that you execute

```
docker build -t my/jenkins -f Dockerfile_jenkins .

docker run -d --name my-jenkins \
    -p 8081:8080 \
	  -p 50000:50000 \
    -v ${JENKINS_HOME}:/var/jenkins_home \
    my/jenkins
```
The JAVA_HOME is setup to be 
https://github.com/jenkinsci/docker/blob/d8d4c1146a3ea3464573842b5390802331ed25e5/17/debian/bullseye/hotspot/Dockerfile#L102-L104

I've created a StackExchange thread, it'd help others if you can comment there as well pls.
https://devops.stackexchange.com/questions/16470/jenkins-jdk17-docker-still-using-jdk9

### Actual result

Java 9 is used in the build

### Expected outcome

Java17 should be used in the build

### Have you tried a non-dockerized Jenkins and get the expected outcome?

no

### Output of `docker version`

Docker version 20.10.3, build 55f0773

### Other relevant information

Jenkins 2.356

**Comment by timja** [comment]
Given the responses on the stackexchange thread it looks like you've installed a version of Java as a tool on the `Configure Tools` page and that's being used for your builds

**Comment by madukan** [comment]
Not really, when JDK17 docker is used, the JDK17 should be used in the Jenkins Controller. Where as in this reported case its using JDK 9 which is incorrect.
