### ISSUE TITLE
Please create a new release tag

### ISSUE THREAD

**Issue by matthsmi** [jenkinsci/docker#1454]
### What feature do you want to see added?

Hey Gang,

I'm hoping you can just generate a new release based upon the latest changes in the repo. There have been quite a few between 2.235.1 and 2.346.3. We use some tooling which pulls based upon a tag, and it'd be nice to have an updated release tag.

thanks!

**Comment by MarkEWaite** [comment]
You should probably change your tooling to depend on the docker repository tag or label rather than depending on a tag placed in the git repository.  We don't use tags in this repository to track releases.
