### ISSUE TITLE
Question: image release process to Docker registry

### ISSUE THREAD

**Issue by scadu** [jenkinsci/docker#1463]
### Describe your use-case which is not covered by existing documentation.

Hello,

I saw [automated commit](https://github.com/jenkinsci/docker/commit/00717102cadcdd3fc82984bd829159040b916326) updating the plugin manager and [related pipeline](https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/master/8025/pipeline).
I wasn't, however, be able to pinpoint where the image release takes place.
Most of the updates in the Docker registry are from 6 days ago, but there are other updates to the main branch in the meantime. Is this process documented somewhere, or is it a manual process requiring maintainers' attention? 
I assume #1228 can be related.

**Comment by timja** [comment]
Images are released as part of the Jenkins release process.

every Tuesday for weekly releases and as part of the LTS release schedule for LTS releases

**Comment by scadu** [comment]
@timja thanks for answering this quick!
I assume that comes from the schedule in [the Jenkinsfile](https://github.com/jenkinsci/docker/blob/c62ce445e4302eaa5c00c4d51a26c6e4c3fb5427/Jenkinsfile#L8)?
I guess my coffee hasn't kicked in yet as I thought there's no conditional on the `Publish` step.

**Comment by timja** [comment]
Kind of.

The publish script only publishes versions that haven't been published yet.
There's a cron that runs it every few hours but it will only do something if it finds a non published version.

We plan to remove the cron and trigger it directly from the release process at some point, currently its generally triggered manually during the release so you don't have to wait for the cron

**Comment by scadu** [comment]
@timja thanks. I think it clarifies a little.
