### ISSUE TITLE
Docker-compose missing documentation in the Jenkins

### ISSUE THREAD

**Issue by iamlauriano** [jenkinsci/docker#1468]
### Describe your use-case which is not covered by existing documentation.

Instructions for using docker-compose is missing from the documentation

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

I'm basing on information from the Jenkins documentation itself

https://hub.docker.com/r/jenkins/jenkins/
https://www.jenkins.io/doc/book/installing/docker/

If possible I can create a pull-request to create this procedure.

**Comment by heggrik** [comment]
@iamlauriano are you currently working on this, i would be interested in taking this on if noone is working on it.

**Comment by RahulSurwade08** [comment]
Hey @iamlauriano , I would love to contribute to this under Hacktoberfest. How can I get started?

**Comment by iamlauriano** [comment]
@heggrik I am available to contribute to this documentation project, if it does not exist

**Comment by iamlauriano** [comment]
@RahulSurwade08 thanks

**Comment by ADITYADAS1999** [comment]
> ### Describe your use-case which is not covered by existing documentation.
> Instructions for using docker-compose is missing from the documentation
> 
> ### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.
> I'm basing on information from the Jenkins documentation itself
> 
> https://hub.docker.com/r/jenkins/jenkins/ https://www.jenkins.io/doc/book/installing/docker/
> 
> If possible I can create a pull-request to create this procedure.

hi  [iamlauriano](https://github.com/iamlauriano) this issue is still open to work ?

**Comment by iamlauriano** [comment]
Thank you all for your help, sorry for the delay in responding, 

has anyone already contributed with the idea?
