### ISSUE TITLE
HTTP 404 when trying to login (docker / docker-machine / digitalocean)

### ISSUE THREAD

**Issue by sebeichholz** [jenkinsci/docker#149]
I did the following:
- create docker instance on digitalocean with this command:

```
docker-machine create \
  --driver digitalocean \
  --digitalocean-access-token=$DIGITAL_OCEAN_TOKEN \
  --digitalocean-region=fra1 \
  dev1

docker-machine start dev1

docker run -itd -p 8080:8080 jenkins
```

In the now running jenkins I created a user and a domain (manage jenkins), and enabled security ("Logged in users can do anything").

But when submitting the login form I get this error:
```
HTTP ERROR 404
Problem accessing /j_acegi_security_check. Reason:    
Not Found
```

Can anybody help? Thanks!

**Comment by thomasleveil** [comment]
it might be an issue with the way reverse proxies are set up on Digital Ocean. See [JENKINS-3761](https://issues.jenkins-ci.org/browse/JENKINS-3761?focusedCommentId=172269&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-172269)

> Maybe this helps. I was able to login when accessing jenkins directly (port 8080) and wasn't when I tried to login through an apache proxy. The error was caused by a proxy pass rule "/jenkins http://localhost:9080/jenkins/" which led to the incomming (jenkins) request "/jenkins//j_acegi_security_check" (double //). So the login page was rejected with 404 (while all other pages where served). Changing the rule to "/jenkins http://localhost:9080/jenkins" solved the problem.

Some also [report](https://issues.jenkins-ci.org/browse/JENKINS-3761?focusedCommentId=166032&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-166032) that disabling Matrix authentication solves the problem, but if you have the issue right after the first run, I guess this is not the root of your issue.

**Comment by carlossg** [comment]
seems like a jenkins question. Try with `--net=host` to ensure docker networking is not messing up the connections
