### ISSUE TITLE
Update Jenkins version for Windows Image

### ISSUE THREAD

**Issue by Jonny-vb** [jenkinsci/docker#1490]
### What feature do you want to see added?

The jenkins base version seems to lag quite a lot in the windows container releases. This means I often get stuck with warnings like this whilst waiting for updates:
![image](https://user-images.githubusercontent.com/26790846/196189013-2e413f4f-dc5b-4011-b513-c5f643de8d25.png)

This is for an issue that was reported over a month ago now (and not the first time I've been stuck with one of these warnings).

It looks like the linux containers have been bumped to 2.373 now, whilst the windows version is stuck on 2.356.

Can the windows version be updated please? Is there a reason that the windows version often lags so much? If so it might be nice to add some documentation explaining this somewhere.

**Comment by Nandini99-git** [comment]
you an use docker official image like busybox to update

**Comment by Jonny-vb** [comment]
> you an use docker official image like busybox to update

I'm really not too sure what you mean by this?

**Comment by Jonny-vb** [comment]
@timja sorry to tag you here, but you were very helpful on the last issue I raised!
Could you provide any insight on how the windows base images are updated for the docker images? Is there anything I can do to get a more up to date Jenkins version into the Windows images?

**Comment by timja** [comment]
@slide possible for you to check this?

**Comment by dduportal** [comment]
> @slide possible for you to check this?

Currently checking the "normal" job on trusted.ci.jenkins.io . The Windows images should be using the same Jenkins version as Linux.

@Jonny-vb can you share with us the image name and digest of the "latest"' image you have ?

@timja can you check if there are remaining SSH deploy key on this repo (like with the docker-*-agent repositories)?

**Comment by dduportal** [comment]
Right now, it seems that the `2.356` is still the version used: https://hub.docker.com/layers/jenkins/jenkins/windowsservercore-2019/images/sha256-f31ea7e5f4582b665826b094aa3f78a50ccfcbb81dfca4025979aac26a935bf0?context=explore

It is the same "version" has the one used by default: the build argument is probably not set up correctly so it does not override the image.

**Comment by dduportal** [comment]
Damn: there is nothing about build arg in https://github.com/jenkinsci/docker/blob/master/make.ps1#L6 🤦

**Comment by dduportal** [comment]
Thanks tim! I confirm that I can reproduce the issue on my Windows machine. This is a problem in the pipeline + `make.ps1` script. I'll see what I can do on short term.

**Comment by dduportal** [comment]
Hi @Jonny-vb , we've cleared any risks of an "old system" building and overriding images behind our back.

Since we reproduce the error, It means that there is an easy that can be solved in this repository.
If you are interested in helping, that would be wonderful!

I can give you guidance, pointers and help if you ping me in this issue or in the Gitter channel jenkins/docker.

The root cause here seems to be the build argument `JENKINS_VERSION` not being passed to Docker when https://github.com/jenkinsci/docker/blob/master/make.ps1#L6 is executed (check the linux build to compare).

**Comment by Jonny-vb** [comment]
So I assume make.ps1 is called from a pipeline somewhere controlled by yourselves?
Just so I'm clear, are you saying this is correctly being called and the correct version string is being passed into this script, but when the script runs the docker make, the argument isn't making it into that? So it instead builds the default 2.356 version in the dockerfile?

It looks like the JENKINS_VERSION param has to be the version number preceded by a hyphen based on the default (i.e. "-2.356" vs "2.356"). Is whatever is calling the make.ps1 script passing the version number in this correct form?

**Comment by dduportal** [comment]
> So I assume make.ps1 is called from a pipeline somewhere controlled by yourselves? Just so I'm clear, are you saying this is correctly being called and the correct version string is being passed into this script, but when the script runs the docker make, the argument isn't making it into that? So it instead builds the default 2.356 version in the dockerfile?
> 
> It looks like the JENKINS_VERSION param has to be the version number preceded by a hyphen based on the default (i.e. "-2.356" vs "2.356"). Is whatever is calling the make.ps1 script passing the version number in this correct form?

Hi @Jonny-vb !

Let me give some pointers:

- First of all, the windows images are published by a Jenkins pipeline run inside a private instance (for obvious reason of security). The [stage "Publish" of the `Jenkinfile` of this repository](https://github.com/jenkinsci/docker/blob/afabdcea8873a8ad45e956a12b763cb7f231447d/Jenkinsfile#L60-L66) is responsible for calling the `make.ps1` script.
- The target `publish` is passed to the `make.ps1` script, which is expected to call the following code block: https://github.com/jenkinsci/docker/blob/afabdcea8873a8ad45e956a12b763cb7f231447d/make.ps1#L151-L176

=> the goal is to check what is this script expected to do and if it is doing it correctly. A good start is to compare with the Linux `make publish` command.

**Comment by Jonny-vb** [comment]
I'm not sure that section you have highlighted is where the problem lies as that is pushing the image to docker hub. From what I can see, docker hub is updating the windows tag image, but it is the image itself that is wrong.
The dockerfile used to build the image has an argument to specify the Jenkins version which defaults to 2.356, which is the version currently used in the windows image:
https://github.com/jenkinsci/docker/blob/e2fbfa6360f32811e5d30b577b9c9f9699c38a86/11/windows/windowsservercore-2019/hotspot/Dockerfile#L41-L49

I don't fully understand how the linux builds work, but to me it looks like the version number has to be set as part of the pipeline, otherwise it will just default to the 2.356 version. So it looks like to me the pipeline needs reviewing - how does the version number to build make it there? I can't see anything in the jenkinsfile that sets this (along with the corresponding SHA for the download)

**Comment by Jonny-vb** [comment]
@dduportal @timja - I think this need a review of the non-public pipeline to really understand what is going wrong here - are either of you able to do this?

**Comment by lemeurherve** [comment]
Reopening until validation with the next Weekly and LTS releases in two days.

**Comment by lemeurherve** [comment]
Jenkins version is now set on build time, and tags containing it are now published, allowing to use and pin a specific Jenkins version, see images since today: https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=windows
