### ISSUE TITLE
Prepare LTS 2.361.3 

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/docker#1507]
Hello @NotMyFault @timja , as I can't join you (Element Matrix is down), this issue is to let you know that we have to update the branch `stable-2.361` here in order to build the Docker Image for the new LTS.

The job on trusted.ci had been disabled has we must check the build on ci.j first (to avoid overwriting existing tags)

**Comment by NotMyFault** [comment]
> (Element Matrix is down)

Just noticed, reposting here again. The job finished successfully, we can enable k8s management again. I reverted my infra fixtures.

**Comment by timja** [comment]
is that due to Java 8 or something else?

**Comment by dduportal** [comment]
Closing, job launched on trusted.ci
