### ISSUE TITLE
Cannot Install plugin

### ISSUE THREAD

**Issue by perezmark** [jenkinsci/docker#1544]
I install jenkins on my Centos 7 VM, the VM is behind a company proxy

# run jenkins
mkdir -p /var/jenkins_home
chown -R 1000:1000 /var/jenkins_home/
docker run -p xxxx:8080 -p xxxx:50000 -v /var/jenkins_home:/var/jenkins_home -d --name jenkins jenkins/jenkins:lts

i edit the advance settings

http proxy = x.x.x.x
port = x
 no proxy = x

update site  ---> make this http

--------------------------
before i edit the proxy it tells me that it can connect to the update site

----------------------------------------------------------
after editing the proxy
there are no notif now on update site.

i tried installing some plugins but it is failed

----------------------------------------------------------

**Comment by MarkEWaite** [comment]
The Jenkins project stopped supporting CentOS 7 after Nov 16, 2023.  More details are available in the [blog post](https://www.jenkins.io/blog/authors/markewaite/).
