### ISSUE TITLE
Can't run the container with a volume

### ISSUE THREAD

**Issue by danillosl** [jenkinsci/docker#155]
When I try to run the container with to command "docker run -p 8080:8080 -v /your/home:/var/jenkins_home jenkins"  docker replies with the error "/usr/local/bin/jenkins.sh: line 25: /var/jenkins_home/copy_reference_file.log: Permission denied".

**Comment by carlossg** [comment]
you need to check permissions of the volume and the user of the docker container

**Comment by danillosl** [comment]
I solved by running the Jenkins container as root.
