### ISSUE TITLE
Cannot build myjenkins-blueocean on Ubuntu WSL

### ISSUE THREAD

**Issue by HamzaaKhattabi** [jenkinsci/docker#1550]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
- Ubuntu 22.04.1 LTS
- WSL 1.1.0.0
- Docker 20.10.22
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

- Ubuntu 22.04.1 LTS
- WSL 1.1.0.0

### Reproduction steps

1. Follow the Jenkins documentation on how to install Jenkins with Docker
2. Create the Docker file as described
3. Run the command `docker build -t myjenkins-blueocean:2.375.2-1 .`

### Expected Results

The build process should be succesful

### Actual Results

Getting an error when trying to install <b>lsb-release</b> during the build process.

<details>
  <summary>Build logs</summary>

```
root@CPX-X6BQCOJQINP:/home/hkhattabi/softwares/Jenkins# docker build -t myjenkins-blueocean:2.375.2-1 .
Sending build context to Docker daemon   2.56kB
Step 1/8 : FROM jenkins/jenkins:2.375.2
 ---> 3385e3c0b235
Step 2/8 : USER root
 ---> Using cache
 ---> 008e0e7e7868
Step 3/8 : RUN apt-get update && apt-get install -y lsb-release
 ---> Running in ad07559b0b06
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:6 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [214 kB]
Get:7 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Get:5 https://packagecloud.io/github/git-lfs/debian bullseye InRelease [24.5 kB]
Get:8 https://packagecloud.io/github/git-lfs/debian bullseye/main amd64 Packages [1905 B]
Fetched 8646 kB in 4s (2448 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  distro-info-data libmpdec3 libpython3-stdlib libpython3.9-minimal
  libpython3.9-stdlib media-types python3 python3-minimal python3.9
  python3.9-minimal
Suggested packages:
  python3-doc python3-tk python3-venv python3.9-venv python3.9-doc binutils
  binfmt-support
The following NEW packages will be installed:
  distro-info-data libmpdec3 libpython3-stdlib libpython3.9-minimal
  libpython3.9-stdlib lsb-release media-types python3 python3-minimal
  python3.9 python3.9-minimal
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 5157 kB of archives.
After this operation, 20.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-minimal amd64 3.9.2-1 [801 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 python3.9-minimal amd64 3.9.2-1 [1955 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3 [38.2 kB]
Err:3 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3
  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
Get:4 http://deb.debian.org/debian bullseye/main amd64 media-types all 4.0.0 [30.3 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 libmpdec3 amd64 2.5.1-1 [87.7 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-stdlib amd64 3.9.2-1 [1684 kB]
Get:7 http://deb.debian.org/debian bullseye/main amd64 python3.9 amd64 3.9.2-1 [466 kB]
Get:8 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3 [21.4 kB]
Err:8 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3
  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
Get:9 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3 [37.9 kB]
Err:9 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3
  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
Get:10 http://deb.debian.org/debian bullseye/main amd64 distro-info-data all 0.51+deb11u3 [7812 B]
Get:11 http://deb.debian.org/debian bullseye/main amd64 lsb-release all 11.1.0 [27.9 kB]
Fetched 5059 kB in 1s (4677 kB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/python3-minimal_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/libpython3-stdlib_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/python3_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y lsb-release' returned a non-zero code: 100
```
</details>

**Comment by MarkEWaite** [comment]
> ### Jenkins and plugins versions report
> Environment
> ### What Operating System are you using (both controller, and any agents involved in the problem)?
> * Ubuntu 22.04.1 LTS
> * WSL 1.1.0.0
> 
> ### Reproduction steps
> 1. Follow the Jenkins documentation on how to install Jenkins with Docker
> 2. Create the Docker file as described
> 3. Run the command `docker build -t myjenkins-blueocean:2.375.2-1 .`
> 
> ### Expected Results
> The build process should be succesful
> 
> ### Actual Results
> Getting an error when trying to install lsb-release during the build process.
> 
> Build logs
> ```
> root@CPX-X6BQCOJQINP:/home/hkhattabi/softwares/Jenkins# docker build -t myjenkins-blueocean:2.375.2-1 .
> Sending build context to Docker daemon   2.56kB
> Step 1/8 : FROM jenkins/jenkins:2.375.2
>  ---> 3385e3c0b235
> Step 2/8 : USER root
>  ---> Using cache
>  ---> 008e0e7e7868
> Step 3/8 : RUN apt-get update && apt-get install -y lsb-release
>  ---> Running in ad07559b0b06
> Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
> Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
> Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
> Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
> Get:6 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [214 kB]
> Get:7 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
> Get:5 https://packagecloud.io/github/git-lfs/debian bullseye InRelease [24.5 kB]
> Get:8 https://packagecloud.io/github/git-lfs/debian bullseye/main amd64 Packages [1905 B]
> Fetched 8646 kB in 4s (2448 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   distro-info-data libmpdec3 libpython3-stdlib libpython3.9-minimal
>   libpython3.9-stdlib media-types python3 python3-minimal python3.9
>   python3.9-minimal
> Suggested packages:
>   python3-doc python3-tk python3-venv python3.9-venv python3.9-doc binutils
>   binfmt-support
> The following NEW packages will be installed:
>   distro-info-data libmpdec3 libpython3-stdlib libpython3.9-minimal
>   libpython3.9-stdlib lsb-release media-types python3 python3-minimal
>   python3.9 python3.9-minimal
> 0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
> Need to get 5157 kB of archives.
> After this operation, 20.0 MB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-minimal amd64 3.9.2-1 [801 kB]
> Get:2 http://deb.debian.org/debian bullseye/main amd64 python3.9-minimal amd64 3.9.2-1 [1955 kB]
> Get:3 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3 [38.2 kB]
> Err:3 http://deb.debian.org/debian bullseye/main amd64 python3-minimal amd64 3.9.2-3
>   Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> Get:4 http://deb.debian.org/debian bullseye/main amd64 media-types all 4.0.0 [30.3 kB]
> Get:5 http://deb.debian.org/debian bullseye/main amd64 libmpdec3 amd64 2.5.1-1 [87.7 kB]
> Get:6 http://deb.debian.org/debian bullseye/main amd64 libpython3.9-stdlib amd64 3.9.2-1 [1684 kB]
> Get:7 http://deb.debian.org/debian bullseye/main amd64 python3.9 amd64 3.9.2-1 [466 kB]
> Get:8 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3 [21.4 kB]
> Err:8 http://deb.debian.org/debian bullseye/main amd64 libpython3-stdlib amd64 3.9.2-3
>   Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> Get:9 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3 [37.9 kB]
> Err:9 http://deb.debian.org/debian bullseye/main amd64 python3 amd64 3.9.2-3
>   Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> Get:10 http://deb.debian.org/debian bullseye/main amd64 distro-info-data all 0.51+deb11u3 [7812 B]
> Get:11 http://deb.debian.org/debian bullseye/main amd64 lsb-release all 11.1.0 [27.9 kB]
> Fetched 5059 kB in 1s (4677 kB/s)
> E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/python3-minimal_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/libpython3-stdlib_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3-defaults/python3_3.9.2-3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.10.132 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> The command '/bin/sh -c apt-get update && apt-get install -y lsb-release' returned a non-zero code: 100
> ```

That's a network connectivity issue from inside your WSL machine to the Debian operating system archives.  The Jenkins project can't fix your network connectivity issues.
