### ISSUE TITLE
images are all lts - no weekly images

### ISSUE THREAD

**Issue by PiersRBME** [jenkinsci/docker#1567]
Looks like what I understand to be intended latest **weekly** images are actually only the latest **LTS** version.

For example tag [_alpine_](https://hub.docker.com/layers/jenkins/jenkins/alpine/images/sha256-9e5e8dffc70c4e2ed5aca23373866a3be08d0b5b32a0bb25161323b513838436?context=explore) includes docker command:
`ARG JENKINS_URL=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.375.3/jenkins-war-2.375.3.war`

I think it **may** be related to [this line of publish.sh](https://github.com/jenkinsci/docker/blob/a0340024b49592181e9c209e649487a0de68fed9/.ci/publish.sh#L158) assuming that the output of get-latest-versions() is different to what it now is, where the LTS versions are last in the list.

**Comment by dduportal** [comment]
That is correct, thanks for reporting and pointing the mistake!

Now that https://github.com/jenkinsci/docker/pull/1564 fixed the root cause, I feel like we should rollback https://github.com/jenkinsci/docker/commit/b9e129dfe9192ffb27a849520a779256bd02a235 and https://github.com/jenkinsci/docker/pull/1558

**Comment by dduportal** [comment]
@PiersRBME On short time, you can still pin your version to the weekly version (and update it): it works very well and ensure no unexpected core changes. You can find an exemple at https://github.com/jenkins-infra/docker-jenkins-weekly

**Comment by PiersRBME** [comment]
Thanks for the tip! Not a big rush this side, more of a head-scratcher for a short time :)

**Comment by dduportal** [comment]
> more of a head-scratcher for a short time :)

Ah ah I feel you :D

**Comment by dduportal** [comment]
Fix applied in #1578. Thanks @PiersRBME ! It should be "applied" for the weekly 2.392 (worst case ETA).

**Comment by dduportal** [comment]
The release 2.392 was published successfuly today.

The tag `latest` is now pointing to the same digest as the `2.392`:

```console
$ docker pull jenkins/jenkins:latest   
latest: Pulling from jenkins/jenkins
Digest: sha256:5f74addba6c8e05b008f5f06cd0f47d45d483b43352c465a59a8dad98e6f9d63
Status: Downloaded newer image for jenkins/jenkins:latest
docker.io/jenkins/jenkins:latest
$ docker pull jenkins/jenkins:2.392 
2.392: Pulling from jenkins/jenkins
Digest: sha256:5f74addba6c8e05b008f5f06cd0f47d45d483b43352c465a59a8dad98e6f9d63
Status: Image is up to date for jenkins/jenkins:2.392
docker.io/jenkins/jenkins:2.392
```

Thanks again for catching and reporting properly, sorry for the inconvenience!

**Comment by gounthar** [comment]
It works now for me, thanks a lot for the fix. 🤗
