### ISSUE TITLE
plugins file does not get parsed when containing Windows EOL

### ISSUE THREAD

**Issue by peteanusergiu** [jenkinsci/docker#157]
A simple plugins.text with the following entries:

gradle:1.24
git:2.4.0

does not get correctly parsed throwing the following exception

_curl: (3) Illegal characters found in URL
Service 'jenkins' failed to build: The command '/bin/sh -c $JENKINS_SCRIPTS/plugins.sh $JENKINS_CONFIG/plugins.txt' returned a non-zero code: 3_

Problem is with EOL in Windows style. 
Once one changes to __UNIX style EOL__ things start working again.

**Comment by ndeloof** [comment]
Who uses windows anyway ? :P

**Comment by w3blogfr** [comment]
When I work with docker, I configured git to disabled EOL/CRLF transformation

`git config --global core.autocrlf false`

It's work for docker, but failed with any others languages

**Comment by carlossg** [comment]
we are moving to install-plugins script, so this doesn't make much sense anymore
