### ISSUE TITLE
Handling permissions in volumes with gosu

### ISSUE THREAD

**Issue by carlossg** [jenkinsci/docker#158]
There are a bunch of problems running the the container with a volume, need to make sure the volume has the correct permissions and the container is started as the right user.
In some environments, like Kubernetes, this handling before starting the container is not yet possible, would need to change permissions by hand in Google disks, AWS EBS volumes,... before attaching to a Jenkins container

An alternative is to start as root user and switch after the correct permissions in the volume are set

I have a working example at [`csanchez/jenkins-for-volumes`](https://hub.docker.com/r/csanchez/jenkins-for-volumes/) that does exactly that
https://github.com/carlossg/jenkins-for-volumes-docker

**Comment by kopax** [comment]
I encounter some problem logging in / logging out. I found your script.
Can you explain further what can of problem you encounter without your script ?

**Comment by carlossg** [comment]
PR at #225

**Comment by yilativs** [comment]
This bug still exist in 1.642.3 and 2.0-beta-1
a workaround is to create data container with the command 
`docker run -it -v /var/jenkins_home  --name jenkins_data busybox adduser -D -h /var/jenkins_home jenkins`

**Comment by gotgenes** [comment]
@yilativs Your workaround of using a container volume works when the volume is mounted to an empty host directory. The workaround does not work when the volume is mounted to a directory with one or more files/subdirectories, and still suffers, and suffers from the same problems of needing all files to be set to uid 1000 as the owner.
