### ISSUE TITLE
Use supervisord for process supervision

### ISSUE THREAD

**Issue by jbpadgett** [jenkinsci/docker#161]
I see you guys are using tini as a very lightweight process supervisor.
I'm creating a derived image and I'd like to lauch another process along with jenkins.  I'm not familiar with tini, but I know this can be done with supervisord easily.  For example, I want to install the consul agent and launch it along with Jenkins for a derived image.  I can install supervisord, but cannot use it since there is already an ENTRYPOINT being used with tini to launch the Jenkins war as a process.
I'd like to see TINI replaced with supervisord to make derived images much more extensible.
If you know a way to do this with tini, I'll accept that as a solution as well.

**Comment by carlossg** [comment]
The best practice is to only launch one process in the container. You can create your own image to override the `ENTRYPOINT` to anything you like

**Comment by jbpadgett** [comment]
You are right on best practice.  In the event that I needed to run 2 processes in a derived image, do you know of a way to run 2 processes using TINI?  This way, I could replicate the existing ENTRYPOINT you have and just add another launched process (consul in my case).

**Comment by krallin** [comment]
Hey @jbpadgett (I'm the author of Tini)

If you absolutely nee to launch two children processes, you can have Tini launch supervisord for you:

    ENTRYPOINT ["/bin/tini", "--", "supervisord"]

And then, have `supervisord` launch `/usr/local/bin/jenkins.sh` and Consul.

---

You *could* also have Supervisord launch Tini and have Tini launch Jenkins. That would work provided you enable subreaping in Tini (there's an option flag for this, try `tini -h` for more details). Getting rid of Tini altogether means you need to address https://github.com/jenkinsci/docker/issues/54 in some other way (supervisor does not reap zombies).

Hope this helps (though I realize I'm late to the party!).

Cheers,

**Comment by jbpadgett** [comment]
Perfect.  Thanks so much for taking the time to answer.  I'll give this a try.
