### ISSUE TITLE
Jenkins management page realizes announcement display window

### ISSUE THREAD

**Issue by coolqz** [jenkinsci/docker#1623]
### What feature do you want to see added?

I have a requirement now that every time Jenkins changes or modifications are made, they need to be emailed to everyone. Is there any other way for me to post a pop-up announcement on Jenkins' management page so that all users can see it when logging in to Jenkins

**Comment by coolqz** [comment]
My Jenkins version: 2.249.2

**Comment by dduportal** [comment]
Hi @coolqz , thanks for raising this feature request.

However, this issue tracker is only for reporting issues or requesting features for the Jenkins Docker image, while your request is either a Jenkins usage question or a Jenkins feature request.

I recommend you to open a thread on community.jenkins.io or in issues.jenkins.io instead.

Closing the issue as "out of scope".

**Comment by coolqz** [comment]
ok,thank you

**Comment by coolqz** [comment]
> Hi @coolqz , thanks for raising this feature request.
> 
> However, this issue tracker is only for reporting issues or requesting features for the Jenkins Docker image, while your request is either a Jenkins usage question or a Jenkins feature request.
> 
> I recommend you to open a thread on community.jenkins.io or in issues.jenkins.io instead.
> 
> Closing the issue as "out of scope".

ok,thank you
