### ISSUE TITLE
Signature verification failed in update site 'default'

### ISSUE THREAD

**Issue by kai0** [jenkinsci/docker#166]
I'm seeing this error when I try to update Jenkins.

It's related to:
https://issues.jenkins-ci.org/browse/JENKINS-31089

**Comment by ismyrnow** [comment]
Seeing the same. Does anyone have a workaround? The jenkins user the container is run as lacks the permissions to modify the java security file as recommended in the jenkins issue.

Is it possible to default to an older jdk version, since it seems like this issue is related to the default security policy in jdk8?

**Comment by cyrille-leclerc** [comment]
+ @daniel-beck + @carlossg + @ndeloof 
cc @michaelneale 

Hi @daniel-beck, this issue on the Docker image seem to be related to [JENKINS-31089 Signature verification failed in update site 'default'](https://issues.jenkins-ci.org/browse/JENKINS-31089).

Do you have an update on these signature issues? The workaround is much more complex on the Docker image.

A temporary solution could be to tweak /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security in the Dockerfile if the fixes on jenkins infra need more time.

**Comment by carlossg** [comment]
we could build a new docker image as a workaround with something like 

```
FROM jenkins
USER root
RUN sed -i -e 's/jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 1024/jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 512/' /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security
USER jenkins
```

**Comment by ismyrnow** [comment]
@carlossg: Thanks, `sed` makes that a whole lot easier.

**Comment by ndeloof** [comment]
Using this JDK patch is a useful workaround but can't be considered a fix to be included in Docker image, need to get JENKINS-31089 fixed by update center infrastructure

**Comment by cyrille-leclerc** [comment]
@ndeloof thank you for the clarification. It's a constraint but it makes sense. I'll sync with @daniel-beck to get more visibility on the ongoing fixes of the signatures.

**Comment by carlossg** [comment]
JENKINS-31089 was fixed so I guess this is too

**Comment by ankitkhadria1** [comment]
https://hub.docker.com/r/ankitkhadria1/jenkins2

Updated Dockerfile with the signature fixed.
