### ISSUE TITLE
Problem with "sign in" in the docker Desktop

### ISSUE THREAD

**Issue by Zhamemo** [jenkinsci/docker#1664]
# Post "https://hub.docker.com/v2/access-tokens/desktop-generate": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I would like to "Sign in" in the docker Desktop, but the credentials are not verified.
[![2023-07-04-07-20.png](https://i.postimg.cc/BZx4YTg6/2023-07-04-07-20.png)](https://postimg.cc/BtQrt1R9)
I have tried many times and it still doesn't work.

**Comment by Zhamemo** [comment]
OK，thanks for your suggestion.



---- Replied Message ----
| From | Peter ***@***.***> |
| Date | 07/04/2023 07:39 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jenkinsci/docker] Problem with "sign in" in the docker Desktop (Issue #1664) |

Docker desktop issue should be posted to Docker https://github.com/docker/for-win not in Jenkins.

**Comment by dduportal** [comment]
Hi @Zhamemo , this issue tracker is only about the Jenkins Docker image.

You should try reaching the Docker community (https://www.docker.com/community/) to get help on this topic.
