### ISSUE TITLE
Throws an error while building a container on macOS (Monterey)

### ISSUE THREAD

**Issue by d0nest** [jenkinsci/docker#1670]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
It throws an error on running  "docker build -t getting-started" command.
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

macOS Monterey (version 12.6.7)

### Reproduction steps

follow every steps on https://docs.docker.com/get-started/02_our_app/ guide until reach "docker build -t getting-started" which throws an error!

### Expected Results

A successful message! congratulating me on building my first ever container.

### Actual Results

ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

### Anything else?

using zsh shell!

**Comment by dduportal** [comment]
Hi, this issue tracker is about the officiel Jenkins Docker image.

your question is a about the docker official documentation so you won’t be able to get an answer.

please check the docker community forum or slack channel.
