### ISSUE TITLE
docker hub UID is wrong

### ISSUE THREAD

**Issue by waynew** [jenkinsci/docker#168]
On [Docker Hub](https://hub.docker.com/_/jenkins/) it specifies uid 102:

![It's the wrong user, Gromit!](https://www.dropbox.com/s/tt4iuhydbcdcjp5/Screenshot%202015-11-16%2012.07.37.png?dl=1)

It'd be nice if that was either updated/fixed or perhaps just changed to point to this README file? Took me a while to think of making sure that the docs matched reality for the Jenkins UID :stuck_out_tongue:

**Comment by carlossg** [comment]
fixed
