### ISSUE TITLE
Can not install plugin

### ISSUE THREAD

**Issue by pwglovejava** [jenkinsci/docker#1681]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows11

### Reproduction steps

I'm ganna install and run jenkins with docker,the command is 

docker run \
 -d  \
 -u root \
 --detach \
 --privileged \
 -p 19008:8080 \
 -p 19009:50000 \
 -v  /data/jenkins/jenkins_home:/var/jenkins_home \
 -v  /opt/maven:/opt/maven \
 -v  /usr/bin/docker:/usr/bin/docker \
 -v  /var/run/docker.sock:/var/run/docker.sock \
 --name myjenkins \
 jenkins/jenkins:lts
and then ,the container is start sussessd,

when I enter the plugin install page , choose git to install ,I see the 'can not install the plugin',so I skip the step into the manage page,when I enter the pugin page again ,I see the whole error;
![33F77668-9914-44c7-8D8C-1569EBE6C3A9](https://github.com/jenkinsci/docker/assets/56385831/da2e3c36-61d7-4fd9-a756-8a966097d70c)

### Expected Results

install plugin correctly

### Actual Results

install plugin fail

### Anything else?

If this is my falt,please tell me how to fix it, Thanks.

**Comment by dduportal** [comment]
Hi @pwglovejava , 

The screenshot shows that the content of the page received by Jenkins when trying to retrieve the plugin index from updates.jenkins.io is unexpected.

The red error message is incomplete so it's hard to tell what is the problem.

- Could you share the logs of this Jenkins container so we can get more details on the network error?
- Do you run behind an HTTP proxy or a firewall?

**Comment by pwglovejava** [comment]
Sorry ,Which folder is the log of jenkins saved in?
And I'm not use HTTP proxy
![B0E2FFE1-B5E1-4cfa-95D0-D678F9A22703](https://github.com/jenkinsci/docker/assets/56385831/9cd96dbe-e6d1-40be-a46e-41718ac22747)
![7B535811-8BD8-47c0-8C85-92A8FE4F394C](https://github.com/jenkinsci/docker/assets/56385831/b47d1265-de89-4941-90c3-dbcccab5149d)

**Comment by pwglovejava** [comment]
> Hi @pwglovejava ,
> 
> The screenshot shows that the content of the page received by Jenkins when trying to retrieve the plugin index from updates.jenkins.io is unexpected.
> 
> The red error message is incomplete so it's hard to tell what is the problem.
> 
> * Could you share the logs of this Jenkins container so we can get more details on the network error?
> * Do you run behind an HTTP proxy or a firewall?

**Comment by dduportal** [comment]
> Sorry ,Which folder is the log of jenkins saved in? And I'm not use HTTP proxy ![B0E2FFE1-B5E1-4cfa-95D0-D678F9A22703](https://user-images.githubusercontent.com/56385831/259362290-9cd96dbe-e6d1-40be-a46e-41718ac22747.png) ![7B535811-8BD8-47c0-8C85-92A8FE4F394C](https://user-images.githubusercontent.com/56385831/259362324-b47d1265-de89-4941-90c3-dbcccab5149d.png)

When using a Docker container, you have the command `docker logs` (with some extra arguments) as documented and explained in the Docker official pages: https://docs.docker.com/engine/reference/commandline/logs/.

Alternatively you can use Jenkins UI by browsing to "Manage Jenkins" -> "System Log" -> "All Jenkin s Logs".

=> The goal is to check which errror is printed when you click on the "Check Now" button (section "Manage Jenkins" -> "Plugins" -> "Updates")

**Comment by dduportal** [comment]
For info, I cannot reproduce (tested on the https://ci.jenkins.io public Jenkins and on a local Docker image on my machine): there is something related to your environment (is it Windows? WSL? Docker ? your network?)

**Comment by pwglovejava** [comment]
nothing
