### ISSUE TITLE
jenkins:weekly is old

### ISSUE THREAD

**Issue by warden** [jenkinsci/docker#170]
The "weekly" branch specifies that Jenkins should be 1.631, while in fact, the image I just pulled is 1.596.

**Comment by warden** [comment]
Also, I think it would be useful to note that the ":latest" tag is actually latest LTS, not latest CI version.

**Comment by NitroPye** [comment]
:+1: I think it would be nice to have a `lts` tag and or `weekly` and latest should be latest. Right now anyone using the docker image is locked to lts

**Comment by carlossg** [comment]
`jenkins:weekly` is no longer updated but I'm not sure if it can be deleted. `jenkins` official repo is only for LTS

For latest builds use https://hub.docker.com/r/jenkinsci/jenkins

**Comment by warden** [comment]
Docker Registry now supports deleting tags.
I think that people using weekly and latest should actually update to use the tags they really want to use. So latest should be replaced by lts tag, and weekly should be deleted if it is not updated anymore. 
Also, now I can see the latest is 1.625.3 but on the repo info page it still shows latest as 1.625.2.
Also, it would be valuable to add info to the /_/jenkins repo about it being LTS only and that /jenkins/jenkins/ is to be used for the latest.

**Comment by carlossg** [comment]
weekly tag has been removed
