### ISSUE TITLE
Ldap authentification failed when using jenkins in container with docker bridge

### ISSUE THREAD

**Issue by jpthiery** [jenkinsci/docker#171]
Hi, 

I tryed to use Ldap to authenticate my users with Docker Jenkins in version 1.625.2 whitout success.
After a long investigation due to no log report, i tryed to setup my Jenkins Docker container with `--net host`. In this configuration, my ldap authentification success.

After looking in Jenkins code, it seem that LdapTemplate used by Jenkins requiere a `RemoteAdressIp`. In case of our Jenkins run in a container with brigeded network, this code retrive private IP of container which not allow to get an Ldap connection. (I try to found this code again).

In my case, i run my docker-engin in a IAAS provider which provide a private network to my VMs. Run my Jenkins Docker with  `--net host` not allow me to solve this issue.

I'm ready to help to solve this issue, but i don't have any idea good entry point to solve it.

Regards,
Jean-Pascal

**Comment by carlossg** [comment]
That's more related to Jenkins than to the Docker image,  you should ask in the Jenkins user mailing list or check the LDAP plugin docs https://wiki.jenkins-ci.org/display/JENKINS/LDAP+Plugin
