### ISSUE TITLE
1.625.1 Tag removed

### ISSUE THREAD

**Issue by cloudnautique** [jenkinsci/docker#172]
Hi, thank you for providing this official image, it works great.

We ran into an issue, where we were using jenkins:1.625.1 docker image and it seems to have disappeared? We will move to 1.625.2, but we are using the image as part of the Rancher catalog and it caused a few issues for users when it disappeared. 

Just so we can plan accordingly, will the previous tags continue to be removed?

**Comment by jpthiery** [comment]
Hi,

1.625.1 provide a version of Jenkins which content a security issue which is fix in 1.625.2.
May be they don't provide Jenkins Docker image 1.625.1 due to this security issue.

You can't change your catalog ti update Docker atg image from 1.625.1 to 1.625.2 ?

**Comment by cloudnautique** [comment]
We have updated the entries in our catalog. We can handle the removal of images, but we just did not expect it. So we are hoping to get clarification if this is going to be common practice and adjust our strategy accordingly.

**Comment by jpthiery** [comment]
I don't know, i'm not commiter.
May be @ndeloof , @michaelneale  or @carlossg which commit on following file https://github.com/docker-library/official-images/blob/master/library/jenkins may answer to your query.

Regards.

**Comment by ndeloof** [comment]
official image do only offer the latest LTS, this is due to the official image process which would make it hard to maintain an up-to-date image for all previous versions.

**Comment by carlossg** [comment]
1.625.1 tag was not removed, it can be pulled and it is listed ~ the middle of https://hub.docker.com/r/library/jenkins/tags/
