### ISSUE TITLE
windowsservercore-2019 image not updated

### ISSUE THREAD

**Issue by Jonny-vb** [jenkinsci/docker#1736]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
N/A
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

n/A

### Expected Results

windowsservercore-2019 docker image updated

### Actual Results

windowsservercore-2019 has not been updated in 3 weeks now (only the jdk11-hotspot-windowsservercore-2019 windows image is being updated)

### Anything else?

Not sure if this is to do with something having changed with the build process, or if something is failing with the windowsservercore-2019 image

**Comment by lemeurherve** [comment]
As Java 17 is now the default since #1724, and as there is no Windows JDK 17 image (cf https://github.com/jenkinsci/docker/tree/master/17), the short tag `windowsservercore-2019` isn't updated as there are no (new) windowsservercore images to build with the default JDK 17.

**Comment by lemeurherve** [comment]
Until/unless Windows JDK17 images is added, you'll have to use the jdk11-hotspot-windowsservercore-2019 windows image (only its tag changes)

**Comment by dduportal** [comment]
Please see https://github.com/jenkinsci/docker/issues/1490#issuecomment-1596957219 : the build process is still not building autoamtically all versions for Windows, but it could be done. Work (help) is required

**Comment by lemeurherve** [comment]
Reopening until validation with the next Weekly and LTS releases in two days.

**Comment by lemeurherve** [comment]
All versions are now automatically built, see https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=windows
