### ISSUE TITLE
Ship production build of Java 21 from Eclipse Temurin

### ISSUE THREAD

**Issue by basil** [jenkinsci/docker#1737]
The container images produced by repository contain an early access build. Since the upstream release is now generally available, this should be switched to the production GA build of Eclipse Temurin.

**Comment by lemeurherve** [comment]
I have prepared the required changes in a local branch for this repo but haven't pushed it yet as there is an issue like for https://github.com/jenkinsci/docker-agent/pull/521: not every architecture are available yet, especially the arm32 & ppc64le ones. (cf https://github.com/adoptium/temurin/issues/8), so switching to upstream images right now would require workaround for these architecture variants.

I can open a PR as draft for now, and put it ready for review when everything will be available.

**Comment by dduportal** [comment]
I'm reopening until the next weekly release which will effectively publish the images with the new JDK21 GA.

**Comment by lemeurherve** [comment]
New `jdk21` images are effectively published with the new JDK21 GA, and `jdk21-preview` ones with JDK21 EA:

```console
$ docker run jenkins/jenkins:jdk21 java -version
Unable to find image 'jenkins/jenkins:jdk21' locally
jdk21: Pulling from jenkins/jenkins
[...]
Digest: sha256:6ce5b2a957e6f0e34a32b7c0c1363dd5e2c84ab27e5c4089b8dcc9632eb706b2
Status: Downloaded newer image for jenkins/jenkins:jdk21
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

$ docker run jenkins/jenkins:jdk21-preview java -version
Unable to find image 'jenkins/jenkins:jdk21-preview' locally
jdk21-preview: Pulling from jenkins/jenkins
[...]
Digest: sha256:f0f3e76bd0a36eae70ebf6f11275f085837b9271c28c3317e0bdcaa204521306
Status: Downloaded newer image for jenkins/jenkins:jdk21-preview
openjdk version "21.0.1-beta" 2023-10-17
OpenJDK Runtime Environment Temurin-21.0.1+12-202310181806 (build 21.0.1-beta+12-ea)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12-202310181806 (build 21.0.1-beta+12-ea, mixed mode)
```
