### ISSUE TITLE
Can't login into jenkins, how to restore efficently Dockerfile/jenkins data

### ISSUE THREAD

**Issue by kopax** [jenkinsci/docker#174]
I am using jenkinsci/docker, I have two directories in my host container : 

```
- /srv/docker/company/jenkins/jenkins_home:/var/jenkins_home
- /srv/docker/company/jenkins/jenkins_data:/var/jenkins_data
```

I did the backup using this command : 

```
sudo docker run --rm --volumes-from 5603fa962600 \
-v /srv/docker/company/jenkins/jenkins_home:/var/jenkins_home \
-v /srv/docker/company/jenkins/jenkins_data:/var/jenkins_data \
-v $(pwd):/backup \
busybox tar czvf /backup/backup_jenkins.tar.gz /var/jenkins_home /var/jenkins_data
```

I wanted to restore on **another host** to test if the backup was efficient : 

```
docker run --rm --volumes-from jenkins_jenkins_1 -v /srv/docker/company/jenkins/jenkins_home:/var/jenkins_home -v /srv/docker/company/jenkins/jenkins_data:/var/jenkins_data -v $(pwd):/backup busybox tar xzvf /backup/backup_jenkins.tar.gz
```

Then I start jenkins, I can see all the list of my projects, everything looks fine until I try to login.

If I use a wrong _user/password_ I have an error message.
If I use a good _user/password_ I come back to jenkins home

Is there anything I need to know about this error regarding docker common usage or simply jenkins ?

Edit : 

This [article](https://engineering.riotgames.com/news/docker-jenkins-data-persists) recommend to use data volumes and link the docker app to the data-volume instead. Used with the same uid on both container, this will save the file permission from one system to another.

**Comment by carlossg** [comment]
If all the files in both jenkins homes are the same I'd ask in the jenkins mailing list to see what could be the problem. Also check the jenkins logs. Maybe the ip is used to salt passwords or something like that

**Comment by TwoSlick** [comment]
Jenkins encrypts credential data on the filesystem.  If you try to restore those files on another machine, it won't be able to decrypt them, and you'll get those errors.  If you use an external authentication tool like Active Directory or LDAP, you should be able to login, since those credentials aren't managed by Jenkins.

**Comment by kopax** [comment]
@TwoSlick sure but the problem is that they exist on the filesystem, could you tell me where ?
If you use data container, you don't have to take care of the uuid/guid
