### ISSUE TITLE
Unexpected loss of more precise labels in favor of less precise labels

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/docker#1754]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins 2.414.3 and Jenkins 2.426
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Compare available labels for 2.414.3-alpine and 2.414.3-slim and see that the set of labels has changed in a way that makes it more difficult to explicitly declare that I want Java 17.

Labels on 2.414.2 included:

* `2.414.2-alpine-jdk17` to run 2.414.2 on Alpine with Java 17
* `2.414.2-slim-jdk17` to run 2.414.2 on Debian slim with Java 17

Labels on 4.414.3 do not include:

* `2.414.3-alpine-jdk17`
* `2.414.3-slim-jdk17`

The labels are replaced by a less precise form:

* `2.414.3-alpine`
* `2.414.3-slim`

This is not new behavior.  Before the change to Java 17, we had labels:

* `2.414.2-alpine` to run 2.414.2 on Alpine with Java 11
* `2.414.2-slim` to run 2.414.2 on Debian slim with Java 11

We did not have labels that made it explicit that I'm running Java 11.

### Expected Results

Should the `-jdk17` suffix be available for the controller images running Java 17 so that it is clear to users that they should expect Java 17 in that container?

### Actual Results

Without the `-jdk17` suffix, the Java version is ambiguous to me as a reader.

### Anything else?

I'm OK if this is intentional and there is no plan to change it.  I was just surprised and wanted to register my surprise in the issue tracker.

**Comment by lemeurherve** [comment]
It's related to the switch to java 17 as default from #1724, hence short tags are jdk17 variants.

In 2.412.2 the situation was the same for jdk11, no "-jdk11" for alpine (for example) as it was the default JDK version:
<img width="639" alt="image" src="https://github.com/jenkinsci/docker/assets/91831478/577f2d62-f632-4433-8543-b3b8990a34cf">

In docker-agent and docker-inbound-agent tags including "jdk17" are also generated alongside the short ones.

I'll prepare a PR to do the same here, so there will also be "-jdk17" tags.

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/jenkins.io/pull/6789 to add a similar warning to the LTS changelog on jenkins.io: https://www.jenkins.io/changelog-stable/

**Comment by dduportal** [comment]
Once #1756 is merged and 2.429 published with the fixed tag, then we'll work on backporting these missing tags on the LTS (`skopeo` will allow use to "copy" images from existing tags to new tags so no need to rebuild and risk changing checksums)

**Comment by dduportal** [comment]
Reopening as the LTS tags still need to be fixed before closing

**Comment by lemeurherve** [comment]
FTR, fixup of #1756: #1757

**Comment by dduportal** [comment]
Update:

- The [freshly released 2.429](https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=2.429) weekly releases shows the missing tag 🥳 
  - [`jenkins/jenkins:2.429-alpine-jdk17`](https://hub.docker.com/layers/jenkins/jenkins/2.429-alpine-jdk17/images/sha256-84444fe65ef65d6d3cae7a6b084e977db3beaddece53c2a24106b20afa98a9cb?context=explore)
  - [`jenkins/jenkins:2.429-slim-jdk17`](https://hub.docker.com/layers/jenkins/jenkins/2.429-slim-jdk17/images/sha256-97944a2490b439ffe27fa1e9622c7ea01fa90cd9db76bc8bdcd774a834ddb055?context=explore)


Next steps:

- Preparing the `skopeo` command to backport on LTS

**Comment by dduportal** [comment]
Update: 

- Running the following commands to adds back the 2 missing labels in LTS

```
skopeo copy docker://docker.io/jenkins/jenkins:2.414.3-alpine docker://docker.io/jenkins/jenkins:2.414.3-alpine-jdk17
skopeo copy docker://docker.io/jenkins/jenkins:2.414.3-slim docker://docker.io/jenkins/jenkins:2.414.3-slim-jdk17
```

**Comment by dduportal** [comment]
Update:

Missing tags are back for the LTS:

![Capture d’écran 2023-10-24 à 19 47 41](https://github.com/jenkinsci/docker/assets/1522731/f8b2e5eb-f8ee-4879-9e20-51119bf273a7)

![Capture d’écran 2023-10-24 à 19 47 51](https://github.com/jenkinsci/docker/assets/1522731/1017a506-a8e9-4d23-9d33-ad119fbfe5b0)

**Comment by dduportal** [comment]
@MarkEWaite @timja @lemeurherve May I ask you for help to:

- Confirm it is ok for you (on the 2.414.3 LTS and the fresh new weekly 2.429 image) ?
- Update the changelogs to map top the new state (e.g. these 2 images are the same as their short version, bit for bit, but their datetime of update is today instead of the LTS release day last week)

**Comment by lemeurherve** [comment]
@dduportal I confirm it's OK for me, I opened https://github.com/jenkins-infra/jenkins.io/pull/6805 to update the LTS changelog.

I've also updated the GitHub release notes https://github.com/jenkinsci/docker/releases/tag/2.414.3, the text can be reviewed later depending on the feedback on the above PR.

<img width="1143" alt="image" src="https://github.com/jenkinsci/docker/assets/91831478/865b64d5-7a6a-4a4b-857e-4e3cb6c43502">

**Comment by dduportal** [comment]
Thanks for confirming! Closing
