### ISSUE TITLE
latest with jdk17 & almalinux

### ISSUE THREAD

**Issue by drhae** [jenkinsci/docker#1768]
### What feature do you want to see added?

Since jdk11 is going to no longer be supported,  when will an image with lastest jenkins, jdk17 and almalinux be available?

**Comment by timja** [comment]
There are no current plans for it.

These are what we are providing for now:
https://github.com/jenkinsci/docker/tree/master/17

**Comment by MarkEWaite** [comment]
As stated by @timja, there is no plan to move almalinux to Java 17.  Switch to use the UBI container image that includes Java 17.
