### ISSUE TITLE
Update Docker Hub description with JDK17 images instead of JDK11

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker#1771]
The current Docker Hub description mentions JDK11 images while the default JDK has been switched to JDK17 since #1724.
This description should be updated.

https://hub.docker.com/r/jenkins/jenkins

<img width="654" alt="image" src="https://github.com/jenkinsci/docker/assets/91831478/70dd3517-8e5a-4013-aaab-015b50d90821">

**Comment by dduportal** [comment]
Good catch! Updating it now

**Comment by dduportal** [comment]
Done:

![Uploading Capture d’écran 2023-11-04 à 14.07.14.png…]()
