### ISSUE TITLE
Publish a Windows image for each supported Java version

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker#1774]
### What feature do you want to see added?

It would be nice to publish Windows images for each supported Java version, as since #1773 only a jdk17 image is published.

Related:
- https://github.com/jenkinsci/jep/pull/400

**Comment by lemeurherve** [comment]
As tests are currently run sequentially, I've kept only the JDK17 and the JDK11 in #1770 to not increase build time too much.

Note: the container images publication on trusted.ci.jenkins.io skips tests so no publication time increase.

**Comment by MarkEWaite** [comment]
As far as I know, this has been completed by

* #1820
