### ISSUE TITLE
Windows - There should be a set of weekly and LTS short tags not including Jenkins version in their names

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker#1783]
### Jenkins and plugins versions report

N/A

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

Notice the set of last tags published today for the 2.426.1 LTS release:
- JDK17 (default JDK)
  - jenkins/jenkins:2.426.1-jdk17-hotspot-windowsservercore-ltsc2019
  - jenkins/jenkins:2.426.1-windowsservercore-ltsc2019
  - jenkins/jenkins:**jdk17-hotspot-windowsservercore-ltsc2019**
  - jenkins/jenkins:**windowsservercore-ltsc2019**

- JDK11
  - jenkins/jenkins:2.426.1-jdk11-hotspot-windowsservercore-ltsc2019
  - jenkins/jenkins:**jdk11-hotspot-windowsservercore-ltsc2019**

Compare them to the last set of last tags published yesterday for the 2.432 Weekly release:
- JDK17 (default JDK)
  - jenkins/jenkins:2.432-jdk17-hotspot-windowsservercore-ltsc2019
  - jenkins/jenkins:2.432-windowsservercore-ltsc2019
  - jenkins/jenkins:**jdk17-hotspot-windowsservercore-ltsc2019**
  - jenkins/jenkins:**windowsservercore-ltsc2019**

- JDK11
  - jenkins/jenkins:2.432-jdk11-hotspot-windowsservercore-ltsc2019
  - jenkins/jenkins:**jdk11-hotspot-windowsservercore-ltsc2019**

### Expected Results

The Weekly release and the LTS release have their own short tags not including Jenkins version in their names so (even if it's not recommended) it's possible to use a constant tag to specify either the last Weekly or either the last LTS release.

### Actual Results

On LTS release week, the short tags `windowsservercore-ltsc2019` and `jdk17-hotspot-windowsservercore-ltsc2019` correspond for one day to the last Weekly release, then the next day and for a week of its publication to the last LTS release until a new Weekly is released, in which case these tags then corresponds to the last Weekly again.

**Comment by dduportal** [comment]
Reopening as the issue need a release or operation on DockerHub to have the expected tags

**Comment by watertianyi** [comment]
@dduportal 
I installed docker-desktop4.24.06 in Windows 10 19042.928. The graphics card driver is 537.42 and the following error is reported. How should I solve it?
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

**Comment by dduportal** [comment]
> @dduportal I installed docker-desktop4.24.06 in Windows 10 19042.928. The graphics card driver is 537.42 and the following error is reported. How should I solve it? docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

this is neither a Jenkins or Jenkins containert image related question. You should ask your question in a Docker community forum.
