### ISSUE TITLE
Suggestion: inheritance-friendly image

### ISSUE THREAD

**Issue by RomanSaveljev** [jenkinsci/docker#181]
With relatively simple modifications the image can be made friendlier to users trying to inherit from it:

* Add `ONBUILD USER root`

**Comment by ndeloof** [comment]
could indeed make it a bit simpler to extend this image, but would also introduce risk for some to run jenkins as root if they don't use `USER jenkins` at the end of their Dockerfile. For this reason I prefer one make it explicit to switch to root escalated privileges then revert to jenkins.
