### ISSUE TITLE
Remove Almalinux image or upgrade it to Java 17

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/docker#1894]
As noted in https://github.com/jenkinsci/docker/issues/1890#issuecomment-2159164375 and since #1891 there won't be any Almalinux (with Java 11) image released for the weekly line as soon as next week, and for the LTS line when Java 17 will be required:
https://github.com/jenkinsci/docker/blob/8ae866615c4deb68787e247179d5c87bd824d31a/docker-bake.hcl#L16-L20

Should we let this image go away with Java 11 or should we upgrade it to Java 17?

**Comment by timja** [comment]
Lets remove it and see if enough user demand

**Comment by dduportal** [comment]
> Lets remove it and see if enough user demand

+1

**Comment by lemeurherve** [comment]
+1

**Comment by MarkEWaite** [comment]
+1  That is the plan that was discussed in the Platform SIG as well.  No further updates to the Almalinux container image

**Comment by MarkEWaite** [comment]
Removed by:

* #1937
