### ISSUE TITLE
new Jenkins version not released for jdk11 

### ISSUE THREAD

**Issue by grayudu** [jenkinsci/docker#1927]
### What feature do you want to see added?

The existing version bookworm-20240812 is not compatible with FIPS enabled runtimes and any apt-get commands fail with

```
Reading package lists...fatal error in libgcrypt, file ../../src/misc.c, line 92, function _gcry_fatal_error: requested algo not in md context
Fatal error: requested algo not in md context
```

`bookworm-20240904` looking good but I do not see [JDK11 Jenkins latest version](https://hub.docker.com/r/jenkins/jenkins/tags?page_size=&ordering=&name=jdk11) with latest `debian` version.
```
~ kubectl run -i --rm --tty debug --image docker.intuit.com/debian:bookworm-20240904 -- apt-get update
If you don't see a command prompt, try pressing enter.
warning: couldn't attach to pod/debug, falling back to streaming logs: Internal error occurred: error attaching to container: container is in CONTAINER_EXITED state
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [179 kB]
Fetched 9223 kB in 1s (10.0 MB/s)
Reading package lists... Done
pod "debug" deleted
```

**Comment by basil** [comment]
Starting with the Jenkins 2.463 weekly release (and the forthcoming October LTS release), Jenkins requires Java 17 or newer. Java 11 is supported in Jenkins 2.462 and earlier weekly, 2.462.x and earlier LTS.

**Comment by grayudu** [comment]
@basil Thanks for your reply. will you be release 2.462.x with latest `debian` version ?

**Comment by dduportal** [comment]
> @basil Thanks for your reply. will you be releasing 2.462.x with latest `debian` version ?

The upcoming 2.462.3 will have the new version yes, but only on a few weeks.
