### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [jenkinsci/docker#1928]
### Describe your use-case which is not covered by existing documentation.

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Jenkins application as shown [here](https://elest.io/open-source/jenkins). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

- https://elest.io/open-source/jenkins

### Are you interested in contributing to the documentation?

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/jenkins)

**Comment by MarkEWaite** [comment]
Won't be done in this repository.  The downloads page on www.jenkins.io is the correct location for the proposed change.
