### ISSUE TITLE
Error processing tar file(exit status 1): unexpected EOF

### ISSUE THREAD

**Issue by hubcomsix** [jenkinsci/docker#1941]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

centos7

### Reproduction steps

docker load -i xxx.tar.gz

### Expected Results

success

### Actual Results

Error processing tar file(exit status 1): unexpected EOF

**Comment by lemeurherveCB** [comment]
You'll need to add more details if you want some help, I don't see how to reproduce nor how it's related to this image.
