### ISSUE TITLE
Multiple JAVA_OPTS or JENKINS_OPTS not handled correctly

### ISSUE THREAD

**Issue by ssaarinen** [jenkinsci/docker#195]
Running following commands against the latest image (1.642.1) does not work
```
docker run -it --rm  -e JENKINS_OPTS="--version --prefix=/jenkins" jenkins
```
or
```
 docker run -it --rm -e JAVA_OPTS="-Xmx1024m -Dfoo=bar" jenkins
```

It think it's either jenkins.sh or user error but using jenkins:1.625.3 both commands work fine

**Comment by carlossg** [comment]
see #194

**Comment by ssaarinen** [comment]
Sorry but looking at #194 I still do not understand how I can pass multiple JAVA_OPTS or JENKINS_OPTS?
