### ISSUE TITLE
The jobs are not getting deleted

### ISSUE THREAD

**Issue by kewlvishnu** [jenkinsci/docker#199]
the jenkins image in docker works and is also creating the container properly, however the jobs are not getting deleted.

**Comment by carlossg** [comment]
wdym?

**Comment by kewlvishnu** [comment]
![image](https://cloud.githubusercontent.com/assets/2000457/12940900/10e89234-cf93-11e5-8024-f970534b25ad.png)

![image](https://cloud.githubusercontent.com/assets/2000457/12940915/35f4fe64-cf93-11e5-8981-bb792d6ff33e.png)

When we click the delete button, the job does not get deleted. for your reference, see below the link the button is pointing to.
![image](https://cloud.githubusercontent.com/assets/2000457/12940948/7a5cf96c-cf93-11e5-8697-75dc12335e3a.png)

**Comment by carlossg** [comment]
You should ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).

Works fine here
