### ISSUE TITLE
Unable to pass multiple parameters through JAVA_OPTS

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/docker#202]
Related to #195 and #194.
When trying to execute following command
`docker run -v ~/jenkins_home:/var/jenkins_home -p 80:8080 -p 50000:50000 -d --env JAVA_OPTS="-Xmx1024m -Duser.timezone=Europe/Kiev" jenkins`

getting
```
Invalid maximum heap size: -Xmx1024m -Duser.timezone=Europe/Kiev
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Second (timezone) setting passing to heap size variable.

**Comment by carlossg** [comment]
the fix will be released in next LTS

**Comment by F1ashhimself** [comment]
Nope, the same issue that we can't pass some variables to `JAVA_OPTS`... #213

**Comment by Samistine** [comment]
Bump

**Comment by carlossg** [comment]
what problem do you have and with what version? 
Tests are passing

**Comment by carlossg** [comment]
What problem do you have and with what version?
Tests are passing

**Comment by DaspawnW** [comment]
Have the same issue with Version 2.7.2 try to pass multiple parameters to JAVA_OPTS: `-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.security.ArtifactsPermission=true"`
Interpreted by Jenkins as key: -Dhudson.model.ParametersAction.keepUndefinedParameters and value: true -Dhudson.security.ArtifactsPermission=true

**Comment by carlossg** [comment]
Please, if you want some help, always always paste the command you are running 

This works for me 

    docker run -ti --rm -e JAVA_OPTS="-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.security.ArtifactsPermission=true" -p 8080:8080 jenkins

in http://localhost:8080/systemInfo

```
hudson.model.ParametersAction.keepUndefinedParameters	true
hudson.security.ArtifactsPermission	true
```

**Comment by DaspawnW** [comment]
Sorry for this. This is my Docker-Compose file...

`jenkinsWaves:
   image: jenkins:latest
   ports:
      - "2020:8080"
      - "50001:50000"
   environment:
      - JAVA_OPTS="-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.security.ArtifactsPermission=true"
   volumes:
      - ~/jenkins_waves:/var/jenkins_home`

**Comment by carlossg** [comment]
have you tried without the quotes?

**Comment by DaspawnW** [comment]
@carlossg Thank you very much, it runs 👍

**Comment by xmeng1** [comment]
mark！

**Comment by gdisk** [comment]
mark
