### ISSUE TITLE
Can't pass own Jenkins_opts with Docker image 1.642.1

### ISSUE THREAD

**Issue by rreinurm** [jenkinsci/docker#204]
With docker image jenkins:1.642.1 I can't pass my own jenkins parameters because jenkins.sh script splits the them. Like --httpPort=-1 is passed as -1.
With current git master where jenkins.sh (commit hash db6eb677da5141c17080c5bd1fe6204e1e0637f9) script has been fixed it works again. Can you rebuild latest docker image and push it to Docker hub?

**Comment by carlossg** [comment]
See #194

**Comment by rreinurm** [comment]
My point was that current Docker image in Docker hub contains older jenkins.sh script, although last image according to Docker hub was pushed 2 days ago. If I build Docker image directly from Github repo with the existing jenkins.sh script, then my issue does not appear.

**Comment by carlossg** [comment]
A new LTS is going to be built by Docker and will be available any time now
