### ISSUE TITLE
Filter out plugins already installed

### ISSUE THREAD

**Issue by jimzucker** [jenkinsci/docker#207]
When we pass in a list of plugins, it would be efficient if the list was filtered based on what is already installed.  If the team is agrees this is a good idea I can take a shot at modifying the script.

**Comment by jimzucker** [comment]
Updated to base analysis on jenkins.war, test results:
Removing intermediate container 7f545b034f1a
Step 7 : RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
 ---> Running in f1606faa6f4a
  ... skipping already installed:  ant:1.2
  ... skipping already installed:  antisamy-markup-formatter:1.1
  ... skipping already installed:  credentials:1.18
Downloading cucumber-testresult-plugin:0.8.2
  ... skipping already installed:  cvs:2.11
  ... skipping already installed:  external-monitor-job:1.4
Downloading git:2.4.0
Downloading git-client:1.19.0
  ... skipping already installed:  javadoc:1.1
  ... skipping already installed:  junit:1.2-beta-4
  ... skipping already installed:  ldap:1.11
  ... skipping already installed:  mailer:1.11
  ... skipping already installed:  matrix-auth:1.1
  ... skipping already installed:  matrix-project:1.4.1
  ... skipping already installed:  maven-plugin:2.7.1
  ... skipping already installed:  pam-auth:1.1
Downloading scm-api:1.0
  ... skipping already installed:  script-security:1.13
  ... skipping already installed:  ssh-credentials:1.10
  ... skipping already installed:  ssh-slaves:1.9
  ... skipping already installed:  subversion:1.54
  ... skipping already installed:  translation:1.10
  ... skipping already installed:  windows-slaves:1.0
 ---> 8da9a950147d
Removing intermediate container f1606faa6f4a
Step 8 : ADD jobs /var/jenkins_home/jobs

**Comment by jimzucker** [comment]
@gmacario I added the use case you suggested on PR #219 when I tested I observed with the current implimentation you have restart the docker instance for the plugins to get copied from the /ref directory and restart jenkins to see them.

I see two choices(maybe you see more):
1. I can print a messages explaining you have to restart docker for the changes to take effect
2. We can install the plugins in a different manner /restart automatically..

I am thinking approach #1 is probably the way to go for right now..

Thoughts?

**Comment by jimzucker** [comment]
@gmacario - I implemented a warning the you have to restart the container and squished the commits.

**Comment by carlossg** [comment]
#219 is merged
