### ISSUE TITLE
Error passing JAVA_OPTS with spaces and quotes

### ISSUE THREAD

**Issue by F1ashhimself** [jenkinsci/docker#213]
According to http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-securityConfigureJenkinsContentSecurity

I should use something like `docker run -v ~/jenkins_home:/var/jenkins_home -p 80:8080 -p 50000:50000 -d --restart=always --env JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';" jenkins` to get allure plugin working.

But when I'm running this command without -d (detached) flag I can see the issue `Error: Could not find or load main class 'self';`.

This is related to #185 #194 #202 
1.5 month already passed, are you going to fix this?

**Comment by carlossg** [comment]
have you pulled last version 1.642.2 ?

**Comment by F1ashhimself** [comment]
Sure, this appears on `latest, 1.642.2 (Dockerfile)`.

**Comment by carlossg** [comment]
I have added tests for `JAVA_OPTS`, `JENKINS_OPTS` and arguments. As it is now `JAVA_OPTS` with spaces and quotes is broken.
If I revert 5fc9cd to use `bash -c` again, it all works except arguments

Unless somebody with more bash fu can find a solution that works in all cases I'll revert 5fc9cd and add a note that args are broken

**Comment by F1ashhimself** [comment]
> Unless somebody with more bash fu can find a solution that works in all cases I'll revert 5fc9cd0 and add a note that args are broken

Seems ok as for now, will try to find a solution.

**Comment by carlossg** [comment]
btw to run the tests just use `bats tests` (`brew install bats` in os x)

**Comment by carlossg** [comment]
fixed now, will publish a new image

**Comment by F1ashhimself** [comment]
@carlossg thank you

**Comment by kalahari** [comment]
This appears to be broken again in `docker pull jenkinsci/jenkins:2.4` but I don't see a corresponding release in this project so I'm not sure where it broke. Was working fine in `docker pull jenkinsci/jenkins:2.0-beta-1`

**Comment by cuipengfei** [comment]
same problem with 2.19.1

**Comment by carlossg** [comment]
there is a test passing, https://github.com/jenkinsci/docker/blob/master/tests/runtime.bats#L33 so what exactly is broken for you?
