### ISSUE TITLE
Jenkins container startup is hung up

### ISSUE THREAD

**Issue by gskrscm** [jenkinsci/docker#217]
$ docker run --name myjenkins -p 8080:8080 -p 50000:50000 jenkins
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 04, 2016 7:16:02 AM winstone.Logger logInternal
INFO: Beginning extraction from war file
Mar 04, 2016 7:16:04 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: jetty-winstone-2.9
Mar 04, 2016 7:16:08 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 04, 2016 7:16:10 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
Mar 04, 2016 7:16:10 AM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Mar 04, 2016 7:16:11 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 04, 2016 7:16:27 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 04, 2016 7:16:27 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 04, 2016 7:16:27 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Mar 04, 2016 7:16:33 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Mar 04, 2016 7:16:38 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Mar 04, 2016 7:16:38 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Mar 04, 2016 7:16:39 AM org.jenkinsci.main.modules.sshd.SSHD start
INFO: Started SSHD at port 41606
Mar 04, 2016 7:16:39 AM jenkins.util.groovy.GroovyHookScript execute
INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Mar 04, 2016 7:16:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Mar 04, 2016 7:16:41 AM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
--> setting agent port for jnlp
--> setting agent port for jnlp... done
Mar 04, 2016 7:16:57 AM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource default
Mar 04, 2016 7:16:58 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
Mar 04, 2016 7:17:00 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Ant.AntInstaller
Mar 04, 2016 7:17:04 AM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tools.JDKInstaller
Mar 04, 2016 7:17:04 AM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 25,629 ms

Am new to containers. 
Can someone point out what could be the issue?

**Comment by carlossg** [comment]
there is no issue

    INFO: Jenkins is fully up and running
