### ISSUE TITLE
Building new Docker image fails on plugin install

### ISSUE THREAD

**Issue by jbrisbin** [jenkinsci/docker#218]
It looks like there's been a change to how the plugins are hosted so that the "latest" version tag isn't where the script is expecting it to be:

https://github.com/jenkinsci/docker/blob/master/plugins.sh#L26

The symlink to the latest is now at /latest/plugin-name.hpi rather than how the script has it.

Was this change just enacted recently?

**Comment by carlossg** [comment]
It works fine for me, it downloads https://updates.jenkins-ci.org/download/plugins/credentials/latest/credentials.hpi
