### ISSUE TITLE
Resolve plugins dependencies

### ISSUE THREAD

**Issue by mathieu-pousse** [jenkinsci/docker#220]
That would be really nice to use this script to install plugins and their dependencies in place of the existing one

https://gist.github.com/rpetti/292d8bdd9e45659e6c86

cc @rpetti 

Thanks in advance

**Comment by rpetti** [comment]
Full disclosure: this is just a modified version of https://gist.github.com/micw/e80d739c6099078ce0f3 by @micw.

While this script takes the same input as the one currently in the docker image, it does not honor any version numbers specified in the plugins.txt given to it. It will only ever fetch the latest release of every plugin and their dependencies. If it's to be a true replacement for the existing script, then it should enhanced to support installing plugins from specific version numbers just as the current script does.

**Comment by carlossg** [comment]
ping @Vlatombe

**Comment by mathieu-pousse** [comment]
I see your point but dealing with versions of plugins could lead to headache when two plugins depend on two different version of another one. If we want to reimplement this behaviour I guess you want to stick to what is done in java.

What is the rule in jenkins. Does the latest always win ?

**Comment by rpetti** [comment]
I'm only referring to the plugins specified in the list, which has the format of <plugin>:<version>. You'll notice that this new script completely ignores the version specification, which does not conform with the behavior of the current script.

When it comes to resolving dependencies, it should probably just get the latest version that's still supported by the core that's installed.

**Comment by carlossg** [comment]
implemented in 0ef5a628c4f1887e401c49dbb616b9881d1e82f9
