### ISSUE TITLE
Connecting to GitHub Enterprise

### ISSUE THREAD

**Issue by formerlyKurt** [jenkinsci/docker#222]
I am trying to create a job from Jenkins that can connect to github enterprise.  I can see the connection from the host but the same connection fails from Jenkins.  Any thoughts on how to debug this issue or why it might be failing in Jenkins?

Thanks!

**Comment by carlossg** [comment]
Questions are better asked in the Jenkins user mailing list https://jenkins.io/content/mailing-lists/
