### ISSUE TITLE
Can't find file init.groovy

### ISSUE THREAD

**Issue by agonyeye** [jenkinsci/docker#228]
Hi Guys

I met a issue when I built the image in step 14, please check as below, would you please help fix the problem>

Step 14 : COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy lstat **init.groovy: no such file or directory   **

Regards
Eric

**Comment by carlossg** [comment]
the file is there, without any logs don't know what your problem may be
