### ISSUE TITLE
Allow to copy SSH public/private keys to image

### ISSUE THREAD

**Issue by babatundebusari** [jenkinsci/docker#230]
How do i add ssh public/private keys to this image to help with connecting to remote servers? I know there is SSH agent plugin, but that is TOO much work. If i can add SSH keys to this container, will make like SO much easier.

I understand jenkins runs as jenkins user, so when i try to copy anything to /var/jenkins_home it never gets copied.

Please HELP

**Comment by dweomer** [comment]
The SSH Agent plugin is difficult to setup and use? I guess I have been ramping up on Jenkins so hard over the last year that I forget such things but this seems like a dubious assertion to me. That aside, have you tried extending the official Jenkins image and `ADD`ing your `id_rsa` and `id_rsa.pub` files to `/usr/share/jenkins/ref/.ssh/`? You will want to make sure your permissions are correct of course. another issues is you will want to setup your default, system ssh client with a proper non-interactive `/usr/share/jenkins/ref/.ssh/config`, something like:

```
Host *
    PasswordAuthentication  no
    StrictHostKeyChecking   no
    UserKnownHostsFile      /dev/null
``` 

Also, you will want to make sure your permissions are all in line for ssh to be happy (there are likely config options to override that as well but I do not know these off the top of my head).

The significance of `/usr/share/jenkins/ref` as per the [README.md](https://github.com/jenkinsci/docker#installing-more-tools) is that, unless overridden, at startup the `jenkins.sh` script will copy all content from `/usr/share/jenkins/ref` to `$JENKINS_HOME` provided there there is not content of the same name already in place.

Hope this helps.

---

P.S. The reason you are losing content you `COPY` to `$JENKINS_HOME` aka `/var/jenkins_home` is that it is declared as a `VOLUME` in the [`Dockerfile`](https://github.com/jenkinsci/docker/blob/master/Dockerfile). This is why the `/usr/share/jenkins/ref` copying facility exists.

**Comment by dweomer** [comment]
Also: don't publish an image with keys in it to Docker Hub if you do choose this route!

**Comment by babatundebusari** [comment]
Actually i just found out jenkins jobs are run as `root` user actually, so i just copied the SSH keys under `/root/.ssh/*` so all is working well now.

So i have no more issues.

P.S. I didn't mean the SSH Agent plugin is hard to use, but i meant its not the best way to approach login to remote servers, because one has to add credentials for all servers to get into, which is one less secured and second too much stuff to manage. 

Using the SSH key inside container means i manage just one file. So i do not need the SSH Agent plugin anymore.

Thanks.
