### ISSUE TITLE
Plugins should not be pinned

### ISSUE THREAD

**Issue by carlossg** [jenkinsci/docker#236]
In #93 plugins installed in the image get pinned. This causes problems when an existing jenkins_home is upgraded to a new docker image and the new war includes those plugins.
They will not be upgraded to the version bundled in the war because they are pinned in jenkins_home

@jglick @tfennelly

**Comment by carlossg** [comment]
Actually it's more complex than that

* plugin is NOT included in war: no need to pin
* plugin is included in war: need to pin it so the war doesn't override it
 * and we still have the problem that if the war is upgraded and plugin removed from image the pin file will remain there, preventing the upgrade from the war

**Comment by MarkEWaite** [comment]
I modified my plugins.txt file to have 3 possible values in the right hand side of the ":".  

- If the value is empty, then that plugin is assumed to be a bundled plugin and is pinned
- If the value is "latest", then the latest version of that plugin is used
- If the value is a non-empty string other than latest, that is taken as the version to use

Thus far, it has worked reasonably well for me across multiple version upgrades.

**Comment by ndeloof** [comment]
@MarkEWaite can you please share your changes ?

**Comment by MarkEWaite** [comment]
I'll see what I can gather from my changes for discussion.

**Comment by carlossg** [comment]
This can probably be closed now that there's no pinning in Jenkins 2
