### ISSUE TITLE
Alpine-based Jenkins image on Docker Hub

### ISSUE THREAD

**Issue by elifarley** [jenkinsci/docker#242]
Even though there's an Alpine branch now (see #239), the Alpine-based image cannot be found at https://hub.docker.com/r/library/jenkins/tags/ - I'd expect to see tags like alpine-latest, alpine-1.642.3 and so on.

It would be nice to have a new Alpine image every time the Alpine branch gets updated.

**Comment by carlossg** [comment]
requested at https://github.com/docker-library/official-images/pull/1622
