### ISSUE TITLE
Source control tools from java:8-jdk

### ISSUE THREAD

**Issue by elifarley** [jenkinsci/docker#246]
See #245.
The master branch is based on **java:8-jdk**, which have these source control tools installed:

1. **git** 1:2.1.4-2.1+deb8u2
2. **Mercurial** 3.1.2-2+deb8u1
3. **Subversion** 1.8.10-6+deb8u3
4. **bzr** 2.6.0+bzr6595-6

Should these be installed on the **alpine** branch?

My first guess is that the Alpine-based Jenkins image should not have these tools, so that it can stay as minimalistic as Alpine is.

**Comment by carlossg** [comment]
I think we should not install any tools in the master image. Adding packages is easy, removing is impossible

@ndeloof WDYT?

**Comment by ndeloof** [comment]
Totally agree on avoiding tool installation as much as possible.

commonly used SCM is a special case for plugin who rely on them for polling (without workspace), so git should be added to alpine image imho. afaik mercurial or subversion aren't (plugin do use java client libraries). Not sure about bzr - but also not such a commonly used SCM.

**Comment by carlossg** [comment]
ok then, alpine already has git and openssh-client to connect to remote git repos

**Comment by elifarley** [comment]
Master has not only git, but also Mercurial, Subversion and bzr.
So I'll create a PR to *alpine* to install them too.
