### ISSUE TITLE
jenkins:alpine broke due -t switch on unzip command

### ISSUE THREAD

**Issue by s17t** [jenkinsci/docker#247]
The -t is not supported in the unzip version included in alpine, this the error when trying build container that include plugins.txxt:
```
unzip: unrecognized option: t

BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: unzip [-lnopq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]

Extract FILEs from ZIP archive

        -l      List contents (with -q for short form)
        -n      Never overwrite files (default: ask)
        -o      Overwrite
        -p      Print to stdout
        -q      Quiet
        -x FILE Exclude FILEs
        -d DIR  Extract into DIR
```

**Comment by tianon** [comment]
Looks like the Alpine variant needs to include `apk add --no-cache unzip` so that it gets a fully-featured `unzip` instead of relying on the version included in BusyBox (or the script adapted to not need `-t` somehow).

**Comment by tianon** [comment]
cc @carlossg

**Comment by carlossg** [comment]
Fixed and added some more tests with bats

**Comment by tianon** [comment]
Sweet, thanks @carlossg! :+1:
