### ISSUE TITLE
Running Jenkins in Docker, gets stuck

### ISSUE THREAD

**Issue by fabianoamorim** [jenkinsci/docker#249]
I'm using docker and run a Jenkins image from Docker.
From hub.docker.com, I select Jenkins which says to type:
 
    docker run -p 8080:8080 -p 50000:50000 jenkins

It downloads and runs Jenkins but then it got stuck in the following message:

INFO: Obtained the updated data file for hudson.tools.JDKInstaller
Apr 19, 2016 8:21:31 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 5,177 ms
--> setting agent port for jnlp
--> setting agent port for jnlp... done

And stays like this forever..

Thanks

**Comment by carlossg** [comment]
you missed the `INFO: Jenkins is fully up and running` message

see #217
