### ISSUE TITLE
SSH boot time is slow inside container

### ISSUE THREAD

**Issue by BenHall** [jenkinsci/docker#255]
I launch the container, after five minutes it launches. What I'm trying to do now is take this container and move it to a different machine however it still takes a long time to boot up.  

As you can see, the slow step is between the SSHD is started. 

```
Apr 28, 2016 5:49:36 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 5,290 ms                                                   
--> setting agent port for jnlp                                                              
--> setting agent port for jnlp... done
Apr 28, 2016 5:56:07 PM org.jenkinsci.main.modules.sshd.SSHD start                           
INFO: Started SSHD at port 36638                                                             
Apr 28, 2016 5:56:07 PM jenkins.InitReactorRunner$1 onAttained                               
INFO: Completed initialization   
```

The UI says "Please wait while Jenkins is getting ready to work"

Is there any way to improve the boot time?

I'm seeing this behaviour with jenkins:1.651.1-alpine and jenkins:2.0

**Comment by BenHall** [comment]
Disabling the SSH service solves the problem (thanks to - https://groups.google.com/forum/#!msg/jenkinsci-users/qZ5bRGWcFso/LBbNbJZXQL4J)

Any reason why SSH is slow to launch?

**Comment by carlossg** [comment]
maybe some name/ip resolution that is slow on your side?

**Comment by carlossg** [comment]
This is typically caused by wrong dns/dhcp settings in the container
