### ISSUE TITLE
Use java:9-jdk image

### ISSUE THREAD

**Issue by phlegx** [jenkinsci/docker#259]
Would it be possible to switch to ```java:9-jdk``` instead of using ```java:8-jdk``` resp. create an additional version that uses Java 9? The java 9 docker image would use Debian ```Sid```whereas the JAVA 8 version still uses Debian ```Jessie```.

Would be very helpful when one needs glibc >= 2.22  for docker in docker (resp. using the hosts docker binary), since to my knowledge, this version of glibc is not available in Debian Jessie.

thanks!

**Comment by carlossg** [comment]
it just uses the official image for `java:latest`, when that changes this one will change

**Comment by phlegx** [comment]
@carlossg hmm but here for the 2.0 version It uses Java 8: https://github.com/jenkinsci/docker/blob/5a51d0a519cb6605280adb8719f0e050ea69bac6/Dockerfile

see also latest (2.0) on the docker hub page: https://hub.docker.com/_/jenkins/

**Comment by dweomer** [comment]
Seems like a brittle setup to bind-mount in the host's docker binary if it is not a static executable.

**Comment by phlegx** [comment]
As far as I understood and find out there are two ways @dweomer either doing that brittle thingy, or installing docker in docker. Both have their disadvantages as far as I have seen.

But of course: I'm totally open for a better way to solve this. What do you guys do?

**Comment by carlossg** [comment]
we will change the FROM when java 9 becomes the "official" latest

I don't use DinD, use bind mounting

**Comment by dweomer** [comment]
@phlegx our Jenkins masters/slaves are run inside containers that bind mount `/var/run/docker.sock`. These containers have the static docker binary installed at image build time (because it is easy). This follows advice at https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ and what @carlossg said above with regards to DinD, aka Docker-in-Docker.

**Comment by phlegx** [comment]
OK I see yes, thanks! I also read this jpetazzo advice and tried it out. However for me this was not working. I had to share also some other libs to make docker inside my CI working. Let me try it via ```/var/run/docker.sock``` only again. I might just did something wrong.
