### ISSUE TITLE
Upgrade to Jenkins WAR is lost when Docker image restarted

### ISSUE THREAD

**Issue by occasl** [jenkinsci/docker#261]
I found that whenever I update plugins and settings in my Docker Jenkins image I have running, everything is persisted between restarts of that same image.  This is good thing!

However, if I upgrade Jenkins itself to the next release from the Web application, that is lost between Docker restarts, presumably because that is not held in the volume I have mounted: /var/jenkins_home vs. /usr/share/jenkins (where the WAR is replaced and copied from per jenkins.sh).

Now I could update the image itself, but then I'll lose all the config/update information I did to the original image. Any suggestions on how I could get around this?

**Comment by carlossg** [comment]
I would say that's the expected behavior, updates from UI don't work because that's what the image is for.

**Comment by carlossg** [comment]
you need to use the same data volume with a newer image
