### ISSUE TITLE
Alpine Images: Add some Packages for (un-)packing

### ISSUE THREAD

**Issue by nolange** [jenkinsci/docker#262]
Hello,

I know this is something depending highly on the use-case, but I would think alot people would like to handle access to VCS and shuffle data around from and too build-nodes.
This typically requires a set of programms like git, tar and gzip etc.

Jenkins (Container or small ARM Board): Checkout sources (git), pack them (tar + xz) and distribute them to worker nodes.
Packing sources requires some options the busybox tar doesnt have (setting owner, transforming directory name).

For this reason I would ask to add **gnu tar** and **xz** to the base Alpine Image, the Debian Image has these 2 Programs aswell.

**Comment by carlossg** [comment]
I'm a bit against adding packages, but let's see how many people vote for this issue

**Comment by carlossg** [comment]
unzip and git are now added https://github.com/jenkinsci/docker/blob/alpine/Dockerfile#L3
