### ISSUE TITLE
latest tags points to Jenkins 1.651.1

### ISSUE THREAD

**Issue by ltagliamonte** [jenkinsci/docker#265]
I just realised that the latest tag is not pointing to latest weekly release anymore but to 1.651.1.
Since last week the latest tag was following the latest weekly Jenkins release, is this an expected behavior?
If yes can we add a latest-weekly tag so that I can easily automate Jenkins update?

**Comment by carlossg** [comment]
This is the Long Term Support release
For weekly releases check out jenkinsci/jenkins

due to my mistake latest pointed to 2.0 last week, but should always point to LTS

**Comment by ltagliamonte** [comment]
Thank you @carlossg what about introducing a latest weekly tag? I keep updated the docker image with a script that fetches the latest tag so it would be easier and less error prone to fetch the latest-weekly tag instead of listing sorting and pull. What do you think about?

**Comment by carlossg** [comment]
weekly is already pushed to  jenkinsci/jenkins
