### ISSUE TITLE
README says image is LTS, but 2.1 is delivered

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/docker#267]
The README says that the image is a long term support release, but the default version being installed is weekly version 2.1.

Shouldn't the default version be 1.651.1 per [LTS changelog](https://jenkins.io/changelog-stable/) and [jenkins.io](https://jenkins.io/)?

**Comment by carlossg** [comment]
There was an error updating latest, but it is back now to 1.651.1

**Comment by MarkEWaite** [comment]
The Dockerfile still seems to reference Jenkins 2.0 (sorry, not 2.1) at https://github.com/jenkinsci/docker/blob/master/Dockerfile#L37

**Comment by carlossg** [comment]
have you tried?
from https://hub.docker.com/_/jenkins/

<ul>
<li><a href="https://github.com/jenkinsci/jenkins-ci.org-docker/blob/b8ad2f606001fb3fa57fa5051d655e894c15c149/Dockerfile"><code>latest</code>, <code>1.651.1</code> (<em>Dockerfile</em>)</a></li>
<li><a href="https://github.com/jenkinsci/jenkins-ci.org-docker/blob/5a51d0a519cb6605280adb8719f0e050ea69bac6/Dockerfile"><code>2.0</code> (<em>Dockerfile</em>)</a></li>
<li><a href="https://github.com/jenkinsci/jenkins-ci.org-docker/blob/bf76339b2a65acb309bcdc472cfcc9306eeb45f3/Dockerfile"><code>alpine</code>, <code>1.651.1-alpine</code> (<em>Dockerfile</em>)</a></li>
<li><a href="https://github.com/jenkinsci/jenkins-ci.org-docker/blob/62229b12c22e6eff4e5960cde4bb86cc61ba14db/Dockerfile"><code>2.0-alpine</code> (<em>Dockerfile</em>)</a></li>
</ul>

**Comment by MarkEWaite** [comment]
I have forked the repository and use "docker build" on my fork so that I can maintain changes in my fork that are relevant to me.  Thus, I'm seeing the JENKINS_VERSION=2.0 value in my build processes, when I really want it to be LTS.

When I make extensions (like storing my preferred pluigns in the ref/plugins directory), I still want to keep myself up to date with the latest changes on the upstream master branch.

Maybe my use model is not the expected use model?  I didn't want to have all my plugins pinned, and I didn't want every "docker build" to download my entire list of plugins, so I made changes on my downstream branches to improve those behaviors.

**Comment by carlossg** [comment]
I'd say the typical use model is build your image `FROM jenkins` on top of the official one.
If you use master branch from git there's no guarantee that it match be the `latest` build and it may be even be broken in-between releases

**Comment by MarkEWaite** [comment]
I'll have to evaluate that with my use model.  I have changes in the Dockerfile that make my `docker build` process much faster.  I'm not willing to surrender the faster `docker build`, but I'll look to see what I can do to better fit in the envisioned use model.
