### ISSUE TITLE
Configure a DNS server for use by Docker

### ISSUE THREAD

**Issue by naccarati** [jenkinsci/docker#268]
Hello, I'm starting to use use docker jenkins but at my company we have some proxies.

How can I do it: 

https://docs.docker.com/engine/installation/linux/ubuntulinux/#configure-a-dns-server-for-use-by-docker

Inside a docker container. I tried to follow the same steps, but I couldn't find the same file inside the Docker Jenkins running container;

**Comment by carlossg** [comment]
that is configured in the host, not in the image

If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
