### ISSUE TITLE
Official Docker image jenkins:1.651.2-alpine provides Jenkins version 1.651.1

### ISSUE THREAD

**Issue by rreinurm** [jenkinsci/docker#270]
It looks that parameter JENKINS_VERSION was not updated  from 1.651.1 to 1.651.2 according to official alpine based Jenkins image Dockerfile:
https://github.com/jenkinsci/docker/blob/bf76339b2a65acb309bcdc472cfcc9306eeb45f3/Dockerfile

The debian based Jenkins image is updated.

**Comment by carlossg** [comment]
fixed in https://github.com/docker-library/official-images/pull/1750
