### ISSUE TITLE
Included version of git is to old

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/docker#273]
docker run --rm jenkinsci/jenkins git version
    git version 2.1.4

Several plugins list a newer version of git as a dependency.
[BitBucket Plugin](https://wiki.jenkins-ci.org/display/JENKINS/BitBucket+Plugin) -> 2.3.5
[GitHub Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Github+Plugin) -> 2.4.0

Maybe consider basing the Jenkins image of [alpine](https://hub.docker.com/_/alpine/)?

**Comment by rbjorklin** [comment]
Just noticed that there already is a tag with alpine which solves this. Might still be worth to consider the git version for the regular build though. Feel free to close this if nothing will be done to fix the git version in the regular build.

**Comment by ndeloof** [comment]
We don't install git, this one is inherited from parent image
