### ISSUE TITLE
Container doesn't start because permission volume error

### ISSUE THREAD

**Issue by junoteam** [jenkinsci/docker#275]
Looks like bash script **/usr/local/bin/jenkins.sh** run as user jenkins and directory **/var/jenkins_home/** was created under root and permissions wasn't changed. 

So container doesn't start: 
`docker run -d -p 49001:8080 --name jenkins -v /root/jenkins:/var/jenkins_home jenkins`

Error:
```
17:46:34 root dev ~ → docker logs 604b3f6ce95f
touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

Can we fix it?

**Comment by carlossg** [comment]
just change the permissions of `/root/jenkins` to whatever user you want (1000 by default)

**Comment by miketwenty1** [comment]
Would you please go into more detail about this?
I'm migrating servers where jenkins will be running.. i zipped up the jenkins_home dir and put it somewhere else and I'm getting the same error as above.

**Comment by carlossg** [comment]
If you are mounting a host directory into a container the file permissions in the host need to allow the container user access. The jenkins image runs as user 1000

**Comment by miketwenty1** [comment]
yeah.. I didn't understand that.. for anyone else that was confused literally just change the owner of the mounted directory to 1000
`sudo chown -R 1000 <mounted_dir>`

**Comment by arthurkhlghatyan** [comment]
@miketwenty1 Thank you, I was confused too :smile:

**Comment by seleniumBatch2017** [comment]
@miketwenty1 you cleared my confusion too

**Comment by Nanduyana** [comment]
how do we handle this in a windows machine ?

can anybody please suggest

**Comment by batmat** [comment]
Please use https://jenkins.io/mailing-lists/ for general questions.

We only distribute Linux images, so you'd need docker for windows or something like this.
