### ISSUE TITLE
Jenkins image could not be pushed to Bluemix using docker command

### ISSUE THREAD

**Issue by dimikhan** [jenkinsci/docker#276]
I worked with the official Jenkins image last week and I could push that to Bluemix. But this week onwards I facing error. The error is always happening while pushing the last image (with biggest size in the group - 349.2MB). Then I checked the document and upgraded my docker version to 1.11.1. But still facing error on that particular image.
However, the error behavior is changed after I upgraded my docker version. Before upgrading, the push progress bar for that image was moving and at the end it was crossing the size 349.2MB and reaching to 354.XXMB (forgot exact size) and then no fail message but one EOF statement was showing.
After upgrading, the push progress bar moves and again crosses 349.2MB and reached to 354.4MB and then start retrying to push the image again. This continues till I break it (Ctr-C).

Below is the command I ran and the output (push ongoing) - 

> $ docker push registry.ng.bluemix.net/sam123/jenkins:my_jenkins
> The push refers to a repository [registry.ng.bluemix.net/sam123/jenkins]
> 6eac6e30a077: Layer already exists
> 5f70bf18a086: Layer already exists
> 008cc0b1c0f1: Layer already exists
> c0b861fe6b50: Layer already exists
> d887a6bbd4b5: Layer already exists
> 72c095b58395: Layer already exists
> d4eb89664ea9: Layer already exists
> ec7adcf6c1db: Layer already exists
> 1abd30ec1bf3: Layer already exists
> 88148dd5f97a: Layer already exists
> aaab6c7855ac: Layer already exists
> 6ef60a97b376: Pushing [============================>                      ] 197.5 MB/349.2 MB
> dd3463e7917c: Layer already exists
> 9dab486f5005: Layer already exists
> f07790056444: Layer already exists
> 8befcf623ce4: Layer already exists
> 3d5a262d6929: Layer already exists
> 6eb35183d3b8: Layer already exists

I expect the image to be pushed into the Bluemix registry.
But in actual the last image is not pushed successfully and retries to push that image again.
Docker version is as per below -

> $ docker --version
> Docker version 1.11.1, build 5604cbe

**Comment by dimikhan** [comment]
Same issue happens when I try to build image using Dockerfile (downloaded from the same repository of course). How to debug deeper and get why it is behaving like that?

**Comment by carlossg** [comment]
Something to ask docker/bluemix?

**Comment by dimikhan** [comment]
Not sure exactly what happened but, yesterday could able to push the image successfully. Might it be an issue with Bluemix as well.

**Comment by dimikhan** [comment]
Please close the ticket. Thanks.
