### ISSUE TITLE
install-plugins.sh fails to resolve a dependency

### ISSUE THREAD

**Issue by tn-osimis** [jenkinsci/docker#280]
```
Step 7 : RUN install-plugins.sh workflow-aggregator
 ---> Running in 5c65cf60df08
download plugin : workflow-aggregator from https://updates.jenkins.io/latest/workflow-aggregator.hpi
 > depends on  workflow-scm-step:2.0,pipeline-stage-view:1.3,pipeline-build-step:2.0,workflow-durable-task-step:2.0,pipeline-stage-step:2.0,workflow-api:2.0,workflow-step-api:2.0,workflow-support:2.0,workflow-basic-steps:2.0,pipeline-input-step:2.0,workflow-job:2.0,workflow-cps-global-lib:2.0,workflow-cps:2.0,workflow-multibranch:2.0
```
(Snip successful downloads)
```
download plugin : workflow-api-plugin from https://updates.jenkins.io/latest/workflow-api-plugin.hpi
failed to download plugin workflow-api-plugin
The command '/bin/sh -c install-plugins.sh workflow-aggregator' returned a non-zero code: 255
```
The issue is that [the script appends `-plugins` to the plugin name](https://github.com/jenkinsci/docker/blob/cf78b915ed6bee7aa30a89783c5bd6f00e34a922/install-plugins.sh#L25) in the URI, when the actual resource does not contain that suffix:

https://updates.jenkins.io/latest/workflow-api-plugin.hpi (incorrect)
https://updates.jenkins.io/latest/workflow-api.hpi (correct)

Given the discussion in [JENKINS-30361](https://issues.jenkins-ci.org/browse/JENKINS-30361), is the use of `install-plugins.sh` even recommended? If one would have to qualify it somehow, how "supported" would one say it is? (This could be a documentation fix.)

**Comment by carlossg** [comment]
this should be fixed by bbd13d05
