### ISSUE TITLE
Security scan

### ISSUE THREAD

**Issue by xueshanf** [jenkinsci/docker#282]
I am trying out CoreOS Clair open source project to check image vulnerabilities. The latest Jenkins official image report shows 14 High CVE security vulnerabilities, 36 medium. Any plan to patch the image?

**Comment by carlossg** [comment]
Most of them come from the base `java` image last time I checked

**Comment by outime** [comment]
Not sure if I'm missing something but if I try to update system packages in `java:8-jdk` container (latest pushed 4 days ago) I get:

```bash
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

However if I try to do it in `jenkinsci/jenkins` (latest pushed 3 days ago):

``bash
The following packages have been kept back:
  openjdk-8-jdk openjdk-8-jre openjdk-8-jre-headless
The following packages will be upgraded:
  apt base-files ca-certificates dbus dbus-x11 dmsetup dpkg git-man gnupg gpgv libapt-pkg4.12 libc-bin libc6 libcairo2 libcurl3-gnutls libdbus-1-3 libdevmapper1.02.1 libexpat1 libfreetype6 libgcrypt20 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif4 libgl1-mesa-dri
  libgl1-mesa-glx libglapi-mesa libglib2.0-0 libgnutls-deb0-28 libgraphite2-3 libgssapi-krb5-2 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libhogweed2 libicu52 libidn11 libjasper1 libk5crypto3 libkrb5-3 libkrb5support0 libldap-2.4-2 libnettle4 libnspr4 libnss3
  libpam-modules libpam-modules-bin libpam-runtime libpam0g libpcre3 libpng12-0 libsasl2-2 libsasl2-modules-db libsndfile1 libssh2-1 libssl1.0.0 libsvn1 libsystemd0 libtasn1-6 libtdb1 libtiff5 libudev1 libxml2 login mercurial mercurial-common multiarch-support
  openssh-client openssl passwd perl perl-base perl-modules subversion systemd systemd-sysv tzdata udev unzip
```

Hence the vulnerabilities (at least some of them). These are fresh images and containers so nothing cached on my side. Does someone have an explanation?

**Comment by carlossg** [comment]
the jenkins image was built and published some weeks ago when the base java image was different

**Comment by outime** [comment]
@carlossg I've pulled the latest container from `jenkinsci/jenkins` (it was 2.8 in my previous comment, now is 2.9 pushed about 8 hours ago) and same situation:

```bash
The following packages have been kept back:
  openjdk-8-jdk openjdk-8-jre openjdk-8-jre-headless
The following packages will be upgraded:
  apt base-files dbus dbus-x11 dmsetup dpkg git-man gnupg gpgv libc-bin libcairo2 libcurl3-gnutls libdbus-1-3 libdevmapper1.02.1 libfreetype6 libgcrypt20 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif4 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglib2.0-0
  libgnutls-deb0-28 libgraphite2-3 libgssapi-krb5-2 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libhogweed2 libicu52 libidn11 libjasper1 libk5crypto3 libkrb5-3 libkrb5support0 libldap-2.4-2 libnettle4 libnspr4 libnss3 libpam-modules libpam-modules-bin libpam-runtime
  libpam0g libpcre3 libpng12-0 libsasl2-2 libsasl2-modules-db libsndfile1 libssh2-1 libssl1.0.0 libsvn1 libsystemd0 libtasn1-6 libtdb1 libtiff5 libudev1 libxml2 login mercurial mercurial-common multiarch-support openssh-client openssl passwd perl perl-base perl-modules
  subversion systemd systemd-sysv tzdata udev unzip
```

Can you check this?

**Comment by carlossg** [comment]
The weekly image is built differently, from jenkins vs the LTS that is built by Docker inc. 
I have changed it so it pulls always latest and builds without cache
A new build of the latest jenkins should happen soon

**Comment by outime** [comment]
Can confirm it has the latest packages, thank you!
