### ISSUE TITLE
2 jenkinsci repositories on Docker Hub with different tags

### ISSUE THREAD

**Issue by charleswhchan** [jenkinsci/docker#288]
When I was searching for Jenkins 2.8 Docker image, I came across the following repos:
* https://hub.docker.com/r/library/jenkins/tags/
* https://hub.docker.com/r/jenkinsci/jenkins/tags/

Not sure if they are both owned by jenkinsci, former only has 1.x release, while the latter has mostly 2.x releases. Would be nice to consolidate into one and/or keep the tags consistent across both. :smiley:

**Comment by carlossg** [comment]
It is described in https://hub.docker.com/r/library/jenkins

> This is a fully functional Jenkins server, based on the Long Term Support release http://jenkins.io/.
> For weekly releases check out jenkinsci/jenkins

**Comment by charleswhchan** [comment]
I missed that. Thanks @carlossg
