### ISSUE TITLE
Docker image weekly releases

### ISSUE THREAD

**Issue by felipeplets** [jenkinsci/docker#294]
Hello all, 

I have a Jenkins test instance based on https://hub.docker.com/r/jenkinsci/jenkins/ image and latest tag.
Since the release of version 2.10 my Jenkins 2.9 is showing me the message to update it.

I have a few questions regarding that and couldn't realize the answer looking at the repo:
- When does the weekly.sh run?
- Wouldn't it be better to point out the **latest** tag to the **master** branch, so people would be able to test the latest features?
- Isn't possible to automate the run of the builds after a new tag push in the Jenkins repo? 

Thanks in advance, 
Felipe

**Comment by carlossg** [comment]
You would be better asking questions in the mailing list
You are probably asking about #293 that fixes the 2.10 build

**Comment by felipeplets** [comment]
Thanks for the answer @carlossg, this is what I was looking for. 

Which mailing list are you referring to? 
As per the [CONTRIBUTING.md](https://github.com/jenkinsci/docker/blob/master/CONTRIBUTING.md) this is the right place for Jenkins Docker image related issues.
