### ISSUE TITLE
hub.docker.com not updating

### ISSUE THREAD

**Issue by slushpupie** [jenkinsci/docker#305]
It seems like hub.docker.com has not updated with the latest version from here (2.7.1). Is automation not enabled? Are the webhooks broken?

**Comment by slushpupie** [comment]
Specifically, https://hub.docker.com/_/jenkins/ is still at 1.651.3

**Comment by g0t4** [comment]
+1

**Comment by carlossg** [comment]
it is manually built by docker inc and takes some time, see https://github.com/docker-library/official-images/pull/1937
