### ISSUE TITLE
Using docker inside jenkins docker container

### ISSUE THREAD

**Issue by barthr** [jenkinsci/docker#313]
At our company we are trying to dockerize everything. Also our new Jenkins ci server. The problem we are currently facing is that we try to execute docker commands from within this jenkins docker container. Although currently we cannot get it to work the right way.

Our build command:

```
docker run \
	-i \
	-u root \
	--name jenkins \
	-v /run/docker.sock:/run/docker.sock \
	-v /home/crowdsense/jenkins_home:/var/jenkins_home \
        -v $(which docker):/usr/bin/docker \
	-p 8080:8080 jenkins
```

But this keeps producing this error when trying to use docker commands inside the jenkins container:

`docker: error while loading shared libraries: libsystemd-journal.so.0: cannot open shared object file: No such file or directory
`

Even when we link the specified library's we keep getting the same error messages, what could be the cause of this problem?
 
Details:

Docker:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

OS:

`Ubuntu 14.04`

**Comment by einarf** [comment]
Someone with a working setup : https://youtu.be/cvmiM0_3NhA?t=44m53s

Personally I just install the docker client binary on the jenkins server and authenticate using TLS using the dns name or hostname. It's better that way in my opinion so you don't have to rethink everything when things start growing. Jenkins in my case just builds and runs containers doing all the building and testing on itself. I have a separate docker host for that specifically.

**Comment by carlossg** [comment]
In newer versions of Docker that use non static binaries you need to install the docker client in the image
