### ISSUE TITLE
ssl error building docker image

### ISSUE THREAD

**Issue by lmeyemezu** [jenkinsci/docker#316]
Hi, 
I try to build docker image but i get error below 
curl: (35) Unknown SSL protocol error in connection to updates.jenkins.io:443
The command '/bin/sh -c /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt' returned a non-zero code: 35
Any idea ?
Regards

**Comment by carlossg** [comment]
are you behind a proxy or maybe there is some temporary error

**Comment by lmeyemezu** [comment]
I'm not behind a proxy

**Comment by lmeyemezu** [comment]
I'm able to execute curl -kv https://updates.jenkins.io from vm
* Rebuilt URL to: https://updates.jenkins.io/
*   Trying 52.202.51.185...
* Connected to updates.jenkins.io (52.202.51.185) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: updates.jenkins.io (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=updates.jenkins.io
*        start date: Sun, 17 Jul 2016 16:15:00 GMT
*        expire date: Sat, 15 Oct 2016 16:15:00 GMT
*        issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: updates.jenkins.io
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 29 Jul 2016 17:23:42 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html;charset=UTF-8

but from container, i get 
curl -kv https://updates.jenkins.io
* Rebuilt URL to: https://updates.jenkins.io/
* Hostname was NOT found in DNS cache
*   Trying 52.202.51.185...
* Connected to updates.jenkins.io (52.202.51.185) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):

I'm using docker 1.12

**Comment by lmeyemezu** [comment]
This was docker 1.12 issue from vpn.
Regards
