### ISSUE TITLE
How to configure programmatically git credentials for Jenkinsfile multibranch?

### ISSUE THREAD

**Issue by F2X** [jenkinsci/docker#317]
Hi,

I would like to know if there is some easy way to configure "global" git credentials (user:password) from the docker image to be used with the Jenkinsfile multibranch feature.
With Jenkins 1.6x I used an ugly `.netrc` file with credentials on the container, and it always works with Jenkins 2.x for legacy jobs, but when I'm creating the following Jenkinsfile in my project, I have a `hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: https://xxx.git: not authorized`

Do you have any idea to fix that properly?

Jenkinsfile:

```
#!groovy

node {
    catchError {

        stage 'Checkout'

        checkout scm
        sh 'git submodule update --init;'

        stage 'Build and deploy'

        sh 'make HOME=/tmp/backend deploy-registry'
    }
    step([$class: 'Mailer', notifyEveryUnstableBuild: true, sendToIndividuals: true, recipients: 'me@home.com'])
 }
```

PS: For now I've created the credentials by hand

**Comment by carlossg** [comment]
That's probably because the git calls are now using the git java library, not the `git` command

You could create the credentials an the save the config file and the file containing the encryption password to the image, but it is a bad idea to save credentials in the image
