### ISSUE TITLE
Install-plugins does not resolve dependencies

### ISSUE THREAD

**Issue by tpeyrard** [jenkinsci/docker#318]
I'm not sure that's the "dependency resolution" expected from install-plugins.sh, but it seems it doesn't work.
Command line:
`RUN /usr/local/bin/install-plugins.sh ssh-agent ...`

Output:
> ssh-agent has no dependencies
> parameterized-trigger has no dependencies
> delivery-pipeline-plugin has no dependencies
> stashNotifier has no dependencies

Log at startup:

> Aug 01, 2016 2:47:47 PM hudson.PluginManager$2$1$1 run
> SEVERE: Failed to install ssh-agent: One or more dependencies could not be resolved for ssh-agent : bouncycastle-api (1.0.2)
> Aug 01, 2016 2:47:47 PM hudson.PluginManager$2$1$1 run
> SEVERE: Failed to install parameterized-trigger: One or more dependencies could not be resolved for parameterized-trigger : conditional-buildstep (1.3.1)
> Aug 01, 2016 2:47:47 PM hudson.PluginManager$2$1$1 run
> SEVERE: Failed to install delivery-pipeline-plugin: One or more dependencies could not be resolved for delivery-pipeline-plugin : parameterized-trigger (2.21)
> Aug 01, 2016 2:47:47 PM hudson.PluginManager$2$1$1 run
> SEVERE: Failed to install stashNotifier: One or more dependencies could not be resolved for stashNotifier : ssh-agent (1.3)

Is it expected?

**Comment by carlossg** [comment]
was fixed in 82272776de and will be out in the next LTS

**Comment by tpeyrard** [comment]
thanks. Sorry for duplicate; I searched only in open issues. My bad :/
