### ISSUE TITLE
Plugins bundled in jenkins.war not loaded

### ISSUE THREAD

**Issue by netrounds-fredrik** [jenkinsci/docker#319]
Using the following Dockerfile to install plugins the jenkins image with a patched install-plugins.sh to fix https://github.com/jenkinsci/docker/pull/309
```
FROM jenkins
...
RUN install-plugins.sh git
```

results in the following error when starting jenkins
```
SEVERE: Failed to install matrix-project: One or more dependencies could not be resolved for matrix-project : script-security (1.13), junit (1.2)
SEVERE: Failed to install git: One or more dependencies could not be resolved for git : matrix-project (1.6)
```

Looking at the output from install-plugins.sh you can see that script-security:1.13 and junit:1.2-beta-4 is bundled in jenkins.war, so the plugins should be available to jenkins.
```
 > matrix-project depends on script-security:1.13,junit:1.2
...
Skipping already bundled dependency script-security:1.13 (1.13 <= 1.13)
Skipping already bundled dependency junit:1.2 (1.2 <= 1.2-beta-4)
```

The `1.2 <= 1.2-beta-4` problem is probably fixed in https://github.com/jenkinsci/docker/pull/307, but the script-security version number is an exact match, so it should be possible to use the bundled version.

**Comment by carlossg** [comment]
script-securit, matrix-project, junit are in the `WEB-INF/detached-plugins/` dir and seems those are not loaded on startup

**Comment by carlossg** [comment]
from http://jenkins-ci.361315.n4.nabble.com/Revisiting-bundled-plugins-td4763593i80.html 

> All the plugins that were bundled in the jenkins.war are still bundled (in WEB-INF/detached-plugins), but are only conditionally loaded on upgrade (not loaded at all on a new install - the wizard handles that).

so install-plugins needs to not count on them as installed

**Comment by netrounds-fredrik** [comment]
Thanks for the update. That was what I ended up doing to be able to move forward, basically just commenting out `bundledPlugins="$(bundledPlugins)"`.
