### ISSUE TITLE
Varying shutdown messages

### ISSUE THREAD

**Issue by wied03** [jenkinsci/docker#321]
I've not been able to pin this down, but is there a reason that sometimes I'll see the winstone shutdown message and sometimes I see nothing?

In either case, `docker stop` does not seem to be timing out at 10 seconds and issuing a SIGKILL.

Maybe it's not a big deal but I'd like to make sure jenkins is shutting down cleanly.

**Comment by wied03** [comment]
I added the `-v` flag to tini and I get this:

```
[INFO  tini (1)] Spawned child process '/usr/local/bin/jenkins.sh' with pid '6'
[INFO  tini (1)] Main child exited normally (with status '143')
```
I get the same output from tini but the winstone/jenkins message I mentioned when I created this issue sometimes does not show up. This is the message I was referring to:

```
Aug 04, 2016 11:53:59 PM winstone.Logger logInternal
INFO: JVM is terminating. Shutting down Winstone
```

**Comment by ndeloof** [comment]
I wonder this is just a buffer flush issue.
