### ISSUE TITLE
Why there is an error when downloading  the tini

### ISSUE THREAD

**Issue by peachyy** [jenkinsci/docker#325]
System：
`root@iZ11kxsvoe6Z:~# uname -a
Linux iZ11kxsvoe6Z 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

ErrorInfo:

`Step 16 : ENV TINI_SHA fa23d1e20732501c3bb8eeeca423c89ac80ed452
 ---> Using cache
 ---> 1e7afe9619b9
Step 17 : RUN curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static -o /bin/tini && chmod +x /bin/tini   && echo "$TINI_SHA  /bin/tini" | sha1sum -c -
 ---> Running in ea6b0a1b2de7
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
The command '/bin/sh -c curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static -o /bin/tini && chmod +x /bin/tini   && echo "$TINI_SHA  /bin/tini" | sha1sum -c -' returned a non-zero code: 56`

**Comment by carlossg** [comment]
are you behind a proxy, using a VPN or something like that?
See http://serverfault.com/questions/555335/root-cause-of-curl-56-ssl-read-errno-5961-errors
