### ISSUE TITLE
Question: Why does the docker image not start after some minor manual changes to it?

### ISSUE THREAD

**Issue by macolo** [jenkinsci/docker#326]
I did this:

Connect to the latest docker image:
`docker run -ti -u root jenkins:latest /bin/bash`
Then make your changes, exit, 
`apt-get update`
`apt-get install php5-cli`
find it
`docker ps -a`
and commit the image with your custom name
`docker commit 72362a6649d1 jenkins:1.7.2_php`

However 
`docker run --name=jenkins-1.7.2_php --rm -p 8080:8080 -p 50000:50000 -v /data/jenkins:/var/jenkins_home jenkins:1.7.2_php`

...results in no output, jenkins is not started anymore automatically.

The same works well when I use the Dockerfile example from https://hub.docker.com/_/jenkins/ with below Dockerfile and `docker build -t jenkins:1.7.2_php .`

``` 
FROM jenkins
# if we want to install via apt
USER root
RUN apt-get update && apt-get install -y php5-cli
USER jenkins
```

**Comment by carlossg** [comment]
when you commit images you lose the CMD/ENTRYPOINT, see http://stackoverflow.com/questions/29015023/docker-commit-created-images-and-entrypoint
