### ISSUE TITLE
Failed to verify image

### ISSUE THREAD

**Issue by eldermoraes** [jenkinsci/docker#330]
Hi all,

I tried to hard to solve this by myself without any success. So here I am...

I was once trying to run a Jenkins container with:

`docker run -p 8080:8080 -p 50000:50000 jenkins`

And them the process stopped before it ended. Then when I tried it again I got the message:

> docker: Error response from daemon: failed to verify image: sha256:b4974ba625983cc1250f3399a262d98398b914ff04d2ba360760b81d1c944983.

Any ideas of what is going on?

**Comment by carlossg** [comment]
error downloading, compatibility issues between your docker and the registry,... nothing caused by this image

see https://github.com/docker/docker/issues/23477 for instance
