### ISSUE TITLE
Image on docker hub are not up to date

### ISSUE THREAD

**Issue by netrounds-fredrik** [jenkinsci/docker#333]
https://hub.docker.com/_/jenkins/ says that the `latest` tag was pushed 2016-08-27, but when pulling the image from docker hub it still does not contain changes merged to the master branch two weeks earlier, for example https://github.com/jenkinsci/docker/pull/329 which was merged 2016-08-13.

```
$ docker pull jenkins
Using default tag: latest
latest: Pulling from library/jenkins
Digest: sha256:0a687937c38f8085a28baa44c397e6559c08cf3bfe9bb5d95fc7067ea903b517
Status: Image is up to date for jenkins:latest

$ docker run --rm jenkins grep "control character" /usr/local/bin/install-plugins.sh
        # ^M below is a control character, inserted by typing ctrl+v ctrl+m
```

From what are the images on docker hub built?

**Comment by carlossg** [comment]
It comes from what's in https://github.com/docker-library/official-images/blob/master/library/jenkins

You can use weekly builds in https://hub.docker.com/r/jenkinsci/jenkins/
