### ISSUE TITLE
Jenkins 2.7.4 not available

### ISSUE THREAD

**Issue by bradynpoulsen** [jenkinsci/docker#347]
# Expected Result

[Jenkins 2.7.4](https://jenkins.io/changelog-stable/) was released on September 8th.

I expected a `docker pull jenkins:alpine` to fetch a docker container with the latest version

# Actual Result

Instead of obtaining the latest version of Jenkins, I received the following message:

```
Status: Image is up to date for jenkins:alpine
```

Which was confirmed by [Docker Hub](https://hub.docker.com/_/jenkins/) that the latest version available for pulling is `2.7.3`

**Comment by bradynpoulsen** [comment]
This will be resolved by PR #346

**Comment by metyl** [comment]
Not so fast, we need one PR to [`docker-library/official-images`](https://github.com/docker-library/official-images) but I will handel this then #346 will be merged.

**Comment by carlossg** [comment]
https://github.com/docker-library/official-images/pull/2140
