### ISSUE TITLE
Make install-plugins.sh compatible with plugins.txt input file in plugins.sh

### ISSUE THREAD

**Issue by Trane9991** [jenkinsci/docker#348]
Hello,
make possible to pass `plugins.txt` file in the old format to the `install-plugins.sh` script:

plugins.txt:

```
...
jacoco:1.0.19
gitlab
...
```

and run with:
`./install-plugins.sh plugins.txt`

**Comment by duckpuppy** [comment]
As a workaround until the enhancement is in, I'll toss this one-liner here:
`RUN /usr/local/bin/install-plugins.sh $(cat /usr/share/jenkins/plugins.txt | tr '\n' ' ')`
