### ISSUE TITLE
Shell-injection vulnerability in jenkins.sh

### ISSUE THREAD

**Issue by charles-dyfis-net** [jenkinsci/docker#351]
The following, from [`jenkins.sh`](https://github.com/jenkinsci/docker/blob/6eaa9b15926232310317490a3b9975ef61be763c/jenkins.sh#L6), (1) relies on `find` behavior not specified by POSIX, and (2) much more seriously, allows arbitrary shell commands to be executed:

```
find /usr/share/jenkins/ref/ -type f -exec \
  bash -c ". /usr/local/bin/jenkins-support; copy_reference_file '{}'" \;
```

This code relies on `{}` within the argument to `bash -c` being replaced with an actual filename (which is not behavior specified by [the POSIX spec for `find`](http://pubs.opengroup.org/onlinepubs/009695399/utilities/find.html)). More importantly, this allows malicious filenames to execute arbitrary commands. Consider the file created by running the following code in bash (don't try the below in any shell which doesn't recognize `$''` quoting; ash and dash are both in this set):

```
# this creates a file which, if present under /usr/share/jenkins/ref/, will have an unfortunate
# string in its name executed as code.
touch $'$(rm -rf $HOME)\'$(rm -rf $HOME)\''
```

Instead, this should be written as follows:

```
# works with all POSIX-compliant implementations of find
# avoids the security vulnerability by passing arguments out-of-band from code
# doesn't spawn "bash" once per file, but performs the minimum necessary number of invocations
find /usr/share/jenkins/ref -type f -exec \
  bash -c '. /usr/local/bin/jenkins-support; for arg; do copy_reference_file "$arg"; done' _ {} +
```

---

With respect to the claim of dependency on behavior not given in the POSIX spec for `find`:

> If a utility_name or argument string contains the two characters "{}", but not just the two characters "{}", it is implementation-defined whether find replaces those two characters or uses the string without change.

This implementation-defined behavior is depended on by the present code.

**Comment by ndeloof** [comment]
By official image requirement, image just let you execute arbitrary command as entrypoint, like `docker run jenkins bash`, so such "_shell-injection_" is supported by design. Abusing `find` like you suggest is probably possible, but wouldn't be simpler way to achieve this.

**Comment by ndeloof** [comment]
feel free to propose a PR with suggested fix to find command.

**Comment by charles-dyfis-net** [comment]
It's appropriate to let the caller execute an arbitrary command. It's inappropriate to run code not present in that command -- hence the necessity of the suggested fix.

**Comment by charles-dyfis-net** [comment]
That there's a documented and intended way for users to run arbitrary commands doesn't mean that any and every undocumented and unintended mechanism should be left in place. PR upcoming.

**Comment by ndeloof** [comment]
thanks
