### ISSUE TITLE
Run Jenkins master and slave with Docker

### ISSUE THREAD

**Issue by ismarslomic** [jenkinsci/docker#356]
I want to setup Jenkins master on server **A** and slave on server **B** with use of Docker.

Both servers are virtual machines dedicated for Jenkins.

Currently I have started Docker container on server A for **master**, based on the [official Jenkins docker image](https://hub.docker.com/_/jenkins/). But what docker image should I use for Jenkins **slave**?

**Comment by carlossg** [comment]
Please send questions to the mailing lists. This is only for issues

**Comment by solaMai** [comment]
Hi author, I also need to setup Jenkins slave as you now. Have you something document share to me? Thanks.

**Comment by oleg-nenashev** [comment]
@solaMai 
> Please send questions to the mailing lists. This is only for issues

**Comment by batmat** [comment]
https://jenkins.io/mailing-lists/ in case.
