### ISSUE TITLE
install-plugins.sh fails due to timeout

### ISSUE THREAD

**Issue by timothyclifford** [jenkinsci/docker#362]
Hi,

I'm trying to use `install-plugins.sh` from China. I understand this may not be a common location but due to poor internet I see the connection timeout.

In the current script, I can see a timeout of 5 seconds.

Is it a valid idea to increase this or make it configurable at least? Or instead do people with poor connections need to manage their own version of this script?

Thanks!

**Comment by carlossg** [comment]
see #361
