### ISSUE TITLE
Enrich the install-plugins.sh to take the download timeout as an optional parameter

### ISSUE THREAD

**Issue by PierreBtz** [jenkinsci/docker#364]
Hello,

I encountered an issue with the download of the plugins using install-plugins.sh. Plugin download was systematically failing. Upon analysis, I found out that the timeout set in the curl command was not enough. Increasing it solved the issue. 

I currently versioned my own version of install-plugins to workaround the issue, but I don't see the situation of the network improving soon and I found out I was [not the only one ](http://stackoverflow.com/questions/39782949/when-building-jenkins-in-docker-plugins-fail-to-install) having this kind of issue.

Would you be willing to take a Pull Request allowing to override the timeout with an environment variable: eg `ENV JENKINS_UC_TIMEOUT 20` would increase the 5 seconds timeout to 20 seconds?

**Comment by carlossg** [comment]
already done in #361

**Comment by PierreBtz** [comment]
Great, sorry I overlooked this :)
