### ISSUE TITLE
Add sudo privileges to jenkins user

### ISSUE THREAD

**Issue by shubhamrajvanshi** [jenkinsci/docker#366]
I want to add a self signed certificate to java keystore but unable to do so as I do not have sudo privileges for jenkins user in my container. Jenkins user should have the ability to run commands in  sudo mode.

**Comment by rodesousa** [comment]
Hello,

In your dockerfile you can set user root and run any cmd

```
ADD resources/keys/ ....
USER root
CMD ...
User jenkins
```

**Comment by shubhamrajvanshi** [comment]
I can do that but my use case is to use Jenkins container image out of the box. Any particular reason it's not there by default

**Comment by carlossg** [comment]
this image includes only the required packages to run jenkins, sudo is not included

**Comment by shubhamrajvanshi** [comment]
Yeah but then there should be a way to use it with self signed certificates using env params or at least permission to add certificates.

**Comment by carlossg** [comment]
can't you do it with a jenkins plugin?

**Comment by canit00** [comment]
As a regular user of this image I don't want unnecessary packages introduced into our environment. If you need to sudo in a Linux container, am afraid you don't know what you're doing.

**Comment by canit00** [comment]
Here's a working example of how to add certificates to the Jenkins keystore via Dockerfile.

http://stackoverflow.com/questions/35304680/how-to-add-a-ssl-self-signed-cert-to-jenkins-for-ldaps-within-dockerfile

Again, if you feel the need to run sudo inside of a Linux container, you most likely have a bigger problem than what you're trying to solve.

**Comment by ndeloof** [comment]
definitively don't want to give extra unnecessary permissions to jenkins user

**Comment by shubhamrajvanshi** [comment]
Repeating my earlier comment:

"I can do that but my use case is to use Jenkins container image out of the box."

**Comment by ndeloof** [comment]
Adding this constraint is a non-sense. Managing changes on top of the official image with any tool vs writing a Dockerfile to extend it is the exact same effort, but the later offer more flexibility
