### ISSUE TITLE
Why is the copy reference needed?

### ISSUE THREAD

**Issue by alledm** [jenkinsci/docker#374]
I am trying to understand why everytime jenkins start it needs to copy the reference files.

```
: "${JENKINS_HOME:="/var/jenkins_home"}"
touch "${COPY_REFERENCE_FILE_LOG}" || { echo "Can not write to ${COPY_REFERENCE_FILE_LOG}. Wrong volume permissions?"; exit 1; }
echo "--- Copying files at $(date)" >> "$COPY_REFERENCE_FILE_LOG"
find /usr/share/jenkins/ref/ -type f -exec bash -c '. /usr/local/bin/jenkins-support; for arg; do copy_reference_file "$arg"; done' _ {} +

```

Why is it needed? It takes very long time to do so and it is error prone.
And if there is a reason for it, why not using rsync?

**Comment by carlossg** [comment]
Files are not being copied if they already exist, so it is only on the first start
rsync is not installed in the image
