### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by roppa** [jenkinsci/docker#377]
Using:

    docker run -p 8080:8080 -p 50000:50000 -v $(pwd)/home:/var/jenkins_home jenkins

I get this error:

    Running from: /usr/share/jenkins/jenkins.war
    webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
    Exception in thread "main" java.io.IOException: No space left on device
    	at java.io.FileOutputStream.writeBytes(Native Method)
    	at java.io.FileOutputStream.write(FileOutputStream.java:326)
    	at Main.copyStream(Main.java:333)
    	at Main.extractFromJar(Main.java:358)
    	at Main._main(Main.java:194)
    	at Main.main(Main.java:91)

My Docker version is:

    Client:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.7.1
     Git commit:   6f9534c
     Built:        Thu Sep  8 10:31:18 2016
     OS/Arch:      darwin/amd64
    
    Server:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   23cf638
     Built:        Thu Aug 18 17:52:38 2016
     OS/Arch:      linux/amd64

**Comment by carlossg** [comment]
can you run 

    docker run -p 8080:8080 -p 50000:50000 -v $(pwd)/home:/var/jenkins_home jenkins df -h

**Comment by roppa** [comment]
Sure. Also, I have 2 machines and it works fine on one. 

    Filesystem      Size  Used Avail Use% Mounted on
    none             19G   18G     0 100% /
    tmpfs           2.0G     0  2.0G   0% /dev
    tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
    osxfs           931G  423G  508G  46% /var/jenkins_home
    /dev/vda1        19G   18G     0 100% /etc/hosts
    shm              64M     0   64M   0% /dev/shm

**Comment by carlossg** [comment]
well, there you have it, for whatever reason you have 18GB in /
