### ISSUE TITLE
Is a Jenkins master in Docker really advantageous?

### ISSUE THREAD

**Issue by jmcgeheeiv** [jenkinsci/docker#378]
I have been working on bringing up the Jenkins Docker container as my new production master instance.  I am finding the following things difficult:
* Networking and managing the mounting of volumes.  I can of course mount volumes, but I need to mount so many in both host and container.  It is tractable yet inconvenient to manage.
* User authentication.  My Jenkins instance authenticates via NIS, so I am working on creating a Dockerfile to install and run NIS in the container.  This is not going so well.  I presume that LDAP authentication would be similarly arduous.

These factors make me think that running a Jenkins master in a container is too complicated compared to the advantages.

Containerized Jenkins agents still seem worthwhile because:
* All the prerequisites for the software under test are preinstalled in the container.  Now this leverages a key advantage of containers.
* The agent deals only with user jenkins

**Comment by rtyler** [comment]
I am not sure what the expected action on this "issue" is?

Plenty of people, myself included, find running a Jenkins master inside of a container to be beneficial.

**Comment by jmcgeheeiv** [comment]
Thank you for your response, @rtyler.  Actually, a response like you gave, "No, plenty of people find it beneficial," does help me.

Can you refer me to a reference on how to set up LDAP or NIS user authentication?  This is my main barrier.

**Comment by rtyler** [comment]
@jmcgeheeiv For [ci.jenkins.io](https://ci.jenkins.io) we run a Dockerized master instance which uses LDAP as the identity provider. The container routes out to a fully qualified hostname which serves up LDAP. 

We also mount the entirety of `$JENKINS_HOME` from the host machine.

**Comment by jmcgeheeiv** [comment]
Nice clues, @rtyler .  Thank you for your time.
