### ISSUE TITLE
User, UID, Group, and GID only changeable at build time

### ISSUE THREAD

**Issue by danielunderwood** [jenkinsci/docker#380]
The user, UID, group, and GID are specified as `ARG` so they can only be specified at build time. This is a bit inconvenient if you're pulling from Docker Hub. If this were declared as `ENV` , it could easily be overridden at runtime. Would there be any interest in making this change or is there a reason to use `ARG` over `ENV`? If so, I can submit a PR.

**Comment by carlossg** [comment]
you need ARG as the files are set at build time, not runtime
