### ISSUE TITLE
Initialize plugins after Initialize Jenkins remove plugins directories

### ISSUE THREAD

**Issue by grzegorz181** [jenkinsci/docker#381]
One of plugin i was installed: websphere-deployer, need two WAS8 library in dir: plugins/websphere-deployer/WEB-INF/lib

When i create this directory with libs in /usr/share/jenkins/ref and after that when container run that libs are deleted. What should I do?

I try in my own Dockerfile run jenkins -jar jenkins.war to create plugin directory structure, and after stoping it add this two library to created plugin directory, but also, after docker run plugins directory for this plugin are recreaded and my libs deleted.

There is any way to run jenkins/jenkins image without recreate plugins after start? There should be a possiblity to add libs to plugins without remove it.

**Comment by carlossg** [comment]
what dockerfile are you running? command? output ?

**Comment by grzegorz181** [comment]
My dockerfile: 

`FROM jenkins
MAINTAINER Grzegorz Trepa (rb11674)

COPY plugins/plugins.txt /usr/share/jenkins/ref/
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt

COPY plugins/com.ibm.ws.admin.client_8.5.0.jar /usr/share/jenkins/ref/plugins/websphere-deployer/WEB-INF/lib/com.ibm.ws.admin.client_8.5.0.jar
COPY plugins/com.ibm.ws.orb_8.5.0.jar /usr/share/jenkins/ref/plugins/websphere-deployer/WEB-INF/lib/com.ibm.ws.orb_8.5.0.jar`

build: call docker build -t my_jenkins:dev .
run: docker run --name jenkins-server -p 8080:8080 -p 50000:50000 -v /mnt/shared/jenkins/home:/var/jenkins_home my_jenkins:dev

After run com.ibm * libs should be in plugins/websphere-deployer/WEB-INF/lib/ but in firsth phaste when refs are copied, libs are in, but after jenkins initialized libs are removed, so plugin not work correctly.

**Comment by carlossg** [comment]
That's jenkins deleting the plugin dir before installing/uncompressing the plugin hpi
Have you tried with jenkins outside of docker?

**Comment by grzegorz181** [comment]
Yes. In my jenkins after initialize plugin directories are removed, but after that, i can copy libs to directory and after start / stop there are not removed. In docker jenkins there is not possible initialize phase during build, and run docker image already initialized (without delete plugin directories on run phase).

**Comment by carlossg** [comment]
you could have a groovy script that copies the files and restarts jenkins, as done here
https://github.com/jenkinsci/docker/blob/master/Dockerfile#L35

but that's more of a jenkins question
