### ISSUE TITLE
 The docker failed to create the jenkins

### ISSUE THREAD

**Issue by xxlaila** [jenkinsci/docker#385]
System is centos 7.2, when creating a docker jenkins mirror tips
[root@localhost ~]# docker run --name myjenkins -p 8080:8080 -v /var/jenkins_home jenkins
docker: Error response from daemon: No command specified.
See 'docker run --help'.
logs
ERRO[0880] Handler for POST /v1.24/containers/create returned error: No command specified

**Comment by carlossg** [comment]
are you building the image yourself? try `docker pull jenkins` to download the correct one

**Comment by xxlaila** [comment]
I found the wrong, the beginning is my company's Unicom line can not pull, and then go home pull, in the package to the company to find the wrong size of the mirror into the company's image than the previous big 10 M, Friend re-pull a to me
thank you for your help
