### ISSUE TITLE
Logging to STDOUT should be the default

### ISSUE THREAD

**Issue by rmoriz** [jenkinsci/docker#391]
The steps mentioned in https://github.com/jenkinsci/docker#configuring-logging should be applied by default as this is the best practice of docker images.

**Comment by carlossg** [comment]
wdym? logging already goes to stdout by default. Logging level is customizable as explained there

**Comment by rmoriz** [comment]
by default, the container does not log anything useful after startup. Having to set an ENV and create a sub-image just to add a log config is very ugly. A good example of having a flexible logging approach are the httpd and nginx images IMHO.

**Comment by carlossg** [comment]
Any specific improvement you suggest? jenkins default logging goes to stdout, the logging is accessible and customizable from the web ui, and the file is only needed for other specific customization cases
