### ISSUE TITLE
Error: more than one instance sharing /var/home

### ISSUE THREAD

**Issue by swkarr** [jenkinsci/docker#399]
### Environment and steps taken
Running Docker for Windows on Windows 10
Jenkins container pulled from an internal mirror of this site.
Startup description
1. Start a new jenkins container instance mapping JENKINS_HOME to a host folder
2. Sleep for 30 seconds to give time to create the JENKINS_HOME folder/files.
3. Copy the UpdateCenter plugin and configuration derived by a file difference comparison. over JENKINS_HOME.  This maps to an offline plugin repository.
4. Restart Jenkins to enable the new functionality.
5. Logged into the Jenkins dashboard creating an admin account.
6. No other activity for the day.

### Docker commands that you execute (Windows Power Shell)
```
docker run --name jenkinsCI -d -p 9095:8080 -p 50030:50030 --env JENKINS_SLAVE_AGENT_PORT=50030  -v /d/docker/jenkinsCI:/var/jenkins_home ArtifactoryDocker/jenkins:2.19.4
Start-Sleep -Seconds 30
Copy-Item -Path D:/docker/UpdateCenter/* -Destination D:/docker/jenkinsCI -Force -Recurse
docker restart jenkinsCI
```

### Actual result
Works as expected, however, with no other changes I am seeing the multiple instance error by the next day.

**Error**
```
Jenkins detected that you appear to be running more than one instance of Jenkins that share the same home directory '/var/jenkins_home’. This greatly confuses Jenkins and you will likely experience strange behaviors, so please correct the situation.
This Jenkins:	1777109262 contextPath="" at 7@7bc7f2506196
Other Jenkins:	1777109262 contextPath="" at 7@7bc7f2506196
```

### Expected outcome
Do not expect this error, especially since the information for This and Other Jenkins is the same.

### Have you tried a non-dockerized Jenkins and get the expected outcome?
Not on this machine, but have directly instantiated multiple instances on a single Linux system user's account using unique "JENKINS_HOME" folders for each instance.

### Output of `docker version`
PS D:\docker> docker --version
Docker version 1.12.2-rc1, build 45bed2c, experimental

### Other relevant information
I have seen it with a single Jenkins container running although currently I have three Jenkins containers on this system.  However, each is mapped to a different host folder based on the instance name.  Using a Power Shell script to enforce this.

First seen using 2.19.1-alpine as is.
Current occurrence is built on 2.19.4 using a Docker file to add Maven and Gradle.
```

FROM ArtifactoryDocker/jenkins:2.19.4
MAINTAINER Shawn Karr <swkarr@hotmail.com>
ADD apache-maven-3.2.2-bin.tar.gz /etc
COPY settings.xml /etc/apache-maven-3.2.2/conf
ENV MAVEN_HOME=/etc/apache-maven-3.2.2
RUN export MAVEN_HOME
ADD gradle-3.1.tar.gz /etc
ENV GRADLE_HOME=/etc/gradle-3.1
RUN export GRADLE_HOME
ENV PATH=${PATH}:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin
RUN export PATH
ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
```

**Comment by ianwhite** [comment]
I'm also experiencing this issue, Docker version 17.06.0-ce, build 02c1d87.

**Comment by nateridderman** [comment]
I also encountered this, with Docker 17.12.0-ce-win47 and the current LTS docker image.

**Comment by batmat** [comment]
> `FROM ArtifactoryDocker/jenkins:2.19.4`

@ianwhite @nateridderman it looks like the wrong place to report. This repository is the source for `jenkins/jenkins`, `jenkinsci:jenkins` and `jenkins` AFAIK. `ArtifactoryDocker/jenkins:2.19.4` is not coming from here.

cc @carlossg @rtyler do you agree? If so I guess this can be closed.

**Comment by batmat** [comment]
Care to clarify what you are trying to achieve? If you are running two Jenkins instances on the same `JENKINS_HOME`, then this is not supported, and not an issue specific to the Jenkins official Docker image. Going to close this, if I misunderstood your intent, please feel free to reopen.

If that is that case, and you wish it to be supported to have many instances sharing the same `JENKINS_HOME`, please file (or watch) an issue at https://issues.jenkins-ci.org/secure/Dashboard.jspa on the `JENKINS` project.

Also, if so, you will likely be interested to read https://jenkins.io/blog/2018/08/31/shifting-gears/ which discusses the current plans for improving Jenkins in many areas like these.

Thanks and cheers!

**Comment by swkarr** [comment]
To clarify:
- ArtifacroryDocker is a corporate proxy of jenkinsci:jenkins
- While the system has a few jenkins images running, they have each been assigned their own unique JENKINS_HOME using docker -v.

**Comment by batmat** [comment]
@swkarr reopening to at least better understand. I think something is simply fishy with your setup.

FYI this double instance checking is simply done through a hidden file located under `$JENKINS_HOME/.owner`. So, if you see this warning this can mean two things:
* either you are actually running two Jenkins instance, and they will detect each other and issue this warning
* or you've copied a pre-existing `$JENKINS_HOME` from a running instance and you're using it for a new one (though as I understand the code at https://github.com/jenkinsci/jenkins/blob/5df63bc63ba352ac24da59729407f3439aa6a26d/core/src/main/java/hudson/util/DoubleLaunchChecker.java#L70 that should still mean many instances are updating this file regularly).

Also, what is that ` D:/docker/UpdateCenter/*` directory? What is this supposed to contain?

**Comment by swkarr** [comment]
Tested 5 instances of 3 versions including the base jenkins:jenkins:lts-alpine.  The only configuration for lts-alpine version 2.121.3 was the inclusion and configuration of the update-sites-manager plugin.

All instances: opened the dashboard in Firefox.  Without closing the dashboard tabs, left Firefox running.  Then the next day, performed an F5 refresh for each Jenkins dashboard tab.  Result was the indicated error.

Error
Jenkins detected that you appear to be running more than one instance of Jenkins that share the same home directory '/var/jenkins_home'.  This greatly confuses Jenkins and you will likely experience stange behaviors, so please correct the situation.
**This Jenkins: 560070034 contextPath="" at 7@53e4f6966b7e
Other Jenkins: 560070034 contextPath="" at 7@53e4f6966b7e**
[Ignore this problem and keep using Jenkins anyway]

Each error page has a unique ID and "at" address but it appears that each instance is colliding with itself.

Further F5 refreshes does not clear the error page.

Clicking [Ignore] button returns to login page.
Able to successfully log into the instance.

**Comment by Coral-Liu** [comment]
I also met same issue as swkarr. Any solution to fix it?

**Comment by dellgreen** [comment]
I'm seeing this issue just running jenkins normally, once in a while it throws this error when the first person in the morning navigates to the jenkisn website after it has been idle all night. There are defintely not 2 instances running on my server
<img width="1088" alt="Screenshot_2019-07-30_at_07 59 30" src="https://user-images.githubusercontent.com/12861109/62113391-70513500-b2ac-11e9-8396-83257f4180fd.png">

maybe lastmodifiedDate of .owner file should be relooked at or at a minimum a system property to disable this check in some way as this error blocks other automated systems talking to jenkins when it happens.

**Comment by ianfixes** [comment]
I'm noticing this problem in some Jenkins tabs that have been open for a few hours:
 
```
This Jenkins: | 1864319447 contextPath="" at 11@33d99e0b230e
-- | --
Other Jenkins: | 548107553 contextPath="" at 7@6d791b76b116
```

Strangely, the bottom of the page where this error occurs says `Jenkins ver. 2.150.2`.  But when I refresh, I get the version from the docker image that I'm running: `Jenkins ver. 2.190.2`. 

Am I commenting on the correct GitHub issue for this?

If so, how would I track down the rogue `2.150.2` process?  And why does it start periodically but vanish immediately afterward?

**Comment by mjeco** [comment]
I'm also noticing this issue. Running Jenkins v2.222.1 in Kubernetes. Only one instance of Jenkins is ever running at the same time. What would cause the [DoubleLaucherChecker ](https://github.com/jenkinsci/jenkins/blob/5df63bc63ba352ac24da59729407f3439aa6a26d/core/src/main/java/hudson/util/DoubleLaunchChecker.java#L97)to collide with itself? To me, this suggests that something outside of Jenkins modified the `.owner` file?
JENKINS_HOME is on an Azure Fileshare (CIFS) and mounted into the Pod as a Volume.

System property to disable this check would be useful.

![jenkins-master-error](https://user-images.githubusercontent.com/12852800/78972825-f6499f00-7b0e-11ea-8e0a-4f4a9eaf1ef5.PNG)

**Comment by dellgreen** [comment]
As it just happened to you, are you able to confirm the timestamps are different in the log files with respects to the the logging statement in: https://github.com/jenkinsci/jenkins/blob/5df63bc63ba352ac24da59729407f3439aa6a26d/core/src/main/java/hudson/util/DoubleLaunchChecker.java#L110

**Comment by mjeco** [comment]
@dellgreen 
```
Apr 10, 2020 1:23:46 AM hudson.util.DoubleLaunchChecker execute
SEVERE: Collision detected. timestamp=1586477926000, expected=1586477925000
```

**Comment by ianfixes** [comment]
As a follow-up to my [previous comment](https://github.com/jenkinsci/docker/issues/399#issuecomment-597985870), I can't say whether this happens all the time but on 2 different occasions I've received this error right around the stroke of midnight when I happened to have Jenkins open in a browser.

**Comment by mjeco** [comment]
Happens to my instance every day between 7PM  and 8PM UTC time.

```bash
Apr 11, 2020 7:47:57 PM hudson.util.DoubleLaunchChecker execute
SEVERE: Collision detected. timestamp=1586629317000, expected=1586629316000

Apr 12, 2020 7:15:58 PM hudson.util.DoubleLaunchChecker execute
SEVERE: Collision detected. timestamp=1586714338000, expected=1586714337000

Apr 13, 2020 7:07:59 PM hudson.util.DoubleLaunchChecker execute
SEVERE: Collision detected. timestamp=1586799539000, expected=1586799538000
``` 

I can assure that the only process running in the pod is Jenkins.

```bash
PID   USER     TIME  COMMAND
    1 jenkins   0:10 /sbin/tini -- /usr/local/bin/jenkins.sh
    7 jenkins  10:49 java -Duser.home=/var/jenkins_home -Xmx4096m -Djava.util.l
 8017 jenkins   0:00 ps aux
```

**Comment by mjeco** [comment]
Also if you notice, the difference in the timestamps is **always** 16 minutes and 40 seconds.
It seems very strange that is is this consistent every day. It looks like an issue with Jenkins to me.

**Comment by mjeco** [comment]
Ok, I think I have figured out what was happening in my case. If you look at the collision logs, the two timestamps always differ by around 1 second. My JENKINS_HOME is set up on a CIFS mount in Azure Fileshare. When Jenkins updates the `.owner` file it immediately records its last-modified timestamp. But I believe there is a small (1 second) delay until the CIFS mount records the actual file modification time. So the timestamp Jenkins has stored and the actual timestamp of the file is not the same, hence the error message.

To get around this issue you can symlink the `.owner` file to `/dev/null`. The symlink has its own last-modified timestamp which does not update when Jenkins writes to the file. This basically makes Jenkins check the same timestamp over and over again. Preventing the error from manifesting.

```bash
rm -f $JENKINS_HOME/.owner
ln -s /dev/null $JENKINS_HOME/.owner
```

**Comment by ianfixes** [comment]
Does this imply that Jenkins could resolve this by reading from the file immediately after writing it in order to determine the proper last-modified time?  Or does that defeat the purpose?

**Comment by mjeco** [comment]
I think there should be some delay between writing to the file and reading the timestamp to cater for delays associated with NFS/CIFS mounts. If you don't care about this check just set the symlink as I mentioned above. Fixed the issue for me.

**Comment by jquejad-bdb** [comment]
> Ok, I think I have figured out what was happening in my case. If you look at the collision logs, the two timestamps always differ by around 1 second. My JENKINS_HOME is set up on a CIFS mount in Azure Fileshare. When Jenkins updates the `.owner` file it immediately records its last-modified timestamp. But I believe there is a small (1 second) delay until the CIFS mount records the actual file modification time. So the timestamp Jenkins has stored and the actual timestamp of the file is not the same, hence the error message.
> 
> To get around this issue you can symlink the `.owner` file to `/dev/null` (or any other file not in JENKINS_HOME). The symlink has its own last-modified timestamp which does not update when Jenkins writes to the file. This basically makes Jenkins check the same timestamp over and over again. Preventing the error from manifesting.
> 
> ```shell
> rm -f $JENKINS_HOME/.owner
> ln -s /dev/null $JENKINS_HOME/.owner
> ```

This works for me. We have the Jenkins implementation in AKS with K8s version v1.17.7. The message no longer appears. Thanks

**Comment by Type1J** [comment]
I'd really like this to be fixed. I'm on an AWS FSx (SMB) drive, and the other timestamp issues have been with CIFS (NFS/EFS), so it seems to affect more than 1 network share based JENKINS_HOME. Although there has been a solution proposed, it hasn't yet had a PR. I'm not setup for Jenkins development, or I would submit a PR. Is anyone capable of attempting a PR for this issue? Please and Thank you!

**Comment by timja** [comment]
Please raise this on https://issues.jenkins.io/, see https://www.jenkins.io/participate/report-issue/

Component: core

I can't see this being related to docker in any way other than manifesting itself here
