### ISSUE TITLE
How to deploy updated docker container without stopping old container

### ISSUE THREAD

**Issue by rajasekaran07** [jenkinsci/docker#406]
Hi Team,

We are following Jenkins CICD pipeline flow for our AWS ECS container based applications. My CICD will start whether we updated any configuration in old container, Task definition, Service or any docker service. That will build new docker images based on the changes and uploaded in AWS ECR than it will deploy in our ECS cluster. 

While we deploying we stopped old containers and start with new one, Since we cant use same docker name and same port for updated container.

Kindly someone can suggest how to deploy updated container without downtime.

Regards,
Raja

**Comment by carlossg** [comment]
Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.
