### ISSUE TITLE
uid/gid of 1000/1000 may conflict with the host user id namespace

### ISSUE THREAD

**Issue by blaffoy** [jenkinsci/docker#412]
If the host already has a user with uid of 1000, then this container will give ownership of the mounted volume to that user, which represents a security risk.

Further, this will prevent the host user running the container from mounting their private keys in ~/.ssh in the container. This is an easier and more secure than copying the private keys into the container itself.

I can't propose a good solution to this problem, but I'm working around it with the following in my Dockerfile, which must be run with `--build-arg uid=$(id -u) --build-arg gid=$(id -g)`:

```
FROM jenkins:2.19.4

ARG user=jenkins
ARG group=jenkins
ARG olduid=1000
ARG oldgid=1000
ARG old_jenkins_home=/var/jenkins_home
ARG uid
ARG gid
ARG new_jenkins_home=/var/lib/jenkins

ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log

USER root

# Modify the container's jenkins user id to match the host user
RUN /bin/sh -c "usermod -u $uid $user && \
    usermod -d $new_jenkins_home $user && \
    groupmod -g $gid $group && \
    usermod -g $gid $group && \
    find / -path /proc -prune -o -group $oldgid -print | xargs chgrp -hv $group && \
    find / -path /proc -prune -o -user $olduid -print | xargs chown -hv $user && \
    cp -R $old_jenkins_home $new_jenkins_home"

# Create a persistent volume from the new user home
RUN chown -R $user:$group $new_jenkins_home
VOLUME $new_jenkins_home
USER $user
```

**Comment by carlossg** [comment]
see #112
