### ISSUE TITLE
Download url in install-plugins.sh part of the docker image is not valid.

### ISSUE THREAD

**Issue by niau** [jenkinsci/docker#413]
The script is trying to download from:

http://mirrors.jenkins.io/download/plugins/....  or http://updates.jenkins.io/download/plugins/....

Which might been the case but now what seems to work is the same url but without "downloads"

http://mirrors.jenkins.io/plugins/....

**Comment by carlossg** [comment]
it downloads from http://updates.jenkins.io/download/plugins/ and that looks fine to me

**Comment by carlossg** [comment]
https://github.com/jenkinsci/docker/blob/master/Dockerfile#L52
