### ISSUE TITLE
Disabling security when using basic_auth in nginx

### ISSUE THREAD

**Issue by majkelcc** [jenkinsci/docker#420]
When using this image behind a basic auth in nginx, how can I disable security in jenkins?

From what I've found I should set `useSecurity` to `false` in `config.xml`, but it's being overwritten on jenkins start.

**Comment by carlossg** [comment]
you go to the UI and disable security or create your own docker image with a config.xml in /usr/share/jenkins/ref as described in https://github.com/jenkinsci/docker#installing-more-tools

**Comment by majkelcc** [comment]
Thank you!
