### ISSUE TITLE
Permission error for COPY_REFERENCE_FILE_LOG

### ISSUE THREAD

**Issue by rmkpatchaa** [jenkinsci/docker#421]
I am having an issue with COPY_REFERENCE_FILE_LOG. Even if my JENKINS_HOME is /var/jenkins_home, the error shows **/var/log/copy_reference_file.log** 

This is my logs in **/var/log/jenkins/jenkins.log**

```
touch: cannot touch ‘/var/log/copy_reference_file.log’: Permission denied
Can not write to /var/log/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch ‘/var/log/copy_reference_file.log’: Permission denied
Can not write to /var/log/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch ‘/var/log/copy_reference_file.log’: Permission denied
Can not write to /var/log/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch ‘/var/log/copy_reference_file.log’: Permission denied
Can not write to /var/log/copy_reference_file.log. Wrong volume permissions?
```

**Comment by carlossg** [comment]
please provide:


### Docker commands that you execute

### Actual result

### Expected outcome

### Have you tried a non-dockerized Jenkins and get the expected outcome?

### Output of `docker version`

### Other relevant information
