### ISSUE TITLE
"An error occurred during installation: No such plugin: cloudbees-folder"

### ISSUE THREAD

**Issue by wheelerlaw** [jenkinsci/docker#424]
I ran: 
```
docker run -d --name=jenkins -p 8080:8080 -p 50000:50000 -v ~/jenkins:/var/jenkins_home jenkins
```
 I got as far as the plugin config screen. Clicked on "Install selected plugins", got this error:
```
An error occurred during installation: No such plugin: cloudbees-folder
```

Only worked when I manually configured and deselected them all.

Docker version:
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by wheelerlaw** [comment]
Update: I removed the `-v ~/jenkins:/var/jenkins_home` and didn't run into any problems. Seems to be a problem with mounting the `jenkins_home` as a volume.

**Comment by carlossg** [comment]
well, it depends on what you have in `~/jenkins` that is breaking the installation

**Comment by wheelerlaw** [comment]
@carlossg There's nothing in it, it's a new folder created for the purpose of starting the container. It should not be erroring.

**Comment by xpxrzerr** [comment]
I ran into the same problem after installing Jenkins in Windows (not in Docker), and in my case it still happened if I deselected cloudbees. Shutting down Jenkins and restarting it fixed the issue and plugins installed fine.

**Comment by rvernica** [comment]
I ran into this error as well with `jenkins:2.32.3-alpine` and without mounting any volume on Linux.

**Comment by rvernica** [comment]
In my case the issue was the http proxy was not set.

I could see the following warning:
```
ci_1     | Mar 21, 2017 11:54:14 AM hudson.model.UpdateCenter updateDefaultSite
ci_1     | WARNING: Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.
ci_1     | net.sf.json.JSONException: Unquotted string 'h1'
ci_1     | 	at net.sf.json.util.JSONTokener.nextValue(JSONTokener.java:432)
ci_1     | 	at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:955)
ci_1     | 	at net.sf.json.JSONObject._fromString(JSONObject.java:1145)
ci_1     | 	at net.sf.json.JSONObject.fromObject(JSONObject.java:162)
ci_1     | 	at net.sf.json.JSONObject.fromObject(JSONObject.java:132)
ci_1     | 	at hudson.model.UpdateSite.updateData(UpdateSite.java:206)
ci_1     | 	at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:190)
ci_1     | 	at hudson.model.UpdateCenter.updateDefaultSite(UpdateCenter.java:2193)
ci_1     | 	at jenkins.install.SetupWizard.init(SetupWizard.java:168)
ci_1     | 	at jenkins.install.InstallState$3.initializeState(InstallState.java:105)
ci_1     | 	at jenkins.model.Jenkins.setInstallState(Jenkins.java:1057)
ci_1     | 	at jenkins.install.InstallUtil.proceedToNextStateFrom(InstallUtil.java:96)
ci_1     | 	at jenkins.model.Jenkins.<init>(Jenkins.java:947)
ci_1     | 	at hudson.model.Hudson.<init>(Hudson.java:85)
ci_1     | 	at hudson.model.Hudson.<init>(Hudson.java:81)
ci_1     | 	at hudson.WebAppMain$3.run(WebAppMain.java:231)
```

The solution was to set the proxy in `JAVA_OPTS`:
```
JAVA_OPTS=-Dhttp.proxyHost=${proxy_host} -Dhttp.proxyPort=${proxy_port} -Dhttps.proxyHost=${proxy_host} -Dhttps.proxyPort=${proxy_port}
```

**Comment by SrLTF** [comment]
I had the same error.
The origin of the problem was the JVM (java -version was java 7).
Once switched to Java 8 (.bash_profile), everything was resolved.

**Comment by carlossg** [comment]
@wheelerlaw if you are saying that this command fails

    docker run -d --name=jenkins -p 8080:8080 -p 50000:50000 -v ~/jenkins:/var/jenkins_home jenkins

and this command succeeds

    docker run -d --name=jenkins -p 8080:8080 -p 50000:50000 jenkins

then it boils down to what permissions or content your ~/jenkins dir has. Have you checked the logs of jenkins for errors ?

**Comment by rroxysam** [comment]
This work for me: 
http://localhost:8080/restart 
OR
service jenkins restart **on Ubuntu 16.04**

**Comment by avishekroy63** [comment]
@techyaura : thanks, restart works for me.

**Comment by chrisuj** [comment]
http://localhost:8080/restart worked on blueocean running in docker container running on Mac ...

**Comment by qhh0205** [comment]
Restart jenkins worked!

**Comment by bolee** [comment]
http://localhost:8080/restart Mac not working!

**Comment by sancex** [comment]
Changing this line 
JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
to 
JAVA_CMD="$JENKINS_JAVA_CMD **-Dhudson.model.DownloadService.noSignatureCheck=true** $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"

**in /etc/init.d/jenkins** 
should fix the problem... 
worked on fedora 28

**Comment by scinfu** [comment]
Same problem with Mac

**Comment by Lingeswaran-R** [comment]
Please check the NTP. If the system runs with incorrect time, this error could occur.

**Comment by Jnchk** [comment]
I met the config error after I ran the command `docker run -u root --restart always -d -p 8090:8080 --name jenkins -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock jenkinsci/blueocean` serveral times when I was fixing docker network problem. I think there's must be something wrong with the directries in the volume. 

So I delete volume jenkins-data through docker. And the error disappeared.

**Comment by t851029** [comment]
> Changing this line
> JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> to
> JAVA_CMD="$JENKINS_JAVA_CMD **-Dhudson.model.DownloadService.noSignatureCheck=true** $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> 
> **in /etc/init.d/jenkins**
> should fix the problem...
> worked on fedora 28

This did the trick for me, ty!

**Comment by justahole** [comment]
> Update: I removed the `-v ~/jenkins:/var/jenkins_home` and didn't run into any problems. Seems to be a problem with mounting the `jenkins_home` as a volume.
> 
> I verified that `~/jenkins` exists in my home directory, and it does.

it works for me

**Comment by ariesduanmu** [comment]
I set the `JAVA_HOME` in `~/.bash_profile` like `export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home` works

**Comment by ankur83d** [comment]
I faced the same issue while installing plugins in my docker container, it turned out to be a proxy issue. Changed proxy settings on my docker and it worked

**Comment by sambapython** [comment]
restart worked for me.

**Comment by r00t4dm** [comment]
restart is not work in mac.

**Comment by ramkrishna2105** [comment]
Restart is not working on window 10

**Comment by oneslideicywater** [comment]
> was the http proxy was not set.

modify `/var/lib/docker/volumes/jenkins-data/_data/hudson.model.UpdateCenter.xml` from https->http fix the problem

**Comment by ykf87** [comment]
> Changing this line
> JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> to
> JAVA_CMD="$JENKINS_JAVA_CMD **-Dhudson.model.DownloadService.noSignatureCheck=true** $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> 
> **in /etc/init.d/jenkins**
> should fix the problem...
> worked on fedora 28

It work for me!
System Environment: centos 8
jenkins installation method:
    wget http://pkg.jenkins-ci.org/redhat-stable/jenkins-2.7.3-1.1.noarch.rpm
    rpm -ivh jenkins-2.7.3-1.1.noarch.rpm

**Comment by CryStal-W6** [comment]
> Changing this line
> JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> to
> JAVA_CMD="$JENKINS_JAVA_CMD **-Dhudson.model.DownloadService.noSignatureCheck=true** $JENKINS_JAVA_OPTIONS -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"
> 
> **in /etc/init.d/jenkins**
> should fix the problem...
> worked on fedora 28

worked for me , centos8

**Comment by hthanhtoan** [comment]
Hi Bros,
I also have the same issue, please help me. thanks,
************* cat docker-compose.yml************
version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins:2.60.3
    ports:
      - "8080:8080"
      - "50000:50000"
-------------------------------------------------

command run: docker-compose up -d
OS: "Ubuntu 20.04.3 LTS (Focal Fossa)"
