### ISSUE TITLE
install-plugins.sh version pinning

### ISSUE THREAD

**Issue by brianantonelli** [jenkinsci/docker#434]
I have to disagree with #327 (commit 119703c55b4f45062be07d333f85455cfffdea9a)

The install-plugins script now always fetches the latest version of plugin dependencies instead of fetching the actual version that the dependency specified. We bake our plugins, pinned to specific versions, in our Dockerfile so we have consistent environments. This change now breaks our ability to pin plugin versions and is now causing our Jenkins deployments to fail. 

For example, we are running Blue Ocean and have it pinned at beta 20. Now when I build my image and run install-plugins it begins fetching Blue Ocean 20, but then when it fetches one of its dependencies (blue-ocean-i18n) it grabs the latest version instead of version 20. The problem is that the newest Blue Ocean depends on SCM 2.0 and forcefully upgrades us to it which breaks our environments since we have jobs that haven't been upgraded yet.

**Comment by carlossg** [comment]
when you talk about pinning you mean installing specific versions of the plugins? because plugin pinning is something that was removed in jenkins 2.x

That change makes it behave like the update center does. You can set specific versions by adding them all to the Dockerfile 

From README 

> Here is an example to get the list of plugins from an existing server:

    curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/'

**Comment by ydubreuil** [comment]
You can take a look at https://github.com/jenkinsci/blueocean-plugin/pull/403 where I proposed a download script based on Maven. It would require that you express the list of plugins you need inside a POM file. With Maven, you should be able to easily catch a dependency problem if you select an incompatible set of plugins and you will have a reproducible build.

**Comment by brianantonelli** [comment]
@carlossg I understand that we can specify the version of the plugin that I want by setting the version in the Dockerfile. The problem is that any dependencies of that plugin will automatically fetch the latest which then creates a cyclical dependency and ends up pulling the latest version of the plugin I tried to pin in my Dockerfile.

For example with BlueOcean. If I say I want blue ocean beta20 the plugin install script will grab all of that plugins dependencies and instead of pulling the dependency version specified by the plugin it just grabs the latest. So when it grabs a blue ocean dep, say blue-ocean-i18n, instead of getting blue-ocean-i18n it grabs blue-ocean-i18n:latest. This then ends up requiring blue-ocean:latest and now I no longer blue-ocean:beta20. I have a workaround in place where I force deps to grab the version I specified instead of latest. This works, but is kind of kludgey.

**Comment by carlossg** [comment]
> The problem is that any dependencies of that plugin will automatically fetch the latest which then creates a cyclical dependency and ends up pulling the latest version of the plugin

Should not happen if you set explicit versions. If it does it is a bug. Then please post an example with the command, dockerfile and output

**Comment by oleg-nenashev** [comment]
Can be closed, response timeout
