### ISSUE TITLE
Update Git version (current 2.1.4, dated 17/12/14)

### ISSUE THREAD

**Issue by fabriziocucci** [jenkinsci/docker#437]
In one of my Jenkins job, due to some unfortunate bash script logic, I had to list all branches on a particular commit using the command:

```shell
git branch --points-at <object>
```

The command failed with:

```
error: unknown option `points-at'
```

So I checked the git version available in the docker container and I got:

```
git version 2.1.4
```

Unfortunately (for me), that git version is too old (17/12/14) and does not support the option I was looking for. 

But, in general, wouldn't be better to have a more recent Git version by default?

**Comment by carlossg** [comment]
git comes from the parent openjdk image, not installed in the jenkins image

**Comment by fabriziocucci** [comment]
Thanks for your prompt reply @carlossg !

But if that is true (and I'm sure it is), what's the purpose of [this](https://github.com/jenkinsci/docker/blob/master/Dockerfile#L3)?

Anyway, this is what I did to install the latest git version:
```shell
docker exec -it --user root <jenkins-container-name> /bin/bash
apt-get install software-properties-common # this is required for 'add-apt-repository'
add-apt-repository ppa:git-core/ppa
sed -i -e 's/jessie/xenial/g' /etc/apt/sources.list.d/git-core-ppa-jessie.list # this is required to make 'apt-get update' succeed
apt-get update
apt-get install git
```

Someone may find this helpful!

**Comment by carlossg** [comment]
sorry, my bad, git and curl are exceptions. 
We are installing the latest available, I'm reluctant to add new repos

**Comment by fabriziocucci** [comment]
Cool, now everything makes sense!

It's a shame that the latest version in the official repo is that old...
