### ISSUE TITLE
Failed to load native library 'libnative-platform.so' for Linux amd64.

### ISSUE THREAD

**Issue by rosolko** [jenkinsci/docker#438]
### Docker commands that you execute
`docker run --name jenkins -d -p 8080:8080 -p 50000:50000 -v /Users/ar/Documents/docker/jenkins:/var/jenkins_home jenkinsci/jenkins:2.46-alpine`

### Actual result
Start build that use gradle and get error:
`Failed to load native library 'libnative-platform.so' for Linux amd64.`

### Expected outcome
Build finish w/o error

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No. As I google - it's alpine image problem

### Output of `docker version`
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### Other relevant information
I try to build my own image with additional **libstdc++** package and seems like it's work well.
Change this _Dockerfile_ line from:
`RUN apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils`
to:
`RUN apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils libstdc++`

**Comment by carlossg** [comment]
This is a base image so we can't add tools to support any possible build, you can use jenkins-slave images for your builds, or create your own image derived from this one https://github.com/jenkinsci/docker#installing-more-tools
