### ISSUE TITLE
Enhancement: Execute script pre-boot of Jenkins.

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/docker#446]
I would like to run a pre-jenkins startup script before Jenkins.  Right now, I build my own docker image based on upstream Jenkins docker images.  I'm opening this issue in case others express interest in such a feature.

The beginning of `jenkins.sh` could have a change as simple as:

```bash
[ -x '/usr/share/jenkins/preboot.sh' ] && /usr/share/jenkins/preboot.sh
```

Use case for such a script includes:
- preparing `$JENKINS_HOME` for a different environment (e.g. using production configurations in a staging environment).
- Any scripted task a user wishes to do before Jenkins starts up.

Then when a user bakes their own customized docker image based on the upstream Jenkins docker image they need only populate `/usr/share/jenkins/preboot.sh` for Jenkins startup.

Please tell me your thoughts.

**Comment by samrocketman** [comment]
Currently I'm using the `patch` command to patch `jenkins.sh` and insert my script at the very top of the file before anything else.

**Comment by rtyler** [comment]
This seems like a reasonable enhancement to me :+1:

**Comment by samrocketman** [comment]
Okay I'll prepare a PR for review.

**Comment by isuftin** [comment]
@samrocketman Have you ever gotten the PR up for review?

**Comment by samrocketman** [comment]
Not yet, I still remember what I want it to do.  I'm traveling from Greece at the moment (on a plane now).  I'll open a PR this week.  Thanks for the reminder.

**Comment by samrocketman** [comment]
@isuftin @rtyler finally submitted my PR.  Sorry it took so long; got distracted by other things.

**Comment by timja** [comment]
Closing given https://github.com/jenkinsci/docker/pull/544#issuecomment-384118526
