### ISSUE TITLE
2.50 not available on docker hub

### ISSUE THREAD

**Issue by smazurov** [jenkinsci/docker#449]
### Docker commands that you execute

`docker pull jenkinsci/jenkins:2.50`

### Actual result

```
$ docker pull jenkinsci/jenkins:2.50
Pulling repository docker.io/jenkinsci/jenkins
Tag 2.50 not found in repository docker.io/jenkinsci/jenkins
```

### Expected outcome

For docker hub to have the latest jenkins version available in a timely fashion. At the time of this post its been 5 days since 2.50 version was released. In addition, this isn't the first time these releases are lagging behind. I would love if whoever is in charge of ensuring a docker image is tagged and built setup some sort of notification system. CC @carlossg @rtyler, sorry to bother you guys but it seems like you were the ones to fix it last time.

**Comment by frekele** [comment]
I agree, it would be great if the weekly docker version was released faster, it takes almost 5 days to be available in the docker hub.

I think the problem is related to another closed issue. https://github.com/jenkinsci/docker/issues/442

**Comment by saiimons** [comment]
The 'latest' tag was uploaded at the same time 2.50 was released, seems there is an issue with tagging it...

**Comment by smazurov** [comment]
now 2.51 is not available (but alpine versions are)

**Comment by rtyler** [comment]
Please do not comment on closed issues with unrelated comments.
