### ISSUE TITLE
--httpPort=8081 "Command not found"

### ISSUE THREAD

**Issue by jordiAtING** [jenkinsci/docker#452]
### Docker commands that you execute
docker run -d -v /root/jenkins/jenkins_home:/var/jenkins_home -p 8081:8081 --name jenkins jenkins:test --httpPort=8081

### Actual result
The jenkins container is created but can't be started. Error message:
**`docker: Error response from daemon: Container command not found or does not exist..`**
Extra error info:
**`exec: "--httpPort=8081": executable file not found in $PATH`**

It looks like the container is trying to execute **--httpPort=8081** as a regular command instead of passing it to the startup of jenkins as a parameter, as mentioned in /usr/local/bin/jenkins.sh: **`#if 'docker run' first argument start with `--` the user is passing jenkins launcher arguments`**

### Expected outcome
A running jenkins container listening on port 8081

### Output of `docker version`
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.x86_64
 Go version:      go1.6.2
 Git commit:      429be27-unsupported
 Built:           Fri Nov 18 17:03:44 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.x86_64
 Go version:      go1.6.2
 Git commit:      429be27-unsupported
 Built:           Fri Nov 18 17:03:44 2016
 OS/Arch:         linux/amd64

### Other relevant information
We have successfully launched jenkins with the "--httpPort=8081" command before, but everything seems to be broken after we did an export, deleted the old image and imported the export as the new baseline.

Any help would be much appreciated! Thanks in advance.

**Comment by hoshsadiq** [comment]
Can't you just do?:
```
docker run -d -v /root/jenkins/jenkins_home:/var/jenkins_home -p 8081:8080 --name jenkins jenkins:test
```

The last argument you provide gets picked up by docker to replace the `CMD` command (which is set to run Jenkins if you don't specify it). Above command will keep Jenkins running on 8080 inside the container, but maps the port to 8081 on localhost (i.e. `http://localhost:8080/` will map to `http://container-ip:8081/`)

**Comment by carlossg** [comment]
to run in a different port use @hoshsadiq advice

Your jenkins:test image is doing something wrong, ie. overriding entrypoint

```
 docker run jenkins --httpPort=8081
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
...
```
