### ISSUE TITLE
(jenkins user - uid 1000) ?  I don't understand，someone can make an example for that? thanks!

### ISSUE THREAD

**Issue by LLitchi** [jenkinsci/docker#453]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

**Comment by carlossg** [comment]
please ask questions in the Jenkins mailing lists.
