### ISSUE TITLE
Why is the official docker image so far behind the current release? 

### ISSUE THREAD

**Issue by jsindy** [jenkinsci/docker#455]
2.32.3 seems to be the latest docker image, al though 2.52 is the current release. I am curious why there is a lag behind the releases. Thanks

**Comment by rmoriz** [comment]
the official "jenkins" image tracks the LTS versions. It's just one release behind atm: https://jenkins.io/changelog-stable/

As noted in the Readme at https://github.com/jenkinsci/docker#readme:

> For weekly releases check out [jenkinsci/jenkins](https://hub.docker.com/r/jenkinsci/jenkins/)

**Comment by jsindy** [comment]
Ah ha!, PR in for 2.46.1
