### ISSUE TITLE
Last line of plugins.txt ignored if a new line is not present on that last line

### ISSUE THREAD

**Issue by matthewwerny** [jenkinsci/docker#46]
When attempting to define a set of plugins to be included via the plugins.txt file, the last line of plugins.txt   file is ignored if a new line is not present on that last line.  While this the default POSIX behavior, it is easy to overlook and a workaround is easily included in the plugins.sh (pull request forthcoming shortly after some testing a fork is complete) to allow it to transparently consider all lines in the plugins.txt file.

**Comment by carlossg** [comment]
See PR #92
