### ISSUE TITLE
Automatically update to LTS on a timely manner

### ISSUE THREAD

**Issue by fboudra** [jenkinsci/docker#461]
See:
* https://github.com/jenkinsci/docker/pull/460
* https://github.com/jenkinsci/docker/pull/458
* https://github.com/jenkinsci/docker/pull/454

The docker image always lags behind a new LTS release. Any chance to get some automation done to update to latest LTS as soon as it is released?
The whole process can be done in continuous integration. It seems to me as simple a creating a new job on https://ci.jenkins.io/ (but I could be wrong).

**Comment by carlossg** [comment]
Automated builds are in jenkinsci/jenkins:lts already
Docker-Official jenkins image needs manual steps

**Comment by fboudra** [comment]
For reference, what are these manual steps that can't be automated?

My own image does FROM jenkins:2.46.1 and I still can't update it after 3 days since Jenkins 2.46.1 has been released.

**Comment by rtyler** [comment]
The "official" Docker Jenkins images require pull requests [like this one](https://github.com/docker-library/official-images/pull/2713).

Frankly, there's no benefit to using the Docker "official" images. Instead I suggest you rely on `jenkinsci/jenkins:2.46.1` which is the official (from the Jenkins project) image for that LTS release.

**Comment by fboudra** [comment]
@rtyler thanks, the difference between docker-official and jenkinsci isn't obvious. Switching to jenkinsci/jenkins:lts seems indeed the right thing to do ... once you're informed about it.
