### ISSUE TITLE
Notary signature missed for 2.46.1-alpine

### ISSUE THREAD

**Issue by roman-vynar** [jenkinsci/docker#466]
Docker Notary signature is missed for `2.46.1-alpine` image, however it is present for the rest images including `2.46.1`.
```
[root@centos7 ~]# notary lookup docker.io/library/jenkins 2.46.1-alpine

* fatal: No trust data for 2.46.1-alpine
[root@centos7 ~]# notary lookup docker.io/library/jenkins 2.46.1
2.46.1 sha256:c0cac51cbd3af8947e105ec15aa4bcdbf0bd267984d8e7be5663b5551bbc5f4b 4290
[root@centos7 ~]#
```

**Comment by rhuddleston** [comment]
So basically all of these tags are signed:

jenkins:2.32.3-alpine
jenkins:alpine
jenkins:latest
jenkins:2.46.1

Just not jenkins:2.46.1-alpine

**Comment by carlossg** [comment]
no longer applies as we are not pushing to `jenkins` anymore
