### ISSUE TITLE
Install plugin behind proxy

### ISSUE THREAD

**Issue by tcoupin** [jenkinsci/docker#471]
### Docker commands that you execute

My dockerfile :
```
FROM jenkinsci/jenkins:2.54-alpine 

## Plugins Installation part
# Doc here: https://github.com/jenkinsci/docker#preinstalling-plugins
COPY plugins.txt /tmp/plugins.txt
RUN echo ${http_proxy}
RUN curl -v -L google.fr
RUN /usr/local/bin/install-plugins.sh $(cat /tmp/plugins.txt)
```

Docker command: `docker build --build-arg http_proxy=${http_proxy}  .`

The ${http_proxy} is set in my env.

### Actual result

```
...
Failed to download plugin: workflow-support or workflow-support-plugin
Failed to download plugin: workflow-step-api or workflow-step-api-plugin

WAR bundled plugins:

Installed plugins:
*:
Some plugins failed to download! Not downloaded: blueocean-autofavorite
Not downloaded: ace-editor
Not downloaded: blueocean-config
Not downloaded: authentication-tokens
Not downloaded: blueocean-display-url
Not downloaded: antisamy-markup-formatter
Not downloaded: blueocean-commons
Not downloaded: blueocean-dashboard
...
```

### Expected outcome

Installation of plugins

### Have you tried a non-dockerized Jenkins and get the expected outcome?

No

### Output of `docker version`

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### Other relevant information

`echo ${http_proxy}` print my proxy
`curl -v -L google.fr` print Google home page

**Comment by koooge** [comment]
`--build-arg` is *Set build-time variables* .
Container does not have their environmental variables. 
 (see. see. https://docs.docker.com/engine/reference/commandline/build/#description)

You must use `docker run -e` or write `ENV` in Dockerfile
cf. https://docs.docker.com/engine/reference/commandline/run/#options
cf. https://docs.docker.com/engine/reference/builder/#env

**Comment by tcoupin** [comment]
But I can curl google.fr so the http_proxy is properly set.
I've tried to add "ENV HTTP_PROXY=${http_proxy}" but it's not better...

**Comment by tcoupin** [comment]
https_proxy must be set too.

I just add in the dockerfile:

```
ENV http_proxy=${http_proxy}
ENV https_proxy=${http_proxy}
```

**Comment by kirhie** [comment]
I am also facing the same issue.
I have created a dockerfile for jenkins version 2.73.1 as below:

FROM jenkins/jenkins:2.73.1

ENV http_proxy http://<proxy-ip>:<proxy-port>/
ENV https_proxy https://<proxy-ip>:<proxy-port>/
ENV JAVA_OPTS -Dhudson.footerURL=https://<footer-url>/ -Djenkins.install.runSetupWizard=false

USER root
RUN echo "Europe/Stockholm" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
USER jenkins

RUN /usr/local/bin/install-plugins.sh git

WORKDIR $JENKINS_HOME

When I try to build and image from this dockerfile, I always get an error "Failed to download plugin: git or git-plugin".

Where as when I just change the version to "2.46.3" the image is created successfully.

I doubt the proxy ENV variables are not getting set in image for version 2.73.1.

Can some one please help with this?

Thanks

**Comment by albertvipe** [comment]
I was facing the same problem. 
Using `--build-args http_proxy=$http_proxy --build-args https_proxy=$https_proxy` instead of  `--build-args HTTP_PROXY=$http_proxy --build-args HTTPS_PROXY=$https_proxy` solved my problem.

I didn't expect that it could be just a caps problem.
