### ISSUE TITLE
container hangs / java zombie process

### ISSUE THREAD

**Issue by rmoriz** [jenkinsci/docker#472]
Hi,

we've recurring issues using the docker image for a couple of LTS (currently 2.46.1) and Docker (17.03.0-ce) versions now : 

After some heavy, reliable use for 1-2 weeks, the container suddenly hangs. It's not manageable anymore through `docker kill` or `docker restart` (commands just hang). All we see on the host using `ps` is a java zombie process. (still plenty of RAM, no OOM kill)

I suspect that Jenkins/the JVM dies for whatever reason (well,  happens…) but tiny is not able to kill the Java process and the container hangs in a "pre-restart" nirvana.

**Comment by rmoriz** [comment]
Maybe using https://github.com/krallin/tini#process-group-killing can fix the issue?

**Comment by carlossg** [comment]
what options do you use to run the container? memory or cpu limits?

**Comment by carlossg** [comment]
no answer, closing
