### ISSUE TITLE
License

### ISSUE THREAD

**Issue by roidelapluie** [jenkinsci/docker#475]
There is no License in this repo. I would like to know which license it is published because I plan to redistribute install-plugins.sh.

**Comment by oleg-nenashev** [comment]
@roidelapluie I would assume it's MIT License since this license is being used in the Jenkins organization by default. Do you agree @ndeloof and @carlossg ?

**Comment by ndeloof** [comment]
I'm fine with MIT licensing

**Comment by carlossg** [comment]
MIT is ok

**Comment by oleg-nenashev** [comment]
Then we have an agreement. I will send a PR

**Comment by carlossg** [comment]
@oleg-nenashev already did #540, but we need @michaelneale as the original contributor
