### ISSUE TITLE
My Jenkins on a Windows 10 host can’t find the Host as Slave

### ISSUE THREAD

**Issue by derChristoph** [jenkinsci/docker#478]
The Windows 10 that runs docker shoud be an agent for Jenkins, I created a “localhost” Node, when I Start I get the Error:

### Actual result

C:\Users\Schindler\Downloads>java -jar slave.jar -jnlpUrl http://localhost:32769/computer/localhost/slave-agent.jnlp
Failing to obtain http://localhost:32769/computer/localhost/slave-agent.jnlp
java.io.IOException: Failed to load http://localhost:32769/computer/localhost/slave-agent.jnlp: 503 Service Unavailable
        at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:400)
        at hudson.remoting.Launcher.run(Launcher.java:248)
        at hudson.remoting.Launcher.main(Launcher.java:218)
Waiting 10 seconds before retry

But I can reach http://localhost:32769/tcpSlaveAgentListener/ from Crome an Download the slave-agent.jnlp
When I start then this:
C:\Users\Schindler\Downloads>java -jar slave.jar -jnlpUrl file:///C:/Users/Schindler/Downloads/slave-agent.jnlp

I get this Error: 
### Actual result
Apr 25, 2017 3:01:12 PM hudson.remoting.jnlp.Main createEngine
INFORMATION: Setting up slave: localhost
Apr 25, 2017 3:01:12 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFORMATION: Jenkins agent is running in headless mode.
Apr 25, 2017 3:01:13 PM hudson.remoting.jnlp.Main$CuiListener status
INFORMATION: Locating server among [http://localhost:32769/]
Apr 25, 2017 3:01:13 PM hudson.remoting.jnlp.Main$CuiListener error
SCHWERWIEGEND: http://localhost:32769/tcpSlaveAgentListener/ is invalid: 503 Service Unavailable
java.io.IOException: http://localhost:32769/tcpSlaveAgentListener/ is invalid: 503 Service Unavailable
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:165)
        at hudson.remoting.Engine.innerRun(Engine.java:335)
        at hudson.remoting.Engine.run(Engine.java:287)

### Expected outcome
The agent should work with jenkins

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No

### Output of `docker version`
OS Version/build: Windows 10
App version: Version 17.03.1-ce-win5 (10743) Channel: stable b18e2a5

**Comment by carlossg** [comment]
> C:\Users\Schindler\Downloads>java -jar slave.jar -jnlpUrl http://localhost:32769/computer/localhost/slave-agent.jnlp
> But I can reach http://localhost:32775/tcpSlaveAgentListener/ from Crome an Download the slave-agent.jnlp

different ports ? 32769 != 32775

**Comment by derChristoph** [comment]
Not realy, this was a typo...

**Comment by carlossg** [comment]
you need to configure the url and ports of jenkins correctly. The container can't access the master, localhost is not the same from the host than form the container. You are probably trying from the host, not from the container

**Comment by derChristoph** [comment]
> You are probably trying from the host, not from the container

Yes, and I chose localhost because of that.

My problem is why can crom accsess is, but Java not? see: [http://imgur.com/download/YTTzcCR](url)

**Comment by derChristoph** [comment]
anybody?
