### ISSUE TITLE
Check Downloaded Files

### ISSUE THREAD

**Issue by amouat** [jenkinsci/docker#48]
Could we add some checking of downloaded files to the Dockerfile?

At the moment the Dockerfile does:

    RUN curl -L http://mirrors.jenkins-ci.org/war/1.596/jenkins.war -o /usr/share/jenkins/jenkins.war

There is no guarantee that this file has come from jenkins, hasn't been tampered with or corrupted in transit. It would be great if we could add a checksum or use a signature file if available. To see how to download files securely, have a look at the Wordpress and MongoDB Dockerfiles:

https://github.com/docker-library/wordpress/blob/990b1b00b8ca4903e11e53e908b1996fbaab3c1a/Dockerfile
https://github.com/docker-library/mongo/blob/fc66d9cbedac47806c7ae05b1b291c4ee32f6e6a/2.8/Dockerfile

**Comment by ndeloof** [comment]
we welcome pull requests :D
