### ISSUE TITLE
Run docker command in jenkins container

### ISSUE THREAD

**Issue by gilgameshs** [jenkinsci/docker#481]
### Docker commands that you execute
`docker run -v ${JENKINS_HOME}:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock    -p 8080:8080 -p 50000:50000 -u 1000 jenkins`
### Actual result
when i create a job and run docker command

> + docker ps
/tmp/hudson1895009214258852964.sh: 4: /tmp/hudson1895009214258852964.sh: docker: not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### Output of `docker version`

> [root@localhost usr]# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false 

how can i run docker command in jenkins container whitout docker in docker

Thanks!

**Comment by carlossg** [comment]
you need to install the docker client in the image

**Comment by LeoAref** [comment]
@carlossg Could you elaborate how to ** install the docker client in the image**?

**Comment by carlossg** [comment]
https://github.com/cloudbees/docker-java-with-docker-client/blob/master/Dockerfile

**Comment by LeoAref** [comment]
@carlossg Thanks 👍 
Could you check this https://forums.docker.com/t/docker-not-found-in-jenkins-pipeline/31683?

**Comment by 5sfayas** [comment]
I am having same issue. I build docker client it did not work out to me!

please provide solution
