### ISSUE TITLE
Security concerns seen on Docker Hub under tags

### ISSUE THREAD

**Issue by mdeguzis** [jenkinsci/docker#487]
Docker Hubs scans of even the latest image show many vulnerabilities. Why isn't this addressed? It has been on going for quite some time it seems. Once you log in, you will see the results.

https://hub.docker.com/r/library/jenkins/tags/latest/

**Comment by carlossg** [comment]
what vulnerabilities is this image adding? there are openjdk base image vulnerabilities and jenkins war vulnerabilities

**Comment by mdeguzis** [comment]
You'd have to login to docker hub and click on the image, there are  quite a few in tree-like drill down views. If you wish I can try to list them here, but it will take a little bit to copy/paste.

**Comment by carlossg** [comment]
I can see them, I'm saying that there's none introduced by this image. 
You can ask docker to handle the [openjdk official image](https://github.com/docker-library/openjdk) issues and ask in the [jenkins mailing lists](https://jenkins.io/mailing-lists/) about the jenkins war ones.

**Comment by mdeguzis** [comment]
Ok, so them it may be pulled in from the opendk image.
