### ISSUE TITLE
Proposal to install `sudo` in the installation phase

### ISSUE THREAD

**Issue by vkotovv** [jenkinsci/docker#488]
I've needed `sudo` for my job's build steps, so I had to ssh into my container and install it manually (not available by default in your image). I could create a derived image and fix it, but I wonder if someone else will need it. What do you guys think?

**Comment by carlossg** [comment]
see https://github.com/jenkinsci/docker/issues/366

**Comment by vkotovv** [comment]
Oh, I see. Thanks for the clarifications
