### ISSUE TITLE
Dockerfile latest tag not using latest Jenkins

### ISSUE THREAD

**Issue by damianoneill** [jenkinsci/docker#491]
### Docker commands that you execute

In my Dockerfile I have the following command. 

RUN /usr/local/bin/install-plugins.sh gitlab mailer gradle junit sonar workflow-aggregator nodejs monitoring thinBackup

When this executes the workflow-aggregator fails to install as the latest Pipeline plugin (Pipeline: Job v2.12) requires a version of Jenkins that is later than the latest on the docker image.

### Actual result

You must update Jenkins from v2.46.2 to v2.60 or later to run this plugin

### Expected outcome

The docker image tag latest will use the latest version of Jenkins

### Have you tried a non-dockerized Jenkins and get the expected outcome?

N/A 

### Output of `docker version`

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by carlossg** [comment]
`jenkins` image and `jenkinsci/jenkins:lts` are lts 2.46.2
`jenkinsci/jenkins:latest` is latest

**Comment by damianoneill** [comment]
Maybe I wasn't clear in my description of the problem.  

If I use the latest docker image and use the install-plugins.sh without specifying a plugin version it will download the latest plugin rather than the one that is appropriate for long term support release.

If you feel that jenkinsci/jenkins:latest should point to lts, then is there an option to generate a tag for jenkinci/jenkins that points to weekly?

I think this would resolve the issue I'm describing above, if you have an alternative solution that doesn't involve me having to track plugin versions I'd appreciate if you could let me know. 

Thanks.

**Comment by carlossg** [comment]
`jenkinsci/jenkins:latest` is not LTS, it is the weekly build. `jenkins:latest` is LTS 

you can install previous plugin versions specifying the version ie. `matrix-project:1.4.1`

**Comment by damianoneill** [comment]
Thankyou Carlos.

**Comment by magnocosta** [comment]
Hello,

I had same problem and I fixed using `jenkinsci/jenkins:latest`.
I recommend read diferences between LTS and weekly on https://jenkins.io/download/

Thanks all!
