### ISSUE TITLE
Pre configure jenkins with jobs / credentials / SCM Sync configuration plugin

### ISSUE THREAD

**Issue by roydekleijn** [jenkinsci/docker#492]
Hello,

Would it be possible to pre configure jenkins with a set of jobs ? Credentials?
Maybe even with some pre configured plugins, like the repo url for the SCM Sync configuration plugin..

Please advise,
Roy

**Comment by isuftin** [comment]
@roydekleijn Take a peek @ this work I did yesterday:

https://github.com/isuftin/docker-WUDS-WaDE/tree/master/jenkins

**Comment by carlossg** [comment]
You can ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists). Populating credentials is a bad idea
