### ISSUE TITLE
fail to install plugins - Downloaded file is not a valid ZIP

### ISSUE THREAD

**Issue by neo-feng** [jenkinsci/docker#498]
### Docker commands that you execute
FROM jenkins:2.46.2
COPY plugins.txt /usr/share/jenkins/ref/
RUN /usr/local/bin/install-plugins.sh ldap:1.11

### Actual result
Downloading plugin: ldap from https://updates.jenkins.io/download/plugins/ldap/1.11/ldap.hpi
WAR bundled plugins:
Installed plugins:
Downloaded file is not a valid ZIP: /usr/share/jenkins/ref/plugins/ldap.jpi
[/usr/share/jenkins/ref/plugins/ldap.jpi]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
ldap:
Some plugins failed to download! Download integrity: ldap

### Expected outcome
intsall plugin successfully

**Comment by carlossg** [comment]
it works here, maybe a temporary issue with your connection

**Comment by er-jagdish** [comment]
similar issue while instaling many plugins together .. how to overcome it ?
