### ISSUE TITLE
Cannot set --sessionTimout or control user login session

### ISSUE THREAD

**Issue by mtdeguzis** [jenkinsci/docker#500]
### Docker commands that you execute:

```
/usr/bin/docker run -d --sessionTimeout=1 --user 1000 --privileged  --volume /home/jenkins:/var/jenkins_home --publish 443:8443 jenkins --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/.keystore/jenkins_keystore.jks  --httpsKeyStorePassword="$KEYSTORE_PASSWORD"

unknown flag: --sessionTimeout
```

I have also tried:

war/WEB-INF/web.xml
```
<session-config>
   <session-timeout>20</session-timeout>
</session-config>
```

docker/jenkins.sh
```
# if `docker run` first argument start with `--` the user is passing jenkins launcher arguments
[...]
  jenkins_opts_array=( )
  while IFS= read -r -d '' item; do
    jenkins_opts_array+=( "$item" )
  done < <([[ $JENKINS_OPTS ]] && xargs printf '%s\0' <<<"$JENKINS_OPTS")
```

### Expected outcome

Jenkins starts with user session timeout of 1 minute (for testing). I have looked up and down this and jenkins source code trying to find out how to control this. It's important from our enterprise standpoint to have a user session timeout of 15 minutes.

### Have you tried a non-dockerized Jenkins and get the expected outcome?

Not applicable in our environment at the moment.

### Output of docker version

Docker version 1.12.6, build 3a094bd/1.12.6

### Other info

* https://github.com/jenkinsci/docker/blob/master/jenkins.sh
* [--sessionTimeout commit](https://github.com/jenkinsci/docker/blob/master/jenkins.sh)
* http://jenkins-ci.361315.n4.nabble.com/How-to-use-sessionTimeout-td4684576.html

**Comment by carlossg** [comment]
you need to pass `--sessionTimeout=1` after `jenkins`, ie. 

    /usr/bin/docker run -d  --user 1000 --privileged  --volume /home/jenkins:/var/jenkins_home --publish 443:8443 jenkins --sessionTimeout=1 --httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/.keystore/jenkins_keystore.jks  --httpsKeyStorePassword="$KEYSTORE_PASSWORD"

**Comment by mtdeguzis** [comment]
Thank you so much. Hard to find documentation of stuff upstream. I only found adding JAVA_OPTS by looking in scripts and the Active Directory plugin mentioning it. I started the container with `--sessionTimeout=1`, but after 1 minute of not touching the mouse, the jenkins_admin session was still logged in and I could click around.

**Comment by carlossg** [comment]
it's a jenkins flag and goes like the other jenkins flags `httpPort`, `httpsPort`,...
