### ISSUE TITLE
Pull the latest from images before publishing

### ISSUE THREAD

**Issue by cronik** [jenkinsci/docker#501]
The Jenkinsfile build stage should include the `--pull` argument to get the latest FROM image (i.e. 8-jdk).

```groovy
stage('Build') {
            docker.build('jenkins', '--pull')
}
```
The openjdk:-8-jdk image has recently updated to 8u131 but that is not reflected in the latest jenkins builds. Either the FROM image should be more specific or the pull argument should be added to the build step.

You can verify this by checking the java version in the most recent jenkins 2.63 build which is about 10 days after the openjdk:8-jdk image was updated.

```bash
➜  docker image ls -f "reference=jenkinsci/jenkins:*alpine"
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jenkinsci/jenkins   2.63-alpine         4ffd9c0aaa1a        2 days ago          224 MB
➜   docker image ls -f "reference=openjdk:8-jdk"            
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
openjdk             8-jdk               ab0ecda9094c        2 weeks ago         610 MB
➜  docker run -it --rm openjdk:8-jdk java -version                                                             
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
➜   docker run -it --rm jenkinsci/jenkins:2.63-alpine java -version                                         
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (Alpine 8.121.13-r0)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by carlossg** [comment]
There is no OpenJDK 1.8.0 131 alpine

**Comment by cronik** [comment]
good point :) I missed that when reading the soup of tags on the docker hub. It looks like the non-alpine version of jenkins does include the latest version of the base image.
