### ISSUE TITLE
RUN mkdir doesn't make directory and how to change ownership to jenkins

### ISSUE THREAD

**Issue by toughrice** [jenkinsci/docker#504]
# Issues and Contributing

I wrote a dockerfile like following:
```
FROM  jenkins:latest

MAINTAINER  Rice<toughrice@163.com>

RUN mkdir -p /var/jenkins_home/maven/ref
COPY ./settings.xml /var/jenkins_home/maven/conf/
```

the image built and run successfully. 
build command: docker build -t jenkins-test:latest .
build logs:
```
Sending build context to Docker daemon 20.48 kB
Step 1/4 : FROM jenkins:latest
 ---> 04c1dd56a3d8
Step 2/4 : MAINTAINER Rice<toughrice@163.com>
 ---> Running in 57cfb56ab513
 ---> 85c0f5ebb086
Removing intermediate container 57cfb56ab513
Step 3/4 : RUN mkdir -p /var/jenkins_home/maven/ref
 ---> Running in 7fd0bc271234
 ---> 5f250063dc58
Removing intermediate container 7fd0bc271234
Step 4/4 : COPY ./settings.xml /var/jenkins_home/maven/conf/
 ---> 5111693352e1
Removing intermediate container 5adfa81f143a
Successfully built 5111693352e1
```

However,  the "ref" directory does exist and the "settings.xml" file is owned by root user and root group, not jenkins. I expect changing its ownership to jenkins. 

In my localhost the file have been changed to userid 100 and groupid 1000.

My Docker version: 1.13.1.

**Comment by carlossg** [comment]
/var/jenkins_home is a volume so it won't be persisted 
Check the README and docker docs about volumes and permissions

**Comment by toughrice** [comment]
@carlossg I am sorry I didn't make it clear. I meant when I logged in the container I found it didn't make the "/var/jenkins_home/maven/ref" directory. And the file "./settings.xml" being copied in my localhost is already assigned to userid 1000 and groupid 1000, but I found it assigned to root user and root group in the container.

**Comment by yogig** [comment]
RUN mkdir -p /var/jenkins_home/maven/ref
COPY ./settings.xml /var/jenkins_home/maven/conf/

You are making direcotry name **/ref** & you are trying to copy in directory **/conf**
