### ISSUE TITLE
unable to run docker inside container

### ISSUE THREAD

**Issue by jeffie9** [jenkinsci/docker#506]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
$ docker run -it --rm --entrypoint /bin/bash jenkins:2.46.1 -c "ls /usr/lib/x86_64-linux-gnu/libltdl.so.7"
/usr/lib/x86_64-linux-gnu/libltdl.so.7

$ docker run -it --rm --entrypoint /bin/bash jenkins:2.46.2 -c "ls /usr/lib/x86_64-linux-gnu/libltdl.so.7"
ls: cannot access /usr/lib/x86_64-linux-gnu/libltdl.so.7: No such file or directory

### Actual result
File found in tag 2.46.1
File missing in tag 2.46.2

### Expected outcome
File found in all tags

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No

### Output of `docker version`
Docker version 1.12.0, build 8eab29e

### Other relevant information
Running Jenkins container in Kubernetes with hostPath volumes to /var/run/docker.sock and /usr/bin/docker

Output from docker pipeline step:
+ docker inspect -f . maven:alpine
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

In fairness, the following fails too:
$ docker run -it --rm --entrypoint /bin/bash openjdk:8-jdk -c "ls /usr/lib/x86_64-linux-gnu/libltdl.so.7"
ls: cannot access /usr/lib/x86_64-linux-gnu/libltdl.so.7: No such file or directory

**Comment by carlossg** [comment]
you need to bring that up in the openjdk image https://github.com/docker-library/openjdk

**Comment by jeffie9** [comment]
If I can't get anyone upstream to fix it, would you consider adding this to the Dockerfile:
RUN apt-get update && apt-get install -y libltdl7 && rm -rf /var/lib/apt/lists/*

**Comment by carlossg** [comment]
no , I don't think it is a good idea as this is a minimal image. Furthermore you would typically run docker in the agents, not in the master

**Comment by jeffie9** [comment]
Ok, I will close because I can just add the missing files to my own image.  Thanks.
