### ISSUE TITLE
User maven in Jenkins failing as  no POM in the workdirectory

### ISSUE THREAD

**Issue by toughrice** [jenkinsci/docker#509]
# Issues and Contributing

### Docker commands that you execute
I put the following command in the building step of jenkins.

docker run --rm --name mvn -v /mnt/maven:/root/.m2 -v /var/jenkins_home/workspace/test2:/usr/src/mvn -w /var/jenkins_home/workspace/test2/ --privileged maven:latest mvn clean deploy -Ptest -U -Dmaven.test.skip=true

### Actual result
the jenkins logs:

> [test2] $ /bin/sh -xe /tmp/hudson4629043010297583674.sh
+ docker run --rm --name mvn -v /mnt/maven:/root/.m2 -v /var/jenkins_home/workspace/test2:/usr/src/mvn -w /var/jenkins_home/workspace/test2/ --privileged maven:latest mvn clean deploy -Ptest -U -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.211 s
[INFO] Finished at: 2017-06-07T10:10:50Z
[INFO] Final Memory: 7M/121M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "test" could not be activated because it does not exist.
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/var/jenkins_home/workspace/test2). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### Expected outcome
expecting the maven command run successfully.

### Have you tried a non-dockerized Jenkins and get the expected outcome?

I have tried it and get the same result.

### Output of `docker version`

Docker version 1.13.1, build 092cba3

**Comment by carlossg** [comment]
you are mounting `/var/jenkins_home/workspace/test2` into `/usr/src/mvn` so the pom is in `/usr/src/mvn` not in `/var/jenkins_home/workspace/test2`

**Comment by toughrice** [comment]
@carlossg The first time my command is as following. But I got the same error, no POM in this directory (/usr/src/mvn). 
docker run --rm --name mvn -v /mnt/maven:/root/.m2 -v /var/jenkins_home/workspace/test2:/usr/src/mvn -w/usr/src/mvn --privileged maven:latest mvn clean deploy -Ptest -U -Dmaven.test.skip=true

**Comment by carlossg** [comment]
if you are running jenkins in a docker container and mounting the docker socket then your container is running in the host and it does not have access to the workspace. You can ask in the jenkins-user mailing list how to set this up

**Comment by toughrice** [comment]
@carlossg I changed the mounting directory to workspace in the host and it worked fine first time. The second time it had no permission to the modify the result directory which produced by maven was owned by root.
I'm wondering if I can remove the user jenkins in the jenkins profile, so that jenkins container has no permission problem.

**Comment by pradeepTechStream** [comment]
Issue
Build with Maven
##[error]Process completed with exit code 1.
Run mvn -B package --file pom.xml    **please Check this command** 
POM file pom.xml specified with the -f/--file command line argument does not exist
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /home/runner/work/jenkins/jenkins/pom.xml: /home/runner/work/jenkins/jenkins/pom.xml (No such file or directory) @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/runner/work/jenkins/jenkins/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/runner/work/jenkins/jenkins/pom.xml: /home/runner/work/jenkins/jenkins/pom.xml (No such file or directory)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
##[error]Process completed with exit code 1.

**Comment by swapnilsworld** [comment]
I am getting the similar error while running the workflow from GitHub actions :(
