### ISSUE TITLE
Installing maven in jenkins, but can not make maven directory

### ISSUE THREAD

**Issue by toughrice** [jenkinsci/docker#511]
# Issues and Contributing

### Dockerfile I have writen

`FROM  jenkins:latest

ARG MAVEN_VERSION=3.5.0
ARG SHA=beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /var/jenkins_home/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-$MAVEN_VERSION-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /var/jenkins_home/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz

ENV MAVEN_HOME /var/jenkins_home/maven
ENV MAVEN_CONFIG "$/var/jenkins_home/.m2"

COPY ./settings.xml /var/jenkins_home/maven/ref/`

### Docker commands that you execute
docker build -t jenkins-test:latest . 
docker run -dit -p 9090:8080 --name jenkins-test -v /mnt/docker/jenkins-test:/var/jenkins_home jenkins-test

### Actual result
Both of docker build and docker run commands were executed fine without any errors.
But it didn't make the directory /var/jenkins_home/maven/ref and maven was not installed.

### Output of `docker version`
Docker version 17.05.0-ce, build 89658be

**Comment by carlossg** [comment]
/var/jenkins_home is a volume 
see https://github.com/jenkinsci/docker#installing-more-tools and docker docs

**Comment by toughrice** [comment]
@carlossg  Won't the volume be deleted until the container is stop or deleted? The container is up and I logged in it to check the directory. And I have mount a local directory to that. Maybe I have misunderstood something. Thank you very much for your answer.
