### ISSUE TITLE
copy_reference_file doesn't maintain permissions on directories

### ISSUE THREAD

**Issue by godbyk** [jenkinsci/docker#513]
### Actual result
I've written a Dockerfile that calls `FROM jenkins:latest`.

I have a `.ssh` directory containing `id_rsa` and `id_rsa.pub` files. I `COPY` the `.ssh` directory to `/usr/share/jenkins/ext` so that it will be installed in `$JENKINS_HOME` for me.

The permissions on `.ssh` are 700 and the permissions on the `id_rsa*` files are 600.

While the files retain their proper 600 permissions (thanks to `cp -r` in the `copy_reference_file` function in the `jenkins-support` script, the `.ssh` directory is improperly created with 755 permissions instead of 700 permissions.

### Expected outcome

I expect the `.ssh` directory to be installed with the same permissions it already has (i.e., 700 and not 755).

### Other relevant information

Instead of copying the existing `.ssh` directory, the `copy_reference_file` function [creates a new directory](https://github.com/jenkinsci/docker/blob/master/jenkins-support#L114) with default permissions (755).

An alternative solution to modifying the `copy_reference_file` function would be to provide another hook that can be used to modify files (e.g., change their permissions and owners) on the mounted volume (e.g., a hook that is called prior to `VOLUME /var/jenkins_home` in the [Dockerfile](https://github.com/jenkinsci/docker/blob/master/Dockerfile#L23).

**Comment by timja** [comment]
This was fixed
