### ISSUE TITLE
Running under different users causes problems for git

### ISSUE THREAD

**Issue by carlossg** [jenkinsci/docker#519]
When running the image with an user that does not exists in the passwd file git clone will break with `fatal: unable to look up current user in the passwd file: no such user`
git is used in the master for pipeline and multibranch at least AFAIK

We could use nss_wrapper to create the passwd file at runtime
http://blog.dscpl.com.au/2015/12/unknown-user-when-running-docker.html
or something like the openshift image does
https://github.com/openshift/jenkins/blob/355600974c22617f5fc4d4bf5eac1aee064e7a2f/2/contrib/jenkins/jenkins-common.sh#L13
although it does not work because `/etc/passwd` is not writable

This would apply for jenkins-slave image too

ping @ndeloof

**Comment by ndeloof** [comment]
@carlossg we had this discussion internally at CloudBees during march 2016 already, I expected recent git version had this issue fixed (see http://git.661346.n2.nabble.com/git-clone-fails-when-current-user-is-not-in-etc-passwd-td7643604.html)
Which version are you running ?

**Comment by ndeloof** [comment]
confirmed this is should be fixed since 2.6.5 
https://github.com/git/git/commit/92bcbb9b338dd27f0fd4245525093c4bce867f3d

or a simple fix is to configure a git user identity

**Comment by carlossg** [comment]
the openjdk image includes git 2.1.4 (does not work) and alpine includes 2.11.2 (does work)

The workaround is to set the GIT_COMMITTER_NAME and GIT_COMMITTER_EMAIL environment variables

**Comment by ndeloof** [comment]
openjdk image is based on debian:jessie, Hopefully Stretch has been published so we can expect to get some updated dependencies.

**Comment by carlossg** [comment]
yeah, stretch has git 2.11.0
