### ISSUE TITLE
install-plugins.sh - line 208: JENKINS_UC: unbound variable

### ISSUE THREAD

**Issue by mabushey** [jenkinsci/docker#520]
```
Step 13 : RUN chmod 744 /usr/local/bin/install-plugins.sh /usr/local/bin/jenkins-support &&     /usr/local/bin/install-plugins.sh $(cat /home/jenkins/plugins.txt | tr '\n' ' ')
 ---> Running in 0c5b3aa2bf42
Creating initial locks...
Analyzing war...
/usr/local/bin/install-plugins.sh: line 208: JENKINS_UC: unbound variable
The command '/bin/sh -c chmod 744 /usr/local/bin/install-plugins.sh /usr/local/bin/jenkins-support &&     /usr/local/bin/install-plugins.sh $(cat /home/jenkins/plugins.txt | tr '\n' ' ')' returned a non-zero code: 1
```

208: `if curl -fsL -o /dev/null "$JENKINS_UC/$jenkinsVersion"; then`

$JENKINS_UC is not set anywhere in the script. I'm not sure why this is working for anyone. I have no idea what version install-plugins.sh is, I downloaded it here: https://raw.githubusercontent.com/jenkinsci/docker/master/install-plugins.sh
https://raw.githubusercontent.com/jenkinsci/docker/master/jenkins-support

**Comment by mabushey** [comment]
I fixed the script by adding `JENKINS_UC=https://updates.jenkins.io` at line 10.

**Comment by carlossg** [comment]
JENKINS_UC is set in the Dockerfile

**Comment by oleg-nenashev** [comment]
IMHO it can be closed as "Not a defect"

**Comment by mabushey** [comment]
@oleg-nenashev Why would say it's not a defect to have a /usr/local/bin script that depends on an ENV var to function? That fits my definition of defect.

**Comment by oleg-nenashev** [comment]
From what I see it's not a defect in terms of the current image and child
developed according to readme. This env var should be always set.

If you create a hardening pull request which enhances the script, it will
be considered and most probably accepted.
