### ISSUE TITLE
koalaman/shellcheck reports an immediate error

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/docker#521]
Building this docker image from the included Jenkinsfile fails due to an error in the current image of koalaman/shellcheck.

### Docker commands that I execute

    $ docker run --rm -t koalaman/shellcheck shellcheck -e SC1091 *.sh

### Actual result

    shellcheck: shellcheck: openBinaryFile: does not exist (No such file or directory)
    install-plugins.sh: install-plugins.sh: openBinaryFile: does not exist (No such file or directory)
    jenkins.sh: jenkins.sh: openBinaryFile: does not exist (No such file or directory)
    plugins.sh: plugins.sh: openBinaryFile: does not exist (No such file or directory)
    publish.sh: publish.sh: openBinaryFile: does not exist (No such file or directory)
    update-official-library.sh: update-official-library.sh: openBinaryFile: does not exist (No such file or directory)

### Expected outcome

    Successful shellcheck of the shell scripts

### Have you tried a non-dockerized Jenkins and get the expected outcome?

    I'm unable to compile koalaman/shellcheck from source, though will continue trying.

### Output of `docker version`

    Docker version 17.05.0-ce, build 89658be

**Comment by carlossg** [comment]
you are not mounting the current dir  in the container, so it has no files

    docker run --rm -w /mnt -v `pwd`:/mnt -t koalaman/shellcheck -e SC1091 *.sh
