### ISSUE TITLE
 hanging on Jenkins is starting, Please wait

### ISSUE THREAD

**Issue by zsjohny** [jenkinsci/docker#529]
2.46.2

### Docker commands that you execute
install plugins 
 docker restart jenkins2

### Actual result
FINE: created build reference for deal-file-server #64 using jenkins.model.lazy.BuildReference$DefaultHolderFactory@ced1267
Jul 18, 2017 3:23:04 PM jenkins.security.ExceptionTranslationFilter doFilter
FINER: Chain processed normally
Jul 18, 2017 3:23:05 PM jenkins.model.lazy.BuildReference findHolder
FINE: created build reference for deal-web-data-server2 #38 using jenkins.model.lazy.BuildReference$DefaultHolderFactory@ced1267
Jul 18, 2017 3:23:06 PM jenkins.model.lazy.BuildReference findHolder
FINE: created build reference for deal-xiaoshouyi-server #378 using jenkins.model.lazy.BuildReference$DefaultHolderFactory@ced1267
Jul 18, 2017 3:23:06 PM jenkins.model.lazy.BuildReference findHolder
FINE: created build reference for deal-calendar-server #34 using jenkins.model.lazy.BuildReference$DefaultHolderFactory@ced1267

**Comment by zsjohny** [comment]
@michaelneale @carlossg @rtyler @kohsuke @ndeloof

**Comment by ndeloof** [comment]
please describe plugins you installed
please also docker exec in container to capture a thread dump

**Comment by KevinLoveGitHub** [comment]
@zsjohny Did you solve the problem, Did you solve the problem?

**Comment by KevinLoveGitHub** [comment]
@zsjohny I have the same problem, Did you solve the problem?

**Comment by oleg-nenashev** [comment]
Not enough info to diagnose the issue

**Comment by ndeloof** [comment]
@KevinLoveGitHub if you have same issue please capture a java stack trace / container state to help understand the root cause.

**Comment by KevinLoveGitHub** [comment]
@ndeloof Thanks，I changed the container network mode to host mode to solve this problem

**Comment by carlossg** [comment]
not enough info
