### ISSUE TITLE
Tag 2.60.2 is missing from jenkinsci/jenkins

### ISSUE THREAD

**Issue by wduda** [jenkinsci/docker#533]
It seems when building/publishing the newest LTS image it was only published as jenkinsci/jenkins:lts (17h ago as of writing this) but no tag 2.60.2 was created. As jenkins/jenkins has 0 tags yet, can this tag be added to jenkinsci/jenkins please? We always build with version specified in the tag.

**Comment by carlossg** [comment]
ping @rtyler

**Comment by rtyler** [comment]
Folks are so impatient, a Pipeline run daily ought to be enough :smiling_imp: 

KK had released the LTS some time last night after the normal cron executed the Pipeline fwiw

**Comment by wduda** [comment]
Thanks, I was just trying to act on the update warning that Jenkins itself now gives in the UI header.
