### ISSUE TITLE
install-plugins.sh seems to randomly read in a blank line from plugins file and fail a build

### ISSUE THREAD

**Issue by dmercer1** [jenkinsci/docker#534]
When I run the install-plugins.sh with a list of plugins to install it will randomly incorrectly read in one line. I've tried this over a dozen times and it has happened every time. The error it returns is this:

```
Failed to download plugin:  or -plugin
```

And the corresponding part of the log where it attempts the download:

```
Downloading plugin: junit from https://updates.jenkins.io/2.60/latest/junit.hpi
Downloading plugin: multi-branch-project-plugin from https://updates.jenkins.io/2.60/latest/multi-branch-project-plugin.hpi
Downloading plugin: nodelabelparameter from https://updates.jenkins.io/2.60/latest/nodelabelparameter.hpi
Downloading plugin: -plugin from https://updates.jenkins.io/2.60/latest/-plugin.hpi
Downloading plugin: pipeline-aws from https://updates.jenkins.io/2.60/latest/pipeline-aws.hpi
Downloading plugin: packer from https://updates.jenkins.io/2.60/latest/packer.hpi
Downloading plugin: ldap from https://updates.jenkins.io/2.60/latest/ldap.hpi
Downloading plugin: performance from https://updates.jenkins.io/2.60/latest/performance.hpi
```

If you run it consecutive times it will move around and happen during a different plugin. Here's the portion of the plugin list I'm referring to, and I will attach the whole list as well.

```
junit
label-linked-jobs
ldap
mailer
mapdb-api
maven-plugin
metrics
momentjs
multi-branch-project-plugin
multiple-scms
nodejs
nodelabelparameter
packer
pam-auth
parameterized-trigger
performance
```
[plugins.txt](https://github.com/jenkinsci/docker/files/1162967/plugins.txt)

**Comment by srajappa** [comment]
Check the solution for issue #535 

Maybe you can also resolve your issue by setting the user as `root` and get the intended results.

**Comment by MichaelGissingNC** [comment]
@dmercer1It's not random, you have a blank line as the first line in your plugins.txt
Give it another try with the blank line removed.

**Comment by dmercer1** [comment]
Boom! Correct. Because it downloads async it would insert the error randomly in the log? Thanks!
