### ISSUE TITLE
how to change timezone when running the image

### ISSUE THREAD

**Issue by FrankJian** [jenkinsci/docker#537]
hi , in the image, the default timezone is UTC, how to change it when run this images?

**Comment by simoncowie** [comment]
I use my own Dockerfile and do this: 

```
#set NZ timezone for jenkins container
ENV TZ=Pacific/Auckland
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

Just replace with the relevant timezone for you. If you need to do it at runtime you could probably do something similar but I image jenkins might need a restart or something?!

**Comment by FrankJian** [comment]
it works. thanks. but the official jenkins images is from openjdk which without /usr/share/zoneinfo/$TZ, i copy this file to /etc/localtime from  host machine directly, and it is working
