### ISSUE TITLE
Disabling security for local usage scenario

### ISSUE THREAD

**Issue by MichaelGissingNC** [jenkinsci/docker#541]
# Request 

It should be possible to optionally disable security.

# Scenario

I have a local Jenkins instance on my developer machine which is only used on my machine by myself. Now I want to provide this well defined environment to my colleagues. Therefore it would be nice if the whole account setup could be skipped when building the image.

There is no need for setting up an admin account in this case.

**Comment by carlossg** [comment]
this is done in jenkins, not in the docker image, and for a good reason. There are ways to configure jenkins on startup with a known user/password

**Comment by pwang2** [comment]
Does this mean we could not reset login for a dockerlized jenkins instance? or could you help point me to the ways you mentioned to use preset user/password
