### ISSUE TITLE
Image not mapping volumes

### ISSUE THREAD

**Issue by lustoykov** [jenkinsci/docker#549]
Hello,

I'm deploying the image on AWS via Elastic Beanstalk, here is my Docker.aws.json

```
{
  "AWSEBDockerrunVersion": "1",
  "Ports": [
    {
      "ContainerPort": "8080"
    }
  ],
  "Volumes": [
    {
      "HostDirectory": "/var/jenkins_home/",
      "ContainerDirectory": "/var/jenkins_home/",
      "readOnly": false
    }
  ]
}
```

The Dockerfile itself contains only the image and exposes 8080. Just wanted to ask if anybody else had problems mapping the volumes? This is the only image I'm having trouble with - neither /var/jenkins_home is created on EC2, nor volume is being mapped even if I created the directory before that. I'd like to provide you with more information, but I don't see any errors in the logs such as permission denied.

I understand this issue might not be directly related to the image, but having problem only with this one in a pretty big setup makes me think that there's something I'm missing.

Thanks.

**Comment by carlossg** [comment]
questions should go to mailing list
