### ISSUE TITLE
Jenkins docker with ldaps

### ISSUE THREAD

**Issue by hiscal2015** [jenkinsci/docker#553]
Hi, 

I want to enable tls for ldap authentication, but how to config the ca certificate for it? Thanks.

**Comment by hiscal2015** [comment]
resolved by customize dockerfile

**Comment by terryxychan** [comment]
@yongzhang 

How did you configure it? Did you add cacerts keystore? If so, to which folder?

Thanks!

**Comment by tomko80** [comment]
> resolved by customize dockerfile

Please share! :)

**Comment by yongzhang** [comment]
@terryxychan @tomko80 Sorry for delay, I found my config, not sure it is helpful:
```
COPY ldapcacert.crt $JAVA_HOME/jre/lib/security
RUN cd $JAVA_HOME/jre/lib/security \
        && keytool -keystore cacerts -storepass changeit -noprompt -trustcacerts -importcert -alias ldapcert -file ldapcacert.crt
```
