### ISSUE TITLE
Upgrade plugins from docker image fails

### ISSUE THREAD

**Issue by goffinf** [jenkinsci/docker#565]
### Docker commands that you execute

docker run .... -e TRY_UPGRADE_IF_NO_MARKER=true

### Actual result

None of the updated plugins within the image (added by running install-plugins.sh) are actually updated in the Jenkins master.

### Expected outcome

The docs state ... -e TRY_UPGRADE_IF_NO_MARKER=true. Then plugins will be upgraded if the version provided by the docker image is newer.

However this does not appear to be the case.

> Upgrading plugins
> 
> By default, plugins will be upgraded if they haven't been upgraded manually and if the version from the docker image is newer than the version in the container. Versions installed by the docker image are tracked through a marker file.
> 
> The default behaviour when upgrading from a docker image that didn't write marker files is to leave existing plugins in place. If you want to upgrade existing plugins without marker you may run the docker image with -e TRY_UPGRADE_IF_NO_MARKER=true. Then plugins will be upgraded if the version provided by the docker image is newer.

### Have you tried a non-dockerized Jenkins and get the expected outcome?

No.

### Output of `docker version`

Docker version 17.06.1-ce, build 874a737

### Other relevant information

Many Jenkins posts talk about since version 2.x both pinned and bundling of plugins is deprecated, for example ....

https://wiki.jenkins.io/display/JENKINS/Bundling+plugins+with+Jenkins
https://wiki.jenkins.io/display/JENKINS/Pinned+Plugins

I note that jenkins_home/plugins still container many .jpi.pinned files but I am assuming that these are ignored.

**Comment by carlossg** [comment]
what are the contents of your `$JENKINS_HOME/plugins` dir 
and the contents of `$JENKINS_HOME/copy_reference_file.log`

**Comment by carlossg** [comment]
no answer, closing
