### ISSUE TITLE
When container is destroyed, maven jobs don't load with host-mapped volumes

### ISSUE THREAD

**Issue by circa10a** [jenkinsci/docker#568]
When using the latest docker image and maven plugin v2.17, if the container is destroyed, maven jobs don't show back up. (when data is host-mapped)

I get this error:
Sep 07, 2017 3:16:29 PM jenkins.model.Jenkins$7 runTask
WARNING: Loading item $jobname failed perhaps due to plugin dependency issues
java.lang.NoClassDefFoundError: org/codehaus/plexus/component/configurator/ComponentConfigurationException

**Comment by carlossg** [comment]
Wdym? More details?

**Comment by circa10a** [comment]
#### Fix for those who may run into this problem:

The issue was due to my customized docker image with preinstalled plugins. I loaded `maven-plugin.hpi` into the image and later updated the plugin which installed as `maven-plugin.jpi`. Once the container was destroyed and recreated, the 2 would clash due to having the hpi file in the image.

The fix was to replace `maven-plugin.hpi` in the docker image with `maven-plugin.jpi`  and delete the `maven-plugin.hpi` from the host.
