### ISSUE TITLE
specify pipeline-library in Jenkinsfile

### ISSUE THREAD

**Issue by larrycai** [jenkinsci/docker#573]
Try to execute the `Jenkinsfile` from local Jenkins instance, and it complains 

    groovy.lang.MissingPropertyException: No such property: infra for class: groovy.lang.Binding

After checked for a while, noticed it would be good to add library in `Jenkinsfile`

    @Library('pipeline-library@master') _.

This is what did in https://github.com/jenkins-infra/azure/blob/master/Jenkinsfile#L6

Surely the `pipeline-library` shall be set in `Global Pipeline Libary` of my Jenkins instance.

Will be nice if can be added to save extra setup locally.

**Comment by carlossg** [comment]
Jenkinsfile is only to build the official images from jenkins infra

**Comment by oleg-nenashev** [comment]
Some automatic library definitions may be helpful later, but `@Library` is probably not the best option while pipeline-library has no versions, etc.
