### ISSUE TITLE
need to re-publish on upstream images updates

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/docker#576]
our [publish.sh](https://github.com/jenkinsci/docker/blob/master/publish.sh) scripts makes complex computation to check tag for a version is already pushed to the hub. As a side effect if a security fix applies to some upstream image we don't get updates, but for future images we build.

As `docker push` do take care of existing layers (based on content checksum), and assuming our `docker build` is idempotent (which it seems to be) we don't need this, can rebuild on regular basis and push, this would just not update tag. As a side effect we ensure images on dockerhub are always clean and up-to-date, with the cost of rebuilding again and again same stuff.

wdyt @rtyler @carlossg ?

**Comment by carlossg** [comment]
`docker build` is not idempotent because we are building with `--no-cache`  and you would also have to run always in the same vm and keep old images around. 
So in order to rebuild only if parent image changes you would need to check the checksum of that image

**Comment by ndeloof** [comment]
I'm not talking about the cache layer on our build nodes, I don't care we consume some extra CPU to re-build existing images. I'm talking about the actual layer resulting of rebuilding same command on top of same image. This will produce same layer checksum and `docker push` will ignore it.

**Comment by carlossg** [comment]
you will not get the same checksum all the time, ie. when there is a new git/curl version we would install it and change all the layers

I think it will be a maintenance nightmare, what do we do with things like #572 or #566 ? do we rebuild all the previous images with those changes? who tests them?
Maybe tagging the repo the first time we build the image and rebuilding from that tag, so we only get changes in the OS packages, but still a lot to test

**Comment by ndeloof** [comment]
@carlossg yes indeed, and this is exactly what I would expect : docker images for jenkins to be up to date with packaged tools. 
About changes we make to the image structure, I admit this could be more problematic. But having docker images but the latest with potential CVE is not good as well. I'm not sure about the impact for changes like #566, but they anyway already impact people who use to upgrade. If one want to stay on a specific image, only using it's sha256 can enforce nothing ever changes.

**Comment by gutoandreollo** [comment]
It's complicated to re-push a specific image (as opposed to a general one like `:lts`), as the expectation might be that every time a specific image is pulled, it will contain the same layers.

If I pull `jenkins/jenkins:2.73.2` twice, in two different days/weeks, should I not expect to receive exactly the same layers?

**Comment by ndeloof** [comment]
@gutoandreollo that's already the case with base images, if you pull "ubuntu:14.04" at different times, you'll get on latest an updated docker image. See https://hub.docker.com/r/library/ubuntu/tags/
all tags where updated 12 days ago, not just latest

As jenkins image is not just jenkins but also JDK and OS image, we need to update on a regular basis - or you'll need to run `apt-get update` just after you pull a new image, which would be painful and introduce security risks.

Don't consider "tags" in a docker registry to have same meaning as "tag" in a SCM :  tags on docker are equivalent to SCM branches. Tags move and _have_ to move. I know some use docker tags to match SCM tags or build numbers, but that's a misuse. A docker image is not just a software packaged, it also bundles all it's runtime and as such has to update on a regular basis.
