### ISSUE TITLE
the 2.80 never initialization 

### ISSUE THREAD

**Issue by opspy** [jenkinsci/docker#584]
# Issues and Contributing

the docker images 2.79 and 2.80 has probolem

the 2.79  when  initialization `/var/jenkins_home/secrets/initialAdminPassword` bottom right  image don't display

the 2.80 never initialization 

the other version  don't have error.(example 2.78,lts)

# start option
docker run  --detach \
    --user root \
    --env JAVA_OPTS="-Xmx2048m" \
    --publish 8080:8080 \
    --publish 50000:50000 \
    --name jenkins \
    --privileged \
    --restart always \
    --volume /srv/jenkins_home/:/var/jenkins_home/ \
    jenkins/jenkins:2.79

docker run  --detach \
    --user root \
    --env JAVA_OPTS="-Xmx2048m" \
    --publish 8080:8080 \
    --publish 50000:50000 \
    --name jenkins \
    --privileged \
    --restart always \
    --volume /srv/jenkins_home/:/var/jenkins_home/ \
    jenkins/jenkins:2.80

**Comment by carlossg** [comment]
> when initialization /var/jenkins_home/secrets/initialAdminPassword bottom right image don't display

a image in the web ui does not display?

**Comment by opspy** [comment]
in the unlock jenkins  ui  bottom right image don't display

**Comment by daniel-beck** [comment]
My guess is this would be resolved by https://github.com/jenkinsci/jenkins/pull/3052 if the resource is directly in the war: https://issues.jenkins-ci.org/browse/JENKINS-47127

**Comment by daniel-beck** [comment]
And, well, 2.80 was terrible.
