### ISSUE TITLE
install-plugins.sh isn't installing plugins, and groovy scripts aren't initializing

### ISSUE THREAD

**Issue by daytonpa** [jenkinsci/docker#585]
### Docker commands that you execute
`RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt`

Example of `plugins.txt`:
```
ace-editor:latest
bouncycastle-api:latest
branch-api:latest
chef-identity:latest
```
Additionally, the `plugins.txt` file gets deleted after the `RUN` command in the Dockerfile

I also have a `security.groovy` script in `/usr/share/jenkins/ref/init.groovy.d/` that doesn't get used by Jenkins

### Actual result
No plugins are installed, and groovy scripts aren't initializing

### Expected outcome
Plugins installed with Matrix Security enabled, as well as a login screen prometing the user for a username and password

### Have you tried a non-dockerized Jenkins and get the expected outcome?
Yes

### Output of `docker version`
`Docker version 17.09.0-ce, build afdb6d4`

### Other relevant information
I am using `docker-compose` to build and start the container.  Jenkins starts, but not in the desired state.

System info:
```
Linux default-ubuntu-1604 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by carlossg** [comment]
You are not providing the dockerfile or output or anything to debug the issue.
It works here fine and there are tests covering it

**Comment by anthonyagresta** [comment]
@daytonpa I had a similar problem, and got installing plugins to work by copying an older version of `plugins.sh` into my docker container:

<https://github.com/jenkinsci/docker/blob/4fa9ebc13069fa8186728622cd63702cddf11162/plugins.sh>

Dockerfile:

```dockerfile
FROM jenkins/jenkins:lts
COPY plugins.sh /usr/local/bin/plugins.sh
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
```

The newer plugins.sh and install-plugins.sh do more, but this one seems to actually work.

**Comment by carlossg** [comment]
closing with no feedback from reporter

**Comment by vimalcs** [comment]
Hi,

I'm having the same issue. Its working fine from non-dockerized Jenkins and getting the expected outcome. We are facing issue while building the Docker Image.

Dokerfile follows:
```
# Official jenkins container image
FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
	rm -f /etc/localtime && \
	ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
	dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update
RUN apt-get install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	wget \
	vim \
	p7zip \
	gnupg2 \
	software-properties-common

RUN wget -qO - https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
	"deb [arch=amd64] https://download.docker.com/linux/debian \
	$(lsb_release -cs) \
	stable"
RUN apt-get update
RUN apt-get install -y docker-ce

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state

```

**Error**

```Downloading plugin: token-macro-plugin from https://updates.jenkins.io/download/plugins/token-macro-plugin/latest/token-macro-plugin.hpi

Failed to download plugin: token-macro or token-macro-plugin

WAR bundled plugins:

Installed plugins:
*:
Some plugins failed to download! Not downloaded: token-macro
```

If the docker image is building without installing plugins (ie, by removing the step `RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt` ), docker image creation completed successfully. Also able to install the plugins by manually executing the script  _/usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt_  from _inside the docker_
