### ISSUE TITLE
How can i deel with "This Jenkins instance appears to be offline."

### ISSUE THREAD

**Issue by Mararesliu** [jenkinsci/docker#596]
can not install plugins when start
logs Wanning follow
AM hudson.model.UpdateCenter updateDefaultSite
WARNING: Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.
java.net.SocketTimeoutException: connect timed out

**Comment by ramizrshaik** [comment]
is it because of OOM kill ??

**Comment by carlossg** [comment]
your container does not have internet access, please ask in docker mailing lists

**Comment by Mararesliu** [comment]
May be can not connect to jenkin’s plugin sever, I go through some days latter.

**Comment by elico** [comment]
Installing a new JDK 8(u101+) with JAVA_HOME should do the trick like at:

- https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04

is making sure that Lets Encrypt certificates are installed and available on the OS/SYSTEM.
To test it you can use the instructions at:

- https://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates

And to install manually if required the Let's encrypt root chain using the next script:

- https://gist.github.com/Firefishy/109b0f1a90156f6c933a50fe40aa777e
