### ISSUE TITLE
running ant build throws error

### ISSUE THREAD

**Issue by shail0dm** [jenkinsci/docker#602]
I have a simple ant project i am trying to build with new docker jenkins installation and i see the same problem with non-dockerized local jenkins installation. On running the build i get following error in the end.

First time build. Skipping changelog.
[local-atg-build] $ ant -file build.xml
ERROR: command execution failed.Maybe you need to configure the job to choose one of your Ant installations?
Finished: FAILURE

I am guessing the ant plugin installed is not in path.

# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

**Comment by carlossg** [comment]
ant is not installed by default in the image
https://github.com/jenkinsci/docker#installing-more-tools
