### ISSUE TITLE
Missing libc6-dev for asciidoctor-maven-plugin

### ISSUE THREAD

**Issue by rgarrigue** [jenkinsci/docker#603]
### Docker commands that you execute

I'm executing a build which include some asciidoc to be converted

### Actual result

Build fail with 

```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on project hbase: Execution output-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
```

### Expected outcome

A working build

### Have you tried a non-dockerized Jenkins and get the expected outcome?

It does work

### Output of `docker version`

[jenkins@jenkins ~]$ docker --version
Docker version 17.03.2-ce, build 7392c3b/17.03.2-ce

[jenkins@jenkins ~]$ docker images | grep jenkins
jenkins/jenkins     lts                 e6b6a36fca5a        3 weeks ago         814 MB

### Other relevant information

I'm running this on EC2 instance running Amazon Linux 201709. After fiddling with jruby & asciidoctor-maven-plugin version, then with temp folder without success, I ended up finding my solution there : https://issues.apache.org/jira/browse/INFRA-12731. I was missing `libc6-dev`. Hence my workaround, building this container

```
FROM jenkins/jenkins:lts
USER root 
RUN apt-get update \
    && apt-get install -y libc6-dev 
USER jenkins
WORKDIR /var/jenkins_home
```

I'm fine as is, I opened this issue here for anyone hitting the same wall. And maybe you could include this lib in the official Dockerfile.

**Comment by oleg-nenashev** [comment]
No strong opinion, the library seems to be generic enough though it's highly advised not to run builds on the master.

@carlossg WDYT?

**Comment by daniel-beck** [comment]
👎 Seems against best practices. Same as e.g. https://github.com/jenkinsci/docker/pull/91

**Comment by carlossg** [comment]
You'll need to create your own image or run in an agent
