### ISSUE TITLE
How to force jenkins slave to use JDK 7 thats build on openJDK 8 image?

### ISSUE THREAD

**Issue by ramizrshaik** [jenkinsci/docker#604]
my aim is to built a jenkins slave that use jdk 7 to run the jobs. so, i took an existing Jenkins slave thats was built on open jdk 8 image. 

![2017-11-05_10-37-11](https://user-images.githubusercontent.com/20799009/32416320-66fb07e4-c215-11e7-9768-c5a9a0101f18.png)

i copied JDK 7 into that slave and updated the JAVA_HOME.  when i built an image its lookin something like this with env variables 

![image](https://user-images.githubusercontent.com/20799009/32416389-393a8ed2-c216-11e7-88d8-c05901212d7d.png)

but i am when i am running the jobs on this slave it is still using jdk 8 but not jdk 7.  Do i need to do any further steps to make this work/?? 

this is the 'ls' of the container 

![capture](https://user-images.githubusercontent.com/20799009/32416361-f5af26d2-c215-11e7-81d6-913b15624c64.PNG)

TIA :) 

# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

**Comment by carlossg** [comment]
If you have Jenkins related issues, please ask in the Jenkins mailing lists.
