### ISSUE TITLE
Cannot start the container

### ISSUE THREAD

**Issue by shmkrause** [jenkinsci/docker#607]
Hello!
Not sure if this is a docker issue or an image issue (and please do let me know if I should be posting elsewhere)... I can't even get the container started.  I have tried following the guide in the README, running:
`docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts`

The container immediately exits, `docker ps -a` gives the following output:
`bb2e6c7b55a3        jenkins/jenkins:lts   "/bin/bash -c bash"   2 weeks ago         Exited (0) 3 seconds ago                       kickass_kirch`

`docker logs bb2e6c7b55a3` produces nothing, adding the 'follow' flag doesn't work either; I've tried everything I can think of.  I had other containers running, tried shutting those down, no difference.  Hoping someone can suggest troubleshooting options.

Thanks!

Docker version 17.03.1-ce, build c6d412e

**Comment by carlossg** [comment]
check docker inspect, but it's a problem with docker. Maybe ports taken
