### ISSUE TITLE
Incorrect indication that Jenkins installation is fully configured

### ISSUE THREAD

**Issue by mrmaxsteel** [jenkinsci/docker#608]
### Docker commands that you execute
From your README.md I have added the following line to my dockerfile:
`RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state`

### Actual result
Still prompted to install plugins on first start
### Expected outcome
To not be prompted to install plugins on first start

### FIX
Correct your the README to echo version to:
`/usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion`
Rather than:
`/usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state`

**Comment by carlossg** [comment]
see #310
