### ISSUE TITLE
docker/tests/test_helpers.bash/get_jenkins_url does not support SSL or IPv6

### ISSUE THREAD

**Issue by timcoote** [jenkinsci/docker#612]
This issue can be taken as feature requests or ignored.

The function get_jenkins_url in docker/tests/test_helpers.bash assumes that DOCKER_HOST is of the format <ipv4-dottedquad>:<port-number>.  DOCKER_HOST has supported ipv6 since Jul 16 (http://bit.ly/2zW9Ygl).

Additionally, the url used cannot use https, only http.

**Comment by timja** [comment]
If someone wants this they can PR it, otherwise no need for an issue for this
