### ISSUE TITLE
Running Jenkins in docker as different user

### ISSUE THREAD

**Issue by mtdeguzis** [jenkinsci/docker#617]
I cannot seem to run the Jenkins docker image as another user. My use case is standing up a "dev" instance of Jenkins on the same host, which also seems to not be doable since I bind to 443 to https. At the end of my extended dockerfile I tried USER (required so we add our certs and such in)

```
USER jenkins
```

Instead of Jenkins I would use
```
USER jenkins_dev
```

And having the appropriate new UID set, but this does not work. Is this possible ? Is Jenkins only designed to run as user jenkins and on one host only, or is more than on instance on a host possible?

```
        echo -e "\n==> Starting "name-prod" container (initialization)\n"; \
        sudo docker run -d \
                --name "jenkins-server-prod" \
                --user NEW_UID \
                --privileged \
                --volume /home/jenkins:/var/jenkins_home \
                --publish 443:8443 \
                --env JAVA_OPTS=""-Dhudson.plugins.active_directory.ActiveDirectorySecurityRealm.forceLdaps=true"  " --env TZ="America/New_York" \
                "name-prod"  \
                "--sessionTimeout=15" \
                --httpPort=-15 \
                --httpsPort=8443 \
                --httpsKeyStore=/var/jenkins_home/.keystore/HOST.DOMAIN.COM.all.jks \
                --httpsKeyStorePassword=PASS; \
                echo -e "\n==> Starting Jenkins container service\n"; \
                sudo systemctl start jenkins-container-prod.service; \
```

**Comment by carlossg** [comment]
error or logs ?

**Comment by mtdeguzis** [comment]
Heading out to get a Xmas tree :P I'll setup build my "dev" image again and attach the logs you need. ty

**Comment by mtdeguzis** [comment]
I was able to make this work by creating the user/group and dynamically passing the UID/GID user/group values from my makefile into the Dockerfile. Early tests seem to be ok.

**Comment by mdeguzis** [comment]
To clarify (this is my personal account), you must create the user/group on the parent host, use the same UID/GID passed into your Dockerfile, and just create the user/group and add the group to the user within the Dockerfile, as you would most OS installs with local users.

**Comment by mtdeguzis** [comment]
I have found that specifying the user in the dockerfile and via docker run seems to work just fine.

Create a new user and a home directory, typically via `mkhomedir_helper`.

Pass in args to your Makefile or script that launches the docker container:
```
# Set build args via bash conventions or via Makefile conventions below
# This assumes you have set this yourself or via ifeq conditions

BUILD_ARGS += --build-arg JENKINS_USER=$(JENKINS_USER) --build-arg JENKINS_UID=$(JENKINS_UID) --build-arg JENKINS_GROUP=$(JENKINS_GROUP) --build-arg JENKINS_GID=$(JENKINS_GID)
```

docker run snippet:
Don't mind some of the args below that may not apply to you (https if you don't use it, ENV_OPTS etc..). What is mainly important is the --user against your host UID.
```
165         sudo docker run -d \
166             --name $(CONTAINER_NAME) \
167             --user $(JENKINS_UID) \
168             --privileged \
169             --volume $(JENKINS_HOME):/var/jenkins_home \
170             --publish $(HOST_PORT):8443 \
171             $(ENV_OPTS) \
172             $(IMAGE_NAME)  \
173             $(JENKINS_OPTS) \
174             --httpPort=-15 \
175             --httpsPort=8443 \
176             --httpsKeyStore=MY_KEYSTORE \
177             --httpsKeyStorePassword="$(KEYSTORE_PASSWORD)"; \
```

In your dockerfile:
```
 15 ARG JENKINS_UID=99
 16 ARG JENKINS_GID=99
 17 ARG JENKINS_USER=nobody
 18 ARG JENKINS_GROUP=nobody
 19
 20 RUN groupadd -g $JENKINS_GID $JENKINS_GROUP
 21 RUN useradd --uid $JENKINS_UID -g $JENKINS_GROUP $JENKINS_USER
 22
 23 # Ensure that $JENKINS_HOME retains it's permmissions
 24 RUN chown -R $JENKINS_USER:$JENKINS_USER /home/$JENKINS_USER
<truncated>
 57 # Drop back to the regular jenkins user
 58 USER $JENKINS_USER
```

This effectively will run the instance as whomever you configure it to. In my Dockerfile, I also include this line to protect against upgrades changing the owner. This may not be needed:

```
 20 # Ensure that $JENKINS_HOME retains it's permmissions
 21 RUN chown -R $JENKINS_USER:$JENKINS_USER /var/jenkins_home
```
