### ISSUE TITLE
Improve documentation on Jenkins volumes

### ISSUE THREAD

**Issue by amouat** [jenkinsci/docker#62]
The documentation on how to use volumes with Jenkins is a bit misleading at the minute. Whoever wrote it seems to think that if the volumes aren't bind mounted to a specified host directory and are transient, which isn't the case - the only difference is they are bound to a directory controlled by docker.

For example, "Backing Up Data" instructs users to use `docker cp` if they haven't bind mounted the volume, but you don't need to do this. Instead you can just ask Docker where the volume lives on the host e.g:

     $ docker inspect -f '{{index .Volumes "/var/jenkins_home"}}' gloomy_carson
    /var/lib/docker/vfs/dir/563c1842d05b2ffd5686de299f533a1525cc9de889a7ec961c06856ed3e749a7

And I can just backup that folder.

I'm happy to come up with a new wording and create a pull-request, but I thought you might prefer to reword it yourselves.

**Comment by ndeloof** [comment]
please open a PR

**Comment by benzht** [comment]
I think the documentation is right. If you 'run' a new jenkins container without anything specified regarding the volume /var/jenkins_home, all data written there will be lost when you remove the container.
You basically have two options to make this data persistent across re-creating the jenkins container:
1. mount a directory from the host, or
2. link the volumes to a [Data Volume Container](https://docs.docker.com/userguide/dockervolumes/)

Off course, a not-bound volume actually exists on the disk in a docker-controlled volume. But it lives and dies with the container. When you pull a new version of the image and re-create the container, you loose the data.

Furthermore, the Docker documentation seems to suggest not to access files in containers through the host file system, but to use Docker-supplied commands.

**Comment by amouat** [comment]
Actually, volumes don't die with the container unless you do `docker rm -v`. But good luck finding the folder that has your data! It's just subtleties like this that can mislead people.

Sorry for not coming up with a pull-request. I'm flat out at the minute, so it won't be this week either.

**Comment by benzht** [comment]
You would have to do the `docker rm` as soon as you want to upgrade to a new version, wouldn't you?

**Comment by amouat** [comment]
You could - and I'm certainly not advocating this approach - use `docker inspect` to find out where docker is keeping your volume, use `docker rm` _without_ the `-v` to remove the container, then launch a new container with the volume bind mounted `docker run -v /var/lib/docker/....:/var/jenkins_home ...`.

**Comment by benzht** [comment]
We might be misunderstanding each other so I'm trying to rephrase it a bit.
* Your original post seems to suggest accessing the files in the container using the hosts files system. At my current level of understanding Docker I would suggest not to do it.
* If you want the data in your volumes to persist, I would (and actually do) use a host-mounted volume, or a Data Volume container. Neither option requires `docker inspect` to find out where the data lives on the disk

**Comment by amouat** [comment]
I'm not suggesting accessing the files from the host, as much as just saying it's possible. (Although you are accessing the files from the host whatever you do, it's just you normally go via the container).

I think the wording "make that a persistent volume" is misleading, as there's not really such a thing as a transient volume. This misunderstanding is reinforced by the docker cp advice, which implies a running container is necessary to access the data and it disappears with the container. This very much isn't the case.

I would just reword a bit and replace the docker cp advice with something like `docker run --volumes-from myjenkins -v $(pwd):/backup debian tar cvf /backup/backup.tar /var/jenkins_home`

(Note that's untested and off the top of my head).

**Comment by benzht** [comment]
OK. I stand corrected.
Removing the jenkins container `docker rm jenkins` (without `-v`) will keep the container intact on your disk....but there seems to be no easy way to discover it. My guess would be that for most users this is equivalent to being lost (me included, until now - I have 'lost' some data this way before).
