### ISSUE TITLE
docker builds and documentation

### ISSUE THREAD

**Issue by xenoterracide** [jenkinsci/docker#620]
Can you add builds that include docker binaries? my understanding is that it's no longer safe to bind mount the binary, as it has become less static, and/or also document the basic setup of docker integration using host/os. I feel like this is probably a pretty common use case, and yet the right way to do it isn't documented here or baked in.

**Comment by carlossg** [comment]
see https://github.com/jenkinsci/docker#installing-more-tools

**Comment by xenoterracide** [comment]
I really find that insufficient for installing and configuring jenkins to use docker while running in a container itself.

**Comment by carlossg** [comment]
See #552
You can ask questions in jenkins-user mailing list
