### ISSUE TITLE
automagic https

### ISSUE THREAD

**Issue by xenoterracide** [jenkinsci/docker#623]
Can you guys add an automagic https to the docker container, based on an env var for the domain? this should be possible with letsencrypt. In lew of doing this could you point to instructions in the readme for setting it up instead of using a proxy?

**Comment by carlossg** [comment]
it would be a duplication of what kube-lego or other solutions out there are doing, I think it's better to have it separate in a microservice fashion

**Comment by carlossg** [comment]
docs (related to the docker image and not Jenkins core) and examples on how to set it up or extending the image to enable letsencrypt SSL are fine and can be added here

**Comment by kyxap** [comment]
@xenoterracide  did you find how to configure https on this image?

**Comment by xenoterracide** [comment]
no, I gave up on it

**Comment by carlossg** [comment]
you can easily generate letsencrypt certificates using several options

* kubernetes https://github.com/jetstack/cert-manager/
* docker https://community.letsencrypt.org/t/automatic-nginx-proxy-docker-image-with-letsencrypt-ssl-cert/35827
