### ISSUE TITLE
Fix slim image to restore graph rendering, or stop distributing it

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/docker#630]
I don't think it's useful to distribute a variant that breaks graph rendering in Jenkins. At least the docs should be super clear about this. Per #536:

> … openjdk-jdk-8-headless instead of the non-headless version.

> ![screen shot](https://user-images.githubusercontent.com/1831569/35244646-24752fc8-ffc1-11e7-90f1-88c36e24d7c2.png)

> ![screen shot](https://user-images.githubusercontent.com/1831569/35244649-2795fa98-ffc1-11e7-9902-0fcfce82bf1a.png)

**Comment by daniel-beck** [comment]
Apparently fixed by https://github.com/jenkinsci/docker/pull/657 @MarkEWaite can you confirm?

**Comment by MarkEWaite** [comment]
Agreed.  This is fixed.  I ran the `jenkins/jenkins:lts-slim` image based on Jenkins 2.190.1 and confirmed that graph rendering works as expected.
