### ISSUE TITLE
UseCGroupMemoryLimitForHeap

### ISSUE THREAD

**Issue by xenoterracide** [jenkinsci/docker#633]
could the following options be added to jenkins' own jvm args? since this is running jenkins in a container `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap`

**Comment by carlossg** [comment]
This was brought before, see #451

**Comment by batmat** [comment]
@carlossg so let's close this in favor of #451 is what you're saying?
