### ISSUE TITLE
Separate volume mounts

### ISSUE THREAD

**Issue by rahulsom** [jenkinsci/docker#635]
When I run this command:

```bash
docker run --rm \
    -p 8080:8080 \
    -p 50000:50000 \
    -v $(pwd):/var/jenkins_home \
    jenkins/jenkins:alpine
```

This is what my working directory looks like

```
config.xml
copy_reference_file.log
hudson.model.UpdateCenter.xml
hudson.plugins.git.GitTool.xml
identity.key.enc
init.groovy.d
jenkins.CLI.xml
jenkins.install.InstallUtil.lastExecVersion
jenkins.install.UpgradeWizard.state
jobs
logs
nodeMonitors.xml
nodes
plugins
queue.xml
secret.key
secret.key.not-so-secret
secrets
updates
userContent
users
war
workflow-libs
```

There is a whole lot going on there.
`users` contains user preferences.
`jobs` contains job logs and settings.
`logs` contains jenkins logs.
Almost everything else can be considered part of jenkins configuration.

When building immutable images, the jenkins configuration is unlikely to change.

It is perhaps a better idea to create separate volume mounts for `users`, `jobs`, and `logs`.

**Comment by batmat** [comment]
And also, `-v $(pwd):/var/jenkins_home \`: please do not use "bind-mounts". This is not a Jenkins specific issue, use volumes, always.
I've written https://batmat.net/2018/09/07/how-to-run-and-upgrade-jenkins-using-the-official-docker-image/ yesterday in case you don't know what to do. HTH

**Comment by batmat** [comment]
Closing as per my last comments. Please feel free to reopen if you have proposals that you think are specific improvements/issues for this Docker image repository. If not, feel free to file it upstream at https://issues.jenkins-ci.org/secure/Dashboard.jspa
