### ISSUE TITLE
How to replace settings.xml

### ISSUE THREAD

**Issue by javydreamercsw** [jenkinsci/docker#638]
### Docker commands that you execute
Updated Dockerfile as follows:

```
FROM jenkinsci/jenkins

USER root
RUN apt-get update && apt-get install -y vim maven subversion
RUN mkdir $JENKINS_HOME/.m2
COPY /settings.xml ${JENKINS_HOME}/.m2/

# drop back to the regular jenkins user - good practice
USER jenkins
```
### Actual result
Everything seems to succeed but the job doesn't find the right ~/.m2/settings.xml
### Expected outcome
Job catches the right Maven settings file.
### Have you tried a non-dockerized Jenkins and get the expected outcome?
Yes
### Output of `docker version`
Docker version 17.12.0-ce, build c97c6d6
### Other relevant information
I agree this is not the best practice and everything should be handled by Configuration Provider, but that's out of my control. Custom code, which I don't control, uses ~/.m2/settings.xml to download some dependencies but seems it doesnt' have the right stuff. Where should it be copied?

**Comment by javydreamercsw** [comment]
Leaving open in case this needs to be turned into documentation.

**Comment by batmat** [comment]
> I agree this is not the best practice and everything should be handled by Configuration Provider

You nailed it. I do not think we should have official docs for this kind of case, where basically it should not be encouraged to be done this way.

Now, you can definitely initiate a PR with some documentation that would document "hacks" with a warning at the beginning explaining those are for desperate people not willing or able. We just want IMO to have it separate and clear enough that people know this is not the way to do it.

**Comment by PaulFang** [comment]
Got the same issue. based on your Dockerfile, i even want to mount my windows7 maven repo to the jenkins contianer with container starting param "-v /c/Users/user/.m2:/var/jenkins_home/.m2". any one can answer it ? Thanks a lot.

**Comment by PaulFang** [comment]
The serious issue is that the "RUN mkdir $JENKINS_HOME/.m2" not executed successfully. as i found the .m2 directory not created actually.....

**Comment by PaulFang** [comment]
> I figured out how to do it. Maybe needs documentation?
> 
> After configuring the volume to a local folder I was able to replace the one there and everything seems to work fine.

Hi sir, could you explain your detail operations ? thanks!
