### ISSUE TITLE
Container keeps crashing

### ISSUE THREAD

**Issue by javydreamercsw** [jenkinsci/docker#639]
### Docker commands that you execute
Using defaults to run instance.
### Actual result
Runs fine but container just crashes running a job.
### Expected outcome
Completes the job.
### Have you tried a non-dockerized Jenkins and get the expected outcome?
No.
### Output of `docker version`
Docker version 17.12.0-ce, build c97c6d6
### Other relevant information
Nothing seems to be in the obvious logs. Is there anywhere else I could look?

**Comment by carlossg** [comment]
Check out articles about OOM killed, ie. https://blog.csanchez.org/2017/05/31/running-a-jvm-in-a-container-without-getting-killed/
