### ISSUE TITLE
Persistent volumes have permissions set incorrectly. Follow Consul's example.

### ISSUE THREAD

**Issue by BookOfGreg** [jenkinsci/docker#642]
### Docker commands that you execute

Mount a persistent volume

### Actual result

`drwxr-xr-x 3 root root 4096 Feb 16 10:28 jenkins_home`

### Expected outcome

`drwxr-xr-x 3 jenkins jenkins 4096 Feb 16 10:28 jenkins_home`

### Other

The official consul docker image manages to set any persistent volume correctly as part of its dockerfile:
`drwxr-xr-x    5 consul   consul        4096 Feb  7 16:28 data`

Not 100% how but may have something to do with their chown:
```
# The /consul/data dir is used by Consul to store state. The agent will be started
# with /consul/config as the configuration directory so you can add additional
# config files in that location.
RUN mkdir -p /consul/data && \
    mkdir -p /consul/config && \
    chown -R consul:consul /consul
```
https://github.com/hashicorp/docker-consul/blob/b820cd370d68d28f91e1c8327616fb8f4c6e9126/0.X/Dockerfile#L34-L36

**Comment by carlossg** [comment]
they just change the ownership on startup when running as root. You can find other issues on why mounting host volumes or running as root is a bad idea

**Comment by BookOfGreg** [comment]
Thanks @carlossg, I'll make a custom image to become root, change the volume permissions, and drop again. Alternately since I'm using Kubernetes I could use `fsgroup`
I'm running on Azure AKS so I don't have much choice when it comes to volume claims.
