### ISSUE TITLE
Plugin metadata in plugin name breaks install-plugins.sh

### ISSUE THREAD

**Issue by mikejoh** [jenkinsci/docker#644]
Sorry for not following the usual issue checklist but this one is kind of a request for a discussion that might lead up to a fix in the end. In one way or the other.

We (Praqma) are developing the [pretested-integration-plugin](https://github.com/Praqma/pretested-integration-plugin) and in the ```pom.xml``` we have a five char git SHA string that we append to the hpi build (metadata). This means that the ```plugins.txt``` file will contain a entry similar to this:

```
... snip ...
pretested-integration:2.4.1 (409ae)
... snip ...
```

When we run install-plugins.sh with the plugins.txt as input (tested on ```2.60.3-alpine```) we get the following error:
```
bash-4.3# /usr/local/bin/install-plugins_new.sh < /usr/share/jenkins/plugins.txt
Creating initial locks...
Analyzing war...
Registering preinstalled plugins...
... snip ...
Downloading plugin: pretested-integration from https://updates.jenkins.io/download/plugins/pretested-integration/2.4.1 (409ae)/pretested-integration.hpi
... snip ...
Failed to download plugin: pretested-integration or pretested-integration-plugin
... snip ...
Some plugins failed to download! Not downloaded: pretested-integration
```
What's actually failing when debugging the ```ìnstall-plugins.sh``` is this ```curl```command (in the ```doDownload()``` function):
```
curl --connect-timeout 20 --retry 5 --retry-delay 0 --retry-max-time 60 -f -L 'https://updates.jenkins.io/download/plugins/pretested-integration-plugin/2.4.
1 (409ae)/pretested-integration-plugin.hpi' -o /usr/share/jenkins/ref/plugins/pretested-integration-plugin.jpi
curl: (22) The requested URL returned error: 404 Not Found
```
We end up in a 404 error due to the appended metadata to the plugin name which of course isn't a correct path to the plugin at the plugin server(s).

The first thing i thought when i encountered this was, maybe we (Praqma) shouldn't add that metadata via the pom.xml but then i looked through the ```ìnstall-plugins.sh``` and saw that it does some plugin name/entry sanitization in a while-loop in ```main()```:

```
# Remove leading/trailing spaces, comments, and empty lines
plugin=$(echo "${line}" | tr -d '\r' | sed -e 's/^[ \t]*//g' -e 's/[ \t]*$//g' -e 's/[ \t]*#.*$//g' -e '/^[ \t]*$/d')
```
So each line in the ```plugins.txt``` file will pass through that code above. With the current chain of regular expressions it does clean up what's stated in the comment but if there's something appended, like the git SHA we've added, it doesn't sanitize correctly. Correctly as in assuming that ```<plugin name>:<versioning scheme>``` is the only thing allowed in the plugins.txt file.

We might be the only ones adding the type of string(s) to the plugin name that breaks ```install-plugins.sh```, and i understand if the spontaneous reaction is "you should not add that metadata, please do the needful and remove it!" but at the same time it might be a good thing to actually sanitize the plugin names and to be clear on what's allowed in the ```plugins.txt``` file.

Any input/feedback on this?

Thanks.

//Mikael

**Comment by carlossg** [comment]
would this be better ? 

    pretested-integration:2.4.1 # 409ae

**Comment by mikejoh** [comment]
> would this be better ?
> `pretested-integration:2.4.1 # 409ae`

Hi,

Not exactly, well it would remove the git SHA appended to the plugin string, so in a sense yes. We're having a discussion at the issue tracker of this particular plugin on how to move forward, basically we had a good reason for adding that git SHA but the format of it differs from what's stated in the pom-file.

I will update this issue accordingly.

**Comment by mikejoh** [comment]
Closing this issue, we (Praqma) fixed the versioning scheme for this particular plugin so that we don't append any metadata to the plugin version suffix (which breaks install-plugins.sh).
