### ISSUE TITLE
Multiarch image spitting error on ppc64le

### ISSUE THREAD

**Issue by vaibhavsood** [jenkinsci/docker#646]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
docker pull jenkins/jenkins:lts
docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

This is on a ppc64le machine
### Actual result
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
        panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x103ebf80, 0xc820165d50)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3a0
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0xc820113278)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x364
panic(0x103ebf80, 0xc820165d50)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4c4
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820112af8, 0xc82001a088, 0xc820112c20)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x184
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc8200587d0, 0x3fffa93454b8, 0xc820165d50)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x504
main.glob.func8(0xc820078780, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x10351560, 0x10501ea0, 0x13, 0x104486c8, 0x4, 0xc8201131e0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/reflect/value.go:435 +0xe54
reflect.Value.Call(0x10351560, 0x10501ea0, 0x13, 0xc8201131e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/reflect/value.go:303 +0x94
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x10351560, 0x10501ea0, 0xc820078780, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x268
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x1044b4d8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x104e0b40, 0x51, 0x0, ...)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xdf0
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x968
main.main()
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main.go:137 +0xca0

### Expected outcome
The docker image starts jenkins on specified port

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No
### Output of `docker version`
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:34:35 2017
 OS/Arch:      linux/ppc64le

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:34:35 2017
 OS/Arch:      linux/ppc64le

### Other relevant information

As per this https://github.com/jenkinsci/docker/pull/579 , multi-arch jenkins dockerimage builds are enabled.

**Comment by carlossg** [comment]
I don't have access to a ppc, can you try these commands from the container?

```
docker run -ti --rm --entrypoint /bin/bash jenkins/jenkins:latest
/bin/tini
/sbin/tini
/usr/local/bin/jenkins.sh
```

**Comment by vaibhavsood** [comment]
The first command fails (ie starting the container), it gives the "exec format error" (same as the detailed message above in the issue description)

>> test@pts00449-vm9:~/vaibhav/breakpad/src$ docker run -ti --rm --entrypoint /bin/bash jenkins/jenkins:latest /bin/tini

panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
        panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x103ebf80, 0xc82015c000)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3a0
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0xc8200f7278)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x364
panic(0x103ebf80, 0xc82015c000)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4c4
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200f6af8, 0xc82001a0b8, 0xc8200f6c20)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x184
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820059590, 0x3fff843756e0, 0xc82015c000)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x504
main.glob.func8(0xc820078a00, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x10351560, 0x10501ea0, 0x13, 0x104486c8, 0x4, 0xc8200f71e0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/reflect/value.go:435 +0xe54
reflect.Value.Call(0x10351560, 0x10501ea0, 0x13, 0xc8200f71e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/reflect/value.go:303 +0x94
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x10351560, 0x10501ea0, 0xc820078a00, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x268
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x1044b4d8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x104e0b40, 0x51, 0x0, ...)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xdf0
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x968
main.main()
        /build/runc-F1mGRW/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main.go:137 +0xca0

**Comment by carlossg** [comment]
are you running them in the same line?

First run this to get a shell in the container

    docker run -ti --rm --entrypoint /bin/bash jenkins/jenkins:latest

From that shell run each of these commands and let me know which ones succeed/fail

```
/bin/tini
/sbin/tini
/usr/local/bin/jenkins.sh
```

**Comment by vaibhavsood** [comment]
> First run this to get a shell in the container

> docker run -ti --rm --entrypoint /bin/bash jenkins/jenkins:latest

Running this itself gives me the above error, cant get to the shell

**Comment by carlossg** [comment]
thanks, what about 

    docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:latest
    docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:alpine
    docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:slim
    docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk
    docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk-alpine
    docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk-slim

**Comment by vaibhavsood** [comment]
Hi, sorry for the delayed response, my network was slow so took some time to pull the images

this is what i get for the commands you mentioned 

> docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:latest
docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:alpine
docker run -ti --rm --entrypoint /bin/sh jenkins/jenkins:slim

These 3 fail with the same error in my earlier comments (exec format)

> docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk
docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk-alpine
docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk-slim

These 3 run correctly, i can get to the container shell. I ran the /bin/tini etc commands inside them, all of them give 'command not found' as below:

test@pts00449-vm9:~/Downloads/idea-IC-173.4548.28$ docker run -ti --rm --entrypoint /bin/sh openjdk:8-jdk-slim
Unable to find image 'openjdk:8-jdk-slim' locally
8-jdk-slim: Pulling from library/openjdk
07a374cd4a95: Pull complete
6db1eeca3bf1: Pull complete
ffa77403ca9a: Pull complete
3cfac90f183e: Pull complete
1db0b5c0c56a: Pull complete
6d4fb7130a5c: Pull complete
Digest: sha256:bd394fdc76e8aa73adba2a7547fcb6cde3281f70d6b3cae6fa62ef1fbde327e3
Status: Downloaded newer image for openjdk:8-jdk-slim
# /bin/tini
/bin/sh: 1: /bin/tini: not found
# /sbin/tini
/bin/sh: 2: /sbin/tini: not found
# /usr/local/bin/jenkins.sh
/bin/sh: 4: /usr/local/bin/jenkins.sh: not found`

**Comment by carlossg** [comment]
doh! sorry, I was confusing this image with another one I maintain `maven`

The `jenkins/jenkins` image published to dockerhub has no support for multiarch, you can build your image in ppc and it should work, that's what #579 enabled. But the jenkins project is not building/publishing those

**Comment by vaibhavsood** [comment]
no prob, thanks for the update!

A quick ques, are there any future plans to publish jenkins multi-arch images to dockerhub? 

we plan to use the jenkins docker image on ppc64le and so it would be nice if it was directly available via a 'docker pull'

I believe docker has the official images program which can help to do that as you might be aware but i also see that the official jenkins image has been deprecated there & hosted under jenkins/jenkins, so would like to know whats the plan for this going forward? thanks!

**Comment by carlossg** [comment]
No plans yet. Official images have other problems because require manual intervention to publish, that's why it was deprecated

**Comment by seth-priya** [comment]
@carlossg I am interested in building an image for ppc64le. However, simply building an image locally using the Dockerfile in this repo. gives me version 2.60.3, how can I build an image for LTS release? 

Any pointers would be of great help ..!!

**Comment by carlossg** [comment]
you need to pass the docker build args JENKINS_VERSION and JENKINS_SHA

**Comment by imdurgadas** [comment]
PR #750 is created to add multi-arch docker image publish in the job so that it runs as part of trusted CI process.

**Comment by timja** [comment]
We're now publishing `arm64`, `ppc64le` and `s390x` images

See tags on dockerhub:
https://hub.docker.com/r/jenkins/jenkins/tags?page=1&ordering=last_updated

Please raise a new issue if any problems with it
