### ISSUE TITLE
[FATAL tini (8)] tcsetpgrp failed: Permission denied

### ISSUE THREAD

**Issue by latel** [jenkinsci/docker#655]
```
sudo docker run --rm 4b974f5ab147
[FATAL tini (8)] tcsetpgrp failed: Permission denied
```

**Comment by batmat** [comment]
This looks like something unrelated, you're running a local image sha. Please use jenkins/jenkins or something linked to what this repo is providing.

Please follow https://github.com/jenkinsci/docker/blob/master/CONTRIBUTING.md

As such, this issue should be closed IMO.
