### ISSUE TITLE
Required RAM to make Jenkins work on Docker

### ISSUE THREAD

**Issue by jaybauson** [jenkinsci/docker#670]
Given the posted result below, what should be the RAM to make Jenkins work on Docker?

### Docker commands that you execute
docker run -p 8080:8080 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-alpine

### Actual result
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000079373d9c8000, 2555904, 1) failed; error='Operation not permitted' (errno=1)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid5.log

### Expected outcome
jenkins should be pulled and executed

### Have you tried a non-dockerized Jenkins and get the expected outcome?
yes, been using jenkins for a while

### Output of `docker version`
Docker version 17.10.0-ce, build ba9946cf23

**Comment by carlossg** [comment]
see https://github.com/frol/docker-alpine-oraclejdk8/issues/12
