### ISSUE TITLE
Split Docker image into an extensible base image and non-extensible image

### ISSUE THREAD

**Issue by PeterLappo** [jenkinsci/docker#672]
Its not possible to perform some operations on the Jenkins home directory defined in the Dockerfile such as RUN chmod or RUN mkdir because the VOLUME command is present in the Dockerfile.
See question here https://stackoverflow.com/questions/50155619/docker-run-command-is-not-applied-to-the-image and https://github.com/moby/moby/issues/12779 that explains why VOLUME is not a good idea in an image that users want to extend. In essence its a feature/bug in Docker that doesn't look like its going to be resolved. The resolution is to contact the authors and ask them to remove the VOLUME command.

I can see why you want VOLUME so that users can quickly fire up an instance of Jenkins but equally there will be a lot of people who want to extend the image (in my case to add ssh keys and create some directories in the Jenkins home directory) that don't want the VOLUME command due to the Docker "feature".

So perhaps there should be two images, a base image without VOLUME and an image that extends the base image that has VOLUME.

Looking back through the issues the use of VOLUME seems to be affecting other people too.

**Comment by batmat** [comment]
@PeterLappo see the documentation, there's a standard way for people to change things that will land into the JENKINS_HOME. See  `/usr/share/jenkins/ref/` directory and the related examples and so on.

**Comment by batmat** [comment]
@carlossg let's close this maybe? Or would you like me to get the necessary permission to do that cleanup without bothering you?

**Comment by carlossg** [comment]
please do
