### ISSUE TITLE
Package updates are not included in Docker images

### ISSUE THREAD

**Issue by jvz** [jenkinsci/docker#676]
This is more important to the standard Docker images, but it also applies to the slim and alpine editions as well. The issue here is that no `apt-get upgrade` or `apk upgrade` command is included when installing packages, so several outdated packages (which include many patched CVEs; check out [this scanner](https://anchore.io/image/dockerhub/jenkins%2Fjenkins%3Alatest) for example) remain with vulnerabilities. For enterprises with strict security standards, this makes the image unusable.

This also arises as an issue due to openjdk Docker images themselves being out of date from openjdk releases currently.

**Comment by rhelms** [comment]
You might be using the deprecated jenkins:latest image, instead of the new jenkins/jenkins:lts. I just worked out why repeated builds were not updating, and it was because I was using the old image.
The old image : https://hub.docker.com/_/jenkins/
The new image : https://hub.docker.com/r/jenkins/jenkins/

**Comment by carlossg** [comment]
we use the upstream openjdk images that are regularly upgraded

**Comment by jvz** [comment]
The upstream openjdk images themselves are regularly out of date with openjdk let alone the addon packages they include for no reason (like Mercurial).

**Comment by batmat** [comment]
@jvz This kind of issue should not be filed nor discussed here, but in the SECURITY tracker. Please follow https://jenkins.io/security/

**Comment by jvz** [comment]
Alright, can do.
