### ISSUE TITLE
The web address page can only reach the Tomcat home page , this why？

### ISSUE THREAD

**Issue by chen497147884** [jenkinsci/docker#684]
mkdir -p  /home/docker/jenkins_home/
sudo chmod 777 /home/docker/jenkins_home/
use  "sudo docker run -p 8081:8080 -p 50000:50000 --privileged=true -v /home/docker/jenkins_home:/var/jenkins_home jenkins/jenkins:lts" create container

curl http:// 127.0.0.1:8081  
show log
```
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html> 
```
----------------------------Segmenting line--------------------------------------------------
OK， I'm careless，it's container port's porblem.  

It has been solved.

Thanks . bye!

**Comment by carlossg** [comment]
no idea what you mean
