### ISSUE TITLE
The alpine branch fails to build on arm64 architecture

### ISSUE THREAD

**Issue by shawnguo2** [jenkinsci/docker#685]
Hi,

While master branch (latest) builds successfully on arm64 architecture, the alpine version/branch fails like below.

```shell
$ git branch -r
  origin/HEAD -> origin/master
  origin/alpine
  origin/master
  origin/windows
$ git checkout -b alpine origin/alpine
Branch alpine set up to track remote branch alpine from origin.
Switched to a new branch 'alpine'
$ uname -m
aarch64
$ docker build -t jenkins:alpine .
Sending build context to Docker daemon  604.2kB
Step 1/34 : FROM openjdk:8u121-jdk-alpine
 ---> 630b87931295
Step 2/34 : RUN apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils
 ---> Running in 5ada8083b5f3
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils' returned a non-zero code: 1
$ 
```

It seems that 8u121-jdk-alpine is not built for arm64 and hence causes the problem.  The master branch doesn't have this problem because Dockerfile-alpine is using 8-jdk-alpine which works fine for arm64.  Since branch 'alpine' is still being used by Docker Hub bashbrew build, I guess we should update the Dockerfile on that branch as well?  Otherwise, when people try to add arm64 architecture support, they will get the following bashbrew build error.

```shell
$ uname -m
aarch64
$ bashbrew build ./library/jenkins
Pulling openjdk:8-jdk (jenkins:2.60.3)
Building bashbrew/cache:0e39731ab6ec2860fa85ed0ae0ac8a318584fe44abe1d6e308d80c1304e93eea (jenkins:2.60.3)
Tagging jenkins:2.60.3
Tagging jenkins:latest
Pulling openjdk:8u121-jdk-alpine (jenkins:2.60.3-alpine)
Building bashbrew/cache:ae1a904f9de85a13aba68c1c568f869fae60236d923d295ff75cfc85c283f3cb (jenkins:2.60.3-alpine)
error: failed building "jenkins" (tags "2.60.3-alpine, alpine")
exit status 1
docker ["build" "-t" "bashbrew/cache:ae1a904f9de85a13aba68c1c568f869fae60236d923d295ff75cfc85c283f3cb" "--rm" "--force-rm" "-"] output:
Sending build context to Docker daemon  92.16kB
Step 1/34 : FROM openjdk:8u121-jdk-alpine
 ---> 630b87931295
Step 2/34 : RUN apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils
 ---> Running in f54ef50d4704
standard_init_linux.go:190: exec user process caused "exec format error"
Removing intermediate container f54ef50d4704
The command '/bin/sh -c apk add --no-cache git openssh-client curl unzip bash ttf-dejavu coreutils' returned a non-zero code: 1
```
The default version builds just fine, but -alpine one fails.

Thanks,
Shawn

**Comment by carlossg** [comment]
The alpine branch is no longer used, see Dockerfile-alpine in master

**Comment by carlossg** [comment]
Not sure what you are talking about, the image is already built and pushed to https://hub.docker.com/r/jenkins/jenkins/
https://github.com/jenkinsci/docker/blob/master/Jenkinsfile#L33

**Comment by shawnguo2** [comment]
Ah, I did not know image jenkins/jenkins [1], and was only looking at image jenkins [2], which is named as Official Jenkins Docker image.  I tested jenkins/jenkins and found that all latest and -silm, -alpine variants can be pulled on arm64 architecture.  That's great.  However, I would like to bring the official jenkins image up to date and see the same level support as jenkins/jenkins image.  That's why I'm looking at library/jenkins file in official-images [3] to convert it to RFC 2822 based format, and add arm64 architecture.  Does it make sense?  Thanks.

[1] https://hub.docker.com/r/jenkins/jenkins/
[2] https://hub.docker.com/_/jenkins/
[3] https://github.com/docker-library/official-images/blob/master/library/jenkins

**Comment by shawnguo2** [comment]
Here is the change I made on official jenkins manifest file [1], and it works for latest image but doesn't for alpine variant because instead of using 'alpine' branch, Dockerfile-alpine on master branch should be used.  The problem right now is that I have no way to specify a Dockerfile with custom name in this format.  Instead, I can only specify a subdirectory for different image variants' Dockerfile which needs to be named as "Dockerfile" exactly.  That's why I was proposing to create subdirectory for alpine and slim image Dockfile.  Hope I made myself clear this time.  Thanks.

[1] https://github.com/docker-library/official-images/blob/master/library/jenkins


```shell
diff --git a/library/jenkins b/library/jenkins
index 0dbe2dd60dc4..79b6f559fca2 100644
--- a/library/jenkins
+++ b/library/jenkins
@@ -1,9 +1,13 @@
-# maintainer: Nicolas De Loof <nicolas.deloof@gmail.com> (@ndeloof)
-# maintainer: Michael Neale <mneale@cloudbees.com> (@michaelneale)
-# maintainer: Carlos Sanchez <csanchez@cloudbees.com> (@carlossg)
+Maintainers: Nicolas De Loof <nicolas.deloof@gmail.com> (@ndeloof),
+             Michael Neale <mneale@cloudbees.com> (@michaelneale),
+             Carlos Sanchez <csanchez@cloudbees.com> (@carlossg)
+GitRepo: https://github.com/jenkinsci/docker.git
 
-latest: git://github.com/jenkinsci/jenkins-ci.org-docker@587b2856cd225bb152c4abeeaaa24934c75aa460
-2.60.3: git://github.com/jenkinsci/jenkins-ci.org-docker@587b2856cd225bb152c4abeeaaa24934c75aa460
+Tags: 2.60.3, latest
+Architectures: amd64, arm64v8
+GitCommit: 587b2856cd225bb152c4abeeaaa24934c75aa460
 
-alpine: git://github.com/jenkinsci/jenkins-ci.org-docker@c2d6f2122fa03c437e139a317b7fe5b9547fe49e
-2.60.3-alpine: git://github.com/jenkinsci/jenkins-ci.org-docker@c2d6f2122fa03c437e139a317b7fe5b9547fe49e
+Tags: 2.60.3-alpine, alpine
+Architectures: amd64, arm64v8
+GitFetch: refs/heads/alpine
+GitCommit: c2d6f2122fa03c437e139a317b7fe5b9547fe49e
```

**Comment by shawnguo2** [comment]
@carlossg Oops, dumb me.  Thanks much for waking me up :)  We are fine then.

**Comment by jmreicha** [comment]
I just tried to run the lts and alpine-lts images on my Rock64 and get errors.

```
 docker run -it --rm jenkins/jenkins:lts-alpine
standard_init_linux.go:190: exec user process caused "exec format error"
```

Am I just missing something?
