### ISSUE TITLE
I'm using Jenkins inside the docker so its get Xcode path error

### ISSUE THREAD

**Issue by Aravindios** [jenkinsci/docker#691]
when I'm build my project its falls error.

FATAL: Cannot find xcodebuild with the configured path /usr/bin/xcodebuild.

FATAL: Cannot find xcodebuild with the configured path /usr/bin/xcodebuild.
Build step 'Xcode' marked build as failure
Finished: FAILURE

**Comment by banwang811** [comment]
Hello, I met the same problem. Have you solved it?

**Comment by batmat** [comment]
This repository is about issues with the Jenkins Docker image itself, and not a support forum.
Please rather use the Users ML for such issues. Or please clarify in what the issue is specifically related to using Jenkins Docker image.

Thank you
