### ISSUE TITLE
[JENKINS-57528] - install-plugins.sh does not handle implied dependencies.

### ISSUE THREAD

**Issue by casz** [jenkinsci/docker#698]
# Issues and Contributing

### Actual result
Using newer cores that have part of it moved to plugins and is now implied dependencies in other plugins is causing to have bad Jenkins installation using JCasC.
https://github.com/jenkinsci/configuration-as-code-plugin/issues/294

Installing [`ssh-slaves`](https://plugins.jenkins.io/ssh-slaves) implies the following plugins
* bouncycastle API v.2.16.0
* Command Agent Launcher v.1.0
* JDK Tool v.1.0

There are plenty of plugins that have this issue.

Yet when you use `install-plugins.sh` you have to ensure that these get installed.

### Expected outcome
That implied dependencies should be installed as well without the need to mention them.

**Comment by ndeloof** [comment]
this would at least require the implied info to be exposed by update-center
but from my PoV this demonstrate this script is going way to far from it's initial intent. We just need jenkins internal PluginManager to be exposed to CLI for the same purpose.

**Comment by casz** [comment]
I concur with @ndeloof 👍

**Comment by casz** [comment]
@jcrben and yet you would not want that.
Since that requires that you build against a higher version of the Jenkins core, which would exclude a bunch of users, and not all plugins are ready for that.

**Comment by jcrben** [comment]
@casz OK - is it expected that plugin authors will begin converting these implied plugins to required plugins at some point? is this tied to some sort of milestone?

**Comment by oleg-nenashev** [comment]
I could fix it in install-plugins, but I need a pre-confirmation from @ndeloof that he will accept such approach as a temporary measure. Disclaimer: itmay stay forever, I do not commit to work on the core patch anytime soon.

So far I am blocked in #668, which is also about install-plugins logic

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/jenkins/pull/4000 will likely address this issue

**Comment by oleg-nenashev** [comment]
@casz would itbe possible to create a mirror issue in Jenkins JIRA?

**Comment by casz** [comment]
could I not just link https://issues.jenkins-ci.org/browse/JENKINS-55582 with this issue?

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-57528 was created for it

**Comment by jglick** [comment]
I think this could be closed now.

**Comment by oleg-nenashev** [comment]
agreed

**Comment by oleg-nenashev** [comment]
Fixed in Jenkins 2.178
