### ISSUE TITLE
Request: Attach version number to LTS tag

### ISSUE THREAD

**Issue by ChrisWeissNike** [jenkinsci/docker#700]
Since it appears that LTS is a moving tag, it's difficult to know what will actually be deployed if the customer pulls jenkins/jenkins:lts. We've had bad experiences with breaking changes when the LTS pin is moved.

Other software projects solve this by pre-pending the version number to the LTS designation (see Ubuntu).

It would be beneficial if the Jenkins containers followed the same policy (at least adding a duplicate tag that specifies the release).

**Comment by oleg-nenashev** [comment]
@ChrisWeissNike what's wrong with `jenkins/jenkins:2.121.1` or other similar tags? They reflect LTS releases

**Comment by ChrisWeissNike** [comment]
How would I see that 2.121.1 is an LTS? I could not find any place that linked actual version with the LTS docker tag (would like to see historical LTS versions as well).

**Comment by oleg-nenashev** [comment]
All 3-digit releases are LTS. See https://jenkins.io/changelog-stable/ for changelogs

**Comment by ChrisWeissNike** [comment]
Ah. We did not know that - Thanks!
