### ISSUE TITLE
Git Pull not working with file URL

### ISSUE THREAD

**Issue by doantranthanh** [jenkinsci/docker#704]
Hi all,

I am using Jenkins docker image. I want to run against the file folder such as

node {
    def Commit = null
    cleanWs()
    stage('Pull code'){
       Commit = git branch: "${Branch}", credentialsId: 'JenkinsStash', url: 'file:////C://projects//stash//kendo//web'
    }
}
But it is not working. Any helps?

Thanks

**Comment by carlossg** [comment]
please ask question in the jenkins-user mailing list and provide output and details on what is not working
