### ISSUE TITLE
docker: curl: (22) The requested URL returned error: 404 Not Found for certain plugins

### ISSUE THREAD

**Issue by jcrben** [jenkinsci/docker#707]
UPDATE: this is no longer happening for now, but still interested in learning more

I noticed today that my build of the docker container stopped working due to plugins not being accessible

Looks like the same issue as https://github.com/jenkinsci/docker/issues/470 and maybe a couple others? Don't see anything open tho. https://github.com/jenkinsci/docker/commit/dc6193987dbe19b5c812246d01886faaf6ebb3bd says "They retry will likely get another mirror" but maybe there's a way to guarantee that?

If I remove `pipeline-model-definition:1.3.1` and `configuration-as-code:experimental` it works. Is downtime on the plugins download site tracked anywhere? Not sure about the best place for these types of issues to be tracked. Also it's not entirely clear which URL precisely is failing.

I poked around at https://updates.jenkins.io/download/plugins/ to see if I could find a missing plugin, but both workflow-steps-api (https://updates.jenkins.io/download/plugins/workflow-step-api/) and structs seem to be available.

### Docker commands that you execute
Reproduction available at https://gitlab.com/jcrben-repro/jenkins-jcasc-docker - run `./builder_jenkins.sh` as mentioned in the readme

Note: the repro repo uses 2.128 but I also tried the latest tag.

### Actual result
Stalls out with `docker: curl: (22) The requested URL returned error: 404 Not Found` for certain plugins

### Expected outcome
Docker container built successfully

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No - specifically want to use the docker version.

### Output of `docker version`
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
### Other relevant information
![image](https://user-images.githubusercontent.com/5614134/42592671-0f906da2-84ff-11e8-87bf-3d78f81464cd.png)

**Comment by carlossg** [comment]
There are some temporary issues, something for the Jenkins INFRA team to look at

**Comment by jcrben** [comment]
Encountering this again now with `jenkins/jenkins:2.133`:
![image](https://user-images.githubusercontent.com/5614134/42901495-8c31c05a-8a80-11e8-8833-fb3b014bda77.png)

Seems like there's a bug here where it's not trying a different mirror.

**Comment by alexnovak** [comment]
Just experienced this myself -- were you able to find a workaround @jcrben ?

**Comment by rhuanbarreto** [comment]
This is still ocurring. I have an automated build to create a jenkins blueocean image from the following Dockerfile:

```
FROM jenkins/jenkins:alpine

USER root

ARG user=root
ARG group=root

RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    apk -U add docker py-pip

RUN pip install docker-compose

RUN /usr/local/bin/install-plugins.sh blueocean

RUN rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*

VOLUME /var/run/docker.sock
```

On the build I get lot's of 404 not found on plugins lke sse-gateway workflow-step-api that are internal dependencies of blueocean.

**Comment by batmat** [comment]
Hello, though this issue can occur from time to time, this is AFAICT not an issue that is specific to this repository. As @caerl

**Comment by jcrben** [comment]
So I guess this isn't tracked anywhere? Do you mind if I open an INFRA issue, or would that just be a distraction or a duplicate?

**Comment by josephaxisa** [comment]
I am having this exact same issue and not sure how to circumvent it. Can't find any other tickets related to this either.
