### ISSUE TITLE
docker pull produces `unauthorized: incorrect username or password.` error

### ISSUE THREAD

**Issue by udev** [jenkinsci/docker#708]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute

```
Test-Machines-iMac:~ iMacTest$ docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
Unable to find image 'jenkins/jenkins:lts' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/jenkins/jenkins/manifests/lts: unauthorized: incorrect username or password.
See 'docker run --help'.
Test-Machines-iMac:~ iMacTest$ 
```

### Actual result

Received an unauthorized error.

### Expected outcome

The image is downloaded.

### Have you tried a non-dockerized Jenkins and get the expected outcome?

N/A

### Output of `docker version`

Docker version 18.03.1-ce, build 9ee9f40

### Other relevant information

This is on a fresh install of OSX Sierra 10.12.6 (16G1510)
The Artifactory docker image downloaded and installed without error.

**Comment by carlossg** [comment]
you must have a wrong username in your docker config. It works fine here

**Comment by udev** [comment]
@carlossg As it would happen an email address rather than the proper hub.docker.com username was used to login to the daemon which the daemon happily accepts. After logging in with the correct username and running `docker login` everything appears to be in order.

Thanks!
