### ISSUE TITLE
jenkins-support fails to copy plugins if plugin REF folder is changed

### ISSUE THREAD

**Issue by darmbrust** [jenkinsci/docker#709]
I was in the process of putting together my own docker install script, based heavily on the reference one from this project.

Noticed this minor issue that can cause pre-installed plugins to fail to be copied to the right place if you change the input path of the plugins.

install-plugins.sh uses:
REF_DIR=${REF:-/usr/share/jenkins/ref/plugins}

jenkins-support does this:

copy_reference_file() {
    f="${1%/}"
    b="${f%.override}"
    rel="${b:23}"

which takes the characters after position 23 of the path from the plugin - if you have changed that to anything other than something with the length of "/usr/share/jenkins/ref/", your plugins will silently go into the wrong folder, and be ignored.

Would be nice if the installed-plugin script had a better mechanism for finding the right place to place the plugins

**Comment by MRamonLeon** [comment]
Addressed on PR https://github.com/jenkinsci/docker/pull/866

**Comment by oleg-nenashev** [comment]
It should be released in the next weekly and LTS, thanks to @slide for the fix!
Whomever wants to try it out, I have deployed a test image to `jenkins4eval/jenkins:2.176.2-jdk8-a2d2c853f8a44895c940827159f6957ba55cb193`
