### ISSUE TITLE
jenkins 2.121.1-alpine to 2.121.2-alpine updates alpine to 3.8

### ISSUE THREAD

**Issue by dirien** [jenkinsci/docker#711]
hi,

with the minor update of Jenkins 2.121.1-alpine to 2.121.2-alpine the whole underlying alpine is updated to version 2.8. [See commit here from 12 days ago](https://github.com/docker-library/openjdk/commit/1778c73b834d04d5b5c61baee4cce8c127031f9c#diff-fe1bcb93483d1e28f57338fb56f20cef) for the main reason. You in the Dockerfile just a plain `FROM openjdk:8-jdk-alpine`. It would be better to fix the From to a specific fixed version to eliminate any changes to the master/parent image.

This brings the problem, that the latest git version 2.18 is installed on the Jenkins. Now i have issues regarding this new git version.

Why i write a issue here, is that it is not okay to do a major version update on a minor jenkins update. It is not even written on the changelog site https://jenkins.io/changelog-stable/

Please revert the FROM back to the apline version 3.7, if possible.

**Comment by oleg-nenashev** [comment]
@dirien. So far we do not track packaging changes in the main changelog. Packagings are expected to have their own changelog if needed. OTOH I understand the frustration, UX is bad. CC @daniel-beck @olivedgondza

I also agree that Docker packaging should have LTS branch to avoid issues. But so far the latest version is used to package LTS afaik

Regardinv pinning the version and reverting the change, please describe your issue with Git for starters

**Comment by oleg-nenashev** [comment]
I also believe that @MarkEWaite fixed the compat issue in https://issues.jenkins-ci.org/browse/JENKINS-50573

**Comment by daniel-beck** [comment]
Changes based in the actual packaging repository are included if we're made aware of them. Our Docker distribution is the lawless wild west. As long as nobody bothers to file corresponding changelog PRs, these changes won't show up, and I will not start monitoring something I don't understand well enough without support by those implementing things.

**Comment by dirien** [comment]
ha all,

thanks for the feedback.

I pinned the issue down to the libcurl 7.61.0 not being able to handle NTLM (we have TFS Server) anymore. The version before can work fine with it.

So what i did, is i build the openjdk/8-jdk-alpine image with alpine 3.7 as parent and us your Dockerfile-alpine build with my custom parent.

i will file a issue with the friends from curl to ask them about the libcurl issue with NTLM.

**Comment by MarkEWaite** [comment]
Git client plugin 2.7.3 includes a fix for OpenSSH 7.7 as bundled with Alpine 3.8.  OpenSSH 7.7 intentionally changed command line argument handling.  The git client plugin relied on the old behavior.  See [JENKINS-50573](https://issues.jenkins-ci.org/browse/JENKINS-50573) for more details.

**Comment by dirien** [comment]
we do not use ssh here, we use http for checkout. I updated every plugin but no avail... still the error. Only downgrading the libcurl helped.

today we encountered the problem also on a client machine with git 2.18 installed. The colleague needed to downgrade the libcurl (aka curl) and everything worked fine event with the latest git client.

**Comment by MarkEWaite** [comment]
If you don't use ssh, then the ssh changes in git client plugin 2.7.2 and 2.7.3 won't help.

Command line git uses curl for its https downloads (as far as I know).  I believe that means you're correct that the problem is with curl and/or libcurl.

I added the reference to JENKINS-50573 in case web searches arrived here that were using ssh.  Sorry to "pirate" this issue with a different issue.

**Comment by dirien** [comment]
i am closing the issue now, as i just wanted to raise awareness that using a FROM from a different source could lead to problems.

-> A solution would be, when you guys use your own jdk image so you are not dependent to others.
