### ISSUE TITLE
jenkins:lts is broken for pipelines

### ISSUE THREAD

**Issue by nitinsurana** [jenkinsci/docker#723]
### Docker commands that you execute
 - Create a docker image using jenkins:jenkins/lts and install workflow-aggregator plugin (pipeline plugins)
 - Create a pipeline project with the hello-world pipeline script
 - Notice, jenkins shows error saying `Missing Property node` 
 - Try with other sample scripts using pipeline and jenkins throws error saying `Missing Property pipeline`

### Actual result
Throws error

### Expected outcome
Should just run fine. Follow the exact same procedure (listed above) with `jenkins/jenkins` image and it works as expected.

**Comment by batmat** [comment]
Hello, can you please follow the issue template?

`### Have you tried a non-dockerized Jenkins and get the expected outcome?`

What is the answer to the previous question? I suspect your issue may not be specific issue to this Docker image. 
Many of us contribute here on our free time, so please file complete reports. Please help us all save time (yours and ours) by answering all questions. 

Please reopen once you can complete the missing parts.

Thanks
