### ISSUE TITLE
java: No such file or directory

### ISSUE THREAD

**Issue by lwx2615** [jenkinsci/docker#724]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
./java -version
### Actual result
./java: No such file or directory
### Expected outcome
openjdk version "1.8.0_171"
### Have you tried a non-dockerized Jenkins and get the expected outcome?
yes
### Output of `docker version`
Docker version 1.13.1
### Other relevant information
When I use the java from the docker it works.But I use the java from jenkins auto installed ,it can not find the java,and the java is realy in it.

**Comment by batmat** [comment]
The `./` prefix in`./java -version` means you are asking for `java` to be in the current directory. I do not think you are running this command outside of Jenkins, but `java -version`.

**Comment by lwx2615** [comment]
/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/maven3.5/bin/mvn: exec: line 199: /var/jenkins_home/tools/hudson.model.JDK/jdk8.0/bin/java: not found，this is the real jenkins error。I just go to the java bin dir，and run java handler ，it also cannot found the java

**Comment by braveswang** [comment]
i have the same issue

**Comment by Michael-Downton** [comment]
This issue has occured for me also today.

logged:
/usr/local/bin/jenkins.sh: line 36: exec: java: not found

docker image
REPOSITORY                              TAG                 IMAGE ID            CREATED              SIZE
jenkins/jenkins                         lts                 b137a5753eb1        5 weeks ago          567MB

**Comment by plutonji** [comment]
I have this issue, too.

Docker Image:
jenkinsci/blueocean:1.19.0

jdk8u65 is downloaded to `/var/jenkins_home/tools/hudson.model.JDK/jdk8u65/` from Global Tools Configuration.

The container is run as root.

**Comment by wardiablo** [comment]
Hi there,
I just met this issue when build docker image in jenkins. The java is copied into docker by Dockerfile and set JAVA_HOME in PATH. But when run docker, entrypoint reports "no such file or directory" for jave executable file.
Docker version 18.09.8-ce
Jenkins 2.222.4
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Comment by lssilva** [comment]
Same issue here

**Comment by slide** [comment]
> Hi there,
> I just met this issue when build docker image in jenkins. The java is copied into docker by Dockerfile and set JAVA_HOME in PATH. But when run docker, entrypoint reports "no such file or directory" for jave executable file.
> Docker version 18.09.8-ce
> Jenkins 2.222.4
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
> OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

If you are talking about building an image in Jenkins, this is the wrong place to file issues. This is specifically about the Jenkins/Jenkins image on dockerhub.

**Comment by slide** [comment]
> Same issue here

Just saying "same issue" is not helpful. It is still not clear what the issue really is. Without providing more information, nothing will get solved.

**Comment by lssilva** [comment]
Saying "Same issue here" is helpful. 

It means I could reproduce what the first poster reported and saying that adds a bit of validity to his claim. 
Sometimes some bugs cannot be reproduced and one could blame on the user's env. 
But if many people have the same issue it actually means something, I agree that on every report a user could try to add more information but the time availability for contribution differs.

Anyway I switched to 
jenkins/jenkins:jdk11 and it now works


> > Same issue here
> 
> Just saying "same issue" is not helpful. It is still not clear what the issue really is. Without providing more information, nothing will get solved.

**Comment by mluckenbill** [comment]
This is still a valid issue and I too have it when running jenkins via docker and using adoptopenjdk. I agree with Issilva on the comment.

**Comment by slide** [comment]
The original ticket is talking about java installation via the automatic installer. Is that what you are using as well? We still don't have clear reproduction information for this.

**Comment by mluckenbill** [comment]
Yes, that is correct I'm using the Jenkins 2.235.3 

What I'm doing is I have tried the following: 
- Using the latest docker image for Jenkins
- Following the instructions and using Docker Volume mounted to the jenkins_home
- Then I use the adoptopenjdk auto installer to pull down JDK14 
- I verify via attaching to the docker instance and navigate to the tools folder and I can see that the jdk was downloaded correctly. 
- I then go back to jenkins and update the JAVA_HOME

I have a JAVA spring boot project that is basically just a hello world project.

In my build script I use "sh ./mvn clean package 

After, which the project is cloned via ssh and then pulls down the dependencies correctly. However, I receive the error at the end of the build process.

**Comment by slide** [comment]
Just a question, why are you updating JAVA_HOME? With the auto installer, you would name the tool installation as JDK14 or something similar and then use that in your pipeline using the `tool` step. Since you said you have a basic example, can you share the pipeline and so forth that you are using?

**Comment by timja** [comment]
No response in a long time, this issue looks like it should be on the mailing list or https://community.jenkins.io and not here

**Comment by truestbyheart** [comment]
Solved this as follow 
- got into the image bash shell
   `docker exec -it <mycontainer> bash`
- locate where java is installed 
  `which java`
- use the location in your setup in my case it was setting up a Jenkins agent 

Hope this is useful

**Comment by jezovuk** [comment]
If anyone stumbles upon this one (as I did today): for me, the problem was in using Alpine-based Jenkins Docker image in combination with glibc-based JDK binary. Once I've switched to alpine (musl) JDK build (in my case Adoptium / Eclipse Temurin) the problem was gone :smiley:
