### ISSUE TITLE
Can't execute scripts without a bind mount and running Jenkins as root

### ISSUE THREAD

**Issue by juliusecker** [jenkinsci/docker#725]
I was trying to get Jenkins going against some code in GitHub. The image booted, everything was going okay until I tried to get a pipeline going with a private GitHub repo. No matter what I did the builds would end in error trying to apply my GitHub creds during the clone step. 

I also tried running arbitrary bash commands with the `bash` pipeline command in a plain pipeline project. Also no joy. Similar errors though.

### Docker commands that you execute
```bash
# create a volume
docker volume create jenkins_home
# I also tried setting options using
docker volume create --opt type=none --opt device=/dev/mapper/VGData-LVData --opt o=rw,exec,noatime,seclabel,data=ordered jenkins_home

# create Jenkins instance with volume
docker run -d --name jenkins -p 18080:8080 -p 50000:50000 --mount type=volume,source=jenkins_home,destination=/var/jenkins_home jenkins/jenkins:lts

# or, create Jenkins instance without volume the problem still occurs!
docker run -d --name jenkins -p 18080:8080 -p 50000:50000 jenkins/jenkins:lts

# as a last ditch effort, I tried jumping into the container as root and running:
mount -o exec /var/jenkins_home
```
### Expected outcome
A filesystem (specifically /var/jenkins_home) where Jenkins can execute scripts since its core to how Jenkins operates

### Actual Outcome
```
# The logs are full of lines like this:
sh: 1: /var/jenkins_home/workspace/my_proj@tmp/durable-9e1b72ac/script.sh: Permission denied
```

### Output of `docker version`
Docker version 18.06.0-ce, build 0ffa825

### Other relevant information
Digging into this, when I run `mount | grep /var` I see 
```
/dev/mapper/VGData-LVData on /var/jenkins_home type ext4 (rw,noexec,noatime,seclabel,data=ordered)
```

As far as I can tell, the 'noexec' option is preventing Jenkins from executing anything out of /var/jenkins_home

I've tried a bunch of different things to get this to work.

Is there a documented way of getting around noexec? If not, should the docs be updated so others don't sink as much time into this as I did?

### Hacktastic Workaround (use a bind mount and run Jenkins as root)
```
docker run -d --name jenkins -v /some/host/path/jenkins_home:/var/jenkins_home -u root -p 18080:8080 -p 50000:50000 jenkins/jenkins:lts
```

This works because when you're bind mounting you get the opts from the host system, not the defaults that docker wants to apply. You need to run as root to satisfy the ownership issues associated with bind mounts. You could also do as the docs suggest and make sure uid 1000 owns your jenkins_home on the host, but running as root is more simple.

**Comment by batmat** [comment]
Looks very fishy indeed. Would you be able to provide reproduction steps, also about the pipeline code you ran? (which protocol did you use for git cloning, for instance, etc.). Thanks!

**Comment by juliusecker** [comment]
Both using Git w/ ssh and GitHub using Personal Access Tokens failed. Each time it was when the plugins tried to apply the secrets using those one-time scripts.

The pipeline code I ran was, (with all the keys in the right place, and the command validated as working when I shell into the instance manually):
```
node {
  sh '''#!/bin/bash
    git clone git@github.com:my_org/my_private_repo.git
  '''
}
```

It failed when Jenkins tried to generate a one off script to execute.

I should also mention that I tried this on two separate boxes, my workstation which is Ubuntu 16.04 and on a server running CentOS 7

**Comment by batmat** [comment]
Did you start fresh, with up to date/latest plugins? Found https://issues.jenkins-ci.org/browse/JENKINS-37069 that seems loosely related, maybe some things there could help figure out what is going wrong here?

Can you possibly record a screencast to demo what you exactly do, the versions in use of all or most components? I think it could help understanding the use case. I will try doing the same as you once I'm sure what you did. We use Jenkins in containers all the time, so I'm trying to understand what could be the difference here.

**Comment by juliusecker** [comment]
After further investigation, the noexec I was seeing on the mount was not due to this image. I was able to rectify the issue on the boxes I was testing this on. Apparently the filesystem docker was running out of was mounted with noexec, which carried through to the volumes. I hadn't noticed it since Jenkins is the first service that tried to exec files directly.
