### ISSUE TITLE
Init with suggested plugins failed

### ISSUE THREAD

**Issue by hsowan** [jenkinsci/docker#732]
Execute this command below do not have any problem, start jenkins service successfully:
`docker run --detach --name jenkins -p 8080:8080 -p 50000:50000 -v /srv/jenkins/home:/var/jenkins_home jenkins`

But when I init jenkins with suggested plugins, there are many plugins that failed to install:
+ ~~Workspace Cleanup~~
+ ~~Pipeline~~
+ ~~Pipeline: GitHub Groovy Libraries~~
+ ~~Pipeline: Stage View~~
+ ~~Subversion~~
+ ~~SSH Slaves~~

Why ???

**Comment by carlossg** [comment]
please ask questions in jenkins-user mailing list and add details of what you are doing and what's the output
