### ISSUE TITLE
Label needs clarification on Using Docker with Pipeline docs

### ISSUE THREAD

**Issue by dragonpiper** [jenkinsci/docker#737]
The Jenkins docs does not properly clarify how to setup labels , where they are located or what they really are.

On the using docker with pipeline page

[https://jenkins.io/doc/book/pipeline/docker/
](url)

 It states 

> Pipeline provides a global option in the Manage Jenkins page, and on the Folder level, for specifying which agents (by Label) to use for running Docker-based 

**Issue 1**
The options to setup labels are not on this page and Folder level to a new user doesn't clarify this. There are 18 different places you can go from the manage page. The docs should intruct the user to go to Manage Jenkins > Configure System and ideally provide a picture of the labels section.

**Issue 2**

The only references to label on that page are to Docker Label. While thats is important, the pipeline will not run at all if Agent labels aren't set up. To make this worse there is a picture of the docker label section on the configure page and the error Jenkins will give when you run your pipeline is docker label does not exist leading to think that you didn't set up Docker Label properly.

**Comment by timja** [comment]
This issue belongs in jenkins-infra/jenkins.io
