### ISSUE TITLE
Permission denied - /var/jenkins_home/copy_reference_file.log - New case

### ISSUE THREAD

**Issue by larsskj** [jenkinsci/docker#739]
# Issues and Contributing

Case #177 is closed - but I have the same issue.

I'm trying to run the Docker container with another Jenkins user/group id. I want to migrate - slowly - from a traditional Jenkins setup to a Docker based setup, and because of this I want to keep the existing uid/gid for the Jenkins user. A uid/gid of 1000 for the Jenkins user is a bad choice, anyway, as this ID is often used for other purposes on host systems.

And yes, I want to bind mount jenkins_home. Docker volumes might be a good idea in a small scale setup, but you cannot move a Docker volume from one host to another, so using Docker volumes means tying the Jenkins Docker container to a single host.

(I know I can make a backup of the Docker volume, create a tarball, move that tarball to another machine, restore it into another volume and make Jenkins run again on the new host - but that's kind of out-of-scope. I want a quick failover.)

### Docker commands that you execute

Before trying to run the stock Jenkins image, I execute

docker container prune -f
docker volume prune -f

to make sure not to have any old runs left.

I then execute

docker run -it -u 400:400 jenkins/jenkins

### Actual result

touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?

### Expected outcome

A running container.

### Have you tried a non-dockerized Jenkins and get the expected outcome?

Oh, yes. :-)

**Comment by carlossg** [comment]
Read the solutions in #177 
Opening duplicate issues just wastes everybody's time
