### ISSUE TITLE
JENKINS_OPTS is ignored

### ISSUE THREAD

**Issue by IceBoosteR** [jenkinsci/docker#745]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

Hello,
after several hours of trying I guess there is an error in the configuration of the latest jenkins-docker image. JENKINS_OPTS="--prefix=/jenkins" is simply ignored. To make it short I have tried several proxies and several configurations.

My docker-compose fiel looks like this:
 `version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: jenkins-proxy
    networks:
      - jenkins_network
    ports:
      - 6004:443
    volumes:
      - /docker/Jenkins/proxy/conf.d:/etc/nginx/conf.d:rw
      - /docker/Jenkins/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /docker/Jenkins/proxy/html:/usr/share/nginx/html:rw
      - /docker/Zertifikate:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    networks:
      - jenkins_network
    depends_on:
      - proxy
    volumes:
      - /docker/Jenkins/jenkins:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=192.168.178.104
      - VIRTUAL_PORT=8080
      - JENKINS_OPTS="--prefix=/jenkins"
    restart: unless-stopped

networks:
  jenkins_network:
`

The proxy, in this case nginx is resolving 8080 as the correct port, but the /jenkins path is ignored. I guess that this is not a proxy issue as this is created dynamicly. Also I have seen setups where this is working as expected, so I do assume that this varialbe is not exposed correctly.

If I am wrong please correct me, and please show me a direction where I have to look.
As I have spended so much hours I came to the conclusion that it might be a bug.

Thanks,
Ice

**Comment by carlossg** [comment]
that works, the error must be in your nginx config. Have you tried `docker run -p 8080:8080 -e JENKINS_OPTS="--prefix=/jenkins" jenkins/jenkins` and accessing `localhost:8080/jenkins` ?

**Comment by IceBoosteR** [comment]
The issue is still present. I also assume it might be the nginx. Nevertheless I have worked around this by using the keystore and access Jenkins directly without a proxy. Ticket can be closed.
Cheers
