### ISSUE TITLE
Mounting External Volumes

### ISSUE THREAD

**Issue by robwithhair** [jenkinsci/docker#75]
Is there not a way you could mount external volumes on the machine and automatically chown 1000 them on startup?  Currently on Google Container Engine it is very difficult to get this running due to finding the external volume and trying to get it to mount.  Requires root access to the host in order to chown the external hard drive before starting jenkins.

**Comment by ndeloof** [comment]
I don't get your question. I deployed this image many times on GCE, just run with a fresh new volume for workspace, then configure jenkins from UI.

**Comment by robwithhair** [comment]
@ndeloof, is this the official jenkins docker repo found at https://registry.hub.docker.com/_/jenkins/ ?  I am experimenting with using this on Kubernetes on Google Container Engine.  When I start it on Container Engine it doesn't start when mounted with a volume either from the local machine or an external disk as the jenkins home without first `chmod  -R 1000  jenkins_home/` the folder.

**Comment by ndeloof** [comment]
yes it is.
You indeed need to have the host user owning the volume to match the container userID. This is a docker restriction, nothing we can do here. Read more on https://groups.google.com/forum/#!msg/docker-user/cVov44ZFg_c/DGqHU4TL8RkJ

**Comment by robwithhair** [comment]
Does jenkins have to be run under the jenkins user? Would running it under root user solve this issue? I don't know enough about jenkins to know if that would be safe though, I doubt it.

**Comment by ndeloof** [comment]
Running as _root_ is a bad practice, this introduces huge security risks for the host running docker container. I don't think this would be validated by docker team so this commit would be rejected for official docker image.
