### ISSUE TITLE
Windows container image pipline builds' show error docker :permission denied

### ISSUE THREAD

**Issue by jingliancui** [jenkinsci/docker#755]
win 10 profession newest version
Docker version 18.06.1-ce, build e68fc7a
docker pull jenkins/Jenkins:lts

cmd command windows:

docker run -d -u root -v /bin/docker:/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v D:\DockerAbouts\jenkins_home:/var/jenkins_home -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

Then use the Team foundation server plugin connect to get the project files.
And in the Jenkinsfile have this:    docker pull xxx

console ouput :

docker :permission denied

**Comment by carlossg** [comment]
you have to configure your docker
ie. https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/

**Comment by jingliancui** [comment]
@carlossg 
Hi sudo usermod -a -G docker $USER is no use in docker whicn on windows.

**Comment by carlossg** [comment]
you have to find how to do it for windows in Docker docs
