### ISSUE TITLE
Github PR comment trigger build ignored

### ISSUE THREAD

**Issue by JiYou** [jenkinsci/docker#757]
I've an issue is about comment trigger build.

# Situation

Once I setup a build job, when it build process meet some error. Maybe disk is full, network issue etc.
The build would failed.

Then I want to use PR comment such as "test this please" to trigger the build job manually, but seems this trigger would be ignored by "PR not changed" etc.

```
Running GitHub Pull Request trigger check for Nov 14, 2018 7:39:44 AM on xxxxxxx
GitHub rate limit before check: GHRateLimit{remaining=1000000, limit=1000000, resetDate=Wed Nov 14 08:39:44 UTC 2018}
PR [#77 [api-server] role create delete list update service test case add] not changed
Finished GitHub Pull Request trigger check for xxxxxxxx at Nov 14, 2018 7:39:44 AM. Duration: 190ms
```

# Want to Get

I want to know is:

```
Is there any option to ignore this GitHub Pull Request trigger check
to make sure comment will trigger the build instead of ignored?
```

Thanks

**Comment by carlossg** [comment]
You should ask questions in jenkins-user mailing list, but AFAIK comments won't trigger builds
