### ISSUE TITLE
Documentation on port mapping under boot2docker needs extra step

### ISSUE THREAD

**Issue by rfagen** [jenkinsci/docker#76]
The documentation is pretty clear about how to get the instance up and running, but if you're using boot2docker on OS X, then you need to execute:

    boot2docker ip

in order to get the host machine IP address of boot2docker, then, you would use that IP address in the browser instead of 0.0.0.0 or localhost to access the UI.

**Comment by carlossg** [comment]
I think that's more a Docker general question than any image

**Comment by carlossg** [comment]
closing as this is a docker question, not the image
