### ISSUE TITLE
Set Proxy details page not visible after opening the jenkins portal for the first time after installation  

### ISSUE THREAD

**Issue by shaik447** [jenkinsci/docker#764]
# Issues and Contributing

Proxy details page is not visible during portal startup configuration due to which suggested plugins installation is failing

### Docker commands that you execute
docker run -d -p 8080:8080 --name myjenkins jenkins/jenkins:lts 

### Actual result
The docker instance was created but the suggested plugins installation failed because the proxy setup page is not displayed before the plugins installation step

### Expected outcome
I tried the previous jenkins image version 2.60.3 . This container displays the proxy setup page before the plugins installation if there is a connection timeout

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No

**Comment by batmat** [comment]
Closing as duplicate in favor of https://github.com/jenkinsci/docker/issues/681. Let's try together to keep data in one place :-). Thanks
