### ISSUE TITLE
whenever I publish  a project that contains the step to execute shell,It will occur that "command not found",and my shell scripts can be executed successfully on the terminal.How to solve this problem?

### ISSUE THREAD

**Issue by wangold5** [jenkinsci/docker#768]
whenever I publish  a project that contains the step to execute shell,It will occur that "command not found",and my shell scripts can be executed successfully on the terminal.How to solve this problem?

**Comment by wangold5** [comment]
I've tried "#!/bin/bash -xeli",it doesnt work

**Comment by carlossg** [comment]
please ask questions in jenkins-user mailing list
