### ISSUE TITLE
install-plugins.sh fails if input file is empty

### ISSUE THREAD

**Issue by mirzmaster** [jenkinsci/docker#769]
https://github.com/jenkinsci/docker/blob/0d8a962574d4b3ea8551705cb8c335ca351bd385/install-plugins.sh#L262

Plugin installation fails if invoked with an empty file:
```bash
install-plugins.sh < plugins.txt # plugins.txt has no contents
```

This condition is not caught in `install-plugins.sh`, causing failure at the attempt to clear locks when none exist (line 262 of `install-plugins.sh`).

**Comment by batmat** [comment]
Err, I belive this is actually a feature, not a bug: passing an empty plugins.txt certainly looks like an oversight in general, so failing in that case seems like the right default behavior, or I'm missing your point.

**Comment by slide** [comment]
I can only replicate this issue on the CentOS based image, is that what you are using? The Debian/Alpine based images don't show this issue.

**Comment by timja** [comment]
The script is deprecated for removal
