### ISSUE TITLE
Can't override curl options in install-plugins.sh

### ISSUE THREAD

**Issue by nikolay-martynov** [jenkinsci/docker#784]
Fix for #636 has introduced overridable environment variable CURL_OPTIONS that defaults to following redirects. However, when variable is dereferenced it is wrapped in quotas letting shell know that this is a single parameter. The default value does not require use of quotes. However, this usage of quotes disallows overriding of curl options unless you can squeeze all of them into a single argument. Given that many curl options are long ones (like --tlsv1.3) or require arguments, they cannot be matched with mandatory -L option of curl. This makes it effectively impossible to override curl options (for example to select tls version).

The fix is just not to wrap CURL_OPTIONS in quotes when invoking curl.

**Comment by carlossg** [comment]
fixed in #796
