### ISSUE TITLE
Cannot install any pipeline plugins on first-time setup

### ISSUE THREAD

**Issue by taylorp36** [jenkinsci/docker#785]
Using jenkins:latest, I’m getting errors similar to this installing almost every pipeline plugin:
 ```
Jan 11, 2019 3:35:53 PM hudson.model.UpdateCenter$DownloadJob run
SEVERE: Failed to install Pipeline: Declarative Agent API
java.io.IOException: Failed to dynamically deploy this plugin
at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1893)
at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to install pipeline-model-declarative-agent plugin
at hudson.PluginManager.dynamicLoad(PluginManager.java:874)
at hudson.PluginManager.dynamicLoad(PluginManager.java:813)
at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1889)
... 5 more
Caused by: java.io.IOException: Pipeline: Declarative Agent API v1.1.1 failed to load.
- Pipeline: Declarative Extension Points API v1.3.2 failed to load. Fix this plugin first.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
at hudson.PluginManager.dynamicLoad(PluginManager.java:864)
... 7 more
```
[](url)

**Comment by batmat** [comment]
This image is deprecated. Please read https://jenkins.io/blog/2018/12/10/the-official-Docker-image/

Thanks

**Comment by taylorp36** [comment]
Oh, thanks @batmat

**Comment by bharathkumar33** [comment]
Hello , I am trying to download the latest Jenkins docker image but when I want to install the selected plugins all the plugins install fails . Any idea why?

**Comment by batmat** [comment]
What's the exact image and tags you're using?

Le ven. 31 mai 2019 à 04:11, bharathkumar33 <notifications@github.com> a
écrit :

**Comment by oleg-nenashev** [comment]
you might want to create a new ticket

**Comment by ultimate809** [comment]
Thanks for the help   "  jenkins/jenkins "  works.

**Comment by noamanhesham** [comment]
jenkins/jenkins fixed the issue

**Comment by shaji-bct** [comment]
I just downloaded the docker image from hub.docker.com and it fails installing any of the plugins. jenkins/jenkins fixed the issue for me, but might need change on docker hub as well.

**Comment by MAHESH-HASBI** [comment]
This worked for me jenkins/jenkins

**Comment by dharam01** [comment]
I also faced same issue with the image from docker hub. 
jenkins/jenkins worked for me.

**Comment by karthickcv** [comment]
> Hello , I am trying to download the latest Jenkins docker image but when I want to install the selected plugins all the plugins install fails . Any idea why?

Try  jenkins/jenkins image  .. not jenkins..

**Comment by sadityalal** [comment]
finally got the answer jenkins/jenkins is the right image

**Comment by rutvik2611** [comment]
i am still facing the same  issue ,you all are saying jenkis fixed it but its not working for me here is the command that i ran 
"docker run --name jenkins-production -d -p 50000:50000 -p 8080:8080 -v jenkins-data:/var/jenkins_home jenkins/jenkins"

i also tried with --previlaged ,-u root ,-u rut(my username)
installations still fails..tried with powersehll on windows and wsl2 ubnuntu

**Comment by slide** [comment]
Please open a new issue, this issue was because people were using the wrong image.

**Comment by HardikaDoshi** [comment]
> i am still facing the same issue ,you all are saying jenkis fixed it but its not working for me here is the command that i ran
> "docker run --name jenkins-production -d -p 50000:50000 -p 8080:8080 -v jenkins-data:/var/jenkins_home jenkins/jenkins"
> 
> i also tried with --previlaged ,-u root ,-u rut(my username)
> installations still fails..tried with powersehll on windows and wsl2 ubnuntu

i am facing the same issue. did you find a solution for this?
