### ISSUE TITLE
Most plugins are incompatible with docker jenkins:lts

### ISSUE THREAD

**Issue by mattesja** [jenkinsci/docker#787]
### Docker commands that you execute
I installed and started jenkins with long term support according to the docs:

```
docker pull jenkins/jenkins:lts
docker run --rm --name jenkins -p 8080:8080 -p 50000:50000 -v $PWD:/var/jenkins_home jenkins
```
### Actual result

Jenkins started in Version 2.60.3
But most plugins could not be used because I should upgrade to v2.73.3

The [manage interface](http://localhost:8080/manage) shows this message:

> Pipeline: Shared Groovy Libraries v2.12
> You must update Jenkins from v2.60.3 to v2.73.3 or later to run this plugin.

### Expected result
So I expected to get a jenkins version which is compatible to the needed plugings.

**Comment by batmat** [comment]
Hello, you are using a deprecated image.

Please read https://jenkins.io/blog/2018/12/10/the-official-Docker-image/

Also, searching existing similar issues is generally a good idea, this duplicates #785 

Thanks

**Comment by mattesja** [comment]
Your're right. I just seen that I started jenkins instead of jenkins/jenkins.

**Comment by Manjunath91** [comment]
yes, i am using deprecated image of jenkin. now what the way to update it to 2.73.3 ?

**Comment by systemsincode** [comment]
Kinematic is still showing the jenkins deprecated images as a primary 'official' image..you have to load the dockerhub page to notice its deprecated.

**Comment by vbisbest** [comment]
I am having the same issue using jenkins/jenkins.  Still says its 2.60.3.   
docker pull jenkins/jenkins:lts

Any ideas on that?

**Comment by avlad** [comment]
Still something wrong!!!

docker pull jenkins/jenkins
Using default tag: latest
latest: Pulling from jenkins/jenkins
146bd6a88618: Pull complete                                                                                                                                                                                      ....                                                                                                                                                a74efef6a6e9: Pull complete                                                                                                                                                                                      Digest: sha256:0d6ac8a67144520546290eb2d591cee07e65f74bb81603ec4f1a5fed0c71c770
Status: Downloaded newer image for jenkins/jenkins:latest
docker.io/jenkins/jenkins:latest

docker images
REPOSITORY                                  TAG                  IMAGE ID            CREATED             SIZE
jenkins/jenkins                             latest               f69bdb978ead        6 days ago          573MB


but still - 2.60.3

**Comment by batmat** [comment]
Where did you take this excerpt from @lzchahaha?

It is wrong, the second line is running a different image from the one pulled on the first one.
It should be:
```shell
docker run --rm --name jenkins -p 8080:8080 -p 50000:50000 -v $PWD:/var/jenkins_home jenkins/jenkins:lts
```

Or, potentially even better to be sure you're using the same (example for Linux shell):

```shell
JENKINS_IMAGE=jenkins/jenkins:lts
docker pull $JENKINS_IMAGE
docker run --rm --name jenkins -p 8080:8080 -p 50000:50000 -v $PWD:/var/jenkins_home $JENKINS_IMAGE
```
