### ISSUE TITLE
Jenkins gets stuck at reloading after changing to v2.160 image

### ISSUE THREAD

**Issue by kahootali** [jenkinsci/docker#789]
I deployed jenkins/jenkins:2.160  with keycloak authentication, it authorized from keycloak and when it redirects back to jenkins, it stucks in forever loop, works fine in 2.159

**Comment by batmat** [comment]
Please use the Jenkins users mailing list. We only handle here issues that are specific to the docker image packaging, and it looks like this issue would also happen using directly the Jenkins war package? 

Thanks

**Comment by kahootali** [comment]
ok
