### ISSUE TITLE
Not able to install a list of plugins using install-plugins.sh

### ISSUE THREAD

**Issue by gakhrejah** [jenkinsci/docker#794]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.
ISSUE:
I am not able to install a list of packages mentioned in a file using this script "install-plugins.sh".

QUERIES:
1) I need to install a list of packages mentioned in a file .
2) If a plugin has a updated version and we want to install that updated version , so can we do that.
3) If a plugin is already present then it will try to install that plugin again

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Actual result
Not able to install plugin
### Expected outcome
It should install a list of plugin mentioned in a file

**Comment by gakhrejah** [comment]
Hi Team,

I am also getting the below error , while building the docker image . Can you please let me know the cause of this issue 

Error Logs
Downloading plugin: git-client from https://updates.jenkins.io/download/plugins/git-client/latest/git-client.hpi
Downloading plugin: ace-editor from https://updates.jenkins.io/download/plugins/ace-editor/latest/ace-editor.hpi
curl: (6) Could not resolve host: updates.jenkins.io
06:40:53 Failure (6) Retrying in 1 seconds.

**Comment by oleg-nenashev** [comment]
@gakhrejah likely there was a temporary glitch in the update center. CC @olblak

**Comment by batmat** [comment]
Please provide your `Dockerfile`, or an excerpt that demonstrates the issue @gakhrejah.

**Comment by gakhrejah** [comment]
DOCKERFILE

FROM jenkinsci/jenkins:alpine
#Just info about who created this

COPY Jenkins-SetInitialState-Completed.groovy /usr/share/jenkins/ref/init.groovy.d/Jenkins-SetInitialState-Completed.groovy

COPY Jenkins-Admin-User-Creation-AtInitial.groovy /usr/share/jenkins/ref/init.groovy.d/Jenkins-Admin-User-Creation-AtInitial.groovy
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN xargs /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

ENV JAVA_OPTS "-Djenkins.install.runSetupWizard=false"

**Comment by batmat** [comment]
What is the content of `plugins.txt` please?

**Comment by slide** [comment]
There hasn't been any response from @gakhrejah since January. I propose closing this out unless more information is provided about the issue.

**Comment by NokiDev** [comment]
Update : 

Actually I have the same issue: failing with Could not resolve host: updates.jenkins.io
I don't do anything exotic just following the doc + adding few perm constraints.

```
COPY --chown=jenkins:jenkins  plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
```

I suppose the update center is kinda broken (It seems there is a redirection from updates.jenkins.io to mirrors.jenkins.io, but 404 ), because it used to work last week.

Performing a handwritten curl it works so I have any clue why (Same if I copy paste url in my browser)
Really weird.

 if anyone has any info, I'll be glad.

Thank you.

**Comment by zgoda** [comment]
I see this in my Ansible task output `"stderr": "curl: (6) Could not resolve host: updates.jenkins.io"`.

**Comment by olblak** [comment]
Normally this issue has been solved, it was probably related to the serverion issue we had several weeks.
More context [here](https://groups.google.com/u/1/g/jenkins-infra/c/KJtrLJaIAek)

In very short, one of the mirrors behind get.jenkins.io(new version of mirror.jenkins-ci.org), had disk raid issues which led to packets drop, then the server changed his IP address from a US one to an EU one which led to packet drop.
In the future, the best way to understand if something wrong is happening is the run the following command. 

```
curl -I -L https://get.jenkins.io/redhat/jenkins-2.275-1.1.noarch.rpm
```
and the location header will tell you to which mirror you are redirected then you can see if that mirror is experience issues

Another location to get information is https://status.jenkins.io
For now, I am closing this ticket but feel free to reopen it, this doesn't.


> Performing a handwritten curl it works 
The curl command must be run on the machine you are having issues as depending on your location you are redirected to a different mirror

**Comment by olblak** [comment]
Another discussion related to the same outage 
https://groups.google.com/u/1/g/jenkins-infra/c/A5vsthU4xF4
