### ISSUE TITLE
plugins.txt list / sequence inside / http request 400

### ISSUE THREAD

**Issue by VJ-2040** [jenkinsci/docker#800]
Using the Script inside a runing Jenkins in a docker container with installed plugins:

            Jenkins.instance.pluginManager.plugins.each{  plugin ->
                println ("${plugin.getShortName()}: ${plugin.getVersion()}")
            }

            ace-editor: x.y
            active-directory: x.y
            ...
            config-file-provider: x.y
            ivy: x.y
            artifactory: x.y

the output I use as input for my plugins.txt. The dockerbuild fails somewhere with:

            Downloading plugin: pipeline-stage-step from https://updates.jenkins.io/download/plugins/pipeline-stage-step/ 2.3/pipeline-stage-step.hpi
            Downloading plugin: pipeline-rest-api from https://updates.jenkins.io/download/plugins/pipeline-rest-api/ 2.10/pipeline-rest-api.hpi
            [91mcurl: (22) The requested URL returned error: 400 Bad Request
            [0mDownloading plugin: pipeline-stage-tags-metadata from https://updates.jenkins.io/download/plugins/pipeline-stage-tags-metadata/ 1.3.4.1/pipeline-stage-tags-metadata.hpi
            [91mcurl: (22) The requested URL returned error: 400 Bad Request

Changing the sequence inside the plugins.txt the dockerbuild will fail elsewhere but it fails. It seems to be try and erro to find the right one.

How can I produce a plugin sequence inside plugins.txt which based on a running Jenkins with plugins and the dependencies in the correct order that work?

Links, hints are welcome. Thx.

I found no button to close this one. The bug was more or less me. Just remove the space between plugin name and version number and all is fine.

Sorry.

**Comment by nishant-dani** [comment]
I had a similar problem but it was because of a error in one of the plugin names the plugins.txt file.  You need to walk back up or down the log to see which is the offending URL, there should be a seperate message for that.  That will give you a hint about which line in plugins.txt needs fixing.
