### ISSUE TITLE
Add Tag naming convention to README.md / Documentation

### ISSUE THREAD

**Issue by JanoschDeurer** [jenkinsci/docker#802]
### Steps to reproduce
Open https://github.com/jenkinsci/docker or https://hub.docker.com/r/jenkins/jenkins in your browser

### Actual result
On https://hub.docker.com/r/jenkins/jenkins it is described, that jenkins/jenkins:lts and jenkins/jenkins exits. There is however no explanation on what these tags reference, and what naming convention is used for the tags. 

### Expected outcome
Other images like the official [node image](https://hub.docker.com/_/node) provide a section of tags that show which tag is currently mapped to which. Also a declaration of the release cycle would be great.

In a quick search I found two tickets that also raised questions about this tag naming convention (#265, #700) so it wold be great to have documentation for this :)

**Comment by chenrui333** [comment]
that is good idea!
