### ISSUE TITLE
Can't connect to updates.jenkins.io from inside Docker image and during build

### ISSUE THREAD

**Issue by cochiseruhulessin** [jenkinsci/docker#808]
# Issues and Contributing

All requests to updates.jenkins.io timeout. I started noticing this when the build of a Docker image that used the `install-plugins.sh` script failed. Then I ran some tests to see what was happening (see below).

It also fails with `http://mirrors.jenkins-ci.org`, but not with `http://ftp-nyc.osuosl.org`.

### Docker commands that you execute

`docker run -it appropriate/curl -o tmp.html https://updates.jenkins.io`

### Actual result

Timeout.

### Expected outcome

```
jenkins $ docker run -it appropriate/curl -o tmp.html https://updates.jenkins.io
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5961    0  5961    0     0  11597      0 --:--:-- --:--:-- --:--:-- 11574
```

### Have you tried a non-dockerized Jenkins and get the expected outcome?

Yes, `curl -o tmp.html https://updates.jenkins.io` completes succesfully in a Bash shell.

### Output of `docker version`

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:53:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Other relevant information

- On the same machine, I **can** reach `updates.jenkins.io` in a bash shell, outside of a Docker container.
- It only times out for this specific destination host, not for other destination hosts.

The machine on which the commands fail is a GCE VM created from an image, that was build using the following Packer template:

```
{
  "builders": [
    {
      "type": "googlecompute",
      "project_id": "wizardsofindustry",
      "source_image_family": "ubuntu-1804-lts",
      "source_image_project_id": "ubuntu-os-cloud",
      "zone": "europe-west4-a",
      "disk_size": "32",
      "image_name": "jenkins-agent-docker",
      "image_family": "docker-agent",
      "ssh_username": "ubuntu",
      "network": "<redacted>",
      "subnetwork" : "<redacted>",
      "use_internal_ip": true,
      "tags": ["nat"],
      "omit_external_ip": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sudo apt-get update",
        "sudo apt-get install -y default-jdk",
        "sudo apt-get install -y apt-transport-https",
        "sudo apt-get install -y ca-certificates",
        "sudo apt-get install -y curl",
        "sudo apt-get install -y software-properties-common",
        "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
        "sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'",
        "sudo apt-get update",
        "sudo apt-get install -y docker-ce",
        "sudo mkdir -p /home/jenkins",
        "sudo groupadd -g 10000 jenkins",
        "sudo useradd -d /home/jenkins -u 10000 -g 10000 -m -s /bin/bash jenkins",
        "sudo chown jenkins:jenkins /home/jenkins",
        "sudo usermod -aG docker jenkins"
      ]
    }
  ]
}
```

**Comment by olblak** [comment]
Hey, 
Thanks for reporting this, it seems that you are having issues with Jenkins Infrastructure services and not the docker image itself, feel free to open an issue on [issues.jenkins.io](https://issues.jenkins.io) as explained [here](https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue)

**Comment by bodhi-one** [comment]
> Hey, Thanks for reporting this, it seems that you are having issues with Jenkins Infrastructure services and not the docker image itself, feel free to open an issue on [issues.jenkins.io](https://issues.jenkins.io) as explained [here](https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue)

olblak, why do you think this is an issue w/Jenkins infrastructure?  Reporter says it works outside of docker on the same VM.   timja, why closed ?

**Comment by jin-ahn** [comment]
I am having this same issue on 2.350. Please reopen the ticket as its not working

**Comment by bodhi-one** [comment]
jin-ahn, please verify that your MTU for the machine/VM is 1500 or whatever is appropriate for your setup.  If you have VMWare VCenter/VSphere, etc running under your VMs you can certainly have packet loss if MTUs are mismatched.  Updates in VMWare 6.5 to 6.7 started to be more stringent in networking rules around packet size allowance, etc.

**Comment by SilentSib** [comment]
Just figured I would leave my "ah!" comment on this because I was also running into this same issue. The MTU lead was a good one as I had forgotten that the host on which the docker container was running had all of its WAN traffic tunneled through a Wireguard VPN interface which ultimately meant that the container's WAN traffic did too.

And sure enough, the MTU on the Wireguard client and server was different from the one in the network the container was using. Aligning the values immediately fixed the issue and the plugins started downloading.

In case this is eye opening to anybody ending up on this issue...
