### ISSUE TITLE
JENKINS_OPTS not honored by administrativeMonitor

### ISSUE THREAD

**Issue by robertofabrizi** [jenkinsci/docker#812]
### Docker commands that you execute
Started Jenkins with docker-compose using JENKINS_OPTS="--prefix=/jenkins", then placed a Traefik reverse proxy in front of it. It all works except that it says: "It appears that your reverse proxy set up is broken".

### Actual result

This url request causes the above message:
http://10.46.90.125:8383/administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http%3A%2F%2F10.46.90.125%3A8383%2Fjenkins%2Fmanage/

### Expected outcome

I'd have expected that the request above would include the /jenkins portion to enable proper routing, as by the JENKINS_OPTS env variable

### Have you tried a non-dockerized Jenkins and get the expected outcome?

I haven't.

### Output of `docker version`

Docker version 18.09.3, build 774a1f4

**Comment by MarkEWaite** [comment]
Works for me with Jenkins 2.332.2 and Docker version 20.10.14+dfsg1, build a224086

Command line I used:

`$ docker run --rm -t -i --env 'JENKINS_OPTS="--prefix=/jenkins"' -p 8080:8080 jenkins/jenkins:2.332.2`
