### ISSUE TITLE
Mounted docker volume /var/jenkins_home/jobs has wrong permissions

### ISSUE THREAD

**Issue by dmolesUC3** [jenkinsci/docker#813]
## Problem

I want to bake Jenkins configuration with [CasC](https://wiki.jenkins.io/display/JENKINS/Configuration+as+Code+Plugin) into a Docker image, but preserve job results when rebuilding/redeploying the container.

### Docker commands that you execute / Actual result

1. If I use a Docker volume for the entire `jenkins_home` directory, as:

   ```
   docker run -v jenkins_home:/var/jenkins_home -P -d myImage
   ```

   then the first CasC YAML file I `COPY` into my Docker image is preserved, and
   subsequent updates in rebuilt Docker images are ignored.

2. If I try using a Docker volume just for the `jobs` directory, as:

   ```
   docker run -v jenkins_home_jobs:/var/jenkins_home/jobs -P -d myImage
   ```

   something bad happens to the Jenkins home directory structure and I get

   ```
   Mar 25, 2019 11:32:59 PM hudson.util.BootFailure publish
   SEVERE: Failed to initialize Jenkins
   hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.io.IOException: 
   jenkins.model.InvalidBuildsDir: ${ITEM_ROOTDIR}/builds does not exist and probably cannot be 
   created
        at hudson.WebAppMain$3.run(WebAppMain.java:250)
   ```

### Expected outcome

- CasC `jenkins.yaml` can be baked into Dockerfile
- job logs, artifacts, etc. are preserved when rebuilding / re-running a container

### Have you tried a non-dockerized Jenkins and get the expected outcome?

- N/A

### Output of `docker version`

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

### Other relevant information

Full project at https://github.com/dmolesUC3/mrt-jenkins-docker

**Comment by dmolesUC3** [comment]
After further investigation, it looks ass through the problem is that the mounted `/var/jenkins_home/jobs` is not writable by `jenkins`. In fact, nothing in `/var/jenkins_home` is:

```
jenkins@e1e903afe125:/$ ls -l /var/jenkins_home/
total 16
-rw-r--r-- 1 root root 1605 Mar 25 23:23 jenkins.yaml
drwxr-xr-x 2 root root 4096 Mar 27 22:58 jobs
-rw-rw-r-- 1 root root 7152 Feb 14 08:55 tini_pub.gpg
```

I tried adding an explicit `RUN chown` command to the Dockerfile:

```
USER root
RUN chown -R jenkins:jenkins /var/jenkins_home

# make sure we still run jenkins as jenkins
USER jenkins
```

but this had no effect, even after blowing away the Docker volume and starting a fresh container.

As a workaround, I was able to start a container with an interactive root shell, `chown` the directory again, `commit` that, and then run the committed version with an explicit endpoint:

```
$ docker run -v jenkins_home_jobs:/var/jenkins_home/jobs -P -it -u root --entrypoint /bin/bash mrt-jenkins-docker 
root@3aa74d03ad9a:/# chown -R jenkins:jenkins /var/jenkins_home
root@3aa74d03ad9a:/# exit
exit
cdl-dmoles-9m:mrt-jenkins-docker david$ docker commit 3aa7 permfix
sha256:4054d5b0c67699678bd889a802d78364c4d4bc09ca7dacadc19473f16c36b969
cdl-dmoles-9m:mrt-jenkins-docker david$ docker run -v jenkins_home_jobs:/var/jenkins_home/jobs -P -d --entrypoint /sbin/tini permfix -- /usr/local/bin/jenkins.sh
552f04dbe4fe7b4152d51bad5db0ea7ee2c84cfc3cd9a88c2550cc6b3cb00367
```

I can probably script all that, but it seems as though there should be a better way.

**Comment by dmolesUC3** [comment]
Workaround: install `sudo`, run as `root`, and override the `ENTRYPOINT` to run the following script, which (1) `chowns` the directory at run time and (2) uses `sudo` to run `jenkins.sh` as `jenkins`.

```
#!/bin/bash -e

chown -R jenkins:jenkins ${JENKINS_HOME} && \
  sudo --login -u jenkins \
    JENKINS_HOME=${JENKINS_HOME} \
    JENKINS_WAR=${JENKINS_WAR} \
    COPY_REFERENCE_FILE_LOG=${COPY_REFERENCE_FILE_LOG} \
    JAVA_OPTS=${JAVA_OPTS} \
    JENKINS_SLAVE_AGENT_PORT=${JENKINS_SLAVE_AGENT_PORT} \
    JENKINS_OPTS=${JENKINS_OPTS} \
    DEBUG=${DEBUG} \
    /usr/local/bin/jenkins.sh "$@"
```

Dockerfile additions, for completeness:

```
USER root
RUN apt-get install -y sudo
COPY scripts/fix-perms-and-start-jenkins.sh /usr/local/bin/
ENTRYPOINT ["/sbin/tini", "-vvv", "--", "/usr/local/bin/fix-perms-and-start-jenkins.sh"]
```

**Comment by carlossg** [comment]
you need to mount directories with the correct permissions in docker

**Comment by dmolesUC3** [comment]
@carlossg I don't understand. Are you saying that the permissions of the directory inside the Docker container need to be different, or the permissions of the host system directory (there isn't any such thing, it's just a Docker volume)? And if so, what would constitute the "correct permissions"?

**Comment by carlossg** [comment]
the permissions in the docker volume need to match the user jenkins is executed as (1000)
how you do that is different depending on how you run the container, ie. with Kubernetes there is a security context
