### ISSUE TITLE
Fix multiarch build permissions

### ISSUE THREAD

**Issue by jmreicha** [jenkinsci/docker#818]
Just trying to keep things moving.

This is a follow up to https://github.com/jenkinsci/docker/pull/750 to enable multiarch builds.  Related to https://github.com/jenkinsci/docker/issues/646 and https://github.com/jenkinsci/docker/issues/686, there is currently a permission issue that is inhibiting pushing the multiarch images to the jenkins4eval repo.

It sounds like the Dockerhub user that is being used to build and push the images needs to have permissions to the jenkins4eval repo.

Job results: https://ci.jenkins.io/job/Packaging/job/docker/job/jenkins4eval/

/cc @oleg-nenashev @imdurgadas @batmat @MarkEWaite

**Comment by lag-linaro** [comment]
Any movement on this @jmreicha @oleg-nenashev?

**Comment by jmreicha** [comment]
@lag-linaro test PR open here https://github.com/jenkinsci/docker/pull/807

Basically, I think there are some authentication issues that need to be debugged.

**Comment by slide** [comment]
I can help look into this, we need to find out what the withDockerCredentials is using and make sure the jenkins4eval has the correct permissions. According to @oleg-nenashev it should since jenkinsfile-runner is able to publish to jenkins4eval just fine.

**Comment by jmreicha** [comment]
Should be able to run the build/publish script with the debug flag turned on to see what's happening.

**Comment by slide** [comment]
The docker push already has --log-level debug, regardless of the debug flag passed to the publish script:

https://github.com/jenkinsci/docker/blob/jenkins4eval/publish-experimental.sh#L222
https://github.com/jenkinsci/docker/blob/jenkins4eval/publish-experimental.sh#L260

I am not sure calling the script with -d will help much in getting more information. Are you proposing adding -D to the docker call as well to enable debug mode?

**Comment by jmreicha** [comment]
Add -d to the publish script, e.g. https://github.com/jenkinsci/docker/blob/jenkins4eval/Makefile#L57.

**Comment by slide** [comment]
I am not sure that will provide information as to why the docker command is failing (for permissions), but we can definitely try it.

**Comment by slide** [comment]
@jmreicha  See https://github.com/jenkinsci/docker/pull/855

**Comment by slide** [comment]
It doesn't seem like my changes did anything during the actual publish phase

**Comment by slide** [comment]
Ok, this build went though, but `docker info` isn't showing the username. Also, it looks like DOCKER_CONFIG exists since there wasn't an early exit from the script with an error message. Other ideas?

**Comment by jmreicha** [comment]
I'm guessing the username being empty is the problem, but I'm not really sure why the credentials are being set.

**Comment by slide** [comment]
I believe this is fixed now. The Packaging folder on ci.jenkins.io had it's own credentials setup that were wrong, these were inherited by the docker builds. That issue has been fixed and pushing to docker hub should work now.
