### ISSUE TITLE
 Application is vulnerable Local File Inclusion(LFI)  attack

### ISSUE THREAD

**Issue by srinivasvadla** [jenkinsci/docker#819]
> 

Hello Everyone how can i prevent the local file inclusion using java jsp technolology
**attachment:filenam=../../../../../../../../../etc/passwords**
here by giving the directory like above we can able to get the content of the file like so ,
please  help me.

Thank you.

**Comment by carlossg** [comment]
see "How to Report a Security Vulnerability" https://jenkins.io/security/
