### ISSUE TITLE
weekly branch behind actual weekly release

### ISSUE THREAD

**Issue by kmadel** [jenkinsci/docker#82]
Current weekly release at 1.610 (2015/04/19) - weekly branch is at 1.605 (2015/03/16).  Should the weekly docker image reflect the very latest weekly release?

**Comment by MarkEWaite** [comment]
Pull request submitted https://github.com/jenkinsci/docker/pull/104

**Comment by MarkEWaite** [comment]
In pull request #104, @carlossg states that weekly has been abandoned.  I closed pull request #104.  I'll continue maintaining a weekly on my fork because I found it helpful in certain cases.

**Comment by carlossg** [comment]
@ndeloof created an auto build in https://registry.hub.docker.com/u/jenkinsci/jenkins/
