### ISSUE TITLE
Github release note seems not maintained

### ISSUE THREAD

**Issue by chenrui333** [jenkinsci/docker#820]
Kind of similar to this issue, #802 about the tagging conventions about the docker images in the Dockerhub side. 

But I am more thinking of the release notes (https://github.com/jenkinsci/docker/releases) management so that we can watch the github releases of this repo.

But it seems there are no release notes in `nodejs/docker-node` repo, it might be just a wishful thought.

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker/pull/856 somewhat addresses it

**Comment by chenrui333** [comment]
Thanks for taking the initiative of doing that. Appreciate it!

**Comment by oleg-nenashev** [comment]
Closing it since it is all I can do for now.
Happy to review any suggestions about improving changelogs in a follow-up
