### ISSUE TITLE
Installing PHP7.1

### ISSUE THREAD

**Issue by Inchie** [jenkinsci/docker#823]
I am trying to install PHP7.1 and get the following error message: 

> The following packages have unmet dependencies:
 php7.1 : Depends: libapache2-mod-php7.1 but it is not going to be installed or
                   php7.1-fpm but it is not going to be installed or
                   php7.1-cgi but it is not going to be installed
 php7.1-cli : Depends: php7.1-opcache but it is not going to be installed
              Depends: libc6 (>= 2.29) but 2.24-11+deb9u4 is to be installed

I added the following code in the DOCKERFILE:

> RUN apt-get update -qq && apt-get install -yqq \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    && apt-get update \
    && LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php

> RUN apt-get update && apt-get -f install -y \
    php7.1 php7.1-common php7.1-cli

Has anybody solved this problem yet?

**Comment by d10i** [comment]
Seeing the same issue, pretty sure this is what's causing the issue:
> Depends: libc6 (>= 2.29) but 2.24-11+deb9u4 is to be installed

Not sure how to solve it...

**Comment by batmat** [comment]
I think you are trying to run workload on the Jenkins `master`. You rather want to use agents for builds. 
See https://stackoverflow.com/questions/47651682/what-does-the-agent-mean-in-jenkins

If you do so, you will be able to design your own Docker image with just PHP, using simply https://hub.docker.com/_/php

I think this addresses the question. Thanks!

**Comment by d10i** [comment]
No, that's not the case. I'm trying to install `php7.2` using base Docker image `jenkinsci/jnlp-slave` (which uses Debian).

```
FROM jenkinsci/jnlp-slave

RUN apt-get update && apt-get install php7.2
```

**Comment by batmat** [comment]
Then this is not the right repository for such issue, this one is for https://hub.docker.com/r/jenkins/jenkins/.

Thank you!
