### ISSUE TITLE
DEBUG on jdk11 accepts only local connections

### ISSUE THREAD

**Issue by dcendents** [jenkinsci/docker#830]
It is possible to enable remote debugging of jenkins by adding the env var DEBUG=true, which then allows remote debugging on port 5005.

Starting from jdk 9, the remote debugging is only allowed from the localhost (See https://www.oracle.com/technetwork/java/javase/9-notes-3745703.html#JDK-8041435)

Which makes it useless in a docker container.

Could you please update the jdk11 containers to allow remote debugging from any host (`-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=*:5005,suspend=y`)

Thanks

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/java11-support

**Comment by MRamonLeon** [comment]
Yes, I faced this issue. the * is pretty important
