### ISSUE TITLE
copy_reference_file.log issue using named volume

### ISSUE THREAD

**Issue by tinue** [jenkinsci/docker#831]
All the references and fixes that I found explain how to change permissions of a bind mount.
I am using a named volume, therefore the proposed solution does not work.  

### Command:
```
docker pull jenkins
```
So far ok. Then:
```
docker run --name testjenkins -p 8080:8080 -p 50000:50000 \
 -v jenkins-testvol:/var/jenkins_home \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -u 386:386 \
 jenkins
```

### Outcome:
```
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

### Expected:
Jenkins starts up.

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No; I have tried without the -u option, and then it works.

### Output of `docker version`
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Other relevant information
`docker volume ls` shows that the volume `jenkins-testvol` does not yet exist.

**Comment by jansohn** [comment]
I have experienced the same problem but unfortunately I think it is standard docker behavior (https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes).

> **Changing the volume from within the Dockerfile:** If any build steps change the data within the volume after it has been declared, those changes will be discarded.

In the Dockerfile `/var/jenkins_home` is created with default uid/gid 1000 and then the volume is explicitly declared.
I think this could only really be fixed if the container would start with root rights and would drop back to the normal jenkins user after making sure that permissions are set correctly.
Of course you can explicitly fix the permissions of the named volume yourself (after it fails the first time) and then you can also run the container with a different uid/gid.

**Comment by tinue** [comment]
Thanks for your analysis!

Wouldn't it be enough to have the `USER ${user}`**before** the `VOLUME $JENKINS_HOME`in the Dockerfile? So far I am only a user of predefined docker files, and not at all a developer. So I might be totally wrong about this...

But anyway: In all of the issues I found talking about the copy_reference_file.log problem, the explicit recommendation was to use named volumes, and not bind mounts. So I am confused as to why this does not work either.

**Comment by jansohn** [comment]
> Wouldn't it be enough to have the `USER ${user}`**before** the `VOLUME $JENKINS_HOME`in the Dockerfile? So far I am only a user of predefined docker files, and not at all a developer. So I might be totally wrong about this...

No, that `USER` instruction just changes the context from root user to jenkins user for the following instructions in the Dockerfile and later when starting up the container. The UID/GID will still be 1000:1000.

**Comment by tinue** [comment]
I think I understand now. Per default, everything runs as "root" until the `USER` instruction in the dockerfile, which is quite late in the case of Jenkins.
But if I set `-u`, then the `USER` instruction is ignored. By this time, the owner of `JENKINS_HOME` is already set to 1000:1000, and the overwritten user can't copy the file.

I wonder if the user that is passed in via `-u` can be retrieved. If this would be possible, then one would simply use the passed-in user instead of 1000:1000 for the chown operations done by root (before the `USER` operation). I couldn't find anything related to this in the Docker documentation, though.

**Comment by jansohn** [comment]
Not quite. The `-u` parameter you are talking about is a runtime parameter only used when running the container. Everything in the Dockerfile is already executed while building the docker image. So to change the UID/GID in the image you need to rebuild the image with build parameters specifying the desired UID/GID.

**Comment by tinue** [comment]
Thanks! I had a very wrong "mental model" of how a docker image works. Somehow I thought it's being built when first pulled.

Would it be fair to say that the support of `-u` in the Jenkins docker image is incomplete? A full support would fix the permissions on every startup of the container. I fix would therefore be in `jenkins.sh`, which is what you already said in your first reply; It's just that I did not understand this correctly ;)

I found [this](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/), specifically this quote "If you absolutely need functionality similar to sudo, such as initializing the daemon as root but running it as non-root), consider using 'gosu'."  
Maybe this is how it should be done.

I'll use your workaround to fix the volume, many thanks for this!

**Comment by batmat** [comment]
I guess a related question is: why are you actually tryinig to use `-u 386:386`? What are you trying to achieve?

**Comment by tinue** [comment]
This is an excellent question, indeed. Specifically because what I wanted to achieve did not work, so I might just as well go back to the default.

After going through the documentation on https://github.com/jenkinsci/docker/blob/master/README.md and spinning up Jenkins, everything looks great at first sight. That is until the first build, which fails with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I find it troubling that this is not covered in the documentation, because it appears to me that everybody gets hit with this. Fundamentally, Jenkins/Docker does not work out of the box. But this would be an issue elsewhere; There probably is an issue tracker for documentation.

So what I tried to do is map the socket, which resulted in `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`. Again, I think pretty much everybody gets hit with this. Only after going through all of https://github.com/jenkinsci/docker/issues/263 I am starting to see a way out of this. I will have to enable the host Docker daemon to listen to TCP, and redirect the Jenkins docker client to this socket. I am not there yet, so I don't know if this will work.

Before I came up with this, I thought I need to add the Jenkins user to the docker group. User 1000 was in use on my host system, so I added another user and added it to the docker group. This user has id 386. Of course this did not work either, because the socket **inside** of the Jenkins container did not allow access. I would have to add the new user to the docker group (or the group owning the socket, I am not sure) inside of the container. I can't do this, because I use docker-compose.

Anyway, I am still stuck. I am actually wondering if anyone gets Jenkins in docker running at all, or if I am particularly thick with my understanding. It should not be that hard...

**Comment by tinue** [comment]
I am closing the issue now. Not because it's solved, but because I no longer need to overwrite the user/group. I no longer mount the docker socket, instead I use the socket via TCP. I have documented my approach [here](https://www.iot-projekte.ch/running-jenkins-in-docker/).
