### ISSUE TITLE
Not able to login after restart

### ISSUE THREAD

**Issue by vrathore18** [jenkinsci/docker#838]
I am stuck on this issue for 3 days.

After restarting the container. I am not able to login. I tried to login with admin:admin. Also changing <useSecurity>false</useSecurity>`

but it's not working.

When I check the config.xml. I find this setting:

```
<authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">
    <denyAnonymousReadAccess>false</denyAnonymousReadAccess>
  </authorizationStrategy>
  <securityRealm class="hudson.security.LDAPSecurityRealm" plugin="ldap@1.20">
    <disableMailAddressResolver>false</disableMailAddressResolver>
    <configurations class="singleton-list">
      <jenkins.security.plugins.ldap.LDAPConfiguration>
        <server>XXXXX</server>
        <rootDN>xxxx,dc=pvt</rootDN>
        <inhibitInferRootDN>false</inhibitInferRootDN>
        <userSearchBase></userSearchBase>
        <userSearch>xxxx</userSearch>
        <groupMembershipStrategy class="jenkins.security.plugins.ldap.FromGroupSearchLDAPGroupMembershipStrategy"/>
        <managerDN>xxxxxx</managerDN>
        <managerPasswordSecret>{AxxxxxxxxoeD9kNvvoOTv0M=}</managerPasswordSecret>
        <ignoreIfUnavailable>false</ignoreIfUnavailable>
      </jenkins.security.plugins.ldap.LDAPConfiguration>
    </configurations>
    <userIdStrategy class="jenkins.model.IdStrategy$CaseInsensitive"/>
    <groupIdStrategy class="jenkins.model.IdStrategy$CaseInsensitive" reference="../userIdStrategy"/>
    <disableRolePrefixing>false</disableRolePrefixing>
  </securityRealm>
```
I don't want this setting. I want to login using admin:admin. I tried changing the config.xml file and mount again but every time container restart it changes the config.xml of the host.

what should I do?? also how can I restart the Jenkins inside the container without stopping it?

**Comment by oleg-nenashev** [comment]
Do you have any kind of Configuration-as-Code or Configuration Management configured in your instance? Official Docker image does not even install the LDAP plugin

**Comment by vrathore18** [comment]
I am building dockerimage from the dockerfile provided here. But I was not setting up the ldap.groovy. I did setup previously my my jenkins instance was up and running. 

BTW: how can I restart the jenkins inside container? @oleg

**Comment by oleg-nenashev** [comment]
> BTW: how can I restart the jenkins inside container? @oleg

You can use Safe Restart Plugin for it. Not that I recommend doing so
