### ISSUE TITLE
How to spin off a sibling container?

### ISSUE THREAD

**Issue by tinue** [jenkinsci/docker#843]
## Question
What is the recommended / sanctioned way to configure docker/jenkins so that it can spin off a build in a sibling container? I have gone through all the documentation that I could find, and read through all the issues, and still end up at: **Impossible**. This does not work, unless I use not recommended or unsafe workarounds.

Since this is a very fundamental functionality of Jenkins, I must overlook something simple. Would anyone knowledgable be so glad and point me to the right piece of documentation?

### Bind-mount 
* When I use a bind mount, I get `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`.
* Jenkins runs with the default 1000:1000.
* User 1000 outside of the container is part of the `docker` group (GID `999`) and can access the docker daemon just fine.
* Inside the container, `/etc/groups` lists GID `101` under `docker`, and GID `999` is named `ping`.
* Ugly workarounds include:
  * Force GID `999` when starting Jenkins, instead of the default `1000`. This is ugly because it's not portable. On other hosts, the docker GID might be different. On the Mac, for example, docker.sock is owned by root:root.
  * Lowering the restrictions of `/var/run/docker.sock`. Ugly because it is unsafe.
  * Building my own dockerfile. Ugly because such a fundamental function should work out of the box.

### Access via TCP
* Opening the docker daemon to allow access from 0.0.0.0. Ugly because the entire world can connect to my docker daemon now.
* Doing the above, but protecting the socket with certificates. This works for every container that I tried, but not for Jenkins. The problem is the Truststore that I have to provide: It contains the docker sockets certificate. Every other SSL connection now fails (e.g. to Github), because the regular Java truststore entries are missing.

And that's it, I found no other suggestions.

My environment is docker-ci on Ubuntu 18.04.2 LTS.

**Comment by fireboy1919** [comment]
I came upon this thread in looking for a solution to this problem...which I then solved. 
Here's code inside a "script" tag in an otherwise declarative Jenkins pipeline:
...
          JENKINSUID = sh ( script: 'id -u jenkins', returnStdout: true ).trim()
          DOCKERGID = sh ( script: 'stat -c %g /var/run/docker.sock', returnStdout: true ).trim()
          JENKINSGID = sh ( script: 'id -g jenkins', returnStdout: true ).trim()
          docker.image('maven:3.6.2-jdk-8').inside("--user=${JENKINSUID}:${JENKINSGID} --group-add ${DOCKERGID} -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker") {
          // This should work:
         sh "docker ps"
}

I based this on this:  https://stackoverflow.com/questions/47854463/got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket-at-uni

...except that I removed the need for an entirely new docker container.

**Comment by timja** [comment]
Using a cloud implementation of some kind

kubernetes, azure, aws etc are the easiest ways
