### ISSUE TITLE
How to skip one step in jenkins pipeline? 

### ISSUE THREAD

**Issue by gauravgemalto** [jenkinsci/docker#844]
Can anyone help me with the pipeline script? I want to skip one step in the pipeline. This is one sample code skip 1st step and second should be a success.

If 1st fail pipeline should not fail.

pipeline {
    agent any
    stages {
			try{
				stage('Test step 1') {
					error('Fail')
				}
			}catch(Exception ex){
					//currentBuild.result='FAILURE'
				}
			stage('prod stpe 2') {
				steps {
					 echo 'step 3 prod'
				}   
			}
	}
}

**Comment by oleg-nenashev** [comment]
Please ask in proper channels. This is a tracker for Jenkins Docker packaging, not a Q&A board fot the entire project
