### ISSUE TITLE
ENV JENKINS_VERSION 

### ISSUE THREAD

**Issue by kknd22** [jenkinsci/docker#845]
There are some of ENV in the Dockerfile are not actually work as intended,   
or I am completely off on this.  
The current LTS, Dockefile that used has: `JENKINS_VERSION=2.176.1` (through `docker inspect`)

Since `JENKINS_VERSION` is defined as `ENV`, I ran the docker container using: 
```
docker run -p 8182:8080 -p 50000:50000 -e JENKINS_VERSION=2.180 -v /home/abc/jenkins_home:/var/jenkins_home jenkins/jenkins:lts
```
and it doesn't take `2.180`, the jenkins version remains `2.176.1`
I found the similar question here:
https://github.com/jenkinsci/docker/issues/266

My questions is that why `JENKINS_VERSION` is an `ENV` (also a `ARG`, which is correct)
Am I missing something?
Thanks

-cl

**Comment by benlangfeld** [comment]
This is a build-time thing. It is not intended to be possible to upgrade Jenkins at runtime.

**Comment by kknd22** [comment]
Agreed. That’s why the question - should ‘JENKINS_VERSION’ be an ‘ARG’ instead of ‘EVN’?

**Comment by slide** [comment]
There are specific tags on Docker Hub for specific versions of Jenkins. This is the way that you would want to change Jenkins versions.
