### ISSUE TITLE
java not found on new builds

### ISSUE THREAD

**Issue by robbinscp** [jenkinsci/docker#846]
### Docker commands that you execute

`docker-compose up -d`

### Actual result

Docker container fails to start, as shown below. 

```docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                        PORTS               NAMES
d94a4afd9eb5        athena/jenkins:latest   "/sbin/tini -- /setu…"   27 minutes ago      Exited (127) 27 minutes ago                       jenkins_jenkins_1
```

Logs for the failed container -

```docker logs d94a4afd9eb5
/usr/local/bin/jenkins.sh: line 35: exec: java: not found
```

### Expected outcome

Docker container starts normally

### Have you tried a non-dockerized Jenkins and get the expected outcome?

N/A - this is a docker-specific issue

### Output of `docker version`

```
$ docker -v 
Docker version 19.03.0-rc2, build f97efcc
```

### Other relevant information

This has been failing since at least 2.178 and newer releases.  We use a custom startup script to handle additional post-container build tasks; I have tried altering the final line of that script to execute the jenkins.sh script (`/usr/local/bin/jenkins.sh`) using `tini` and setting the user as `jenkins` with no change in the result.  Has something changed that has broken `java` in newer releases?  Is there a better way to manage startup of Jenkins?

**Comment by roger104** [comment]
I have same issue running docker on Synology NAS, since 2.178, I have no customization

**Comment by roger104** [comment]
Performed some troubleshooting on this by staring a terminal session (execution command /bin/bash) to find out where Java are installed in 2.186. 
Java are in `/usr/local/openjdk-8` directory. 

Since I have been upgrading to newer version using same **JSON** file for at least one year I did need to change two lines in the **JSON** file. 
First line was **PATH** statement to include `/usr/local/openjdk-8/bin` and second line was **JAVA_HOME** to point at `/usr/local/openjdk-8`

With these changes done to the **JSON** file I could get Jenkins running by import the saved JSON file which automatically launch the Jenkins container.

Running jenkins/jenkins:latest in docker on a Synology  DS716+II with DSM 6.2

**Comment by slide** [comment]
I am unable to replicate this issue. Please check that like @roger104 you are not overriding the JAVA_HOME environment variable. The JAVA_HOME comes from the upstream openjdk docker library images, so if they modify the JAVA_HOME, it could be different in newer images for Jenkins.

**Comment by roger104** [comment]
Checking a bit more into this of interest, the **JSON** file that worked up to version 2.176 did have JAVA_HOME set to `JAVA_HOME=/docker-java-home` and in 2.186 no such path exist causing the failure. 
I did moved on and modify the **JSON** file with the input from @slide file and remove JAVA_HOME definition from the **JSON** file and re-launch the container. JAVA_HOME are inherited into the container with value set to `/usr/local/openjdk-8` and the container is running as expected.

**Comment by robbinscp** [comment]
Apologies - forgot to close this guy out.  I found a solution by using fixing my startup script to end with the following line, and installed `gosu` in my container.  

`gosu jenkins "/usr/local/bin/jenkins.sh"`

I believe the solution provided by @roger104  would also work as well.

**Comment by mbaitelman** [comment]
I am having the same issue.
Which JSON file are you referring to?

**Comment by meiswjn** [comment]
Would also be interested in what JSON file you edited - we are facing the same issue.

**Comment by hansi-b** [comment]
We have just run into the same error message with the latest "jenkins/jenkins". Container does not start, but logs
`...  | /usr/local/bin/jenkins.sh: line 37: exec: java: not found`
However, if I `run` the built image with a `bash` entrypoint, `java` and `JAVA_HOME` seem to be correct, and running `/usr/local/bin/jenkins.sh` works.

**Comment by mbaitelman** [comment]
One thing I found is that if you upgrade an existing container with a new image but the tool you use for updating (I've used Portainer) keeps the env vars when recreating the container the `java` and `JAVA_HOME` vars will use the old config.
Delete them and restart, docker will use the image-provided versions vs the ones you provided.

**Comment by hansi-b** [comment]
Oops - in our case, it has turned out to be a simple mount point issue: Our `docker-compose.yml` contains a volume mounted to `/opt/java`. This worked with the old image, but in the new image, this shadows the `/opt/java/openjdk` used in the container ...
