### ISSUE TITLE
If I run jenkins as container, does it means I have to run any pipeline in that container?

### ISSUE THREAD

**Issue by Linshiqi** [jenkinsci/docker#848]
I'm totally beginner in CI and Jenkins

My question is If I run jenkins as container, does it means I have to run any pipeline in that container?  If I push my code to github, and clone it in jenkins pipeline, then this pipeline runs in 
docker container, and cloned code also in that container? What if I want to deploy my code to run on docker host instead of jenkins container?

**Comment by slide** [comment]
This is a Jenkins master image, which means it functions as if you were running "java -jar jenkins.war" on some system. This just allows containerizing the Jenkins master. You don't need to do anything special in your Jenkinsfiles to run them when you are running using a container. You just run jobs like a normal master.
