### ISSUE TITLE
Credentials looks fine but the repository URL is invalid

### ISSUE THREAD

**Issue by CuteErica** [jenkinsci/docker#849]
image:jenkins/jenkins:lts

When I add svn account in a jenkins job, it showwd "Credentials looks fine but the repository URL is invalid".But the build succeed.Is it a bug or I have some mistakes while using it?
![image](https://user-images.githubusercontent.com/37364519/61262624-762d1d80-a7b8-11e9-8dfa-fadfccad3d37.png)

**Comment by slide** [comment]
I don't think this is related to the docker image. Please check the Jenkins issue tracker at https://issues.jenkins.io.
