### ISSUE TITLE
copy_references: Add support of custom /usr/share/jenkins/ref/ locations

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker#861]
Currently `copy_references` method in jenkins-support hardcodes `/usr/share/jenkins/ref/` by making substraction at 23 symbol in the codebase. It would be great to make /usr/share/jenkins/ref/  configurable so that custom images can specify other reference paths

**Comment by slide** [comment]
Similar to https://github.com/jenkinsci/docker/issues/709

**Comment by MRamonLeon** [comment]
Addressed on https://github.com/jenkinsci/docker/pull/866
