### ISSUE TITLE
Inactive OK button on New Item page.

### ISSUE THREAD

**Issue by medined** [jenkinsci/docker#87]
I am unable to create projects. I created my host directory:

mkdir /data/jenkins
chmod 777 /data/jenkins

I am using the following docker command:

docker run \
--name jenkins \
-p 28080:8080 \
-p 50000:50000 \
--rm=true \
-v /data/jenkins:/var/jenkins_home \
jenkins

I can connect to Jenkins on port 28080. And I can click the New Item link. But after entering a project name and selecting 'maven project', then OK button remains inactive and unresponsive.

I see no console error messages.

Have you seen this behaviour before?

Do I need to configure Jenkins before creating projects? If so, can the documentation be updated about what needs to be configured?

**Comment by ndeloof** [comment]
Until I'm proven wrong this doesn't seem to be related to docker image but generic jenkins issue, please ask on jenkins-dev mailing list
