### ISSUE TITLE
Any plans for CUDA support?

### ISSUE THREAD

**Issue by zingdle** [jenkinsci/docker#870]
Current Jenkins docker images don't support CUDA runtime, though [CUDA container Toolkit](https://github.com/NVIDIA/nvidia-docker) has been available. I'm wondering if there are any plans for this?

**Comment by slide** [comment]
What would be the purpose of this?

**Comment by zingdle** [comment]
@slide I'm trying to use jenkins for a CUDA project's testing. However I can't run CUDA program in current jenkins docker image beacuse it doesn't contain libraries to leverage GPUs.

**Comment by slide** [comment]
Then I would recommend creating an agent image based on either docker-ssh-slave or docker-jnlp-slave and include the libraries you need. The master image should not need the CUDA libraries since you should not be building things on master.
