### ISSUE TITLE
Combine publish and publish-experimental build scripts

### ISSUE THREAD

**Issue by jmreicha** [jenkinsci/docker#872]
Now that multi-arch images are building and getting pushed to the jenkins4eval repo, it would be nice to wrap everything up into one build script so that build scripts are kept DRY and in sync.

Any suggestions for how to test and verify that all the various new multi-arch builds are working correctly?  I have tested aarch64 manually and it seems to work fine but I haven't done any type of systematic testing.

/cc @slide @oleg-nenashev @imdurgadas @lag-linaro

**Comment by lag-linaro** [comment]
Thanks for this Josh (@jmreicha).

I too have tested AArch64 and it appears to be functioning correctly. 

It would be fantastic to pull the main repo and get AArch64 support.

Does anyone have an idea on timelines?

**Comment by oleg-nenashev** [comment]
> Does anyone have an idea on timelines?

Depends on the number of contributions we get. Thanks for testing it BTW!
I think we can safely proceed once the new LTS baseline is cut and once we have some insights into what's happening on Trusted CI. I have a ticket to get access for @batmat and myself

**Comment by lag-linaro** [comment]
> once the new LTS baseline is cut

Any idea how that translates roughly into time?  1 day, 3 weeks, 6 months?

**Comment by oleg-nenashev** [comment]
ETA for the new LTS baseline is Sep 25. 

I will not provide any ETA for the feature itself. It is open-source. It is done when it is done, any time commitments just put stress on contributors who often invest their personal time to maintain the project. Depending on contributions, it might happen before or after LTS (or it might never happen at all).

**Comment by lag-linaro** [comment]
Right.  I understand the ethics of open source. :smiley: 

The AArch64 image appears to be working.  What contributions are left wanting?

**Comment by slide** [comment]
Some level of compatibility checking with plugins and so forth would be good. Also, there are two other architectures that need to be tested

**Comment by oleg-nenashev** [comment]
To add to the list, ongoing ci.jenkins.io instabilities do not help: https://groups.google.com/forum/#!topic/jenkinsci-dev/v9d-XosOp2s . It may delay it a bit

**Comment by vielmetti** [comment]
You might consider doing multi-arch testing using Drone Cloud, which you can run tests on x86 and arm64 native

**Comment by lag-linaro** [comment]
Any news on the LTS date?

**Comment by kushalkoolwal** [comment]
Any update on this issue?

**Comment by wilinger** [comment]
Which tag should I be using with raspberry pi 4B?  2.214-alpine-arm64 Keeps crashing

**Comment by slide** [comment]
@willinger all of the non amd64 images are experimental, so any issues you run into would best be filed in Jira (https://issues.jenkins.io).

**Comment by timja** [comment]
Script has been combined / removed
