### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by zhao1532072926** [jenkinsci/docker#878]
The image's tag that I'm using is lts, and I don't know the root's passwd. 
So I can't install a docker by apt in the container

**Comment by oleg-nenashev** [comment]
I doubt you really want to do so.
If you need to install any additional tools, you should extend the image

**Comment by zhao1532072926** [comment]
> 
> 
> I doubt you really want to do so.
> If you need to install any additional tools, you should extend the image

I get it, thank you!
