### ISSUE TITLE
"e.getAttribute is not a function" message

### ISSUE THREAD

**Issue by medined** [jenkinsci/docker#88]
I used "docker run -d -p 9000:8080 jenkins" to start Jenkins. After the message indicated "Jenkins is fully up and running", I tried to configure jenkins. Without changing any fields, I clicked Save and saw the following popup message:

TypeError: e.getAttribute is not a function
(form not submitted)

Is that an error that I am causing?

**Comment by ndeloof** [comment]
Until I'm proven wrong this doesn't seem to be related to docker image but generic jenkins issue, please ask on jenkins-dev mailing list
