### ISSUE TITLE
404 not found apache-httpcomponents-client-4-api-plugin.hpi

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/docker#883]
latest build 7cfe34701992 (lts) as of 1500 of Fri 13th UK time.

NOT FOUND
https://updates.jenkins.io/2.176/latest/apache-httpcomponents-client-4-api-plugin.hpi

can't figure out which plugin depends on this, but 5 hours ago this worked, now it doesn't. reverted to 2.194 and it works again.

**Comment by oleg-nenashev** [comment]
Not sure. I have released https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/releases/tag/apache-httpcomponents-client-4-api-4.5.10-1.0 , so maybe there is an issue with the mirror update
