### ISSUE TITLE
Status of Multiarch Support 

### ISSUE THREAD

**Issue by james-crowley** [jenkinsci/docker#891]
I been reading through all the issues related to multiarch support, it seems like #750 is main issue being tracked. It is a lot of information to process and go through. 

Thus, I wanted to see if we could compile some of issues and progress into here. I am ready and willing to jump in but need to know where I can help.

Currently, it seems like we are building for multiple architectures, outlined in the `HACKING.adoc`, and they are getting pushed to [this](https://hub.docker.com/r/jenkins4eval/jenkins) repository, `jenkins4eval/jenkins`. 

It seems like not all tags/versions of Jenkins are being built, mostly just `slim` builds. Are these builds being generated using the Docker “templates” in the `multiarch` folder? Also is there a reason the other “templates” are not getting built? Are we “easing” into testing with only doing `slim` at first?

Next, I assume from this comment, https://github.com/jenkinsci/docker/pull/750#issuecomment-466531209, that ` jenkins4eval/jenkins` is only a temporary thing. Meaning that, after the testing we will official support multiarch images in the main docker repository? 

Additionally, when building multiarch images we utilize the `publish-experimental.sh` to publish said images; is that correct?

That is my understanding of the current environment, please correct me if I got anything wrong or enrich it to further my understanding. 

Now some questions on some more specific `s390x` and `ppc64le` builds/processes. 

First is there a reason to why we are still using the `manifest-tool` outlined in the `HACKING.adoc` instead of using Docker’s built in manifest support? I know this is pretty new, but did not know if there was still a specific reason why we might still being using this, other than we have not had time to update the process.

Secondly, is there a reason why the “base” Docker image still uses OpenJDK 8? This is going to cause some serious performance issue with the `s390x` platform. In OpenJDK 8, the `s390x` package does not include the `JIT`, thus performance is going to take a noise dive. In OpenJDK 9, they started to bundle the `JIT` for `s390x` with the package. This is something to keep in mind when build multiarch images. I saw a Dockerfile for JDK11 which would work fine on `s390x`, but that tag/version is not being built for multiarch images.

Lastly, using QEMU to do builds for `s390x` and `ppc64le` will work fine ~95% of the time. It is better to run on real hardware, to make sure it works 100%. I saw mention of using the “official” Docker images Pipeline to build out images, but it looks like you moved away from that. Is there a reason for that? I know they support also all different architectures under the sun, which is extremely helpful. Someone was briefly talking about it here, https://github.com/jenkinsci/docker/pull/579#issuecomment-331432303 . 

If we are not using the “official” Docker images Pipeline, I can probably get some hardware, `s390x` and `ppc64le`, for this project. 

I also saw mention of sig platform meeting, I would love to sit in and get caught up to speed on enabling multiarch support. Is there a way for me to join the conversation/meetings? I saw [this]( https://jenkins.io/sigs/platform/) link but did not know how to join.

**Comment by james-crowley** [comment]
Just tagging some people I think might have interest in this issue.


@oleg-nenashev @imdurgadas @olblak @batmat @jmreicha @carlossg

**Comment by jmreicha** [comment]
@james-crowley 👋 I haven't had much free time to work on the multiarch support recently but I think my knowledge is still recent enough to help answer some of your questions.

> It seems like not all tags/versions of Jenkins are being built, mostly just slim builds. Are these builds being generated using the Docker “templates” in the multiarch folder? Also is there a reason the other “templates” are not getting built? Are we “easing” into testing with only doing slim at first?

The images that are built are defined in the [Makefile](https://github.com/jenkinsci/docker/blob/master/Makefile#L64-L67).

> Next, I assume from this comment, #750 (comment), that jenkins4eval/jenkins is only a temporary thing. Meaning that, after the testing we will official support multiarch images in the main docker repository?

That is correct.  

> Additionally, when building multiarch images we utilize the publish-experimental.sh to publish said images; is that correct?

Correct.  Ideally the publish and publish-experimental scripts will merge once the multiarch images have been tested and vetted.

> First is there a reason to why we are still using the manifest-tool outlined in the HACKING.adoc instead of using Docker’s built in manifest support? I know this is pretty new, but did not know if there was still a specific reason why we might still being using this, other than we have not had time to update the process.

The multiarch support was added before this was a thing and the process has not been updated.

> Secondly, is there a reason why the “base” Docker image still uses OpenJDK 8?

Again, support was added awhile ago and the build script hasn't been updated yet.

> Lastly, using QEMU to do builds for s390x and ppc64le will work fine ~95% of the time. It is better to run on real hardware, to make sure it works 100%. I saw mention of using the “official” Docker images Pipeline to build out images, but it looks like you moved away from that. Is there a reason for that?

Building on hardware was a no go at the time because the Jenkins infra is locked down and it was easier to just use QEMU rather than fighting the infra.  I think there was another reason for not building on top of the Docker pipeline but I can't recall what it is now, others can probably fill in more details there.

> I also saw mention of sig platform meeting, I would love to sit in and get caught up to speed on enabling multiarch support. Is there a way for me to join the conversation/meetings? I saw this link but did not know how to join.

I think https://gitter.im/jenkinsci/platform-sig is what you're looking for 😄

**Comment by james-crowley** [comment]
> The images that are built are defined in the Makefile.

Just to confirm, when I am looking at the tags listed on the docker repository, I see `slim` tag which is pulling from `openjdk:8-jdk-slim`. Then I see `alpine` tag which is pulling from `openjdk:8-jdk-alpine`. I also see just a `2.196` tag. I am not sure I understand where this tag is getting built from. I see in the `Makefile` you linked, it shows:

```
publish-experimental:
	./publish-experimental.sh ; \
	./publish-experimental.sh --variant alpine ; \
	./publish-experimental.sh --variant slim ;
```

I understand the bottom two lines, that these cause the `alpine` and `slim` images to build, but I am not sure what the first line is doing. I tried reading over the `publish-experimental.sh` quickly, but I think I am missing something. Does this build the `Debian` image in the `multiarch` folder? Thus, producing the `2.196` tag? I figured if it is pulling from `Debian` it would contain the word `stretch` in the `publish-experimental.sh`, but it does not.

> Correct. Ideally the publish and publish-experimental scripts will merge once the multiarch images have been tested and vetted.

Awesome! That is what I was hoping. Getting all the multi-arch images in one Docker repository is essential.   

> The multiarch support was added before this was a thing and the process has not been updated.

Thanks for confirming this. That is what I figured, just wanted to double check!

> Again, support was added awhile ago and the build script hasn't been updated yet.

Sweet, hopefully we can change the base images to pull from OpenJDK 9 or above. That would give `s390x` images a huge performance boost! 

> Building on hardware was a no go at the time because the Jenkins infra is locked down and it was easier to just use QEMU rather than fighting the infra. I think there was another reason for not building on top of the Docker pipeline but I can't recall what it is now, others can probably fill in more details there.


Well if `s390x` and `ppc64le` machines would be helpful to the team, we can get them in a couple different ways. It all depends on how everyone wants to interact with the resources. 

Ideally, I think using the “official” Docker pipeline would be best, due to the resources they provide. I would love to know more about this issue and get other people's thoughts. If anyone else has more information please let me know!

> I think https://gitter.im/jenkinsci/platform-sig is what you're looking for 😄

Thank you for the link, I will try to join today!

**Comment by jmreicha** [comment]
> Does this build the Debian image in the multiarch folder? Thus, producing the 2.196 tag?

Yeah that's basically what happens.  Check [this function](https://github.com/jenkinsci/docker/blob/master/publish-experimental.sh#L63) for details on how it picks the Dockerfile to use.

> Ideally, I think using the “official” Docker pipeline would be best, due to the resources they provide. I would love to know more about this issue and get other people's thoughts. If anyone else has more information please let me know!

From my experience that will be quite a lot of work and could take a long time.  What is wrong with using QEMU?

**Comment by jmreicha** [comment]
One more thing I just remembered, there is a status tracking ticket for combining the build scripts [here](https://github.com/jenkinsci/docker/issues/872).

**Comment by timja** [comment]
Moved on a bit since this, given we’ve changed approach the new tracking issue is https://github.com/jenkinsci/docker/issues/1139
