### ISSUE TITLE
Proposal to switch from OpenJDK to AdoptOpenJDK

### ISSUE THREAD

**Issue by james-crowley** [jenkinsci/docker#893]
As we start to look into supporting multiple architectures, we might want to pivot from using OpenJDK to AdoptOpenJDK. There are couple reasons behind this.

First, it makes our build scripts and Dockerfiles easier to maintain. Currently, in ` publish-experimental.sh`, we have logic that handles pulling from the “right” OpenJDK for a specific architecture. 

```
    # Parse architectures and variants
    if [[ $arch == amd64 ]]; then
        BASEIMAGE="openjdk:8-jdk"
    elif [[ $arch == arm ]]; then
        BASEIMAGE="arm32v7/openjdk:8-jdk"
    elif [[ $arch == arm64 ]]; then
        BASEIMAGE="arm64v8/openjdk:8-jdk"
    elif [[ $arch == s390x ]]; then
        BASEIMAGE="s390x/openjdk:8-jdk"
    elif [[ $arch == ppc64le ]]; then
        BASEIMAGE="ppc64le/openjdk:8-jdk"
    fi
``` 

This could be remove as the AdoptOpenJDK Docker image, https://hub.docker.com/_/adoptopenjdk, has a manifest file that will handle pulling the correct image for the given architecture. This would simplify the above logic to just `FROM adoptopenjdk:XXXX`.

Second, the OpenJDK image’s we are pulling from to build out our multi-arch images, `s390x/ openjdk:8-jdk`, `arm32v7/openjdk:8-jdk`, etc. will not be updated anymore. This has to do with OpenJDK not publishing “official” binaries for these architectures. More information on this issue can be found here, https://github.com/docker-library/openjdk/issues/364#issuecomment-540821603.

Lastly, this would pair nicely with the proposal to add OpenJ9, #884. The AdoptOpenJDK image has tags that support OpenJ9, so it should not be to much more work to support this additional tag for our Jenkins images.

**Comment by slide** [comment]
I think a PR would be welcome. :+1:

**Comment by timja** [comment]
The switch is complete from what I can tell
