### ISSUE TITLE
bash，dotnet command not found

### ISSUE THREAD

**Issue by zx972243884** [jenkinsci/docker#896]
[root@localhost ~]# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
[root@localhost ~]# docker ps -a |grep jenkins
29a2e828e1a6        jenkins/jenkins     "/sbin/tini -- /usr/…"   25 minutes ago      Up 25 minutes       0.0.0.0:8080->8080/tcp, 0.0.0.0:50000->50000/tcp   jenkin
[root@localhost ~]# docker exec -it 29a2 /bin/bash
root@29a2e828e1a6:/# dotnet --info
bash: dotnet: command not found

-------------------------
docker run -idt -p 8080:8080 -p 50000:50000 --name jenkins -v /usr/bin/docker:/usr/bin/docker -v /run/docker.sock:/run/docker.sock -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone  -v /data/docker-data/jenkins:/var/jenkins_home -u root jenkins/jenkins
-------------------------
Please tell me how to solve it, thank you

**Comment by jvitorinoj** [comment]
If you need to build with donet, run another container, specific to build dotnet and add this container as jenkins slave.
