### ISSUE TITLE
how to change JAVA_OPTS after the jenkins is already run

### ISSUE THREAD

**Issue by loudDD** [jenkinsci/docker#899]
when i run the pipeline , the windows slave warm me the error :
![b6a2a0e68d7cd1a7a3586e89021ce5c](https://user-images.githubusercontent.com/33220071/68009767-c7a4de00-fcbd-11e9-851a-cf23b6c94079.png)

 and i search other people's answer , maybe JAVA_OPTS can be update to fix this. but i don't get jenins/config in the container.
pls let me know if there is other solution .,or how to change JAVA_OPTS

**Comment by MarkEWaite** [comment]
The issue tracker for the jenkins.io documentation site is used to track issues with the Jenkins documentation.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
