### ISSUE TITLE
Need to run update-ca-certificates for self signed and other certificates not included

### ISSUE THREAD

**Issue by dannymk** [jenkinsci/docker#901]
# Docker commands that you execute
$ update-ca-certificates

### Actual result
Updating certificates in /etc/ssl/certs...
rm: cannot remove 'ca-certificates.crt': Permission denied

### Expected outcome
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
...

### Have you tried a non-dockerized Jenkins and get the expected outcome?
yes

### Output of `docker version`
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Other relevant information
This obviously happens because the user running the container is set to "jenkins"

Possible solution:

```
========= Dockerfile =====================
FROM jenkins/jenkins:2.203-slim

USER root
#  ===================================================== 
#  Need to add CA certificates to container
#  
RUN apt update && apt -y install sudo \
   && sed -i "2 iexport JAVA_HOME=${JAVA_HOME}" /etc/ca-certificates/update.d/docker-openjdk \
   && echo 'jenkins ALL=(ALL) NOPASSWD: /usr/sbin/update-ca-certificates' > /etc/sudoers.d/jenkins

USER jenkins
```

**Comment by dannymk** [comment]
Guess it is resolved in newer Ubuntu images.

**Comment by andrisro** [comment]
I'm running into the same issue with the newer images. Any suggestions how to resolve this issue and add self-signed-certificates to the Jenkins Trust Store?
