### ISSUE TITLE
need to exclude workspace from /var/jenkins_home

### ISSUE THREAD

**Issue by NurPech** [jenkinsci/docker#918]
Hi,

I want to change the workspace from /var/jenkins_home/jenkins to /var/workspace. The backgrouund for this is that i want to use different volumes for jenkins config and the workspace.

Will this be possible with this? I know that i can change the workspace in the web interface, but is there any chance to do this during deployment?

**Comment by KasperHeyndrickx** [comment]
You can pass the workspace directory as a java option when jenkins starts up. 
Using docker this can be set with the environment variable `JAVA_OPTS`, value "-Djenkins.model.Jenkins.workspacesDir= ..." 

In your case this would be:

`docker run -v workspace:/var/workspace -v home:/var/jenkins_home -p 8080:8080 -p 50000:50000 -e JAVA_OPTS="-Djenkins.model.Jenkins.workspacesDir=/var/workspace/${ITEM_FULL_NAME}" jenkins/jenkins:lts`
