### ISSUE TITLE
Rsync missing

### ISSUE THREAD

**Issue by jvalters** [jenkinsci/docker#928]
Hello,
Could you please add a rsync into the image?
yum install rsync

This is useful and sometimes you need to deploy code using rsync command.

Thank you.

**Comment by oleg-nenashev** [comment]
Hi. You can extend the base image and add tools you need. We try to reduce the size of the images, so we generally do not install extra tools if they are not needed for Jenkins.

Pro-tip: you probably want to run your deployment in agents, not on the master
