### ISSUE TITLE
Perinstalling plugins fails for ansicolor on 2.204 LTS

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/docker#929]
Running
```
RUN /usr/local/bin/install-plugins.sh \
  ansicolor
```
Will fail with `Some plugins failed to download! Not downloaded: ansicolor`

This is because https://updates.jenkins.io/2.204/latest/ansicolor.hpi redirects to http://archives.jenkins-ci.org/plugins/ansicolor/0.6.3/ansicolor.hpi which returns 404.

Workaround is to run: 

```
RUN /usr/local/bin/install-plugins.sh \
  ansicolor:0.6.2
```

**Comment by DukeCheng** [comment]
same problem wait for resolve.
