### ISSUE TITLE
Jenkins plugins metadata url return 404 https://updates.jenkins.io/platform-plugins.json

### ISSUE THREAD

**Issue by DukeCheng** [jenkinsci/docker#930]
I use the https://hub.docker.com/r/jenkins/jenkins to run a new jenkins instance, during the setup process, after init secret verify page, the plugins install page show "can not connect to jenkins" and jenkins logs show below error:

> FINE: Invalid response code (404) from URL: https://updates.jenkins.io/platform-plugins.json
java.net.HttpRetryException: Invalid response code (404) from URL: https://updates.jenkins.io/platform-plugins.json
        at jenkins.install.SetupWizard.getPlatformPluginList(SetupWizard.java:454)
        at jenkins.install.SetupWizard.doPlatformPluginList(SetupWizard.java:400)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)

I tested the https://updates.jenkins.io/platform-plugins.json address, it return 404
`curl -I https://updates.jenkins.io/platform-plugins.json
HTTP/1.1 404 Not Found
Date: Thu, 27 Feb 2020 11:46:26 GMT
Server: Apache/2.4.29 (Ubuntu)
Content-Type: text/html; charset=iso-8859-1`

can anybody fix the 404 error?

**Comment by oleg-nenashev** [comment]
Jenkins tries to retrieve a `platform-plugins.json` from update centers so that they can override the installation wizard suggestions. The default update center does not include this file, because it is shipped within Jenkins itself. This warning is printed on the `FINE` level, and it is not considered as an error.

We could improve the log message to be more explicit, but I do not consider it as a major defect

**Comment by DukeCheng** [comment]
@oleg-nenashev thanks for your reply, now I can't init a new Jenkins instance for new environment, So can you help to ask team who can resolve the problem for now, looks the platform-plugins.json stoped the installation wizard, it means no body can init a Jenkins instance for now all over the world, If I was wrong understanding, can you tell me how to skip this step and move forward and install related plugin manually, I need it for now, Thanks.

**Comment by DukeCheng** [comment]
3 hours ago, https://hub.docker.com/r/jenkins/jenkins/tags released a new version, it support to skip plugin install step, It resolved my problem, thank you to Jenkins team
