### ISSUE TITLE
Running as different user

### ISSUE THREAD

**Issue by arthur798** [jenkinsci/docker#933]
So on my linux machine I created jenkins user which has id 1002, I have set a folder permission to jenkins:jenkins and ran

`sudo setfacl -Rm u:jenkins:rwx jenkins`

I start the container with command, `sudo docker run -d -v /app/jenkins:/var/jenkins_home -p 9790:8080 -p 50000:50000 -u 1002:1002 jenkins/jenkins:lts

however container stops with errors:

Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?

what could be wrong?

**Comment by SVMK1009** [comment]
> So on my linux machine I created jenkins user which has id 1002, I have set a folder permission to jenkins:jenkins and ran
> 
> `sudo setfacl -Rm u:jenkins:rwx jenkins`
> 
> I start the container with command, `sudo docker run -d -v /app/jenkins:/var/jenkins_home -p 9790:8080 -p 50000:50000 -u 1002:1002 jenkins/jenkins:lts
> 
> however container stops with errors:
> 
> Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
> 
> what could be wrong?

was that issue cleared @arthur798

**Comment by SVMK1009** [comment]
Is this issue cleared @arthur798 .,
im too having this issue, mounting is happening for other folders, but not for /var/jenkins_home

**Comment by timja** [comment]
@dduportal you recently implemented a work around here, would you be able to add what you did?

**Comment by timja** [comment]
https://github.com/jenkinsci/docker/issues/881 would be a generic fix for this

**Comment by dduportal** [comment]
See my comment in https://github.com/jenkinsci/docker/issues/881#issuecomment-882611061

**Comment by timja** [comment]
closing in favour of #881
