### ISSUE TITLE
How to add our own scripts/content?

### ISSUE THREAD

**Issue by mtdeguzis** [jenkinsci/docker#942]
I have a javascript file that I try to add via extending the docker image with `FROM`, but anything that is in /var/jenkins_home seems to be trounced on no matter what I do. We use a javascript file with Simple Theme to adjust the span class controlling the top-left title text "Jenkins".

```
ADD js/ui-overrides.js /var/jenkins_home/userContent/ui-overrides.js
RUN sed -i "s/@ENV@/$JENKINS_ENV/g" /var/jenkins_home/userContent/ui-overrides.js
```

Isn't there a mechanism to / or can there be, to load scripts via /usr/local/bin/jenkins.sh? A simple solution is to use con run-parts to allow users to adjust items before the JVM kicks off. We do this with Icinga (monitoring) and is common:

```
run-parts /opt/setup
```

Our current solution is to mount our Docker volume and add content before the actual `docker run`.

**Comment by Gazzonyx** [comment]
Ugly solution : run it in like /etc/rc.d/rc.local or some such before the service starts?  It's hacky, but maintainable-ish?

**Comment by timja** [comment]
Put it in the reference directory instead which will be copied in on startup
