### ISSUE TITLE
Error installing fastlane: signet requires Ruby version >= 2.4.0

### ISSUE THREAD

**Issue by CarlitosDroid** [jenkinsci/docker#948]
# Why can't I install fastlane?
Unable to install fastlane due to ruby ​​2.3.3, I can't update ruby to newest versions.

### Docker commands that you execute
* docker run --name my_jenkins_container jenkins/jenkins:lts
* docker container exec -u 0 -i -t my_jenkins_container bash
#### Inside the container: 
* apt-get update && apt-get install
* echo yes| apt-get install ruby-full
* echo yes | apt-get install build-essential
* gem install fastlane -NV
### Actual result
ERROR:  Error installing fastlane:
        signet requires Ruby version >= 2.4.0.

### Expected outcome
Install fastlane successfuly

### Output of `docker version`
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

### Other relevant information

![Screen Shot 2020-04-19 at 13 16 32](https://user-images.githubusercontent.com/10377529/79699041-6adcb600-8252-11ea-8d42-47855d3ca4dc.png)

![Screen Shot 2020-04-19 at 13 17 52](https://user-images.githubusercontent.com/10377529/79699046-74661e00-8252-11ea-938f-8f885061116b.png)

![Screen Shot 2020-04-19 at 13 16 14](https://user-images.githubusercontent.com/10377529/79699048-78923b80-8252-11ea-8dc8-eb3992bbc24d.png)

**Comment by AirOnSkin** [comment]
@slide I'm looking for these Jenkins images that are based on Debian Buster for similar reasons as CarlitosDroid. Can you provide a link to them?

**Comment by slide** [comment]
So, do you have what you need?

**Comment by AirOnSkin** [comment]
I'll be able to test it tomorrow. Not sure if the change to :slim will require more adaptions.
What other tags in jenkins/jenkins use Debian Buster?

**Comment by slide** [comment]
It looks like slim is the only one right now. That will change once some PR's are merged and the main docker image will be Buster instead of Stretch.

**Comment by AirOnSkin** [comment]
Good to know. Thanks for the info :)

**Comment by AirOnSkin** [comment]
@slide The `:slim` image works well for us. Needed some adjustments, but nothing major :+1:
