### ISSUE TITLE
/usr/local/bin/jenkins.sh failed: No such file or directory

### ISSUE THREAD

**Issue by Atihinen** [jenkinsci/docker#949]
# Issues and Contributing

### Docker commands that you execute

 docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

### Actual result

Unable to find image 'jenkins/jenkins:lts' locally
lts: Pulling from jenkins/jenkins
Digest: sha256:15fca69266f4cc2107449d9fa2595acf0cbe1584eb425ee6f2fe9cefc9fc4b97
Status: Downloaded newer image for jenkins/jenkins:lts
[FATAL tini (6)] exec /usr/local/bin/jenkins.sh failed: No such file or directory

### Expected outcome

something else

### Have you tried a non-dockerized Jenkins and get the expected outcome?

not yet

### Output of `docker version`

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by MarkEWaite** [comment]
I'm unable to duplicate the failure when I ran it on Debian Linux using Docker version 19.03.7, build 7141c19.

Does it still fail for you?

**Comment by Atihinen** [comment]
Yes it does, but might be vagrant / synced folder issue, can be closed and I'll create new one if it's not that one.
