### ISSUE TITLE
Do not rely on the tiered update center directory layout

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/docker#954]
The canonical way to access a version-compatible update site is through `/update-center.json?version=...`.

Do not rely on `/stable-2.222/update-center.json`,  `/2.222/update-center.json`, etc. to exist. Those are implementation details that may change at any time.

**Comment by daniel-beck** [comment]
Here's the proposed change that will impact `install-plugins.sh`: https://github.com/jenkins-infra/update-center2/pull/376

**Comment by daniel-beck** [comment]
Can we make 2.235 the last update center tier to support? I.e. 2.24x would no longer be a fixed tier? @slide ?

**Comment by slide** [comment]
I would love to make that possible, I haven't had a chance to look into this yet though. I will try and look into it today if I can manage some time.

**Comment by slide** [comment]
See #964 964

**Comment by lemeurherve** [comment]
@daniel-beck do you know if this issue is still relevant?

**Comment by timja** [comment]
Not since https://github.com/jenkinsci/docker/pull/1408

**Comment by lemeurherve** [comment]
For the record, I asked that as I found this issue linked in https://github.com/jenkins-infra/update-center2/blob/77bcef2630467ba31f4bcabdec74421f2ca629e3/site/README.md#L38-L39
