### ISSUE TITLE
Allow SSL and HTTP/2 from Docker images

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/docker#955]
## Allow SSL and HTTP/2 from Docker images

The Jenkins Wiki describes how to add the ALPN jar files to the bootclasspath (before 8u252) and to the runtime classpath (8u252 and later) so that the user can provide HTTP/2 support.  Those steps should be feasible to embed inside the Docker image so that the Docker image could be used to confirm SSL is working inside the Jenkins Docker image.

Refer to the [HTTP/2 section of the Install Guide](https://www.jenkins.io/doc/book/installing/#using-http2) for the details.  @olamy is one of the experts on the topic.

**Comment by timja** [comment]
Hmm do we think we need this, given that in general we recommend people terminate SSL at their own reverse proxy?

**Comment by MarkEWaite** [comment]
I'm fine without it.  The primary motivator was that it might allow easier access to testing that SSL and HTTP/2 support are working.  I'm not going to spend the effort to implement it and I suspect others won't spend the implementation effort either
