### ISSUE TITLE
jenkins in docker container

### ISSUE THREAD

**Issue by mahsa-frj** [jenkinsci/docker#96]
what is the benefits of running jenkins in docker container?

**Comment by snayler0** [comment]
There are many reasons i can think of, but in my case we are building several jenkins environments.

eg. one for our Java devs, one (maybe even two) for Python devs.

Using Docker we can pull the jenkins official image, and then make changes for our 'base' jenkins. 

Then we can allow users to pull down a copy of that base image with plugins installed and configurations made depending on the requirement (Java, Python, Other).

All of this can be done by just creating derived dockerfiles for each environment. So the image that users will build is only a few steps ontop of the existing 'in-house base image', which in turn pulls from the official jenkins image.

**Comment by MarkEWaite** [comment]
I really like the concept of readily duplicated personal continuous integration machines as described by @snayler0.

I use Jenkins in a docker container to speed the setup and teardown of different Jenkins configurations for testing of Jenkins plugins.  The Jenkins git client plugin and the Jenkins git plugin need to run well on many different platforms and many different git versions.  A docker container makes it much easier to assemble and disassemble different Linux platforms (CentOS 5, 6, 7, Debian 6, 7, 8, Ubuntu 12.04, 14.04, 15.04) with their matching git versions.
