### ISSUE TITLE
This Jenkins instance appears to be offline.

### ISSUE THREAD

**Issue by h-ravichandra** [jenkinsci/docker#960]
I am getting this "Jenkins instance appears to be offline." when i start localhost:8080. As based on some solutions, i replaced https to http in hudson.model.UpdateCenter.xml file and restarted jenkins still didnt work. This issue got closed by telling pull jenkinsci/jenkins image, but still i am working on the same. Do i need to configure proxy all the time? Is there any solutions to overcome this issue

**Comment by Nielius** [comment]
Probably the same as this issue: https://github.com/jenkinsci/docker/issues/885

**Comment by lovefromCode** [comment]
> I am getting this "Jenkins instance appears to be offline." when i start localhost:8080. As based on some solutions, i replaced https to http in hudson.model.UpdateCenter.xml file and restarted jenkins still didnt work. This issue got closed by telling pull jenkinsci/jenkins image, but still i am working on the same. Do i need to configure proxy all the time? Is there any solutions to overcome this issue

xfbfgb

**Comment by lovefromCode** [comment]
nvn
