### ISSUE TITLE
script.sh: docker: not found

### ISSUE THREAD

**Issue by jiankafei** [jenkinsci/docker#962]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
```shell
docker run \
  -u root \
  --name jenkins_lts \
  -d \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkins/jenkins:lts-slim
```
### Actual result
/var/jenkins_home/workspace/trial_master@tmp/durable-dd76dfd6/script.sh: 1: /var/jenkins_home/workspace/trial_master@tmp/durable-dd76dfd6/script.sh: docker: not found
### Expected outcome
Correct implementation
### Have you tried a non-dockerized Jenkins and get the expected outcome?
No
### Output of `docker version`
Docker version 19.03.8
### Other relevant information
Use Blue Ocean
### OS
```txt
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
```
### Jenkinsfile
```Jenkinsfile
pipeline {
  agent {
    docker {
      image 'node:lts-buster-slim'
      args '-p 8989:8989'
    }
  }
  environment {
    NODE_ENV = 'production'
  }
  stages {
    stage('Install') {
      steps {
        echo 'Installing..'
        sh 'yarn'
        echo 'Install Success'
      }
    }
    stage('Build') {
      steps {
        echo 'Building..'
        sh 'yarn build'
        echo 'Build Success'
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying..'
        input message: 'Finished using the web site? (Click "Proceed" to continue)'
        sh './jenkins/deploy.sh'
        echo 'Deploy Success'
      }
    }
  }
}
```

**Comment by slide** [comment]
I don't think the docker images have docker inside of them. This is not something that we really want to do at this point I think. You can setup docker based agents though.

**Comment by jiankafei** [comment]
@slide I have solved the problem, but I think Jenkins docs should supplement the corresponding warnings or prompts, as well as the corresponding solutions, so that users can run successfully according to the configuration of docs, and avoid confusion.

**Comment by slide** [comment]
I'm not sure I understand what you mean, what docs are you following that the behavior doesn't match?

**Comment by jiankafei** [comment]
I see Jenkins manual here [jenkins doc](https://www.jenkins.io/zh/doc/)

**Comment by undead85** [comment]
@jiankafei how you solve the problem?

**Comment by jiankafei** [comment]
@undead85 
You can read this article. [Running Docker in Jenkins (in Docker)](https://blog.container-solutions.com/running-docker-in-jenkins-in-docker)

**Comment by tbernacchi** [comment]
@jiankafei I set up my jenkins to be able to run docker commands and in the example on this link the 'docker run hello-world' works pretty fine as well as another projecsts/pipeleine but in this one when I finished build my docker image and try to pull to my registry I got 'docker not found':

`docker build -t tadeuuuuu/infra-developer:22 .
/var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: 1: /var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: docker: not found`

**Comment by quangthe** [comment]
If you run docker Jenkins, you will likely to face this issue. The guide https://blog.container-solutions.com/running-docker-in-jenkins-in-docker does not work on Mac (it may work in Linux).

**Comment by patelrutva** [comment]
> @jiankafei I set up my jenkins to be able to run docker commands and in the example on this link the 'docker run hello-world' works pretty fine as well as another projecsts/pipeleine but in this one when I finished build my docker image and try to pull to my registry I got 'docker not found':
> 
> `docker build -t tadeuuuuu/infra-developer:22 . /var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: 1: /var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: docker: not found`
> 
> Ideas? Any light will be appreciate!

Did you solve this?

**Comment by jiankafei** [comment]
> @jiankafei I set up my jenkins to be able to run docker commands and in the example on this link the 'docker run hello-world' works pretty fine as well as another projecsts/pipeleine but in this one when I finished build my docker image and try to pull to my registry I got 'docker not found':
> 
> `docker build -t tadeuuuuu/infra-developer:22 . /var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: 1: /var/jenkins_home/workspace/infra-dev@tmp/durable-7abc7028/script.sh: docker: not found`
> 
> Ideas? Any light will be appreciate!

**Comment by rapkalya** [comment]
add `$(which docker):/usr/bin/docker `to volume like below 
```
docker run \
  -u root \
  --name jenkins_lts \
  -d \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $(which docker):/usr/bin/docker
  jenkins/jenkins:lts-slim
```

**Comment by rapkalya** [comment]
but for me it says` /var/jenkins_home/jobs/Offline_job/workspace@tmp/durable-ce67d22e/script.sh: zip: not found `
need help

**Comment by HoffiMuc** [comment]
any solution for this on MacOS ?

**Comment by rapkalya** [comment]
Irrespective of O.S it will work if u include docker to jenkins container in volume will work . check in MacOs where ur docker is install (i.e path ) and bind the path it to jenkins container

**Comment by timja** [comment]
This isn’t relevant to this repository, try stackoverflow or https://community.jenkins.io if you need more.

we will not be adding docker to the images

**Comment by skyhitnow** [comment]
I also encountered this problem: `var/jenkins_home/jobs/Offline_job/workspace@tmp/durable-ce67d22e/script.sh: zip: not found`,and I think it's related to the incorrect referencing of the docker in Jenkinsfile，though I don't know how to write it correctly. The thing is if you designate the docker as an agent, then it would download the Jenkins file as well in the container, then it seemly want to spawn a container in the container,which is not as we supposed.

**Comment by skyhitnow** [comment]
I find the reason and I also thought it's a bit confusing in the docs.Though you use a cloud configured docker agent,you should write like `agent{label 'xxx‘}`which would not in the container want to call the docker command. If you write like agent{docker{...}},the discussed problem would appear. For your reference.

**Comment by quangthe** [comment]
@skyhitnow Yep, correct. Try some examples in https://www.jenkins.io/doc/book/pipeline/docker/ and it works. Thanks
