### ISSUE TITLE
Side effects of manually copying from jenkins/ref to jenkins_home

### ISSUE THREAD

**Issue by arjunKay** [jenkinsci/docker#967]
I am trying to load Jenkins job configuration dynamically (from a cloud volume) into the Jenkins master container so that every time a job is added/modified, the need to rebuild the container can be eliminated. As per my current implementation plan, I first copy the configuration files from the cloud volume to `/usr/share/jenkins/ref/config` in the container, create corresponding `.override` files,  copy these files (excluding `.override` files) to `jenkins_home`, and then perform a safe-restar so that the post-initilaization script can use the new config and reflect the changes. I am following this approach because the files/directories that are placed in  `/usr/share/jenkins/ref/` during docker baking is copied over to `jenkins_home` during the container bootstraping and I want to mimic this behavior. Is this a good approach or would there be any potential side-effects of doing this? 
It should also be noted that I plan to use this to load not only job configutation, but also to load post-initialization scripts (init.groovy.d) and plugins.txt.

**Comment by slide** [comment]
My recommendation would be to post questions to the users mailing list (https://groups.google.com/g/jenkinsci-users). This repo's issues are not really used for asking questions and as you can see it takes time for us to look.
