### ISSUE TITLE
run success but it shows Offline

### ISSUE THREAD

**Issue by quliting** [jenkinsci/docker#973]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.
https://hub.docker.com/_/jenkins

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
docker run -d  -p 808:8080 -p 50000:50000 jenkins

### Actual result
success but it shows Offline
### Output of `docker version`
Docker version 19.03.12, build 48a66213fe
### Other relevant information
![QQ截图20200804104911](https://user-images.githubusercontent.com/14035957/89247677-735dce80-d640-11ea-86da-3246c85a46f4.png)

**Comment by quliting** [comment]
is the docker version problem?

**Comment by quliting** [comment]
because i can't access the google.com?
the china can't access.will you use the china vps to do this ?

**Comment by timja** [comment]
Jenkins needs internet connectivity to download plugins it will fail without this. This is not related to the docker image as far as I can tell

**Comment by timja** [comment]
https://issues.jenkins.io/browse/JENKINS-66161 appears to be the issue this should be tracked by at least for google

**Comment by shyandsy** [comment]
it because you fucking network cannot access the following link
```
http://updates.jenkins.io/update-center.json cannot access 
```

I just curios why these fucking guys block this url

**Comment by quliting** [comment]
the problem in network .
in dockercompose i set the host .slove it
