### ISSUE TITLE
Can't install python3.8 

### ISSUE THREAD

**Issue by parrotrueper** [jenkinsci/docker#974]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

**Comment by parrotrueper** [comment]
Here is a fork of this repo, where the main Dockerfile uses the image ubuntu focal-fossa that already has python3 

https://github.com/parrotrueper/docker

**Comment by slide** [comment]
You are welcome to create a PR for a focal based image, but it is not currently on our roadmap to implement support for it ourselves.
