### ISSUE TITLE
security critical issues

### ISSUE THREAD

**Issue by gudipudipradeep** [jenkinsci/docker#980]
Please provide the way to fix vulnerability inside the image.
![Jenkins-2 235 5-alpine-lts-ScanReport_25-Aug](https://user-images.githubusercontent.com/8638634/91125739-0af29200-e6c0-11ea-89eb-a2aae70205ac.png)

**Comment by MarkEWaite** [comment]
Jenkins 2.235.5 has been superseded by Jenkins 2.249.x which was superseded by Jenkins 2.263.x.  The Jenkins project provides security fixes for current LTS and current weekly releases, not for older LTS or for older weekly releases.
