### ISSUE TITLE
Publish docker images to GitHub container registry

### ISSUE THREAD

**Issue by felipecrs** [jenkinsci/docker#983]
[Since Docker Hub has imposed pull rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/), I'm not able to pull anything from there from my company anymore. So I have to manually mirror the image to another registry that I can access.

This is a suggestion for you to push the Docker images not only to Docker Hub, but also to the [recently introduced GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

It would be awesome to be able to:

```sh-session
$ docker pull ghcr.io/jenkins/jenkins:lts
```

**Comment by jalaziz** [comment]
We're running into rate limits too. Would be great if there were official GHCR and Public ECR mirrors.

**Comment by dduportal** [comment]
> We're running into rate limits too. Would be great if there were official GHCR and Public ECR mirrors.

Hi @jalaziz , that is unexpected: the Jenkins Docker images (check the logo "Sponsored OSS" at https://hub.docker.com/r/jenkins/jenkins) are under the Docker OSS program (https://www.docker.com/community/open-source/application/) whihc remove API rate limits.

Could you share details about the rate limit you see please (context, technical elements)?

**Comment by jalaziz** [comment]
> > We're running into rate limits too. Would be great if there were official GHCR and Public ECR mirrors.
> 
> Hi @jalaziz , that is unexpected: the Jenkins Docker images (check the logo "Sponsored OSS" at https://hub.docker.com/r/jenkins/jenkins) are under the Docker OSS program (https://www.docker.com/community/open-source/application/) whihc remove API rate limits.
> 
> Could you share details about the rate limit you see please (context, technical elements)?

Well this is embarrassing. You're absolutely right. We saw "pull QPS exceeded" and thought it was coming from docker but it's actually a k8s kubelet issue.

**Comment by dduportal** [comment]
> > > We're running into rate limits too. Would be great if there were official GHCR and Public ECR mirrors.
> > 
> > 
> > Hi @jalaziz , that is unexpected: the Jenkins Docker images (check the logo "Sponsored OSS" at https://hub.docker.com/r/jenkins/jenkins) are under the Docker OSS program (https://www.docker.com/community/open-source/application/) whihc remove API rate limits.
> > Could you share details about the rate limit you see please (context, technical elements)?
> 
> Well this is embarrassing. You're absolutely right. We saw "pull QPS exceeded" and thought it was coming from Docker but it's actually a k8s Kubelet issue.
> 
> For anyone else running into this and using Karpenter, see [aws/karpenter#1269](https://github.com/aws/karpenter/issues/1269).

Thanks for sharing @jalaziz . Happy to here that you found a solution and that the Docker OSS program is still working well for end users 🥳

**Comment by timja** [comment]
Closing as not planned currently, due to our sponsorship at docker hub there should be no need of this.
