### ISSUE TITLE
Unable to pull dependent layers

### ISSUE THREAD

**Issue by snayler0** [jenkinsci/docker#99]
Howdy!

I'm unable to pull a copy of the official jenkins image at the moment.

I am able to pull other docker repos without any troubles.

The pull starts out ok, and starts to grab dependant layers but then falls over and gives the error:

1520f72eb8b6: Error pulling image (latest) from jenkins, Get https://registry-1.docker.io/v1/images/1520f72eb8b6f5c2d5cbe71431af204db2c1370fd36cd5b119103a3d3bf49550/ancestry: unexpected EOF b119103a3d3bf49550/ancestry: unexpected EOF

Seems like this issue: https://github.com/docker/docker/issues/2151

If relevant,  i'm in Australia, ACT.

I can't for the life of me find an answer to the problem though...

**Comment by carlossg** [comment]
You should raise that with the Docker Hub team

**Comment by snayler0** [comment]
Thanks Carlossg.

It's been worked out now though. The proxy server i was trying to work through was hitting a disk limit which explains why i was able to pull a few layers before it failed.

Sorry for the noise... :)
