### ISSUE TITLE
install-plugins.sh fails to install in latest LTS

### ISSUE THREAD

**Issue by holmesb** [jenkinsci/docker#991]
Upon upgrading from previous to current LTS (v2.235.5 --> v2.249.1), the install-plugins.sh no longer works.  When reducing the plugin list to just ansicolor, it outputs:

_jenkins@jenkins:/$ /usr/local/bin/install-plugins.sh ansicolor:0.6.3
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins.._

But the plugin is not installed, just an empty lock directory:
_jenkins@jenkins:/$ ls -al /usr/share/jenkins/ref/plugins/ansicolor.lock
total 8
drwxr-sr-x 2 jenkins jenkins 4096 Sep 17 11:25 .
drwxrwsrwx 3 root    jenkins 4096 Sep 17 11:25 .._

Proceeds no further than:
[`jenkinsUcJson=$(curl -Ls -o /dev/null -w "%{url_effective}" "${JENKINS_UC}/update-center.json?version=${jenkinsVersion}")`](https://github.com/jenkinsci/docker/blob/f70397a4efcc70e464379ccab9be1dde80202a26/install-plugins.sh#L249)
which was [pushed ](https://github.com/jenkinsci/docker/commit/9f10ee2e61e42560ec843ac4d37731b51c54e729)a couple of months ago.  Removing the -o /dev/null makes no difference.  
If I just run line
`curl -Ls -o /dev/null -w "%{url_effective}" "${JENKINS_UC}/update-center.json?version=${jenkinsVersion}"`
it outputs:
https://updates.jenkins.io/update-center.json?version=2.249
which I guess is right, so can't figure why execution stops.

I'm in two minds whether to troubleshoot this further or hold-off upgrading until the switchover to the new [plugin installation manager](https://github.com/jenkinsci/helm-charts/issues/8).  But thought I'd report it here for reference

**Comment by tamirble** [comment]
Having the same problem in 2.249.1. Trying to install plugins with install-plugins.sh

Examining the script I see at line 248 the following code:
`jenkinsUcJson=$(curl -Ls -o /dev/null -w "%{url_effective}" "${JENKINS_UC}/update-center.json?version=${jenkinsVersion}")`

The CURL_OPTIONS parameter is missing from the curl command.

Since we work through a proxy, the script stuck at this point.

**Comment by holmesb** [comment]
Yes we use a proxy too, so must be related

**Comment by holmesb** [comment]
We fixed by adding our root CA cert to Jenkins' keystore.  Since this appears a valid solution, I'm closing this.

**Comment by tamirble** [comment]
It's more of a workarround than a solution in my opinion...
