### ISSUE TITLE
Jenkins v2.256 and later is skipping bitbucket authentication

### ISSUE THREAD

**Issue by cotvictor** [jenkinsci/docker#999]
Hello, 

We are using Jenkins container v2.204.1, which works perfectly fine with lots of plugins (including: bitbucket-oauth:0.10). Although when it was upgraded to version 2.256 or to a newer one, it always deploys the instance, but sadly it skips authentication part with bitbucket, redirecting to /login, which isn't the expected output.

Relevant errors in docker logs are: 
`2020-10-06 10:22:20.849+0000 [id=30]	WARNING	hudson.ExtensionFinder$Sezpoz#scout: Failed to scout hudson.plugins.swarm.UDPFragmentImpl
java.lang.ClassNotFoundException: hudson.UDPBroadcastFragment`

and 

`2020-10-06 10:22:26.689+0000 [id=28]	WARNING	hudson.ExtensionComponent#compareTo: Failure during Descriptor#getDisplayName for hudson.security.LDAPSecurityRealm$DescriptorImpl
java.lang.NoSuchMethodError: hudson.security.Messages.LDAPSecurityRealm_DisplayName()Ljava/lang/String;`

### Actual result
Instance deployed with no Bitbucket integration.

### Expected outcome
No authentication required in Jenkins

### Output of `docker version`
Docker version 19.03.5, build 633a0ea

**Comment by slide** [comment]
This sounds like a Jenkins issue, not a docker container issue. Please open an issue against the `core` component at https://issues.jenkins.io.
